### ISSUE TITLE
Lint for Unnecessary Path Push

### ISSUE THREAD

**Issue by mmstick** [rust-lang/rust-clippy#1010]
I have seen some of the following usage:

``` rust
let new_path = {
    old_path.push(file);
    old_path
};
```

It could be helpful if Clippy could recommend to use the `join()` method instead.

``` rust
let new_path = old_path.join(file);
```

**Comment by Stebalien** [comment]
These aren't quite the same. The first updates `old_path` in place and then moves it, the other allocates a new path.

**Comment by camsteffen** [comment]
Reusing the existing `PathBuf` is better perf so I don't think Clippy should ever suggest this. In fact, we could suggest the opposite as a perf lint.
