### ISSUE TITLE
`==` check instead of `opt.map_or(false, |val| val == n)` or `if let Some(n) = opt`

### ISSUE THREAD

**Issue by laralove143** [rust-lang/rust-clippy#10118]
### What it does

It converts a code like
```rust
opt.map_or(false, |val| val == 5)
```
to
```rust
opt == Some(5);
```
This could apply to `Result` and technically any enum wrapping a value, for example
```rust
matches!(err, Error::Io(5));
```
to
```rust
err == Error::Io(5);
```

### Lint Name

Unnecessary pattern matching

### Category

style

### Advantage

- Readability
- Conciseness
- Possible optimization (Could someone that can read assembly verify this? The resulting assembly has fewer lines)

### Drawbacks

The enum needs to implement `PartialEq`

### Example

```rust
#[derive(PartialEq)]
enum Error {
    Io(u16),
    Os(u16),
}

fn unnecessary_pattern_match() {
    let err = Error::Os(1);
   matches!(err, Error::Io(5));
}

fn unnecessary_map_or() {
    let opt = Some(1);
    opt.map_or(false, |val| val == 5);
}
```

Could be written as:

```rust
#[derive(PartialEq)]
enum Error {
    Io(u16),
    Os(u16),
}

fn unnecessary_pattern_match() {
    let err = Error::Os(1);
    err == Error::Io(5);
}

fn unnecessary_map_or() {
    let opt = Some(1);
    opt == Some(5);
}
```

**Comment by llogiq** [comment]
Note that depending on the `PartialEq` implementation, this lint might change behavior! There is no guarantee that those will be equal. Consider:

    enum AllTheSame {
        One(u32),
        Other(bool),
    }

    impl core::ops::PartialEq for AllTheSame {
        fn eq(&self, other: &Self) -> bool { true }
    }

This is a valid type with a valid `PartialEq`  impl, yet changing `matches!(ats, AllTheSame::Other(true))` to `ats == AllTheSame::Other(true)` would effectively remove the check.

What we might try is check if the `PartialEq` impl was derived and only lint for those types.

**Comment by laralove143** [comment]
Good point but yes we can do that, or we can check if it's equal to the pattern match (not sure if you can run code while linting)

Another consideration though is if they implemented it custom, maybe they don't want you to use pattern matching, for example:

```rust
enum Num {
    Small(u8),
    Large(u64),
}

assert_eq!(Num::Small(5), Num::Large(5));
```

**Comment by llogiq** [comment]
We can run code while linting, but only constant code, which won't be too helpful in this case. Apart from checking if the impl is derived, we could also just have a list of types to check for that might be user-extensible via config.

**Comment by laralove143** [comment]
They could just allow the lint in that case, I think checking if the impl is derived is our best bet then

**Comment by llogiq** [comment]
There is still a difference between allowing the lint wholesale or giving the user the option to disable it by type.

**Comment by laralove143** [comment]
I meant allowing it for a module/method but the config makes sense too

**Comment by Jacherr** [comment]
I can take a crack at implementing this.

@rustbot assign

**Comment by Jacherr** [comment]
Whoops

@rustbot claim
