### ISSUE TITLE
Use byte string instead of slice of byte characters

### ISSUE THREAD

**Issue by matthiasbeyer** [rust-lang/rust-clippy#10147]
### What it does

I accidentially used

```rust
let a = &[b'a', b'/', b'b'];
```

instead of

```rust
let a = b"a/b";
```

so I figured this could be a clippy lint.

### Lint Name

bytestring_instead_of_byte_chars

### Category

style

### Advantage

- Easier to read
- Easier to change/extend

### Drawbacks

None

### Example

```rust
let a = &[b'a', b'/', b'b'];
```

Could be written as:

```rust
let a = b"a/b";
```

**Comment by matthiasbeyer** [comment]
If this is wanted, I would like to try to contribute the implementation for it.

**Comment by Alexendoo** [comment]
Sounds like a good lint to me, would be great if you'd like to implement it. If you have any questions ever you can ask here or on [the Zulip channel](https://rust-lang.zulipchat.com/#narrow/stream/clippy)
