### ISSUE TITLE
needless_range_loop suggests using iter on a value that do not have iter method

### ISSUE THREAD

**Issue by malbarbo** [rust-lang/rust-clippy#1014]
In this example:

``` rust
use std::ops::Index;

struct S(Vec<u32>);

impl Index<usize> for S {
    type Output = u32;

    fn index(&self, index: usize) -> &u32 {
        &self.0[index]
    }
}

fn main() {
    let s = S(vec![1, 2, 3]);

    for i in 0..3 {
        println!("{:?}", s[i]);
    }
}
```

Clippy says "Consider using `for item in s.iter().take(3)`, but `s` does not have `iter` method.

**Comment by mcarton** [comment]
I guess being indexable but not iterable is so uncommon no one ever noticed :sweat:

**Comment by llogiq** [comment]
Maybe we should suggest implementing an `.iter()` function for something that has a `.len()` and is `Index`able?

**Comment by mcarton** [comment]
Why the `len`?  Iterators need not to be finite.

**Comment by llogiq** [comment]
True. Perhaps we should only require `Index<usize>` then.

**Comment by montrivo** [comment]
The example isn't linted anymore. 

The check early returns when the has no `.iter()` method: 
```rust
                // don't lint if the container that is indexed does not have .iter() method
                let has_iter = has_iter_method(cx, indexed_ty);
                if has_iter.is_none() {
                    return;
                }
```
