### ISSUE TITLE
Disable result_unwrap_used / option_unwrap_used in tests

### ISSUE THREAD

**Issue by llogiq** [rust-lang/rust-clippy#1015]
If clippy is used as a dependency, the lints can pick up test code. Since that code does not need to have full-blown error handling, unwrap is ok.

To solve this, we can use `get_parent` to walk up the parent chain and check all items for `#[test]` annotations.

**Comment by link2xt** [comment]
This will not work properly if test module contains helper functions that do `unwrap()` and `#[test]` function calls this helper function rather than `unwrap()`. Such lints should be disabled for the whole test module.

**Comment by llogiq** [comment]
We now have an `is_in_test` function in `clippy_utils` that checks both function and module path.

**Comment by smoelius** [comment]
Should this be configurable? I.e., is the change in behavior a concern?
