### ISSUE TITLE
warn on strings that look like inline format strings but aren't

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-clippy#10195]
### What it does

````rust
fn main() {
    let number = 123;
    let s = "{number:?}"; // this is likely a bug.
    println!("{s}");
}
````

### Example

```rust
fn main() {
    let number = 123;
    let s = "{number:?}"; // this is likely a bug.
    println!("{s}");
}
```

Could be written as:

```rust

fn main() {
    let number = 123;
    let s = format!("{number:?}"); 
    println!("{s}");
}

```

**Comment by matthiaskrgr** [comment]
I just found an even more interesting case IRL  in kani, where it looks like `expect()`would take a format string, but it does just print the raw `str`without applying any formatting :smile: 

https://github.com/model-checking/kani/pull/2865 

````rust
pub fn main() {
    let mut x = Some(3);
    let y = "aaa";
    x = None.expect("hello {y}");
}
````

will print literally `hello {y}` instead of `hello aaa`
````

**Comment by TTWNO** [comment]
Found some code in my crate that did the same thing:

```
role.rs:632: let encoded = to_bytes(ctxt, &from_role).expect("Unable to encode {from_role}");
role.rs:635: from_slice(&encoded, ctxt).expect("Unable to convert {encoded} into Role");
interface.rs:390: let serde_val = serde_plain::to_string(&iface).expect("Unable to serialize {iface}");
tests.rs:35: .expect("Could not set sender to {unique_bus_name:?}")
tests.rs:91: .expect("Could not set sender to {unique_bus_name:?}")
tests.rs:169: .expect("Could not set sender to {unique_bus_name:?}")
```

Could we get a comment on if this would be a reasonable lint or not?

**Comment by emilk** [comment]
This is an easy mistake when using UI toolkits:

```rs
let x = 42;
ui.label("The value is {x}"); // oops!
```

**Comment by emilk** [comment]
@GuillaumeGomez wdyt?

It requires some thought on exactly what patterns to look for, and I'm sure there will be false positives (so this should probably be an opt-in lint). But at looking for the regex `\{\w*:?\??\}` should catch quite a lot of the problems, without too many false positives. Looking for the regex `\{.*}` would catch all problems, but would perhaps have too many false positives

**Comment by GuillaumeGomez** [comment]
I think it's common enough to definitely deserve a lint. I'm at rustconf currently but I'm putting it in my todo list for next week when I'm back.
