### ISSUE TITLE
Add `Cargo.lock` to git.

### ISSUE THREAD

**Issue by the-kenny** [rust-lang/rust-clippy#1019]
To make builds reproducible, projects building executables should add their `Cargo.lock` to their git repository. This is also noted in http://doc.crates.io/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

Doing this also makes packaging for distributions (in my case NixOS) much easier as it's guaranteed that the dependencies won't change between two builds.

**Comment by mcarton** [comment]
The main crate has both a plugin and a binary, what should we do about that?

**Comment by killercup** [comment]
@mcarton I'm fairly certain Cargo will ignore the lock file when clippy is used as a library. So the lock file would only affect `cargo install clippy` and manual builds.

**Comment by the-kenny** [comment]
That sounds like a nice solution :)
Am 17.06.2016 20:34 schrieb "Pascal Hertleif" <notifications@github.com>:

**Comment by the-kenny** [comment]
Any updates on this? I think the comment of @killercup clears the way to include `Cargo.lock` in the repository.

**Comment by Manishearth** [comment]
IIRC the lock file won't affect `cargo install`, it only affects using the library as a git clone, which is a rare use case (only clippy devs, basically). I'm not sure of this though.

**Comment by the-kenny** [comment]
As I mention in the opening description: A `Cargo.lock` file is crucial to get reproducible builds. This is not only useful for development (as every developer will have the same set of dependencies, which makes it easy to reproduce bugs), but also useful for people trying your package your software for distribution. 

Please take a look at [this](http://doc.crates.io/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries) and [this](http://doc.crates.io/guide.html#cargotoml-vs-cargolock) for a detailed description of the benefits.

**Comment by Manishearth** [comment]
I know why it's useful, I was just wondering if it applied to binaries. Turns out it does, so we can go ahead with this 😄

**Comment by sanmai-NL** [comment]
@Manishearth @the-kenny: seems like a small PR is still needed to close this.

**Comment by oli-obk** [comment]
We can't do this due to the rustc integration, where we are in the rustc workspace. we used to have it but removed it during the merger
