### ISSUE TITLE
Consider deprecating `integer_arithmetic` in favor of `arithmetic_side_effects`

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/rust-clippy#10200]
Even though both lints can live separated, perhaps it might be worth considering deprecating `integer_arithmetic` in favor of `arithmetic_side_effects`.

1. `arithmetic_side_effects` can detect arithmetic operations of **any** type, not only integers, which prevents more runtime overflows or panics.
2. `integer_arithmetic` fires on trivial operations that in fact shouldn't be linted.  On the other hand, `arithmetic_side_effects` is smarter.
2.1. `Adding or Subtracting 0`¹: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=8c37520d26e4e59a85b419efc32c02c8
2.2. `Multiplying 1 or 0`¹: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=5e95f95870e7cb6d6c3df178b98c2bd2
2.3. `CTFE`: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=5144fb63c938b3796e65f91007eae9b0
2.4. `References`: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=46c03f3b0851c376113f8ea161e92d08
2.5. You can take a look at other spotted cases in https://github.com/rust-lang/rust-clippy/pulls?q=is%3Apr+author%3Ac410-f3r+is%3Aclosed.

If desired, I can introduce a new `arithmetic_side_effects` option, say `arithmetic-side-effects-only-integers` to ignore everything but integers to maintain compatibility.

###### ¹: Used to reinforce the arguments. It its known that `no_effect` and similar exist.

**Comment by c410-f3r** [comment]
Closing due to the lack of feedback.

**Comment by xFrednet** [comment]
> Closing due to the lack of feedback.

Sorry for not providing feedback earlier. We sadly get too many issues, to review them all. If you want a discussion or feedback, I recommend pinging `@rust-lang/clippy`, asking on Zulip or even better in this case, adding the `I-nominated` later to add the issue as a topic in the next meeting. :)

**Comment by c410-f3r** [comment]
Hey @xFrednet, I really appreciate your feedback and tips. Thank you very much!
