### ISSUE TITLE
Indexing into a `&Vec<T>` or `&mut Vec<T>` is slower than into a `&[T]` or `&mut [T]`

### ISSUE THREAD

**Issue by Shnatsel** [rust-lang/rust-clippy#10269]
### What it does

Recommend slicing a `&Vec<T>` or `&mut Vec<T>` before indexing into it multiple times.

A similar lint [`ptr_arg`](https://rust-lang.github.io/rust-clippy/master/#ptr_arg) already exists, but only covers style concerns and only applies to function arguments. This lint is different because it applies regardless of where the borrowed `Vec` comes from. 

Perhaps the description of the [`ptr_arg`](https://rust-lang.github.io/rust-clippy/master/#ptr_arg) lint should also be updated to mention performance implications, and the `performance` category added.

### Lint Name

indirect_indexing

### Category

perf

### Advantage

Indexing into a `&Vec<T>` or `&mut Vec<T>` is slower than into a `&[T]` or `&mut [T]` for a number of reasons:

1. Indexing into a borrowed `Vec` requires **two pointer dereferences** instead of one ([godbolt](https://godbolt.org/z/5jK9vjh3f))
2. `&mut [u8]` **provides aliasing guarantees** while a `Vec` or `&mut Vec` does not ([godbolt](https://godbolt.org/z/PazT7Gnf9); the `noalias` for the `Vec` only applies to the on-stack part of the `Vec` but not the heap storage, thanks to @saethlin for clarifying)
3. Unlike a `Vec`, a slice is fixed-size, which makes it much easier for the optimizer to **elide bounds checks** (there's an example [in my article on bounds checks](https://shnatsel.medium.com/how-to-avoid-bounds-checks-in-rust-without-unsafe-f65e618b4c1e))

As a real-world example, a simple conversion from `&mut Vec<T>` to `&mut [T]` has [sped up the `fastblur` crate by 15%.](https://github.com/fschutt/fastblur/pull/3)

### Drawbacks

 - A slight increase in code complexity, except when changing the function argument in a non-public function
 - ~~Potential false positives on `&mut Vec<T>` if it's being both extended and indexed into~~ the `ptr_arg` lint [already solved this](https://github.com/nnethercote/perf-book/issues/50#issuecomment-1411444043)

### Example

The problematic pattern looks like this:

```rust
pub fn iter_vec(input: &Vec<u8>) -> u64 {
    let mut acc: u64 = 0;
    for i in 0..input.len() {
        acc += input[i] as u64; // slow indexing
    }
    acc
}

```

A better way is to slice the `Vec` and index into the slice:

```rust
pub fn iter_vec_opt(input: &Vec<u8>) -> u64 {
    let slice = input.as_slice(); // improves performance
    let mut acc: u64 = 0;
    for i in 0..slice.len() {
        acc += slice[i] as u64; // faster indexing thanks to the slice
    }
    acc
}
```

**Comment by Shnatsel** [comment]
It might. This example is deliberately simplified; it can be reduced to a `fold()` or even a `sum()`, and I would not be surprised to find there are lints for that.

**Comment by Jarcho** [comment]
Assembly output for both for your examples are the same. It's probably possible to make an example where the output is different, but I don't see this being useful in general over `ptr_arg`.

**Comment by Shnatsel** [comment]
I could just add a blurb about performance to `ptr_arg`, but that would be then asking for a potentially breaking change when the same performance issue could be resolved just by slicing before you index.

I feel this info needs to be surfaced *somehow,* but I'm not sure what's the best way to do this. I'd love to hear from Clippy maintainers about the best way to approach this.

**Comment by TimeEngineer** [comment]
Ok I think I understand what you say.
You would like a `lint` if `clippy` can't remove index (When there are a lot of indexing for example) ?

**Comment by Shnatsel** [comment]
Yes, AFAIK this performance pitfall only applies to indexing, although admittedly I haven't checked that with godbolt.

**Comment by TimeEngineer** [comment]
FYI: this problem is also related to `&[T]`, `&[T]` is a little more faster than `&Vec<T>`, because of the deference,
as you can see, I can also optimize slice ^^
https://godbolt.org/z/EvW3GhMEv

**Comment by TimeEngineer** [comment]
FYI: This problem is also related to `&[T]`, `&[T]` is a bit faster than `&Vec<T>` because of deference,
but we can also optimize `&[T]` if we know his length ^^
For example: https://godbolt.org/z/x1PKoYrvc
If you give array as input, then you will not encounter this problem

**Comment by Shnatsel** [comment]
@TimeEngineer those snippets are not equivalent. Your optimized snippets immediately panics because you're indexing out of bounds in the "optimized" version.

**Comment by TimeEngineer** [comment]
@Shnatsel I provided another link, sorry if you saw the wrong one :sweat_smile:

**Comment by Shnatsel** [comment]
Yes, I wrote [an entire article](https://shnatsel.medium.com/how-to-avoid-bounds-checks-in-rust-without-unsafe-f65e618b4c1e) about this kind of optimization. 

That's not really what this lint is about; I just want to get rid of the two dereferences on every access instead of one, first and foremost.

**Comment by TimeEngineer** [comment]
It's only about the deference optimization ?

**Comment by Shnatsel** [comment]
I see, thank you. Since [ptr_arg](https://rust-lang.github.io/rust-clippy/master/#ptr_arg) lint already exists and the performance impact outside that is unproven, I'll go ahead and close this.
