### ISSUE TITLE
suggestion: .rev().next()

### ISSUE THREAD

**Issue by bojanserafimov** [rust-lang/rust-clippy#10274]
### What it does

Suggest `.next_back()` insteaad of `.rev().next()` when that's equivalent.

### Lint Name

iter_rev_next

### Category

pedantic

### Advantage

People will point it out at code review anyway. Might as well spare them some typing

### Drawbacks

I haven't thought about edge cases where applying the suggestion would not be correct

### Example

```rust
foo.iter().rev().next()
```

Could be written as:

```rust
foo.iter().next_back()
```

**Comment by KisaragiEffective** [comment]
This is applicable when the type of `foo.iter()` is [`DoubleEndedIterator`](https://doc.rust-lang.org/std/iter/trait.DoubleEndedIterator.html): both `rev` and `next_back` requires it as a bound.
