### ISSUE TITLE
needless cast

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust-clippy#1027]
Warn on casts that could also be a coercion and suggest using an intermediate let binding.

Examples: 

* `b"foo" as &[u8]`
* `&mut x as *mut T`

Basically we can check if there's a cast whose lhs has an adjusted type that's equal to the rhs.

**Comment by camsteffen** [comment]
I believe this is [`trivial_casts`](https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#trivial-casts).
