### ISSUE TITLE
uninlined_format_args doesn't seem to provide better code in assert

### ISSUE THREAD

**Issue by BusyJay** [rust-lang/rust-clippy#10281]
### Description

Consider following:
```
assert!(
    self.value_type_str(),
    "key \"{}\" does not refer to a string",
    a
);
```

Clippy suggest to write it as:
```
assert!(
    self.value_type_str(),
    "{}",
    "key \"{a}\" does not refer to a string"
);
```

To me, the second one is quite confusing as it inline formatting but requires additional `{}` format arg. I suppose this is due to the implementation of `assert` macro, but it's really not better than the first one.

### Version

```text
rustc 1.67.0 (fc594f156 2023-01-24)
binary: rustc
commit-hash: fc594f15669680fa70d255faec3ca3fb507c3405
commit-date: 2023-01-24
host: aarch64-apple-darwin
release: 1.67.0
LLVM version: 15.0.6
```

**Comment by Alexendoo** [comment]
Should be fixed by #10055, it's a bug that `panic`/`assert` macros were linted in code that isn't using the 2021 edition, which then caused the rustc `non_fmt_panics` lint to fire
