### ISSUE TITLE
extend manual_strip with {,r}split_once

### ISSUE THREAD

**Issue by hellow554** [rust-lang/rust-clippy#10373]
### Summary

I encountered this code in production:

```rust
fn parse_checked_line(&mut self, line_num: usize, line: &str) -> Result<()> {
    if let Some((_, command)) = line.split_once(";$") {
        self.parse_command(command.trim(), line_num)
    } else if let Some((_, output)) = line.split_once(";`") {
        self.parse_expected(output.trim(), line_num)
    } else {
        Ok(())
    }
}
```

If I see it correctly you can easily replace `if let Some((_, command)) = line.split_once(";$")` with `if let Some(cmd) = line.split_prefix(";$")`, right?

So my suggestion would be, if the if let chain as `split_once` and the first item of result of the binding is ignored and the second one is used, suggest `split_once`.

Similarly `if let Some((cmd, _)) = line.rsplit_once("bla")` can be replaced by `split_suffix("bla")`.

Is that correct?

### Lint Name

manual_strip

### Version

```text
rustc 1.69.0-nightly (4507fdaaa 2023-02-18)
binary: rustc
commit-hash: 4507fdaaa27ea2fb59a41df2ce7d1f290da53dae
commit-date: 2023-02-18
host: x86_64-unknown-linux-gnu
release: 1.69.0-nightly
LLVM version: 15.0.7
```

**Comment by samueltardieu** [comment]
> If I see it correctly you can easily replace `if let Some((_, command)) = line.split_once(";$")` with `if let Some(cmd) = line.split_prefix(";$")`, right?

I don't think so: `"abc;$def".split_once(";$")` returns `("abc", "def")` while `"abc;$def".strip_prefix(";$")` will return `None` as the string does not start with the needle.

**Comment by hellow554** [comment]
You're absolutely right! Thanks for the clarification :)
