### ISSUE TITLE
Warn on redundant update

### ISSUE THREAD

**Issue by ndmitchell** [rust-lang/rust-clippy#10476]
### What it does

If your update changes no fields, e.g. `MyRecord {..value}` then the update is providing very little value, and `value` directly would be better.

### Lint Name

redundant_update

### Category

style

### Advantage

- Simpler.

### Example

```rust
MyRecord { ..value}
```

Could be written as:

```rust
value
```

**Comment by samueltardieu** [comment]
Are they really equivalent? `MyRecord { ..value }` moves `value` unless it implements `Copy`, so wouldn't `MyRecord { ..value }` be equivalent to `value`, and not `value.clone()`?
