### ISSUE TITLE
Team members link in CONTRIBUTING.md is broken

### ISSUE THREAD

**Issue by bluthej** [rust-lang/rust-clippy#10521]
The link to the list of team members in [CONTRIBUTING.md](https://github.com/rust-lang/rust-clippy/blob/master/CONTRIBUTING.md) yields a 404 error. The file it's supposed to link to does not seem to exist.

**Comment by llogiq** [comment]
Tnis is now in [triagebot.toml](https://github.com/rust-lang/rust-clippy/blob/master/triagebot.toml).
