### ISSUE TITLE
Make lint formulation more consistent

### ISSUE THREAD

**Issue by bluthej** [rust-lang/rust-clippy#10631]
### Description

When trying to figure out how I should formulate the [documentation](https://github.com/rust-lang/rust-clippy/blob/83e42a2337dadac915c956d125f1d69132f36425/clippy_lints/src/methods/mod.rs#L3196) for `clear_with_drain`, I had a look at how other lints are formulated, and I found a few different ways which are pretty much equivalent.

Here are the statistics I gathered:

| Formulation | Number of occurrences |
|---------------|---------------------------|
| "Checks for usage" | 59 |
| "Checks for use" | 16 |
| "Checks for usages" | 12 |
| "Checks for uses" | 6 |
| "Checks for using" | 3 |
| "Detect uses" | 2 |
| "Detects uses" | 2 |
| "Check for use" | 1 |
| "Detect use" | 1 |
| Total | 102 |

> Note: I used case-insensitive search and I made sure plural and singular forms were counted separately by using `[^s]` in the regexes for singular forms. Also, to double check, the Total is not just the sum of all the occurrences, it was obtained by a single call with a regex that matches all these cases (and more which I did not include because they had 0 occurrences).

These represent about 1/6 of the total number of lints, which is quite significant.

I propose to standardize the formulation, opting for the most frequent one, i.e. **Checks for usage**. Of course, I am open to picking a different one if a native English speaker (which I'm not) tells me that it is not the most idiomatic 🙂 

### Additional Labels

@rustbot label +C-enhancement +A-documentation

**Comment by xFrednet** [comment]
I think this is a good proposal. You're welcome to create a PR with these changes. We might also be able, to create a custom lint for this :)

**Comment by bluthej** [comment]
Good idea! I hadn't thought of that 🙂

I will submit a quick PR with the standardized formulation and then open an issue for a new lint.
