### ISSUE TITLE
needless_bool loses comments when invoked with --fix

### ISSUE THREAD

**Issue by yuzisee** [rust-lang/rust-clippy#10710]
### Summary

```
warning: this if-then-else expression returns a bool literal
    --> src/model_view_impl/project_main/mvc_models.rs:1580:11
     |
1580 | /           if acp_spec.cancellation_required() == false {
1581 | |             // ... This is an important comment with a detailed discusion justifying the business logic / business decisions behind this specific behavior.
1582 | |             true
1583 | |           } else {
1584 | |             false
1585 | |           }
     | |___________^ help: you can reduce it to: `acp_spec.cancellation_required() == false`
     |
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_bool
     = note: `#[warn(clippy::needless_bool)]` on by default
```

With the lint above, when used with `--fix` causes the following code changes:

```
         (false, _) => true,
         // Cancellation info not available...
         (true, Some(acp_spec)) => {
-          if acp_spec.cancellation_required() == false {
-            // ... This is an important comment with a detailed discusion justifying the business logic / business decisions behind this specific behavior.
-            true
-          } else {
-            false
-          }
+          !acp_spec.cancellation_required()
         }
         _ => false,
       }
```

but the comment line is lost.

While I'm not sure where the comments should be retained it seems like a bad idea to remove them, especially if they are describing some important business logic that justifies the behavior.

### Reproducer

I tried this code: `cargo clippy --fix`

```rust
if acp_spec.cancellation_required() == false {
  // ... This is an important comment with a detailed discusion justifying the business logic / business decisions behind this specific behavior.
  true
} else {
  false
}
```

#### I expected to see this happen:

The comment is somehow preserved, and at the very least, not completely deleted.

#### Instead, this happened:

The comment was removed, and only `!acp_spec.cancellation_required()` remained.

### Version

- `cargo --version` cargo 1.69.0 (6e9a83356 2023-04-12)
- `rustc --version` rustc 1.69.0 (84c898d65 2023-04-16)
- `cargo clippy --version` clippy 0.1.69 (84c898d6 2023-04-16)

**Comment by blyxyas** [comment]
I'm sorry but this probably won't ever get fixed. `needless_bool` is a "late" lint, so it works on the HIR level. This means that we cannot detect really comments without doing tremendous amounts of work. Maybe displaying a warning about this behaviour would "solve" the problem?

**Comment by yuzisee** [comment]
Is there a way to mark lints as "unsafe for --fix"? Mostly I'm trying to figure out which lints are safe to use with --fix since ideally we can run this from CI.

The documentation has a "Known Problems" section,
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/523543/235387270-6f1997dc-fcc8-430e-8d24-a7f5bdc27761.png">
but reading every single Known Problems of every single lint to build a custom list of what is considered "safe to use with --fix" seems like not quite the right developer workflow (maybe I'm missing something; are there eventual plans for `--fix-safe` option instead?)

**Comment by blyxyas** [comment]
AFAIK there aren't any plans to implement a safe fix. But I think that there should an option like that.

I'll comment it on the Zulip chat and open a PR in a few hours if everything goes smoothly.

**Comment by samueltardieu** [comment]
> I'm sorry but this probably won't ever get fixed. `needless_bool` is a "late" lint, so it works on the HIR level. This means that we cannot detect really comments without doing tremendous amounts of work. Maybe displaying a warning about this behaviour would "solve" the problem?

I'm not sure I follow this reasoning: `NEEDLESS_BOOL_ASSIGN`, a late lint in the same file as `NEEDLESS_BOOL`, does this check and does not rewrite the `if` expression if there is any comment inside a branch (and there are tests fr this). For this I used `span_extract_comment()` on the whole `if` expression.

I'll have a look at this issue.

@rustbot claim
