### ISSUE TITLE
run linkcheck in clippy ci 

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-clippy#10711]
### Summary

This often causes pain when doing clippy->rustc syncs, as @flip1995  pointed out we could we should see to we can run linkcheck in clippy CI to catch this earlier https://github.com/rust-lang/rust/pull/110718#issuecomment-1519557770

**Comment by flip1995** [comment]
This should be relatively easy to add to our `remark.yml` CI with the [`linkcheck.sh` script](https://github.com/rust-lang/rust/blob/master/src/tools/linkchecker/linkcheck.sh) from the rustc repo. 

I would just download it in CI through a github permalink and then run it on the book with:

```bash
cd book
sh linkcheck.sh clippy  # "clippy" is the name of the book and doesn't really matter what we put here, I think
```
