### ISSUE TITLE
Lint unnecessary `.into_iter()` in function arguments

### ISSUE THREAD

**Issue by yongqli** [rust-lang/rust-clippy#10743]
### What it does

If someone didn't know that various functions can take an `impl IntoIterator` instead of an `impl Iterator` for their arguments, they might have wrote useless explicit `.into_iter()`s.

See also https://github.com/rust-lang/rust-clippy/issues/1094

### Lint Name

explicit_into_iter_fn_arg

### Category

pedantic

### Example

```rust
fn main() {
    let mut v = vec![];
    v.extend(vec![0].into_iter());
}
```

Could be written as:

```rust
fn main() {
    let mut v = vec![];
    v.extend(vec![0]);
}
```

**Comment by y21** [comment]
@rustbot claim

I feel like instead of adding a new lint for this, we could just add it to the existing `useless_conversion` lint that you linked? Seems like another relevant case that it could handle
