### ISSUE TITLE
Use `.extend(some_iter)` over `.extend(some_iter.collect())`

### ISSUE THREAD

**Issue by b05902132** [rust-lang/rust-clippy#10762]
### What it does

`Extend::extend` takes an `IntoIterator`. Since every `Iterator` is also an `IntoIterator`, you can `extend` from an iterator; `collect()` an iterator before `extend()` from it leads to extra memory allocations and extra copying, and is probably a mistake.

### Lint Name

extend_collect

### Category

suspicious, perf

### Advantage

Fewer memory allocations and fewer copying.

### Drawbacks

Maybe `collect()` actually leads to a performance boost because of, say, better cache behavior, and is actually intentional.

### Example

```rust
let mut v = vec![0i32];
v.extend((1..10).collect::<Vec<_>>());
```

Could be written as:

```rust
let mut v = vec![0i32];
v.extend(1..10);
```

**Comment by b05902132** [comment]
I saw this in the wild: https://github.com/huhu/rust-search-extension/blob/8942eadf1e7c721294e87c7e9beac0356e0fdd2d/rust/src/tasks/crates.rs#L66

**Comment by samueltardieu** [comment]
This is not even specific to `extend`. It could be used everywhere a `IntoIterator` is expected.
