### ISSUE TITLE
Needless question mark

### ISSUE THREAD

**Issue by killercup** [rust-lang/rust-clippy#1077]
Given that `ProgrammError` is a "good" error (i.e., it implements `From` for various other `Error`s), this code

``` rust
fn json_from_file(file_name: &str) -> Result<String, ProgramError> {
    let content = read_file_to_string(&file_name)?;

    Ok(content)
}
```

can also be written as

``` rust
fn json_from_file(file_name: &str) -> Result<String, ProgramError> {
    read_file_to_string(&file_name).map_err(ProgramError::from)
}
```

**Comment by killercup** [comment]
I'm not sure if suggesting `.map_err(From::from)` is better, but it works as well.

**Comment by mcarton** [comment]
Marking `E-hard` given that our `implements_trait` function does not work with generics, but if it did that would be `E-medium`.

**Comment by mcarton** [comment]
I usually prefer `Trait::foobar` to `Type::foobar`. But I'm not sure if one is more common than the other.

**Comment by killercup** [comment]
Lol, in any other project I'd think having 'A-unnecessary' was pretty rude 😉 

I generally prefer `Trait::method` as well, but it reads so weird when it's of the form `Name::name`!

**Comment by mcarton** [comment]
> in any other project I'd think having an issue labeled 'A-unnecessary' was pretty rude :wink:

@Manishearth maybe you could rename that label to eg. 'A-unnecessary-code' or something?

**Comment by killercup** [comment]
Haha, no need to do that on my account, I think it's quite funny! (And it's not like it's called _A-hole_ or something like that 😄 )

**Comment by Manishearth** [comment]
ahahaha love that label.

I don't think it has a chance of offending, really, so we could keep it as is. Or change it. meh.

You can edit labels in the labels tab when you open the list of issues. It's ... counterintuitive.

**Comment by mcarton** [comment]
> It's ... counterintuitive.

Oh… that's a button on the right of the issue search bar… I would have imagined that's to search by labels -_-

**Comment by camsteffen** [comment]
I declare this issue to appear when I search for "question mark".

**Comment by Manishearth** [comment]
Yeah I'd say the question mark operator makes the original code nicer than this so we can close it

**Comment by camsteffen** [comment]
I think the original request is still relevant if you replace `try!` with `?`.

**Comment by camsteffen** [comment]
Well...I was thinking of the case where the error does not need conversion.

**Comment by Manishearth** [comment]
Yeah exactly

**Comment by Manishearth** [comment]
Also IME it's kinda normal to do this so you don't have to think about the error type and so you can easily move code around, so I'm not sure if we should lint for even the more restricted "types are the same" case

**Comment by camsteffen** [comment]
That makes sense. Preference for the question mark gives you "refactoring flexibility" at little cost. Closing again! (someone could create a new issue, but it would probably be restriction so meh)
