### ISSUE TITLE
Don't emit `clippy::useless_conversion` on type aliases

### ISSUE THREAD

**Issue by Centri3** [rust-lang/rust-clippy#10773]
### Description

Currently, `clippy::useless_conversion` will still be emitted even on type aliases, for example:
```rust
HWND::from(0isize)
```
Clippy will suggest:
```rust
0isize
```
This conveys the type worse, but looking over rustc_hir, it doesn't seem whether it's a type alias is available so I don't know if this is possible to implement. I saw a few things relating to whether it's a trait alias but not whether it's a type alias. If this is possible, I'm happy to implement this :slightly_smiling_face:

### Version

```text
rustc 1.71.0-nightly (9ecda8de8 2023-04-30)
binary: rustc
commit-hash: 9ecda8de85ce893cc3fc748ab06be0b8250147a7
commit-date: 2023-04-30
host: x86_64-unknown-linux-gnu
release: 1.71.0-nightly
LLVM version: 16.0.2
```

### Additional Labels

@rustbot label +C-enhancement

**Comment by samueltardieu** [comment]
IMO, `From::from()` conveys the idea of a conversion, I'm not surprised that it warns even in the case of a type alias.

Note that `0isize as HWND` would not trigger a warning, and for me it better conveys the idea of a representation rather than a conversion.

**Comment by Centri3** [comment]
That's fair enough, though `0isize as HWND` also warns if you have `clippy::as_conversions` on warn (which is actually really handy, so I don't feel like just disabling that would be wise). And I also agree with this since an as conversion can silently change types.

I feel `HWND::from(0isize)` would be better though, since if HWND in some world changed which primitive type it was an alias of, `0isize as HWND` would still compile; even if it could suddenly wrap and cause issues. Along with disallowing default_numeric_fallback and you know exactly where issues may arise when updating.

0isize would function the same, but also wouldn't convey its purpose very well.

**Comment by Centri3** [comment]
Created #10778 which implements this.
