### ISSUE TITLE
Merge some lints together

### ISSUE THREAD

**Issue by mcarton** [rust-lang/rust-clippy#1078]
Clippy has a lot of lints now, but sometimes there is not much difference between two lints. I think we should merge some of them together.
# Advantages
- Slightly shorter [big-list-of-all-the-lints](https://github.com/Manishearth/rust-clippy#lints).
- Less documentation duplication (see [`new_without_default`](https://github.com/Manishearth/rust-clippy/wiki#new_without_default) and [`new_without_default_derive`](https://github.com/Manishearth/rust-clippy/wiki#new_without_default_derive)).
- Two lints should be different only when one would want to set different allow/warn/deny level for them. Why would anyone ever want to forbid calls to `Option::unwrap` but not `Result::unwrap`?
- Less confusing as to why there are two different lints for that.
# Disadvantages
- Might be a breaking change, but IIRC `rustc` has a way to indicate a lint was renamed (and hopefully handle properly `#[allow]`s etc. on it).
- Need to find new names.
# Candidates

Here are some candidates (there might be other):
- [`block_in_if_condition_expr`](https://github.com/Manishearth/rust-clippy/wiki#block_in_if_condition_expr) and [`block_in_if_condition_stmt`](https://github.com/Manishearth/rust-clippy/wiki#block_in_if_condition_stmt) → rename them both to `block_in_if_condition`;
- [`option_map_unwrap_or`](https://github.com/Manishearth/rust-clippy/wiki#option_map_unwrap_or) and [`option_map_unwrap_or_else`](https://github.com/Manishearth/rust-clippy/wiki#option_map_unwrap_or_else) → `option_map_unwrap`;
- [`result_unwrap_used`](https://github.com/Manishearth/rust-clippy/wiki#result_unwrap_used) and [`option_unwrap_used`](https://github.com/Manishearth/rust-clippy/wiki#option_unwrap_used) → `unwrap_used`;
- [`for_loop_over_option`](https://github.com/Manishearth/rust-clippy/wiki#for_loop_over_option) and [`for_loop_over_result`](https://github.com/Manishearth/rust-clippy/wiki#for_loop_over_result) → ?
- [`new_without_default`](https://github.com/Manishearth/rust-clippy/wiki#new_without_default) and [`new_without_default_derive`](https://github.com/Manishearth/rust-clippy/wiki#new_without_default_derive) → `new_without_default` (the only difference is how the suggestion is built);
- [`string_add`](https://github.com/Manishearth/rust-clippy/wiki#string_add) and [`string_add_assign`](https://github.com/Manishearth/rust-clippy/wiki#string_add_assign) → `string_add`;
- [`identity_op`](https://github.com/Manishearth/rust-clippy/wiki#identity_op) and [`modulo_one`](https://github.com/Manishearth/rust-clippy/wiki#modulo_one) → `useless_arithmetic`

**Comment by Manishearth** [comment]
Bit iffy on string_add, but otherwise LGTM.

Perhaps this should be tabled till the RfC at https://github.com/Manishearth/rust-clippy/issues/533? I'm thinking of starting the RfC this week or so, so add more issues to that thread if you find them.

**Comment by mcarton** [comment]
> Bit iffy on string_add, but otherwise LGTM.

There already is `assign_op_pattern` vs. `assign_ops` for the `+` vs. `+=` difference (and those are different, they should not be merged), so keeping the distinction between those just for the `String` case seems redundant IMO.

**Comment by Manishearth** [comment]
I guess so.
