### ISSUE TITLE
unused `allow` annotation

### ISSUE THREAD

**Issue by laralove143** [rust-lang/rust-clippy#10801]
### What it does

we add `#[allow(lint)]` to a function to suppress a lint, when that function's body changes and no longer raises that lint, we have the old `#[allow(lint)]` annotation silently staying there

we might also add `#[allow(lint)]` to a function because we're sure it will raise that lint, and we turn out to be wrong we dont realize we added that for no reason

### Lint Name

unused_allow

### Category

style

### Advantage

- keeps code clean
- doesnt give the idea that the function raises the lint
- gives no hint to the history of a function

### Drawbacks

we might wanna allow a lint to express that we dont care if this happens in the future, in which case we can also allow this lint to express that more explicitly

### Example

say we think ignoring an error is fine
```rust
#[allow(unused_must_use)]
fn foo() {
  let _: Result<_, _> = fallible();
}
```
then we realize we do need to handle the error so we rewrite the function to
```rust
#[allow(unused_must_use)]
fn foo() {
  fallible().handle();
}
```
but here `#[allow(unused_must_use)]` stays even tho it doesnt need to

**Comment by xFrednet** [comment]
Hey @laralove143, this is a feature which would need to be implemented in the compiler and not Clippy. There was already an RFC to add a feature like this, see: https://github.com/rust-lang/rfcs/pull/2383. If you're interested, you can ready the tracking issue and the linked Zulip conversation:

* https://github.com/rust-lang/rust/issues/54503
* https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/Expect.20attribute.20mental.20model/near/340449104

**Comment by laralove143** [comment]
as far as i understand, that only works when the allow is given an `expect` attribute, why is that required?

**Comment by xFrednet** [comment]
I'm closing this issue, as the discussion moved into the tracking issue. If such a lint would be added, it would need to be implemented in rustc anyways :)
