### ISSUE TITLE
Add a feature to show just the summary suggestion statistics

### ISSUE THREAD

**Issue by nyurik** [rust-lang/rust-clippy#10837]
### Description

Add a new flag to `cargo clippy`, for example `--summary` to print output similar to below without the details of each suggestion. If `--fix` is given, it could also print `(3 out of 7 was fixed)` at the end.

### Use cases
* View suggestion summary using CLI
* Publish automated CI comment on a pull request (markdown output?)
  * This allows non-blocking CI Clippy run.
  * Currently, Clippy is mostly used as a CI gatekeeper (pass/fail), but not suggestions.

### Alternatives

I currently use this somewhat hacky way to print a similar summary. It allows one to quickly focus on just one small subset of the issues in a single PR to make reviewing easier (I ran it on the cxx project):

```
# This uses ripgrep, could could be done with grep as well, possibl
❯ cargo clippy --workspace --tests --bins --lib --benches --examples -- -W clippy::pedantic 2>&1 | rg --trim -- '-W clippy::' | sort | uniq -c | sort -h -r

     11 = note: `-W clippy::let-underscore-untyped` implied by `-W clippy::pedantic`
      5 = note: `-W clippy::semicolon-if-nothing-returned` implied by `-W clippy::pedantic`
      3 = note: `-W clippy::redundant-closure-for-method-calls` implied by `-W clippy::pedantic`
      3 = note: `-W clippy::match-wildcard-for-single-variants` implied by `-W clippy::pedantic`
      3 = note: `-W clippy::items-after-statements` implied by `-W clippy::pedantic`
      1 = note: `-W clippy::unused-async` implied by `-W clippy::pedantic`
      1 = note: `-W clippy::ptr-as-ptr` implied by `-W clippy::pedantic`
      1 = note: `-W clippy::must-use-candidate` implied by `-W clippy::pedantic`
      1 = note: `-W clippy::missing-errors-doc` implied by `-W clippy::pedantic`
      1 = note: `-W clippy::implicit-clone` implied by `-W clippy::pedantic`
      1 = note: `-W clippy::cast-possible-truncation` implied by `-W clippy::pedantic`
```

### Version

```text
rustc 1.69.0 (84c898d65 2023-04-16)
binary: rustc
commit-hash: 84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc
commit-date: 2023-04-16
host: x86_64-unknown-linux-gnu
release: 1.69.0
LLVM version: 15.0.7
```

### Additional Labels

@rustbot label +C-enhancement
@rustbot label +C-an-interesting-project

**Comment by blyxyas** [comment]
Isn't this too much of a niche case? I think we should nominate this for the next meeting.

**Comment by nyurik** [comment]
@blyxyas I think it goes a bit beyond a niche - tools like `ripgrep` also have a summary mode, even though most of the time you want all found instances to be shown as is.

In a CI setup, clippy can only be used as a gatekeeper - either pass or fail a build.  Having summary mode would allow a new usecase - add a summary comment to the pull request without blocking the merge.  This way repo admins can decide to ignore or handle clippy suggestions, while using CI for the more important aspect - code correctness (compiles / builds / tests).

**Comment by flip1995** [comment]
We discussed this in the [last Clippy meeting](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Meeting.202023-05-30/near/362173594). While we see that this can be useful, we don't think that it should be implemented in Clippy, but rather in `cargo` or `rustc` and then just be inherited by Clippy. For the CI use case, it should be ok to just copy and paste your code snippet. If you want, you can update the section about CI in the book and add this snippet as a tip for other people that are looking for it.

**Comment by nyurik** [comment]
@flip1995 thx for discussing it.  I have noticed that Clippy sometimes doesn't re-print the ID of the lint on each instance.  Would it be possible to force it?

**Comment by nyurik** [comment]
@flip1995 right, but that also means that my approach with `sort | uniq` won't work properly until we introduce something to the rustc compiler?

**Comment by flip1995** [comment]
Yes. You might be able to get what you need with `--error-format=json` and then use `jq` to filter through it. The json output contains the lint name:

<details>
<summary>JSON output</summary>

```json
{
   "message":"use of a disallowed/placeholder name `foo`",
   "code":{
      "code":"clippy::disallowed_names",
      "explanation":null
   },
   "level":"warning",
   "spans":[
      {
         "file_name":"main.rs",
         "byte_start":20,
         "byte_end":23,
         "line_start":2,
         "line_end":2,
         "column_start":9,
         "column_end":12,
         "is_primary":true,
         "text":[
            {
               "text":"    let foo = 10;",
               "highlight_start":9,
               "highlight_end":12
            }
         ],
         "label":null,
         "suggested_replacement":null,
         "suggestion_applicability":null,
         "expansion":null
      }
   ],
   "children":[
      {
         "message":"for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#disallowed_names",
         "code":null,
         "level":"help",
         "spans":[
            
         ],
         "children":[
            
         ],
         "rendered":null
      },
      {
         "message":"`#[warn(clippy::disallowed_names)]` on by default",
         "code":null,
         "level":"note",
         "spans":[
            
         ],
         "children":[
            
         ],
         "rendered":null
      }
   ],
   "rendered":"warning: use of a disallowed/placeholder name `foo`\n --> main.rs:2:9\n  |\n2 |     let foo = 10;\n  |         ^^^\n  |\n  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#disallowed_names\n  = note: `#[warn(clippy::disallowed_names)]` on by default\n\n"
}
```

</details>

**Comment by nyurik** [comment]
For anyone who may want to run it locally, the `jq` version:

```
cargo clippy --all-targets --workspace --message-format=json --quiet -- -W clippy::pedantic \
   | jq -r '.message.code.code | select(. != null and startswith("clippy::"))' \
   | sort | uniq -c | sort -h -r
```
