### ISSUE TITLE
Lint to remove instances of `pub(self)` and `pub(in self)`

### ISSUE THREAD

**Issue by LikeLakers2** [rust-lang/rust-clippy#10964]
### What it does

This lint would check for instances of `pub(self)` and `pub(in self)` and suggest that they be removed.

### Advantage

Removes extraneous visibility syntax where it has no effect at all. Per [Visibility and Privacy](https://doc.rust-lang.org/reference/visibility-and-privacy.html#pubin-path-pubcrate-pubsuper-and-pubself) from the Rust Reference:

> `pub(self)` [...] is equivalent to `pub(in self)` or not using `pub` at all.

### Drawbacks

Some codebases may use `pub(self)` or `pub(in self)` to denote a item that is meant for use within a submodule, and the lack of such to denote an item meant only for use within the same file.

### Example

```rust
pub(self) struct State;
```

Could be written as:

```rust
struct State;
```

**Comment by Centri3** [comment]
These two(three?) lints could probably be paired together. @rustbot claim

**Comment by LikeLakers2** [comment]
@Centri3 Fair - I just figure it's best to make two separate lint suggestion issues, since one's about code style and the other is about removing needless syntax.

**Comment by Centri3** [comment]
I meant they could be paired into the same PR, and lint pass :D separate issues is fine.
