### ISSUE TITLE
Warn against using legacy std integral constants

### ISSUE THREAD

**Issue by pitaj** [rust-lang/rust-clippy#10995]
### What it does

This lint triggers on usage of legacy integral constants and functions, such as:

- `std::i32::MAX`
- `u64::max_value()`

### Advantage

Enforce a consistent style across the ecosystem.

This lint should probably be placed into the `clippy::style` group.

### Drawbacks

Older projects will experience some churn, but this should be trivially auto-fixable in most cases.

[T-libs-api opposes deprecating this outright](https://github.com/rust-lang/rust/pull/107587#issuecomment-1599053799) so a clippy lint is the next best thing.

### Example

```rust
if x == std::i32::MAX {
```

Could be written using the associated constant as:

```rust
if x == i32::MAX {
```

**Comment by xFrednet** [comment]
The PR was closed due to inactivity, if anyone is interested in picking up this issue, that PR would be a good starting point. We also discussed, how the lint should behave in that PR.
