### ISSUE TITLE
Categorizing tests using their names

### ISSUE THREAD

**Issue by blyxyas** [rust-lang/rust-clippy#11037]
[ui_test:](https://github.com/oli-obk/ui_test)

> ## Magic behavior
> * Tests are run in order of their filenames (files first, then recursing into folders). So if you have any slow tests, prepend them with a small integral number to make them get run first, taking advantage of parallelism as much as possible (instead of waiting for the slow tests at the end).

Could we categorize these tests, so that tests with more lines get assigned lower numbers?
For example:

* `test1.rs` 20 lines
* `test2.rs` 550 lines
* `test3` 50 lines

Using `cargo dev update-lints`, we could rename this files based on their line number.
Obviously line number isn't a perfect metric, but it makes a rough categorization starting with the biggest files. Good enough.

Before implementing this, we should take into account that this may confuse new contributors and work to document this behavior and maybe adding a `tests/` README file documenting this?

@rustbot label: +C-an-interesting-project

**Comment by Alexendoo** [comment]
That sounds confusing, what's the benefit?

**Comment by Centri3** [comment]
I'm not too sure how much this would help, as tests take <1s already, you aren't really waiting at the end for a select few to finish (afaict?)

**Comment by xFrednet** [comment]
I agree with the others, that categorizing them based on their length could get confusing. But, I do think, we could clean up/categorize our test more. Currently, we have one gigantic folder with so many files that it's sometimes had to find the correct test, and GH just stops loading all files. Maybe we could try to categorize them based on what they lint. Similar to how we group `method` and `ty` lints together in `clippy_lints` :)
