### ISSUE TITLE
Small: Optimize `suspicious_xor_used_as_pow`

### ISSUE THREAD

**Issue by blyxyas** [rust-lang/rust-clippy#11060]
The `suspicious_xor_used_as_pow` lint is very poorly done (it was my first lint :heart:!), [this lines in particular](https://github.com/rust-lang/rust-clippy/blob/1990b72e8abde637414a683c24ea46f1dd7f830b/clippy_lints/src/suspicious_xor_used_as_pow.rs#L36-L41), instead of getting the context, it takes a snippet of the code. It's horrible.

If someone could fix it, it would improve a lot that lint's performance!

cc @Centri3 Maybe interesting for you?

**Comment by Centri3** [comment]
Hmm I'll take a look. I'm a bit curious on `instead of getting the context`, unless I'm missing something `NumericLiteral` requires a snippet...

This could probably be rewritten to just use the `LitKind`, though, at the cost of less abstraction

**Comment by blyxyas** [comment]
Sorry for the brain melt:
I meant that instead of checking a snippet (which is really slow), just get the typeck results and parse them.

**Comment by Centri3** [comment]
Hmm, is even *that* necessary? Is there any reason it can't use the `LitKind`? I don't think `Ty` has any info regarding whether it's a decimal or not, so at the end of day I believe a snippet will likely be needed regardless.
