### ISSUE TITLE
Optimize HashSet contains+insert usage

### ISSUE THREAD

**Issue by nyurik** [rust-lang/rust-clippy#11103]
### What it does

Optimize hashset (and possibly similar HashMap?) usage when the user first uses `contains()` to check the non-existence of a value, followed by insertion.

### Advantage

- Faster code
- Shorter code

### Example

```rust
use std::collections::HashSet;

fn main() {
    let mut vals = HashSet::new();
    insert_if(&mut vals, 10);
}

fn insert_if(set: &mut HashSet<i32>, value: i32) {
    if !set.contains(&value) {
        set.insert(value);
        println!("inserted {value:?}");
    }
}
```

Could be written as:

```rust
fn insert_if(set: &mut HashSet<i32>, value: i32) {
    if set.insert(value) {
        println!("inserted {value:?}");
    }
}
```

**Comment by lochetti** [comment]
Interesting! I will try to do it. I might need some help, though :)
If you know some other lint that has similar logic (looking if two expressions happen one after another and then linting) let me know.

@rustbot claim

**Comment by Centri3** [comment]
I believe `unnecessary_unwrap`, @lochetti ^^

**Comment by Jarcho** [comment]
`map_entry` does this for `HashMap`/`BTreeMap`.
