### ISSUE TITLE
hang in `<clippy_lints::needless_pass_by_ref_mut::MutablyUsedVariablesCtxt>::add_mutably_used_var`

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-clippy#11176]
### Summary

I don't have any code yet, I noticed this checking `rustc_mir_dataflow` with clippy that it seemed to hang. 

### Reproducer

I tried this code:

```rust
<code>
```

I expected to see this happen:

Instead, this happened:

### Version

```text
rustc 1.73.0-nightly (4eaad89dc 2023-07-17)
binary: rustc
commit-hash: 4eaad89dce57da09cebbf651e9ac3bd3292b4725
commit-date: 2023-07-17
host: x86_64-unknown-linux-gnu
release: 1.73.0-nightly
LLVM version: 16.0.5
```

**Comment by matthiaskrgr** [comment]
https://github.com/rust-lang/rust-clippy/blob/d4a6634d3745bcca70cc1063c99ed101808dbdef/clippy_lints/src/needless_pass_by_ref_mut.rs#L205 there's a suspicious `while` loop there but I'm not sure it would seemingly loop infinitly (for 20+ minutes on a single crate)

**Comment by GuillaumeGomez** [comment]
Is the problem still present?

**Comment by matthiaskrgr** [comment]
seems to be fixed
