### ISSUE TITLE
1.71.0 doc is missing  in rust-lang.github.io/rust-clippy

### ISSUE THREAD

**Issue by hehaoqian** [rust-lang/rust-clippy#11217]
### Description

https://rust-lang.github.io/rust-clippy/

The doc of 1.71.0 is missing in stable.

Beta and master includes 1.71.0

Is that forgotten?

**Comment by xFrednet** [comment]
Hey, thank you for the issue, this is quite interesting. AFAIK, this should b created automatically, not sure why it wasn't this time. @flip1995 do you maybe have an idea about this?

Meanwhile, you can use this link: https://rust-lang.github.io/rust-clippy/master/index.html#?versions=lte:71 :)

**Comment by flip1995** [comment]
Sorry, I totally forgot to do the [release](https://doc.rust-lang.org/clippy/development/infrastructure/release.html).

They are available now: https://rust-lang.github.io/rust-clippy/rust-1.71.0/index.html
