### ISSUE TITLE
repr(packed) is not ffi safe

### ISSUE THREAD

**Issue by zzwxh** [rust-lang/rust-clippy#11327]
### Description

I'm writing a binding to liburing
https://github.com/axboe/liburing/blob/liburing-2.4/src/include/liburing/io_uring.h 
line 76
The union in c is packed 
but packed union is not ffi safe
Does this mean that this struct is impossible to create and pass through ffi in rust

### Additional Labels

C-question

**Comment by Centri3** [comment]
This isn't a clippy issue. You should ask this on the rust users forum or zulip, really.

However, `repr(packed)` is not FFI safe (like you realized). `repr(packed)` and C's `packed` attribute achieve similar things, but it's not a 1-1 correspondence. When you use only `repr(packed)`, this is still `repr(Rust)`, just without any packing; thus isn't FFI safe, at all. You should use `repr(C)` instead, or `repr(C, packed)` (though iirc, this is identical to `repr(C)`.)

Please ask somewhere else though, I'm not 100% confident that's the entire truth.
