### ISSUE TITLE
Missing Entry::or_default on LinearMap

### ISSUE THREAD

**Issue by dhardy** [rust-lang/rust-clippy#11355]
### Summary

Lint [unwrap_or_default](https://rust-lang.github.io/rust-clippy/master/index.html#/unwrap_or_default) suggests use of `or_default` with [`LinearMap::Entry`](https://docs.rs/linear-map/latest/linear_map/enum.Entry.html) which does not support this method.

It may be easier to add the method to `linear-map`, but the crate is in maintenance-only mode.

### Lint Name

unwrap_or_default

### Reproducer

```rust
let mut map = LinaerMap::new();
map.entry("x").or_insert_with(Default::default);
```

**Comment by Centri3** [comment]
We could fix this by using `associated_value` on `FnCtxt`, or perhaps the `associated_item` query (but this works on the `impl` level, not the type), then checking if `or_default` exists.
