### ISSUE TITLE
 `clippy::arithmetic_side_effects` triggers on operations using `Wrapping<T>` in `no_std` environments

### ISSUE THREAD

**Issue by JarredAllen** [rust-lang/rust-clippy#11424]
### Summary

 #11145 was fixed when in an environment with access to `std`. However, the exception added to fix this only works for `std::num::Wrapping` specifically. If you're using `#![no_std]`, then the type has the name `core::num::Wrapping`, which is a different name, and the lint still triggers.

### Lint Name

arithmetic_side_effects

### Reproducer

I tried [this code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=76e62f96da51f73df207c5c40c72734f):

```rust
#![deny(clippy::arithmetic_side_effects)]
#![no_std]

use core::num::Wrapping;

struct Foo {
    wrapping: Wrapping<usize>,
}

pub fn foo(n: usize) -> usize {
    let mut value = Foo {
        wrapping: Wrapping(5),
    };
    value.wrapping += n;
    value.wrapping.0
}
```

I saw this happen:

```
error: arithmetic operation that can potentially result in unexpected side-effects
  --> src/lib.rs:14:5
   |
14 |     value.wrapping += n;
   |     ^^^^^^^^^^^^^^^^^^^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#arithmetic_side_effects
note: the lint level is defined here
  --> src/lib.rs:1:9
   |
1  | #![deny(clippy::arithmetic_side_effects)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I expected to see this happen:

No lints raised

As a note: removing the `#![no_std]` from the reproducer example silences the lint.

### Version

```text
rustc 1.72.0 (5680fa18f 2023-08-23)
binary: rustc
commit-hash: 5680fa18feaa87f3ff04063800aec256c3d4b4be
commit-date: 2023-08-23
host: x86_64-unknown-linux-gnu
release: 1.72.0
LLVM version: 16.0.5
```

**Comment by c410-f3r** [comment]
The snippet can not be reproduced with the latest nightly toolchain

**Comment by J-ZhengLi** [comment]
> The snippet can not be reproduced with the latest nightly toolchain -> https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=87c9a7a9647ade5409ea2df14536a027

Nice, seems it got fixed somehow, cuz last week I tried and it triggers the warning.

Strangely enough, when I put that reproducer into a separated ui test last week (clippy was using nightly-2023-08-24 that time), no warning emitted, but when I put it in a project, and run clippy with the same tool-chain, it lints as expected... Which is kinda weird?
But anyway, since it's fixed then I'll stop worrying too much about it~

**Comment by JarredAllen** [comment]
I think #11395 happened to fix it while making unrelated changes for other issues. I'll close this since it's now fixed.
