### ISSUE TITLE
Warn on levels of indention

### ISSUE THREAD

**Issue by lengyijun** [rust-lang/rust-clippy#11442]
### What it does

If a function has too many levels of indention, give a warning
The level can be customized, for example: 3

### Advantage

In [linux kernel](https://www.kernel.org/doc/html/v4.10/process/coding-style.html) , 3 levels is upperbound

> The answer to that is that if you need more than 3 levels of indentation, you’re screwed anyway, and should fix your program.

### Drawbacks

None

### Example

None

**Comment by Centri3** [comment]
This already exists in the lint `excessive_nesting`.
