### ISSUE TITLE
Preserve hex literals in `match` ranges

### ISSUE THREAD

**Issue by virtualritz** [rust-lang/rust-clippy#11461]
### Description

I am sorry if there is a lint/option for this already. I couldn't find any though.

Below is code from [`DNGlab`](https://github.com/dnglab/dnglab), a CLI to convert camera RAW files to DNG format.

Hex literals are used with intent in the codebase to match vendor documentation about hardware, e.g. [lenses](https://github.com/dnglab/dnglab/blob/e447946358264f2c4373060bb5dbe70ade1c124d/rawler/src/decoders/nef/lensdata.rs#L68):

``` rust
    let lensdata = match version {
      0x100 => ...,
      0x101 => ...,
      0x201 | 0x202 | 0x203 => { ... }
      [...]
```

`clippy --fix` turns this into this:

```rust

``` rust
    let lensdata = match version {
      0x100 => ...,
      0x101 => ...,
      513..=515 => { ... }
      [...]
```

It would be great if the hex literals could be preserved here, i.e. `clippy` would instead suggest/generate:

``` rust
    let lensdata = match version {
      0x100 => ...,
      0x101 => ...,
      0x201..=0x203 => { ... },
      [...]
```

### Version

```text
rustc 1.74.0-nightly (58e967a9c 2023-09-03)
binary: rustc
commit-hash: 58e967a9cc3bd39122e8cb728e8cec6e3a4eeef2
commit-date: 2023-09-03
host: x86_64-unknown-linux-gnu
release: 1.74.0-nightly
LLVM version: 17.0.0
```

**Comment by Centri3** [comment]
There is the [`NumericLiteral`](https://doc.rust-lang.org/nightly/nightly-rustc/clippy_utils/numeric_literal/struct.NumericLiteral.html) type which handles this. It shouldn't be too difficult to switch to it.
