### ISSUE TITLE
Update Rust toolchain version?

### ISSUE THREAD

**Issue by EFanZh** [rust-lang/rust-clippy#11490]
### Description

Currently, Clippy is not able to be compiled with the latest Rust toolchain (For example: `nightly-2023-09-10`) due to API change, I think we may need to merge changes from <https://github.com/rust-lang/rust/commit/f49382c0508db608aa9c33d6a8c77d2955d8f62c> into this repository. Now I can help submit a PR, but I am not sure if there is a specific workflow for synchronizing commits between these two repositories (For example: keeping commit authors, dates, etc).

### Version

```text
rustc 1.74.0-nightly (8ed4537d7 2023-09-09)
binary: rustc
commit-hash: 8ed4537d7c238eb77509d82445cf1cb861a3b5ff
commit-date: 2023-09-09
host: x86_64-unknown-linux-gnu
release: 1.74.0-nightly
LLVM version: 17.0.0
```

**Comment by Alexendoo** [comment]
It gets synced every couple weeks, the process is documented [here](https://doc.rust-lang.org/clippy/development/infrastructure/sync.html). The nightly will be updated after https://github.com/rust-lang/rust/pull/115790 is completed

If you're looking to compile clippy with the current nightly you can do that from the main rust repo, [`src/tools/clippy`](https://github.com/rust-lang/rust/tree/master/src/tools/clippy) is the code that's built for public installation, this repo is to aid the development of Clippy

**Comment by flip1995** [comment]
Clippy is synced every other week. Next sync is on 2023-09-21. Since this is the first issue ever opened for `dylint` conflicts with the rust toolchain used to compile Clippy, I'd rather not do a out-of-cycle sync for this. 

Why can't you use a older nightly toolchain for you dylint?

**Comment by EFanZh** [comment]
@flip1995 There is a certain bugfix of the Rust compiler required by our project, and it is only included in `nightly-2023-09-10` or later version.

**Comment by flip1995** [comment]
What's the bugfix? Do you have a PR?

**Comment by EFanZh** [comment]
This one: <https://github.com/rust-lang/rust/pull/115638>. Since the next sync is only 7 days later, I think I’ll just wait till then. Thank you all for your help!

**Comment by flip1995** [comment]
FYI: I finally got to the toolchain update: https://github.com/rust-lang/rust-clippy/pull/11563

Sorry for the delay!
