### ISSUE TITLE
Suggest memchr instead of &str/&[u8].iter().position(_)

### ISSUE THREAD

**Issue by llogiq** [rust-lang/rust-clippy#1155]
For string slices, if the searched value is an ASCII char (fits in one byte), or for byte searches, we could suggest `memchr(..)``, which is much faster than the naive solution.

See https://github.com/BurntSushi/rust-memchr

**Comment by leonardo-m** [comment]
A different solution is to recognize this pattern and then make the compiler it optimize it better using memchr.

**Comment by clarcharr** [comment]
Perhaps this sort of fix should be offered to the standard library?

**Comment by sinkuu** [comment]
@clarcharr 
`Iterator::position` takes a predicate (`FnMut(Item) -> bool`), and this optimization works only if predicate `|x| x == b'?'` is given.

**Comment by clarcharr** [comment]
@sinkuu, oh, my mistake. I was thinking of `str::find`. Perhaps slices should have such a method which could be optimised.

**Comment by llogiq** [comment]
Even then there could be a MIR optimization pass that detects byte searches and replaces them with the appropriate `memchr` call.

**Comment by clarcharr** [comment]
I agree. I personally would prefer this sort of fix on the compiler side instead of on clippy's side.

**Comment by cyplo** [comment]
What would be the best way to get this issue visible on the compiler side and easy for people to pick up ?

**Comment by camsteffen** [comment]
I don't think suggesting crates is in scope for Clippy. Not to discourage further discussion but I'm going to go ahead and close this.
