### ISSUE TITLE
Clippy suggests using a for-loop instead of while-let, even when the for loop doesn't compile.

### ISSUE THREAD

**Issue by DemiMarie** [rust-lang/rust-clippy#1156]
Clippy suggests using a for loop instead of any `while let` loop over an iterator.  But this gives a lifetime error if we don't own the iterator.

**Comment by Manishearth** [comment]
You may need to `for i in &iter`

probably can improve the suggestion, bit tricky though.

**Comment by llogiq** [comment]
That can fail if `&iter` fails to implement `Iterator` though. I have also seen cases where the iterator was used after the loop, which gives us trouble because `for` loops consume their iterators.

**Comment by DemiMarie** [comment]
I am in the latter case: the iterator outlives the loop (and, in some
cases, is used by the loop body).

**Comment by Manishearth** [comment]
So does `&iter` work?

**Comment by DemiMarie** [comment]
Not in my case, where the iterator is already a reference.

**Comment by Manishearth** [comment]
References are `Copy` though. It's fine to use them like this. Is it a mutable reference? In that case, does `&mut iter` work?

Could you post a snippet of the function?

**Comment by leodasvacas** [comment]
Similar to #600

**Comment by DemiMarie** [comment]
In my case I use the iterator in the loop body.
