### ISSUE TITLE
Unnecessary `.as_ref()` when cloning

### ISSUE THREAD

**Issue by mathstuf** [rust-lang/rust-clippy#11626]
### What it does

Detects `opt.as_ref().map(Clone::clone)` and suggests `opt.clone()` instead.

`Result` is not so clear cut as cloning the `Err` may be unnecessary (e.g., if followed by an `.unwrap()`-family call).

### Advantage

Fewer methods to chain; clearer intent.

### Example

```rust
opt.as_ref().map(Clone::clone)
```

Could be written as:

```rust
opt.clone()
```

**Comment by GuillaumeGomez** [comment]
It was done in https://github.com/rust-lang/rust-clippy/pull/12105 so can be closed.
