### ISSUE TITLE
Detect unknown features inside `#[cfg(feature = "…")]` blocks

### ISSUE THREAD

**Issue by emilk** [rust-lang/rust-clippy#11649]
### What it does

Look for `#[cfg(feature = "NAME")]`, `cfg!(feature = "NAME")`, `#[cfg_attr(feature = "NAME", …)]` etc and check that `NAME` is a real feature found in `Cargo.toml`

### Advantage

- Catches typos (`#[cfg(feature = "sedre")]`)
- Catches refactors that removes or renames a feature

### Example

```rust
#[cfg_attr(feature = "sedre", derive(serde::Deserialize, serde::Serialize))]
struct Foo {
}
```

Suggested output:
> Clippy: "No feature called `sedre`. Available features are: `default`, `serde`

### Related
* https://rust-lang.github.io/rfcs/3013-conditional-compilation-checking.html
* https://doc.rust-lang.org/cargo/reference/unstable.html#check-cfg

May sounds similar, but are different:
* https://github.com/rust-lang/rust-clippy/issues/10224
* https://github.com/rust-lang/rust-clippy/issues/5051

**Comment by emilk** [comment]
Tagging @GuillaumeGomez, as they suggested I do so

**Comment by GuillaumeGomez** [comment]
I'll check what can be done about it. https://rust-lang.github.io/rfcs/3013-conditional-compilation-checking.html seems to be covering this case as well. The big blocker here is in case a project is not using Cargo. But I guess the lint can be skipped in this case.

**Comment by GuillaumeGomez** [comment]
There is a work in progress for this to be done in rust directly: https://github.com/rust-lang/rust/issues/82450

**Comment by Alexendoo** [comment]
Closing in favour of https://github.com/rust-lang/rust/issues/82450
