### ISSUE TITLE
Replace &[t] with std::slice::from_ref(&t) when the &[T] is going to be stored within another object.

### ISSUE THREAD

**Issue by iddm** [rust-lang/rust-clippy#11653]
### What it does

This code is incorrect and produces garbage when optimisations are enabled:

```rust
        // Blending.
        let color_blend_attachment = vk::PipelineColorBlendAttachmentState::builder()
            .color_write_mask(vk::ColorComponentFlags::RGBA)
            .blend_enable(true)
            .src_color_blend_factor(vk::BlendFactor::SRC_ALPHA)
            .dst_color_blend_factor(vk::BlendFactor::ONE_MINUS_SRC_ALPHA)
            .color_blend_op(vk::BlendOp::ADD)
            .src_alpha_blend_factor(vk::BlendFactor::ONE)
            .dst_alpha_blend_factor(vk::BlendFactor::ZERO)
            .alpha_blend_op(vk::BlendOp::ADD)
            .build();

        let color_blend_state = vk::PipelineColorBlendStateCreateInfo::builder()
            .logic_op_enable(false)
            .attachments(&[color_blend_attachment])
            .build();
```

After the `color_blend_state` is built, namely after the `attachments` call is made, the pointer to the temporary array may be freed as it is no longer used. This results in the `color_blend_state` object having a piece of data inside with garbage values.

A fix for this is having a slice made with the use of the `std::slice::from_ref` instead:

```rust
        let color_blend_state = vk::PipelineColorBlendStateCreateInfo::builder()
            .logic_op_enable(false)
            .attachments(std::slice::from_ref(&color_blend_attachment))
            .build();
```

Implementation:

```
/// Converts a reference to T into a slice of length 1 (without copying).
#[stable(feature = "from_ref", since = "1.28.0")]
#[rustc_const_stable(feature = "const_slice_from_ref_shared", since = "1.63.0")]
#[must_use]
pub const fn from_ref<T>(s: &T) -> &[T] {
    array::from_ref(s)
}
```

### Advantage

- Make the code more correct.
- Make the mistake more visible to the user.

### Drawbacks

Perhaps, it should be instead a compile-time error emitted by rustc.

#### Example with one object:

```rust
        let color_blend_state = vk::PipelineColorBlendStateCreateInfo::builder()
            .logic_op_enable(false)
            .attachments(&[color_blend_attachment])
            .build();
```
Output:
```
   .attachments(&[color_blend_attachment])
                ^^^^^^^^^^^^^^^^^^^^^^^^^
error: a reference to a temporary array is attempted to be stored, but the contents will be deleted after the function call.
hint: consider using `std::slice::from_ref(&color_blend_attachment)` instead, as follows:

    .attachments(std::slice::from_ref(&color_blend_attachment))
```

#### Example with multiple objects:

```rust
        let color_blend_state = vk::PipelineColorBlendStateCreateInfo::builder()
            .logic_op_enable(false)
            .attachments(&[color_blend_attachment, color_blend_attachment2])
            .build();
```
Output:
```
   .attachments(&[color_blend_attachment, color_blend_attachment2])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error: a reference to a temporary array is attempted to be stored, but the contents will be deleted after the function call.
hint: consider using a let binding instead and passing a reference to it as follows:

    // ...
    let binding = [color_blend_attachment, color_blend_attachment2];
    // ...
    .attachments(&binding)
```

**Comment by Alexendoo** [comment]
This is a very specific quirk of that API, I don't think a general lint makes sense because lifetimes are a better solution for it

e.g. `ash` [recommends not calling `build`](https://docs.rs/ash/latest/ash/vk/struct.PipelineColorBlendStateCreateInfoBuilder.html#method.build), which would've caught this

**Comment by Jarcho** [comment]
Triggering UB in `ash` this way requires calling `create_graphics_pipelines` which is an unsafe function. Until that call happens it's just a dangling raw pointer.

**Comment by Alexendoo** [comment]
Producing a dangling pointer is considered safe, the unsafety is deferred until the point it's used. Hence `NonNull::dangling` being a safe fn

Concrete examples help pinpoint what we should be targeting to catch the issue. For example here it shows that the problem is not storing a temporary, there's nothing wrong with that and it's used frequently

It's a problem because it is *not* storing the temporary, it immediately turns it into a pointer and stores the lifetime separately with a method that erases said lifetime
