### ISSUE TITLE
Incosistency between `else_if_without_else` and `needless_else`

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/rust-clippy#11662]
`else_if_without_else` is allowed in `restriction` while `needless_else` warns in `style` although both deal with the same pattern. It is then probably a good move to put both in the same category.

**Comment by y21** [comment]
I personally disagree. They deal with the opposite pattern rather, and one is (in my experience) more idiomatic than the other.
Requiring an `else` on every single `else if` even when it's not needed sounds quite restrictive. An empty `else` OTOH seems much more sane to warn and is likely a mistake, possibly leftover from refactoring.

The same sort of argument can be made for `implicit_return` (restriction) and `needless_return` (style). Omitting `return;` as the last statement of a function is idiomatic Rust so it seems good to have `needless_return` be warn by default.

**Comment by Alexendoo** [comment]
Yeah having both of these warn by default would create a cycle where we repeatedly ask the user to add an `else {}` then on the next run ask them to remove it

**Comment by c410-f3r** [comment]
Looks like this is a desired undocumented behaviour, or is there any?

For those interested in consistency, `semicolon_inside_block` and `semicolon_inside_block` among possibly others, are in the same category with the same level of restriction.

**Comment by Alexendoo** [comment]
There are several pairs of lints that suggest opposites to each other, but the only case where they should be in the same category is if that category is `restriction`, meaning they're both considered individually opt in

**Comment by c410-f3r** [comment]
@Alexendoo https://github.com/rust-lang/rust-clippy/pull/11666
