### ISSUE TITLE
error[E0425]: cannot find function, tuple struct or tuple variant `Some` in this scope

### ISSUE THREAD

**Issue by marcbrevoort-cyberhive** [rust-lang/rust-clippy#11682]
### Summary

Likewise, 

error[E0425]: cannot find function, tuple struct or tuple variant `Ok` in this scope
error[E0425]: cannot find function, tuple struct or tuple variant `Err` in this scope

This seems a bit overzealous for enums that are practically language keywords.
There's a lot of cross-compiling going on over at ours so this may have something to do with it.

The start of the clippy log states
```
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-linux-musl` target may not be installed
  = help: consider downloading the target with `rustup target add x86_64-unknown-linux-musl`
```
Trying as suggested, I get
```
$ rustup target add x86_64-unknown-linux-musl
info: component 'rust-std' for target 'x86_64-unknown-linux-musl' is up to date
$ rustup component add rust-std
info: component 'rust-std' for target 'x86_64-unknown-linux-gnu' is up to date
```

Running clippy on a fresh native project works fine.

### Lint Name

clippy

### Version

```text
rustc 1.73.0 (cc66ad468 2023-10-03)
```

**Comment by Alexendoo** [comment]
If it can't find `std` yeah there's some configuration issue going on, is the clippy being run also installed via rustup and from the same toolchain?
