### ISSUE TITLE
lint suggestion: `redundant_paths`

### ISSUE THREAD

**Issue by thetayloredman** [rust-lang/rust-clippy#11725]
### What it does

I propose a lint `redundant_paths` (unless a better name exists) that will lint when a path is used that is already in scope under a different name.

### Advantage

My repository [zirco-lang/zrc](https://github.com/zirco-lang/zrc) recently enabled the lint that prevents absolute paths over a certain length, and a lot of redundant paths exist after I decide to `use` a path and do not change the other usages. This lint could prevent that, simplifying code readability and helping refactor.

This works well with the path length lint, as mentioned above.

### Drawbacks

- Implementation complexity?
- Unresolved questions (see the end)

### Example

Imagine a crate `math` which exports a function `fn add(a: i32, b: i32) -> i32`.

```rust
use math::add;

fn main() {
    let x = math::add(3, 2);
//          ^^^^^^^^^ path 'math::add' already in scope
    println!("{x}");
}
```

Could be written as:

```rust
use math::add;

fn main() {
    let x = add(3, 2);
    println!("{x}");
}
```

## Unresolved questions
What is the behavior of the following?:
```rust
use math::add as add1;
use math::add as add2;
```
Could the lint trigger on the above two lines?

**Comment by Alexendoo** [comment]
I made an implementation of this locally a bit ago, but found there is [an existing rustc](https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#unused-qualifications) lint that does this

The rustc lint is allow by default though which isn't very discoverable and doesn't seem to catch local imports, let's nominate this for discussion

**Comment by thetayloredman** [comment]
Question (I am not very familiar with the project/team infrastructure):
1. Why nominate for discussion if it already exists?
2. Why does rustc have this lint, instead of clippy?

**Comment by Alexendoo** [comment]
The discussion will be to see if we want to pursue it in clippy, and if so what should be done with the rustc lint

If it were created today it would most likely land in clippy, but `unused_qualifications` is older than clippy

**Comment by kpreid** [comment]
> The rustc lint is allow by default though which isn't very discoverable

This seems like a problem worth solving in general. **What if the clippy lint documentation included rustc lints?** After all, running `cargo clippy` also emits rustc lints, so they're always usable in the same way. This would increase discoverability and also make a searchable list of rustc lints.

**Comment by thetayloredman** [comment]
How possible could it be to remove lints from rustc entirely and make them a Clippy thing? I assume difficult without breaking stability?

**Comment by Alexendoo** [comment]
> How possible could it be to remove lints from rustc entirely and make them a Clippy thing? I assume difficult without breaking stability? Would this be a bad idea in itself _excluding backwards compatibility?_

There is a mechanism to remove/replace lints, it would result in a warning wherever `unused_qualifications` is used. This could break builds where deny warnings is used, but removing rustc lints is [not unprecedented](https://github.com/rust-lang/rust/blob/d1611e39c43e26333ba989cedbd63117be798741/compiler/rustc_lint/src/lib.rs#L352-L513)

**Comment by Alexendoo** [comment]
Results of [the meeting](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Meeting.202023-10-31):

> We don't really want to "downlift" this lint as this might be breaking for some rustc users. At the same time allow-by-default rustc lints should be more discoverable. So rustc should do something to make allow-by-default lints more discoverable (e.g. adding a `pedantic` group).

We also decided that documenting rustc lints in the clippy documentation would be too complicated
