### ISSUE TITLE
[comparison_chain]: Recommended fix not possible in no_std

### ISSUE THREAD

**Issue by jcdubois** [rust-lang/rust-clippy#11785]
### Summary

On a library designed for #![no_std] Clippy is recommending the following:

$ cargo clippy
    Checking heatshrink-rs v0.4.1 (/home/jcd/Projects/compress/heatshrink-rs)
error: `if` chain can be rewritten with `match`
   --> src/decoder.rs:314:9
    |
314 | /         if count < self.bit_index {
315 | |             // enough bits left in the current_byte
316 | |             // shift accumulator right
317 | |             accumulator >>= self.bit_index - count;
...   |
350 | |             accumulator >>= self.bit_index;
351 | |         }
    | |_________^
    |
    = help: consider rewriting the `if` chain to use `cmp` and `match`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#comparison_chain
note: the lint level is defined here
   --> src/lib.rs:3:9
    |
3   | #![deny(warnings)]
    |         ^^^^^^^^
    = note: `#[deny(clippy::comparison_chain)]` implied by `#[deny(warnings)]`

error: could not compile `heatshrink-rs` (lib) due to previous error
$

But as this is a `#![no_std]` library we cannot use the would be required `use std::cmp::Ordering;`

### Lint Name

comparison_chain

### Reproducer

I tried this code:

```rust
#![no_std]
 #![deny(warnings)]
 
 fn a() {}
 fn b() {}
 fn c() {}
 pub fn f(x: u8, y: u8) {
     if x > y {
         a()
     } else if x < y {
         b()
     } else {
         c()
     }
 }
```

I saw this happen:

```
$ cargo clippy
    Checking heatshrink-rs v0.4.1 (/home/jcd/Projects/compress/heatshrink-rs)
error: `if` chain can be rewritten with `match`
  --> src/lib.rs:8:5
   |
8  | /     if x > y {
9  | |         a()
10 | |     } else if x < y {
11 | |         b()
12 | |     } else {
13 | |         c()
14 | |     }
   | |_____^
   |
   = help: consider rewriting the `if` chain to use `cmp` and `match`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#comparison_chain
note: the lint level is defined here
  --> src/lib.rs:2:9
   |
2  | #![deny(warnings)]
   |         ^^^^^^^^
   = note: `#[deny(clippy::comparison_chain)]` implied by `#[deny(warnings)]`

error: could not compile `heatshrink-rs` (lib) due to previous error
```

I expected to see this happen:

No warning and no recommendation involving `std::`

### Version

```text
rustc 1.75.0-nightly (42b1224e9 2023-10-15)
binary: rustc
commit-hash: 42b1224e9eb37177f608d3f6a6f2be2ee13902e4
commit-date: 2023-10-15
host: x86_64-unknown-linux-gnu
release: 1.75.0-nightly
LLVM version: 17.0.2
```

**Comment by y21** [comment]
You should be able to use `core::cmp::Ordering`, even in `#![no_std]`. The `Ordering` in std is merely a re-export of `core::cmp::Ordering`.

**Comment by jcdubois** [comment]
OK Thanks.

However when following the provided link (https://rust-lang.github.io/rust-clippy/master/index.html#/comparison_chain) the (misleading ?) recommended solution is to use:

use std::cmp::Ordering;
fn f(x: u8, y: u8) {
     match x.cmp(&y) {
         Ordering::Greater => a(),
         Ordering::Less => b(),
         Ordering::Equal => c()
     }
}

**Comment by GuillaumeGomez** [comment]
I'll improve the suggestion in case this is a `no_std` crate and the documentation as well.

**Comment by GuillaumeGomez** [comment]
I think we can close this issue. A lot of lints are suggesting to add `std` items and if people use `no_std`, we can expect them to know which items are available in this case.
