### ISSUE TITLE
Simplify fully qualified names to remove unneeded prefixes

### ISSUE THREAD

**Issue by nyurik** [rust-lang/rust-clippy#11838]
### What it does

Given a fully or a partially qualified identifier, checks if it can be shortened using all of the currently declared `use` statements in the current scope.

### Advantage

- Keeps code shorter and more readable
- Keeps code more consistent because the same identifier will be used the same way throughout the scope

### Drawbacks

Some people might still prefer a more verbose declaration, but in my opinion they should not have declared the more specific name in the `use` statement.

### Example

```rust
use std::f64::consts;
use std::f64::consts::PI;
use std::fs;
use std::sync::atomic::Ordering;
use std::sync::atomic::Ordering::Relaxed;

fn main() {
    println!("Pi is roughly {}", ::std::f64::consts::PI); // Const
    println!("Pi is roughly {}", consts::PI); // Const
    println!("Ordering is {:?}", Ordering::Relaxed); // Enum variant
    println!("Opening as {:?}", std::fs::OpenOptions::default()); // `fs` is available, can be shortened
}
```

Could be written as:

```rust
fn main() {
    println!("Pi is roughly {}", PI);
    println!("Pi is roughly {}", PI);
    println!("Ordering is {:?}", Relaxed);
    println!("Opening as {:?}", fs::OpenOptions::default());
}
```

**Comment by Centri3** [comment]
I tried adding smth like this (detecting an unnecessary root path, `::`) but detecting if it's needed or not is tricky, e.g., there could be a module named `std` in the same scope. afaik there is no easy way to get whether a certain path is in scope currently, as most of the `Resolver` is private

**Comment by nyurik** [comment]
I agree that we might not resolve it 100% from the start,  but we might be able to get to the first 90% using some heuristics, making the lint as pedantic or even experimental. This will also encourage us to refactor the resolver

**Comment by Alexendoo** [comment]
See #11725/the meeting it links, I don't think anybody brought it up on the rustc side though yet
