### ISSUE TITLE
Unnecessary path prefixes

### ISSUE THREAD

**Issue by alice-i-cecile** [rust-lang/rust-clippy#11888]
### What it does

Strips out unnecessary path qualifiers on types/functions/structs when the module they are being imported from is already in scope.

See https://github.com/bevyengine/bevy/pull/10749 for an example of this in practice, powered by RustRover's refactoring tools.

### Advantage

- clarifies that this is the standard, already imported form
- reduces noise and saves characters

### Drawbacks

Maybe makes imports less clear in cases where you really want to be explicit?

This is a weaker version of [absolute_paths](https://rust-lang.github.io/rust-clippy/master/index.html#/absolute_paths), focused on redundancy rather than enforcing a universal style. In some cases, you might want the latter.

### Example

```rust
use bevy::prelude::*;

let world = bevy::ecs::World::new();
```

Could be written as:

```rust
use bevy::prelude::*;

let world = World::new();
```

**Comment by EdJoPaTo** [comment]
There exists a rustc lint which is allowed-by-default: [`unused_qualifications`](https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#unused-qualifications)
