### ISSUE TITLE
option_if_let_else: don't suggest map_or_else

### ISSUE THREAD

**Issue by SUPERCILEX** [rust-lang/rust-clippy#11893]
### Description

Using `map_or_else` makes readability much worse in my opinion because those expressions tend to be more complicated.

### Version

```
rustc 1.76.0-nightly (283170175 2023-11-17)
binary: rustc
commit-hash: 2831701757eb7b3105eda26a306c2f3a97e2664b
commit-date: 2023-11-17
host: x86_64-unknown-linux-gnu
release: 1.76.0-nightly
LLVM version: 17.0.5
```

**Comment by SUPERCILEX** [comment]
Or a less nuclear option is to never suggest `map_or_else` for unit conditions:

```rust
if let Some(name) = get_name(parent) {
    writeln!(output, "{name:?}").unwrap();
} else {
    panic!("Haven't thought about this condition. {parent}");
}
```

This should use `map_or_else`.

**Comment by samueltardieu** [comment]
@SUPERCILEX Could you provide a full (compilable) example that exhibits the behavior you are describing?

**Comment by SUPERCILEX** [comment]
Here you go: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=bb94b5d5ed71301bb0571a37da6a05bc

Run clippy on that.
