### ISSUE TITLE
`clippy --fix` incorrectly handles unused variables in unreachable code, producing code that can't compile.

### ISSUE THREAD

**Issue by FractalFir** [rust-lang/rust-clippy#11906]
### Summary

I am working on a `rustc` backend targeting .NET, and have a lot of partially completed features.

In order to temporarily disable some of those features with bugs in them, I insert a `todo!()`  before the buggy code.(This makes it really easy to quickly disable/enable them). 

This `todo!()` causes Clippy to assume some of the variables later referenced in the code are unused, and preapend `_` to them. This is incorrect, because it causes the resulting code to be invalid.

Clippy incorrectly transformed this code:
```rust
 GlobalAlloc::Static(def_id) => {
         todo!("Statics are buggy, so they are not supported yet!"); 
         let alloc = tyctx.eval_static_initializer(def_id).unwrap();
         let tyctx = tyctx.reserve_and_set_memory_alloc(alloc);
         let alloc_id = crate::utilis::alloc_id_to_u64(alloc_id);
         return vec![CILOp::LoadGlobalAllocPtr { alloc_id }];
}
```
into this code:
```rust
GlobalAlloc::Static(_def_id) => {
        todo!("Statics are buggy, so they are not supported yet");
        let alloc = tyctx.eval_static_initializer(def_id).unwrap();
        let _tyctx = tyctx.reserve_and_set_memory_alloc(alloc);
        let alloc_id = crate::utilis::alloc_id_to_u64(alloc_id);
        return vec![CILOp::LoadGlobalAllocPtr { alloc_id }];
}
```
The difference is within the match arm -  `def_id` has been renamed to `_def_id` there, but nowhere else.  The `def_id` is later referenced within the unreachable code (within a call `eval_static_initializer`) but it is named `def_id`. This causes the code produced by `clippy --fix` to be invalid and unable to compile.
This issue is present a couple more times within my codebase, but this example is the simplest one within the original codebase.
The bug is present both on nightly and stable.

### Reproducer

I have also produced this simplified example, which triggers the bug too.
Original:
```rust
fn main() {
    let a = 0;
    todo!();
    let b = a;
}
```
After `clippy --fix`:
```rust
fn main() {
    let _a = 0;
    todo!();
    let _b = a;
}

```

### Version

```text
rustc 1.76.0-nightly (dd430bc8c 2023-11-14)
binary: rustc
commit-hash: dd430bc8c22f57992ec1457a87437d14283fdd65
commit-date: 2023-11-14
host: x86_64-unknown-linux-gnu
release: 1.76.0-nightly
LLVM version: 17.0.5
```

**Comment by y21** [comment]
If I'm reading this correctly, the lint that causes this is a rustc lint, so it's a bug in the compiler. You should be able to also repro this with normal `cargo fix`.

See also #11644 and the upstream issue https://github.com/rust-lang/rust/issues/107734
