### ISSUE TITLE
Typo in redundant_as_str documentation

### ISSUE THREAD

**Issue by glmdgrielson** [rust-lang/rust-clippy#11922]
### Description

The documentation for [`redundant_as_str`](https://rust-lang.github.io/rust-clippy/stable/index.html#redundant_as_str) contains a Markdown typo that affects rendering.

```rust
Checks for usage of `as_str()` on a `String`` chained with a method available on the `String` itself.
```

It should be:

```rust
Checks for usage of `as_str()` on a `String` chained with a method available on the `String` itself.
```

### Additional Labels

@rustbot label +C-enhancement

**Comment by ericwu2003** [comment]
Thanks for pointing out this issue! This was fixed recently by pull request https://github.com/rust-lang/rust-clippy/pull/11826.

**Comment by xFrednet** [comment]
Thank you for the comment!
