### ISSUE TITLE
consider using `env::var(CARGO)` instead of looking for cargo in PATH

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust-clippy#11943]
### Description

Currently, cargo-clippy hard-codes `cargo` as the command to run and looks for it in PATH: https://github.com/rust-lang/rust-clippy/blob/1c8cbe79abd1ee75cbbc0b4a93d873c7d1a5fd8f/src/main.rs#L108
This means that, e.g., running `/home/jyn/.cargo/bin/cargo-clippy` directly, without having `~/.cargo` in PATH, will not work.

I cannot think of a use case where this would break things, but it makes me a little uncomfortable. Cargo sets the environment variable `CARGO` for subcommands: https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates
It would be nice if clippy defaulted to that environment variable before falling back to the cargo in PATH.

### Version

```text
clippy 0.1.76 (ae25d69dea5 2023-11-17)
```

**Comment by Alexendoo** [comment]
Fixed by #11944
