### ISSUE TITLE
Lint std::panic::catch_unwind

### ISSUE THREAD

**Issue by llogiq** [rust-lang/rust-clippy#1196]
This should only be used when one has no control over code that may panic, e.g. using integer division with unknown operands (although [overflower](https://github.com/llogiq/overflower) should cover that, too). Otherwise, using a `Result` type should be the preferred way of dealing with errors.

**Comment by camsteffen** [comment]
This can be done with `disallowed_method`. A dedicated lint would be restriction so I don't think that's any better.
