### ISSUE TITLE
Add lint that suggest using const thread_local whenever possible

### ISSUE THREAD

**Issue by SUPERCILEX** [rust-lang/rust-clippy#12015]
### What it does

Tells you to use const thread_locals because they offer many more performance opportunities due to not having to check for re-initialization on every call.

See this godbolt for the potential performance impact: https://godbolt.org/z/rnPsb6Y7v

### Advantage

Performance

### Drawbacks

None I think? Honestly I don't understand why this is even a feature, i.e. why the compiler can't do this automatically.

### Example

```rust
thread_local! {
    static BUF: RefCell<String> = RefCell::new(String::new());
}
```

Could be written as:

```rust
thread_local! {
    static BUF: RefCell<String> = const { RefCell::new(String::new()) };
}
```

**Comment by SUPERCILEX** [comment]
Quote from @thomcc (https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Stabilizing.20.60thread_local_const_init.60.3F/near/410023178):

> Realistically, there are no downsides to using the const{} thread local init syntax.

So looks like we're good to make this a machine applicable lint and enable it by default.

**Comment by PartiallyTyped** [comment]
This should only be triggered on expressions that can be correctly evaluated as constants :D

**Comment by SUPERCILEX** [comment]
That was fast, thanks!
