### ISSUE TITLE
let_unit_value disallows `let () = ...;` when it is useful to ensure the type does not change

### ISSUE THREAD

**Issue by SUPERCILEX** [rust-lang/rust-clippy#12017]
### Summary

An explicit `let () =` (or `let _: () =`) binding is used to guarantee that the return type of an API hasn't changed. This is useful to ensure that the API of an auto-generated C API doesn't change its return type to something that must be freed for example.

Basically if the unit type is explicitly specified, this lint shouldn't fire.

### Lint Name

let_unit_value

**Comment by KisaragiEffective** [comment]
related: #9048

**Comment by cocodery** [comment]
[PR#10844](https://github.com/rust-lang/rust-clippy/pull/10844) seems like has solved this issue already.
wait it merged to master.
