### ISSUE TITLE
`manual_let_else` doesn't obey msrv

### ISSUE THREAD

**Issue by udoprog** [rust-lang/rust-clippy#12020]
### Description

A newer version of Clippy currently can be configured to suggest changes would would be incompatible with the rust-version of the project, for eample `manual_let_else`.

Clippy could instead take the cargo specified rust-version into account, and only apply lints which are appropriate for the targeted Rust version. The workaround I'm currently using is to pin the Clippy version in use in CI.

**Comment by PartiallyTyped** [comment]
This is already supported via Minimum Supported Rust Version (MSRV). It seems that some checks like `manual_let_else` are not behind such a check.

**Comment by udoprog** [comment]
All right, it could also use the `rust-version` specified in the `Cargo.toml` relevant to the crate being linted, which is what this issue relates to.

**Comment by udoprog** [comment]
Actually README.md claims it *does*. So this is just an issue with `manual_let_else`.

**Comment by PartiallyTyped** [comment]
Would you like to give this a try? Otherwise I could submit a patch for that.

**Comment by udoprog** [comment]
I'm good thanks. Patch away.

**Comment by PartiallyTyped** [comment]
Seems like the issue isn't `MSRV` 🤔 

https://github.com/rust-lang/rust-clippy/blob/eb679c7f34cc6f052c92b20709a8c0075844fb47/clippy_lints/src/manual_let_else.rs#L52-L54

**Comment by udoprog** [comment]
I double checked, and it seems I might've been using a Cargo.toml which specified the wrong `rust-version` when running Clippy. Testing it now, it works correctly.

Sorry about that!
