### ISSUE TITLE
Suggestion to anonymise trait imports that are not used directly

### ISSUE THREAD

**Issue by bayov** [rust-lang/rust-clippy#12072]
### What it does

Changes trait imports that are not directly used to be anonymous.

### Advantage

- Removes unused identifiers from scope.
- Clearly marks the intent of imports; seeing `use std::fmt::Write as _` is an indicator that Write is only being used so that its trait methods are in scope, and not referred to directly.
- Lowers chance of conflicts with similarly named traits.

### Example

```rust
fn foo() {
    use std::fmt::Write;
    let mut s = String::new();
    s.write_char('x');
}
```

Could be written as:
```rust
fn foo() {
    use std::fmt::Write as _; // anonymous
    let mut s = String::new();
    s.write_char('x');
}
```

**Comment by jrose-signal** [comment]
Same as https://github.com/rust-lang/rust-clippy/issues/11969 ?
