### ISSUE TITLE
thread 'copy LTO artifacts for 51uix69s9xia1hjk' panicked after saving file.

### ISSUE THREAD

**Issue by LucasLehmann** [rust-lang/rust-clippy#12196]
### Summary

When running cargo clippy after file has been written to rustc panics, running cargo clean fixes it until next write.
I was unable to reproduce this on any other machine(not attempted on another windows machine).
I am using sccache but unsetting RUSTC_WRAPPER does not seem change the outcome as error output stays the same.

### Version

```text
rustc 1.75.0 (82e1608df 2023-12-21)
binary: rustc
commit-hash: 82e1608dfa6e0b5569232559e3d385fea5a93112
commit-date: 2023-12-21
host: x86_64-pc-windows-msvc
release: 1.75.0
LLVM version: 17.0.6
```

### Error output

<details><summary>Backtrace</summary>
  <p>

  ```
  <backtrace>
  ```
thread 'copy LTO artifacts for 51uix69s9xia1hjk' panicked at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\compiler\rustc_codegen_ssa\src\back\write.rs:890:5:
assertion failed: module_config.emit_obj != EmitObj::None
stack backtrace:
   0:     0x7ff81a0e3053 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h99d8f55dc77ea58e
   1:     0x7ff81a115a3d - core::fmt::write::hde05c98aa8466c89
   2:     0x7ff81a0d9951 - <std::io::IoSlice as core::fmt::Debug>::fmt::hfbd96d963048182d
   3:     0x7ff81a0e2e5a - std::sys_common::backtrace::lock::h19b13d03fb733c4f
   4:     0x7ff81a0e6329 - std::panicking::default_hook::h809e3ce877795dde
   5:     0x7ff81a0e5feb - std::panicking::default_hook::h809e3ce877795dde
   6:     0x7fffe7f7f522 - <tracing_subscriber[6409740a17f48d06]::fmt::format::Writer>::write_fmt
   7:     0x7ff81a0e6903 - std::panicking::rust_panic_with_hook::hac29101b109c3744
   8:     0x7ff81a0e676b - <std::panicking::begin_panic_handler::StaticStrPayload as core::panic::PanicPayload>::take_box::h1529e0c3d6e161ce
   9:     0x7ff81a0e3949 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h99d8f55dc77ea58e
  10:     0x7ff81a0e64b4 - rust_begin_unwind
  11:     0x7ff81a13ae57 - core::panicking::panic_fmt::ha2a0d31008962eb7
  12:     0x7ff81a13af12 - core::panicking::panic::h5c1fb882612266eb
  13:     0x7fffe41efcb8 - <rustc_codegen_llvm[eb66d98aff7de962]::debuginfo::CodegenUnitDebugContext as core[94f19dc4588870f6]::ops::drop::Drop>::drop
  14:     0x7fffe419b520 - <<rustc_mir_transform[29ac58ce2f161f8c]::const_prop::ConstPropMachine as rustc_const_eval[46da42dcc0bad855]::interpret::machine::Machine>::panic_nounwind::Zst as rustc_middle[adf162ff1c7ec31e]::mir::interpret::error::MachineStopType>::add_args
  15:     0x7fffe419c362 - <<rustc_mir_transform[29ac58ce2f161f8c]::const_prop::ConstPropMachine as rustc_const_eval[46da42dcc0bad855]::interpret::machine::Machine>::panic_nounwind::Zst as rustc_middle[adf162ff1c7ec31e]::mir::interpret::error::MachineStopType>::add_args
  16:     0x7ff81a0f8b6c - std::sys::windows::thread::Thread::new::h7b3ce3a09b163019
  17:     0x7ff893bd257d - BaseThreadInitThunk
  18:     0x7ff89444aa58 - RtlUserThreadStart

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new?template=ice.yml

note: rustc 1.75.0 (82e1608df 2023-12-21) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED] -C target-cpu=native

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
note: Clippy version: clippy 0.1.75 (82e1608d 2023-12-21)

thread 'coordinator' panicked at compiler\rustc_middle\src\util\bug.rs:36:26:
/rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\compiler\rustc_codegen_ssa\src\back\write.rs:1590:29: worker thread panicked
stack backtrace:
   0:     0x7ff81a0e3053 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h99d8f55dc77ea58e
   1:     0x7ff81a115a3d - core::fmt::write::hde05c98aa8466c89
   2:     0x7ff81a0d9951 - <std::io::IoSlice as core::fmt::Debug>::fmt::hfbd96d963048182d
   3:     0x7ff81a0e2e5a - std::sys_common::backtrace::lock::h19b13d03fb733c4f
   4:     0x7ff81a0e6329 - std::panicking::default_hook::h809e3ce877795dde
   5:     0x7ff81a0e5feb - std::panicking::default_hook::h809e3ce877795dde
   6:     0x7fffe7f7f522 - <tracing_subscriber[6409740a17f48d06]::fmt::format::Writer>::write_fmt
   7:     0x7ff81a0e6903 - std::panicking::rust_panic_with_hook::hac29101b109c3744
   8:     0x7fffe92b6864 - <rustc_middle[adf162ff1c7ec31e]::mir::interpret::allocation::ConstAllocation as rustc_middle[adf162ff1c7ec31e]::ty::context::Lift>::lift_to_tcx
   9:     0x7fffe92b4949 - <rustc_middle[adf162ff1c7ec31e]::mir::interpret::allocation::ConstAllocation as rustc_middle[adf162ff1c7ec31e]::ty::context::Lift>::lift_to_tcx
  10:     0x7fffe91eaad3 - ar_archive_writer[d46d07e9296ae6a3]::archive_writer::write_symbols
  11:     0x7fffe92bcece - rustc_middle[adf162ff1c7ec31e]::util::bug::bug_fmt
  12:     0x7fffe92bcdbd - <rustc_middle[adf162ff1c7ec31e]::ty::error::TypeError>::to_string
  13:     0x7fffe92bcd8a - <rustc_middle[adf162ff1c7ec31e]::ty::error::TypeError>::to_string
  14:     0x7fffe92bcdf2 - rustc_middle[adf162ff1c7ec31e]::util::bug::bug_fmt
  15:     0x7fffe6fe6dde - rustc_interface[845e99c2fcb4bb36]::proc_macro_decls::proc_macro_decls_static
  16:     0x7fffe419c830 - <<rustc_mir_transform[29ac58ce2f161f8c]::const_prop::ConstPropMachine as rustc_const_eval[46da42dcc0bad855]::interpret::machine::Machine>::panic_nounwind::Zst as rustc_middle[adf162ff1c7ec31e]::mir::interpret::error::MachineStopType>::add_args
  17:     0x7ff81a0f8b6c - std::sys::windows::thread::Thread::new::h7b3ce3a09b163019
  18:     0x7ff893bd257d - BaseThreadInitThunk
  19:     0x7ff89444aa58 - RtlUserThreadStart

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new?template=ice.yml

note: rustc 1.75.0 (82e1608df 2023-12-21) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED] -C target-cpu=native

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
note: Clippy version: clippy 0.1.75 (82e1608d 2023-12-21)

thread 'rustc' panicked at compiler\rustc_middle\src\util\bug.rs:36:26:
/rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\compiler\rustc_codegen_ssa\src\back\write.rs:1964:17: panic during codegen/LLVM phase
stack backtrace:
   0:     0x7ff81a0e3053 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h99d8f55dc77ea58e
   1:     0x7ff81a115a3d - core::fmt::write::hde05c98aa8466c89
   2:     0x7ff81a0d9951 - <std::io::IoSlice as core::fmt::Debug>::fmt::hfbd96d963048182d
   3:     0x7ff81a0e2e5a - std::sys_common::backtrace::lock::h19b13d03fb733c4f
   4:     0x7ff81a0e6329 - std::panicking::default_hook::h809e3ce877795dde
   5:     0x7ff81a0e5feb - std::panicking::default_hook::h809e3ce877795dde
   6:     0x7fffe7f7f522 - <tracing_subscriber[6409740a17f48d06]::fmt::format::Writer>::write_fmt
   7:     0x7ff81a0e6903 - std::panicking::rust_panic_with_hook::hac29101b109c3744
   8:     0x7fffe92b6864 - <rustc_middle[adf162ff1c7ec31e]::mir::interpret::allocation::ConstAllocation as rustc_middle[adf162ff1c7ec31e]::ty::context::Lift>::lift_to_tcx
   9:     0x7fffe92b4949 - <rustc_middle[adf162ff1c7ec31e]::mir::interpret::allocation::ConstAllocation as rustc_middle[adf162ff1c7ec31e]::ty::context::Lift>::lift_to_tcx
  10:     0x7fffe91eaad3 - ar_archive_writer[d46d07e9296ae6a3]::archive_writer::write_symbols
  11:     0x7fffe92bcece - rustc_middle[adf162ff1c7ec31e]::util::bug::bug_fmt
  12:     0x7fffe92bcdbd - <rustc_middle[adf162ff1c7ec31e]::ty::error::TypeError>::to_string
  13:     0x7fffe92bcd8a - <rustc_middle[adf162ff1c7ec31e]::ty::error::TypeError>::to_string
  14:     0x7fffe92bcdf2 - rustc_middle[adf162ff1c7ec31e]::util::bug::bug_fmt
  15:     0x7fffe41f2081 - <rustc_codegen_llvm[eb66d98aff7de962]::debuginfo::CodegenUnitDebugContext as core[94f19dc4588870f6]::ops::drop::Drop>::drop
  16:     0x7fffe41a96f6 - <rustc_codegen_llvm[eb66d98aff7de962]::LlvmCodegenBackend as rustc_codegen_ssa[982fe69def522a2a]::traits::backend::CodegenBackend>::join_codegen
  17:     0x7fffe41688c3 - <rustc_interface[845e99c2fcb4bb36]::queries::Linker>::link
  18:     0x7fffe412d962 - rustc_driver_impl[b4ac4ed7e8bb44fd]::args::arg_expand_all
  19:     0x7fffe411f4bb - rustc_driver_impl[b4ac4ed7e8bb44fd]::args::arg_expand_all
  20:     0x7fffe412f101 - rustc_driver_impl[b4ac4ed7e8bb44fd]::args::arg_expand_all
  21:     0x7fffe412a6df - rustc_driver_impl[b4ac4ed7e8bb44fd]::args::arg_expand_all
  22:     0x7fffe4122861 - rustc_driver_impl[b4ac4ed7e8bb44fd]::args::arg_expand_all
  23:     0x7ff81a0f8b6c - std::sys::windows::thread::Thread::new::h7b3ce3a09b163019
  24:     0x7ff893bd257d - BaseThreadInitThunk
  25:     0x7ff89444aa58 - RtlUserThreadStart

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new?template=ice.yml

note: rustc 1.75.0 (82e1608df 2023-12-21) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED] -C target-cpu=native

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
note: Clippy version: clippy 0.1.75 (82e1608d 2023-12-21)

error: could not compile `testing` (bin "testing")
  </p>
</details>

**Comment by Jarcho** [comment]
This is an incremental compilation issue which might be fixed in later versions. If not you can report this in the rustc repo.
