### ISSUE TITLE
prohibit the use of unwrap()

### ISSUE THREAD

**Issue by rxdiscovery** [rust-lang/rust-clippy#12228]
### What it does

using unwrap() in code exposes it to two risks:

- uncontrolled exceptions (application crash)
- exposure of confidential data (such as the project path, which generally contains the OS user's name), since unwrap() integrates the complete path of the source file into the final executable.

### Advantage

1. more stable code 
2. improved confidentiality 
3. the final executable will be smaller, since it won't include the path strings for panic.

### Example

```rust
        let str = "1000".to_string();
        let number = str.parse::<i32>().unwrap(); //<------ risk of uncontrolled exception if str does not contain a number
```

Could be written as:

```rust
       let number = match str.parse::<i32>(){
            Ok(n) => n,
            Err(_) => todo!(),
        };
```

thank you in advance :

**Comment by kpreid** [comment]
This lint is already available as [`clippy::unwrap_used`](https://rust-lang.github.io/rust-clippy/master/#/unwrap_used).
