### ISSUE TITLE
nonminimal_bool: `id == !0` is not `id != 0`

### ISSUE THREAD

**Issue by ytakano** [rust-lang/rust-clippy#12369]
### Summary

`id == !0` is not `id != 0`.

### Lint Name

nonminimal_bool

### Reproducer

I tried this code:

```rust
if id == !0 {
```

I saw this happen:

```
if id == !0 {
   ^^^^^^ help: try: `id != 0`
```

I expected to see this happen:

`id != 0` and `id == !0` are different.

`id == !0` is equivalent to `id == 0xFFFF` if `id` is `u16`.

### Version

```text
rustc 1.78.0-nightly (ef324565d 2024-02-27)
binary: rustc
commit-hash: ef324565d071c6d7e2477a195648549e33d6a465
commit-date: 2024-02-27
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0
```

**Comment by GuillaumeGomez** [comment]
It will be fixed with https://github.com/rust-lang/rust-clippy/pull/12372.
