### ISSUE TITLE
De-group `attrs.rs`

### ISSUE THREAD

**Issue by blyxyas** [rust-lang/rust-clippy#12390]
### Description

Currently, the file `attrs.rs` has 16 instances of `declare_clippy_lint!` (so it groups 16 lints.) And the checking itself (implementing `LateLintPass` and `EarlyLintPass`) just calls other functions, or can be refactored to call other functions.

It would be nice to, instead of having a ~1300 line file, to move these lints into their own directory inside the `clippy_lints` directory (just like we have the `functions` or `methods` directory).

### Version

```text
N/A
```

**Comment by CBSpeir** [comment]
The pull request I submitted moves most of the lints in to their own file. 

The lints `empty_line_after_doc_comments`/`empty_line_after_outer_attr` and `deprecated_cfg_attr`/`deprecated_clippy_cfg_attr` were both kept together respectively in their own submodule.
