### ISSUE TITLE
warn on `iter.enumerate.map(|(_, pat)| expr)`

### ISSUE THREAD

**Issue by KisaragiEffective** [rust-lang/rust-clippy#12411]
### What it does

emits warning on `iterator.enumerate().map(|(_unused_index, elem)| expr)`.

### Advantage

- Removes counter, improving performance.

### Drawbacks

None

### Example

https://github.com/KisaragiEffective/origlang/blob/fa487aab90c7bbe1b0b4ebaedfa33b847985a1ba/package/origlang-compiler/src/type_check.rs#L270:
```rust
iter.enumerate().map(|(_i, elem)| { whatever })
```

Could be written as:

```rust
iter.map(|elem| { whatever })
```

**Comment by Ethiraric** [comment]
Indeed! Thanks for the pointer!

**Comment by Ethiraric** [comment]
I don't think I can work on the lint directly as it is called from `clippy_lints/src/loops/mod.rs`, which calls all lints that operate on loops.

I know not enough about the clippy architecture and performance impact to know which would be best to implement it. What I can think of is to either:
1. Move the lint out of the `loops` mod as a standalone mod
2. Create another `LateLintPass` in a standalone mod that would emit `UNUSED_ENUMERATE_INDEX`

**Comment by y21** [comment]
You could also create `methods/unused_enumerate_index.rs`, look for the iterator adapter pattern here and emit `crate::loops::UNUSED_ENUMERATE_INDEX`, that would likely be the simplest option

**Comment by Ethiraric** [comment]
I could have looked a bit further and find the `methods` directory myself, which is what I was looking for. Thanks!

I didn't have anything in mind that would warrant a new lint pass, but that was the only other way I thought of. My knowledge of this codebase grows with time, but is still very vague.
