### ISSUE TITLE
Avoid implementing traits on type aliases

### ISSUE THREAD

**Issue by lambda-fairy** [rust-lang/rust-clippy#1242]
Due to rust-lang/rust#19381, trait `impl`s on type aliases are not shown in automatically generated documentation. Until this bug is fixed, it is better not to write code this way.

**Comment by mcarton** [comment]
IMO this is something to be fixed in rustdoc rather than linted about in Clippy.

**Comment by camsteffen** [comment]
The issue has been fixed
