### ISSUE TITLE
Suggest equivalent unsafe code if simpler.

### ISSUE THREAD

**Issue by bingmatv** [rust-lang/rust-clippy#12504]
### What it does

Sometimes unsafe code is simpler.

### Example

```rust
fn main() {
    let a = [1u8, 2, 3, 4];
    let mut b = [0u8; 3];
    b.copy_from_slice(&a[..3]);
    let a = (b, a[3]);
    println!("{a:?}")
}
```
The safe version seems to be complex, but unsafe version is simple:
```rust
fn main() {
    let a = [1u8, 2, 3, 4];
    println!("{:?}", unsafe { *(a.as_ptr() as *const ([u8; 3], u8)) })
}
```

**Comment by Alexendoo** [comment]
It's shorter but I would not call it simpler, the reader now has to consider if all the unsafe requirements are upheld. Pedantically  the example does not - tuples are considered `repr(Rust)` and do not have guaranteed field ordering

You're also risking UB if the lengths of `a` or the array ever change

**Comment by bingmatv** [comment]
> You're also risking UB if the lengths of `a` or the array ever change

If clippy can check unsafe code then show warnings about possible UB, it's friendly for beginners.

**Comment by Alexendoo** [comment]
It's not really worth suggesting `unsafe` here - it's a pretty niche situation since `a` would more often be a slice/vec where the suggestion is inappropriate

Particularly as there are alternative safe solutions to be had, such as destructuring or via `TryFrom`
