### ISSUE TITLE
Consolidate `unnecessary_filter_map` and  `filter_map_identity` into `filter_map.rs`

### ISSUE THREAD

**Issue by m-rph** [rust-lang/rust-clippy#12590]
### Description

**Context**: There are quite a few lints that operate on `filter_map`, some of which catch very special cases, such as `unnecessary_filter_map` and `filter_map_identity`.

**Task**: Consolidate `unnecessary_filter_map` and  `filter_map_identity` lints into the `filter_map.rs` module.

**Acceptance Criteria**: Lints are merged and we observe the same behaviour without regressions.

More details on [zulip](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Consolidating.20lints.20on.20.60filter_map.60).

Lints:
 - `unnecessary_filter_map`
 - `filter_map_identity`

Candidate / possibly optional lints:
 - `filter_map_bool_then`
 - `filter_map_next`

**Comment by m-rph** [comment]
@omer-shtivi I was about to close this issue as I don't think it's necessary. Perhaps you could consider one of the other good first issues?

**Comment by m-rph** [comment]
Closing, it's best to keep them separate, too many stuff moving around. It's easier to just extend one of these to enable the follow up issues.

**Comment by omer-shtivi** [comment]
Sure, I will take a look
