### ISSUE TITLE
Clippy is no longer available via crates.io

### ISSUE THREAD

**Issue by sharma-shray** [rust-lang/rust-clippy#12651]
### Description

Good afternoon, today for some reason there is a problem with starting cargo install clippy

error: failed to run custom build command for `clippy v0.0.302`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installOPE2nx/release/build/clippy-9f107f4418802678/build-script-build` (exit status: 1)
  --- stderr

### Version

```text
rustc 1.79.0-nightly (1684a753d 2024-04-01)
binary: rustc
commit-hash: 1684a753dbca5d23b2e03568e6fbbb48eb72d0e6
commit-date: 2024-04-01
host: x86_64-unknown-linux-gnu
release: 1.79.0-nightly
LLVM version: 18.1.2
```

**Comment by matthiaskrgr** [comment]
Indeed, clippy is nowadays shipped as a `rustup` component.

`rustup component add clippy` is the way to go :)

**Comment by blyxyas** [comment]
I can confirm Matthias' comment. The crates.io page is just set up to instruct the user the correct way to install Clippy.
Thanks for the report!

**Comment by Maferep** [comment]
Can this new method be added to the documentation? I can suggest an edit https://doc.rust-lang.org/stable/clippy/usage.html
