### ISSUE TITLE
clippy suggests to use retain in the same way as filter

### ISSUE THREAD

**Issue by itrumper** [rust-lang/rust-clippy#12663]
### Summary

When using `filter` on a collection that clippy detects can be simplified to a single `retain` call, the predicate used in the `filter` is not the boolean negation in the suggested usage.

### Reproducer

```rust
collection = collection
            .into_iter()
            .filter(|x| check(x))
            .collect();

fn check(x: f64) -> bool {
    x > 0.0
}
```

produces the following clippy lint

```
this expression can be written more simply using `.retain()`
for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_retain

consider calling `.retain()` instead: `collection.retain(|x| check(x))`
```

which uses the `check` function in the same way as before, leading to the inverse outcome of which elements of `collection` are filtered. To fix, change the suggested usage to read

```
consider calling `.retain()` instead: `collection.retain(|x| !check(x))`
```

### Version

```text
rustc 1.76.0 (07dca489a 2024-02-04)
binary: rustc
commit-hash: 07dca489ac2d933c78d3c5158e3f43beefeb02ce
commit-date: 2024-02-04
host: x86_64-pc-windows-msvc
release: 1.76.0
LLVM version: 17.0.6
```

**Comment by Alexendoo** [comment]
The current suggestion is correct, for both `filter` and `retain` the kept items are the ones where the function returns `true`

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=95dbb7a705a58b4c7d07cae890276ada

**Comment by itrumper** [comment]
My mistake! Thank you for the correction.
