### ISSUE TITLE
error: the 'cargo' binary, normally provided by the 'cargo' component, is not applicable to the '1.78.0-x86_64-unknown-linux-gnu' toolchain

### ISSUE THREAD

**Issue by zonglin-hub** [rust-lang/rust-clippy#12763]
### Description

error: the 'cargo' binary, normally provided by the 'cargo' component, is not applicable to the '1.78.0-x86_64-unknown-linux-gnu' toolchain

### Version

```text
❯ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/zonglin/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu
1.78.0-x86_64-unknown-linux-gnu

active toolchain
----------------

1.78.0-x86_64-unknown-linux-gnu (overridden by '/home/zonglin/github/leet_code/rust-toolchain.toml')
(rustc does not exist)
```

**Comment by Alexendoo** [comment]
I would guess this is https://github.com/rust-lang/rustup/issues/988, where e.g. rust analyzer runs at the same time you run a `cargo` command after updating the toolchain file. If it's not that please open a new rustup issue

The workaround is to uninstall the toolchain and reinstall it, usually stopping rust analyzer or similar while you're doing that

**Comment by Weisonorz** [comment]
For my device uninstalling rustup completely and reinstalling it solves the problem

**Comment by agirardeau** [comment]
I am experiencing this issue and have tried removing and reinstalling each of these without success:

* The `cargo` component
* The `x86_64-unknown-linux-gnu` toolchain
* `rustup` itself
