### ISSUE TITLE
New lint: adding a `char` to a String through `to_string()`

### ISSUE THREAD

**Issue by jakubdabek** [rust-lang/rust-clippy#12775]
### What it does

Warns when turning a `char` into a `String` before pushing it to another `String`.

### Advantage

- It's more clear that we're pushing only a single `char`
- It doesn't allocate a new `String`

### Example

```rust
let mut s = String::from("...");
let c = 'a';
// or: let c = &'a';
s.push_str(&c.to_string());
// or: s = s + &c.to_string();
// or: s += &c.to_string();
```

Could be written as:

```rust
let mut s = String::from("...");
let c = 'a';
s.push(c);
// or: s.push(*c); for the reference case
```

**Comment by J-ZhengLi** [comment]
could be an extension of `clippy::single_char_add_str`, which is a lot easier
