### ISSUE TITLE
Lint for loops that will never run more than once

### ISSUE THREAD

**Issue by nox** [rust-lang/rust-clippy#1290]
Clippy should warn about `loop { return; }`.

**Comment by Havvy** [comment]
I'm going to take my hand at this.

**Comment by mcarton** [comment]
@Havvy Thanks! Feel free to ask if you have any question.

**Comment by Havvy** [comment]
Blocked on https://github.com/rust-lang/rust/pull/37535

Well, theoretically anyways. I more want those methods there because they then have a guarantee that each node will have its NodeIndex with it in the iterator.

**Comment by Havvy** [comment]
Also, I'm using a CFG analysis for this, not AST. So T-AST is wrong. As is E-easy. E-medium perhaps.

**Comment by camsteffen** [comment]
Resolved by #1549.
