### ISSUE TITLE
Rename lint `THREAD_LOCAL_INITIALIZER_CAN_BE_MADE_CONST` 

### ISSUE THREAD

**Issue by alex-semenyuk** [rust-lang/rust-clippy#12934]
### Description

Existing lint `THREAD_LOCAL_INITIALIZER_CAN_BE_MADE_CONST` sounds against convention for other lints which describe the issue/wrong code but not suggestion. Also the name is quite long.

**Comment by m-rph** [comment]
Any suggestions? Iirc we iterated a bit until we found a descriptive enough name.

**Comment by y21** [comment]
`missing_const_for_tls` or `missing_const_for_threadlocal` would be in line with `missing_const_for_fn` (would help w/ the length at least)

**Comment by m-rph** [comment]
`missing_const_for_tl_init` perhaps?

**Comment by alex-semenyuk** [comment]
+1 `missing_const_for_tl_init`
