### ISSUE TITLE
Query: Integration with coverity

### ISSUE THREAD

**Issue by vithalsm** [rust-lang/rust-clippy#12946]
### Description

Hi,
Planning to use 'cargo clippy' and integrate the output with 'coverity' using 'cov-import-results'.
'cov-import-results' expects files/list of issues listed in xml format.  However 'cargo clippy' doesnt seem to have a way to product output in that format.

So, what is the right way to achieve same?  Appreciate any help on this regard.

Reference - https://community.synopsys.com/s/article/Does-Coverity-Support-Rust

Thanks in advance.

**Comment by Alexendoo** [comment]
`Cargo` has [`--message-format=json`](https://doc.rust-lang.org/cargo/reference/external-tools.html?highlight=output-format#json-messages) for machine readable output

You're probably best off asking Synopsys what the intended way to import the issues are

**Comment by vithalsm** [comment]
'--message-format' is not available with 'cargo clippy' command.
Unsure if 'Synopsys' can help here, as input has to come from 'cargo ..' commands.

**Comment by vithalsm** [comment]
Looks like 'snopsis' expects in certain format of json.  So, using '--message-forma=json' and passing the input to cov-import-results doesn't help.

**Comment by Alexendoo** [comment]
Right, clippy/cargo aren't going to add an output format for this specific tool, so you'll have to find out what Synopsis wants you to do or adapt it into the format it accepts yourself
