### ISSUE TITLE
Suggest longer lifetimes for function return values

### ISSUE THREAD

**Issue by matthew-piziak** [rust-lang/rust-clippy#1304]
In https://github.com/utkarshkukreti/select.rs/commit/ae590b50e4d1ca099ef089645fbff571e6495374, the returned references are given a type-bound lifetime.

It would be nice if clippy could make these recommendations automatically.

**Comment by Manishearth** [comment]
This would be interesting to implement; you have to track where the borrow comes from.

**Comment by matthew-piziak** [comment]
@oli-obk and I talked about this during Rust Belt Rust. We tried to refactor a piece of code to the effect of replacing a `&String` parameter to a `&str` parameter. We eventually tracked down to a lifetime problem in the `select.rs` library. When we went to make a pull request we discovered that the change had already been made in master.

**Comment by camsteffen** [comment]
Related #305
