### ISSUE TITLE
Doc broken on the website for `arithmetic_side_effects`

### ISSUE THREAD

**Issue by tguichaoua** [rust-lang/rust-clippy#13051]
### Description

The doc is broken for [`arithmetic_side_effects` on the website](https://rust-lang.github.io/rust-clippy/master/index.html#/arithmetic_side_effects):

![image](https://github.com/rust-lang/rust-clippy/assets/33934311/186f430f-99ad-4788-8929-2908361457eb)

### Additional Labels

@rustbot label +A-documentation +A-website

**Comment by GuillaumeGomez** [comment]
@alex-semenyuk Still working on it? Otherwise I'd like to fix it since it's been a few weeks already.

**Comment by xFrednet** [comment]
@GuillaumeGomez I think it's safe to claim the issue :D

**Comment by GuillaumeGomez** [comment]
Better safe than sorry. :wink: Thanks!

**Comment by alex-semenyuk** [comment]
@GuillaumeGomez yes, thanks for quick fix
