### ISSUE TITLE
Lint for redundant mut declaration in let binding to &mut

### ISSUE THREAD

**Issue by nivekuil** [rust-lang/rust-clippy#1309]
`let mut foo: &mut Vec<String> = &mut Vec::new();`
compiles with no warnings, but does not need the first `mut` to compile. It does make it more clear that `foo` is meant to be used mutably, though.

**Comment by oli-obk** [comment]
this should probably be a fix in the rustc lint, otherwise we end up duplicating a lot of the code.

**Comment by camsteffen** [comment]
This triggers `unused_mut` today.
