### ISSUE TITLE
Suggest using `eq_ignore_ascii_case` on non case-sensitive string comparision

### ISSUE THREAD

**Issue by CrazyboyQCD** [rust-lang/rust-clippy#13204]
### What it does

Lint that suggests using `eq_ignore_ascii_case` on non case-sensitive string comparision.

### Advantage

- avoid extra allocation([example](https://github.com/oxc-project/oxc/pull/4570))

### Example

```rust
a.to_xx_case() == b.to_xx_case()
```

Could be written as:

```rust
a.eq_ignore_ascii_case(b)
```

**Comment by nyurik** [comment]
@CrazyboyQCD hi, I finished the implementation, but it may need some more unit tests - could you add some you could think of? Thx!
