### ISSUE TITLE
Lint unnecessary negation when checking Option/Result value

### ISSUE THREAD

**Issue by fuine** [rust-lang/rust-clippy#1323]
This line: `!x.is_none()` should be rewritten as `x.is_some()`.  Same goes for `is_err` and `is_ok` on `Result`.

**Comment by oli-obk** [comment]
Should probably be part of the quine mc cluskey boolean simplification lint. Iirc that one already knows that `!(x==y)` is `x != y`

**Comment by camsteffen** [comment]
This is covered by `nonminimal_bool`.
