### ISSUE TITLE
Cargo clippy --fix not working with 1.80.1

### ISSUE THREAD

**Issue by psibi** [rust-lang/rust-clippy#13258]
### Summary

The command `cargo clippy --fix --allow-dirty` is not working as expected with 1.80.1. 

### Reproducer

I tried this code on a fresh project:

```rust
fn main() {
    let f = 1;
}
```

I expected the file to modify like this when I run `cargo clippy --fix --allow-dirty`:

```
fn main() {
    let _f = 1;
}
```

Instead the file was still this:

```
fn main() {
    let f = 1;
}
```

Infact, I confirmed that this was not the behavior in 1.76.0 and everything was working as expected there.

### Version

```text
❯ rustc -Vv
rustc 1.80.1 (3f5fd8dd4 2024-08-06)
binary: rustc
commit-hash: 3f5fd8dd41153bc5fdca9427e9e05be2c767ba23
commit-date: 2024-08-06
host: x86_64-unknown-linux-gnu
release: 1.80.1
LLVM version: 18.1.7
```

**Comment by y21** [comment]
This was intentionally changed in https://github.com/rust-lang/rust/pull/120470. The lint `unused_variables` no longer has a machine-applicable suggestion so rustfix won't try to automatically apply this particular warning.

Other suggestions that are marked as machine-applicable should still work, e.g. `useless_vec`: `vec![1].first()` should get autofixed to `[1].first()`

**Comment by psibi** [comment]
Ah, didn't realize that. Thanks! And the `useless_vec` does work.
