### ISSUE TITLE
Lint use of functions with underscore-prefixed names

### ISSUE THREAD

**Issue by laniakea64** [rust-lang/rust-clippy#13260]
### What it does

Flag use of functions with underscore-prefixed names.  See https://github.com/rust-lang/rust-clippy/discussions/13256

### Advantage

Same as the [existing `used_underscore_binding` lint](https://rust-lang.github.io/rust-clippy/stable/index.html#/used_underscore_binding).

### Example

```rust
fn _foo() {
  println!("Foo");
}

fn main() {
  _foo();
}
```

Could be written as:

```rust
fn foo_() {
  println!("Foo");
}

fn main() {
  foo_();
}
```

**Comment by flip1995** [comment]
Possible lint name: `used_underscore_items`.
