### ISSUE TITLE
clippy subcommand does not work properly when root directory is an executable

### ISSUE THREAD

**Issue by debris** [rust-lang/rust-clippy#1330]
steps to reproduce

1. Create new project and enter it
    ```
    cargo new foo --bin
    cd exe
    ```

2.  Create subproject and edit `Cargo.toml`
    ```
    cargo new bar
    ```

    ```toml
    [dependencies]
    bar = { path  = "bar" }
    ```

3. Run cargo clippy for subproject
    ```
    cargo clippy -p bar --verbose
    ```

cargo clippy exits with misleading error message

```
error: no bin target named `foo`
```

Other observations:
Above issue does not occur if root directory is a library. It looks like the issue is caused by incorrectly prepending `--bin` flag instead of `--lib` [here](https://github.com/Manishearth/rust-clippy/blob/6a73c8f8e3f513f6a16c6876be3d326633dbc78d/src/main.rs#L191)

**Comment by camsteffen** [comment]
I wasn't able to reproduce this.
