### ISSUE TITLE
rustc_tools_util: does not emit any "rerun-if-changed"

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust-clippy#13312]
In Miri, a while ago we replaced vergen by rustc_tools_util. However, unlike vergen, rustc_tools_util does not emit any "rerun-if-changed" and therefore the git hash it shows will not be properly updated on rebuilds.

**Comment by matthiaskrgr** [comment]
Right now i'm not sure if this can be solved while
1) making sure an empty commit retriggers a build
2) making sure when crate sources are NOT from a git repo root (crates io or rustc subrepo, basically no `.git/`), we do not trigger a rebuild every single time because the .git is not found

:/

**Comment by samueltardieu** [comment]
Wouldn't this cover all cases?

- Check if `.git/HEAD` is present, and if it is `rerun-if-changed` for `.git/HEAD`
- And in this case, if `git/HEAD` contains a `ref: REF_PATH`, `rerun-if-changed` for `$REF_PATH`

**Comment by RalfJung** [comment]
Yeah that seems to be what vergen does as well:

- If using one of the git enabled libraries, will emit [`cargo:rerun-if-changed=.git/HEAD`](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rerun-if-changed).  This is done to ensure any git instructions are regenerated when commits are made.
- If using one of the git enabled libraries, will emit [`cargo:rerun-if-changed=.git/<path_to_ref>`](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rerun-if-changed).  This is done to ensure any git instructions are regenerated when commits are made.
