### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by mcarton** [rust-lang/rust-clippy#1335]
At work I have a VS plugin warning about names such as `TOMLParser`. [According to Rust's naming conventions, this should be `TomlParser`.](https://github.com/rust-lang/rfcs/blob/master/text/0430-finalizing-naming-conventions.md#fine-points)
We should warn on more that 2 consecutive capital letters in a name.

**Comment by Manishearth** [comment]
I'd be wary of this, because of the amount of false positives it may cause. We used to do this but turned it off.

(Separate lint maybe?)

**Comment by oli-obk** [comment]
`CString` is an example of such a false positive

**Comment by mcarton** [comment]
*strictly more than 2
