### ISSUE TITLE
Unclear message in `type_complexity`

### ISSUE THREAD

**Issue by ChrisJefferson** [rust-lang/rust-clippy#13387]
### Summary

I'm not clear what `type_complexity` wants me to do.

The output says " very complex type used. Consider factoring parts into `type` definitions"

The webpage ( https://rust-lang.github.io/rust-clippy/master/index.html#/type_complexity ) tells me the same thing (use a type definition to simply).

The example shows me some bad code, but there is no example of what it should look like 'fixed'.

Attempts to google for 'type definition rust' just get me to pages that define what a type is in rust, and list the various data types available in Rust.

I suspect this is an easy doc fix for someone who knows what a 'type definition' is, and could maybe give an example on the webpage (might be too long for the terminal?) -- or is there a more searchable term than `type definition`?

**Comment by alex-semenyuk** [comment]
@ChrisJefferson merged clarified example. Could you please check - is it clear now? if so you could close

**Comment by ChrisJefferson** [comment]
Thanks, much clearer :)
