### ISSUE TITLE
auto-fix `if_not_else`

### ISSUE THREAD

**Issue by Rudxain** [rust-lang/rust-clippy#13411]
### Description

> [!note]
> I'm unsure if this is a bug-report or feature-request

`cargo clippy --fix` should swap the 2 blocks

### Version

1.81.0

> I'm sorry, I'm not using the device that has the tool-chain installed

**Comment by lukaslueg** [comment]
@Rudxain, there is no content in your op

**Comment by Rudxain** [comment]
> no content in your op

I guess it's the new GH Beta Issues. I can see the content

**Comment by samueltardieu** [comment]
@Rudxain Is it supposed to contain some code?

![Image](https://github.com/user-attachments/assets/1d5571a5-d09c-41fe-9c66-96f1a38fdc61)

**Comment by Rudxain** [comment]
What I meant is that the [example given](https://rust-lang.github.io/rust-clippy/master/index.html#/if_not_else):
```rust
if !v.is_empty() {
    a()
} else {
    b()
}
```
(and anything of the same form) should be auto-fixable.

Trying to fix it manually is very error-prone for bigger blocks, and `git diff` doesn't help much either :(
