### ISSUE TITLE
Compiler error when using `--fix` on `clippy::implicit_saturating_sub`

### ISSUE THREAD

**Issue by FreezyLemon** [rust-lang/rust-clippy#13524]
### Summary

`cargo clippy --fix` seems to sometimes cause a compiler error when fixing the `implicit_saturating_sub` lint.

### Reproducer

I tried running `cargo +nightly clippy --fix` on this code:

```rs
pub fn test(a: usize, b: usize, c: bool) -> usize {
    if c {
        123
    } else if a >= b {
        0
    } else {
        b - a
    }
}
```

I expected to see this happen:

```rs
pub fn test(a: usize, b: usize, c: bool) -> usize {
    if c {
        123
    } else {
        b.saturating_sub(a)
    }
}
```

Instead, this happened (compiler error):

```rs
pub fn test(a: usize, b: usize, c: bool) -> usize {
    if c {
        17
    } else b.saturating_sub(a)
}
```

### Version

rustc 1.83.0-nightly (3ae715c8c 2024-10-07)
binary: rustc
commit-hash: 3ae715c8c63f9aeac47cbf7d8d9dadb3fa32c638
commit-date: 2024-10-07
host: x86_64-unknown-linux-gnu
release: 1.83.0-nightly
LLVM version: 19.1.1

**Comment by blyxyas** [comment]
Note to future contributos: This is not an ICE, this is a lint that outputs code that is invalid.
I'll go check this out.
