### ISSUE TITLE
How does clippy record logs?

### ISSUE THREAD

**Issue by yu532758082** [rust-lang/rust-clippy#13527]
### Description

Hello Project Owner

I'm browsing clippy's code and hope to contribute.

But I found that clippy does not rely on the log library（e.g. tracing）, so how to debug the detection logic without logs?

**Comment by blyxyas** [comment]
Hi @yu532758082,
When I implement a new lint or a bugfix, I mainly rely on [`std::dbg`](https://doc.rust-lang.org/std/macro.dbg.html) and `cargo uitest`, yeah, maybe this isn't the best debugging method, but it's been there every time I needed it.

Take into account that we don't want `dbg` statements in PRs! Only use them for debugging problems and then remove them! 🌈 :heart:

**Comment by yu532758082** [comment]
> Hi [@yu532758082](https://github.com/yu532758082), When I implement a new lint or a bugfix, I mainly rely on [`std::dbg`](https://doc.rust-lang.org/std/macro.dbg.html) and `cargo uitest`, yeah, maybe this isn't the best debugging method, but it's been there every time I needed it.
> 
> Take into account that we don't want `dbg` statements in PRs! Only use them for debugging problems and then remove them! 🌈 ❤️

Why don't we use tracing crates to add logs? I tried it, but found that debug-level logs cannot be displayed normally.

**Comment by blyxyas** [comment]
The Rust compiler (Which Clippy calls) uses `env_logger` with `RUSTC_LOG` as the env. variable. 

The rustc-dev guide has [a section on this](https://rustc-dev-guide.rust-lang.org/tracing.html?highlight=log#using-tracing-to-debug-the-compiler), you may find it helpful.

**Comment by yu532758082** [comment]
> NOTE: The Rust compiler (Which Clippy calls) uses `env_logger` with `RUSTC_LOG` as the env. variable.
> 
> The rustc-dev guide has [a section on this](https://rustc-dev-guide.rust-lang.org/tracing.html?highlight=log#using-tracing-to-debug-the-compiler), you may find it helpful.

Thanks ， You solved all my problems, I will close this issue
