### ISSUE TITLE
website: dark color them renders code unreadable

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-clippy#13536]
### Description

https://rust-lang.github.io/rust-clippy/master/index.html#/panic

select the "coal" theme for example

![Image](https://github.com/user-attachments/assets/ffcbe5e5-888d-451e-8368-d09189286ffb)

**Comment by xFrednet** [comment]
cc: @GuillaumeGomez & @Alexendoo

**Comment by GuillaumeGomez** [comment]
The problem is fixed in https://github.com/rust-lang/rust-clippy/pull/13539. It was simply that the highlighting was not run.
