### ISSUE TITLE
Consider publishing `clippy_utils` as a crates.io crate for others to reuse

### ISSUE THREAD

**Issue by alice-i-cecile** [rust-lang/rust-clippy#13556]
### Description

Over at the `bevy_cli` project, we're implementing custom lints for Bevy, and bootstrapping off of Clippy's existing tools :) We'd love to publish this to crates.io so folks can `cargo install bevy_cli`, but can't do so easily due to `clippy_utils` only existing as a git dependency.

We don't particularly care about stability or the like: simply publishing whatever you have periodically would be enough.

Prompted by https://github.com/TheBevyFlock/bevy_cli/issues/150

**Comment by BD103** [comment]
For the period, you could definitely match what [Cargo does](https://lib.rs/crates/cargo) and publish for every stable release.

The API doesn't need to be stable, it just needs to be compatible with the nightly corresponding to that release.

Thanks for your consideration!

**Comment by flip1995** [comment]
> as long as each release provides what nightly version they were pinned to at that time

How would you recommend to best provide this information?

**Comment by BD103** [comment]
> > as long as each release provides what nightly version they were pinned to at that time
> 
> How would you recommend to best provide this information?

The `channel` field within [`rust-toolchain`](https://github.com/rust-lang/rust-clippy/blob/a109190d7060236e655fc75533373fa274ec5343/rust-toolchain) is enough! :)

If releases are to be automated, you can automatically extract this value using [Taplo](https://taplo.tamasfe.dev/). I did something very similar in `bevy_lint`'s [CI](https://github.com/TheBevyFlock/bevy_cli/blob/1cb8e3a9c24c855994fba58ee199ccc9dce0df0d/.github/workflows/ci.yml#L10-L34).

**Comment by flip1995** [comment]
Offtopic: shouldn't [this](https://github.com/TheBevyFlock/bevy_cli/blob/1cb8e3a9c24c855994fba58ee199ccc9dce0df0d/.github/workflows/ci.yml#L76) be 

```
toolchain: ${{ needs.extract-rust-version.outputs.toolchain }}
```

in your workflow file?

---

Extracting this in an automated way from the `rust-toolchain` file is easy. My question is more: where should I put this information? Just in the `README` of `clippy_utils`/`clippy_config`?

**Comment by BD103** [comment]
> Offtopic: shouldn't [this](https://github.com/TheBevyFlock/bevy_cli/blob/1cb8e3a9c24c855994fba58ee199ccc9dce0df0d/.github/workflows/ci.yml#L76) be
> 
> ```
> toolchain: ${{ needs.extract-rust-version.outputs.toolchain }}
> ```
> 
> in your workflow file?

For a second I thought so too, but [I rename it in the job outputs](https://github.com/TheBevyFlock/bevy_cli/blob/1cb8e3a9c24c855994fba58ee199ccc9dce0df0d/.github/workflows/ci.yml#L16):

```yaml
    outputs:
      channel: ${{ steps.toolchain.outputs.toolchain }}
      components: ${{ steps.toolchain.outputs.components }}
```

This is confusing, though, so I'll probably change it.

> Extracting this in an automated way from the `rust-toolchain` file is easy. I'd probably just use a `grep` command though. My question is more: where should I put this information? Just in the `README` of `clippy_utils`/`clippy_config`?

If you use [Github Releases](https://github.com/rust-lang/rust-clippy/releases), you could add it there. (Maybe also the `CHANGELOG.md`?)

**Comment by flip1995** [comment]
`CHANGELOG.md` is just for stable and external releases for Clippy itself. Not for something like this. And I'd like to keep it that way.

If we would start using Github releases, I think we would need to copy the whole changelog there every time, so that it is a proper release. I'd rather avoid that.

So I guess, I will add it to the `README` of the crates, so that it also shows up on the crates.io page when publishing.

**Comment by BD103** [comment]
> So I guess, I will add it to the `README` of the crates, so that it also shows up on the crates.io page when publishing.

If that's too much of a hassle, each release is tagged, so I can figure it out using the tagged commit.

**Comment by flip1995** [comment]
Let's wait for the clippy meeting where we talk about this. And if we decide that we want to publish it, I'll think about what would work for me and other people involved in releases and would make it easy for you to find the toolchain.

**Comment by smoelius** [comment]
> We'd love to publish this to crates.io so folks can `cargo install bevy_cli`, but can't do so easily due to `clippy_utils` only existing as a git dependency.

Won't the user have to specify the toolchain on the command line, e.g.:
```
cargo +nightly-2024-10-03 install bevy_cli
```
Or am I missing something?

**Comment by BD103** [comment]
> Won't the user have to specify the toolchain on the command line, e.g.:
>
> ```
> cargo +nightly-2024-10-03 install bevy_cli
> ```
>
> Or am I missing something?

You're right, but I still prefer it to `--git https://github.com/ TheBevyFlock/bevy_cli --tag lint-v0.1.0 bevy_lint`! It's shorter and I trust it more, since unlike tags versions published to crates.io cannot be modified.

**Comment by flip1995** [comment]
https://crates.io/crates/clippy_utils

#13700 will close this issue.
