### ISSUE TITLE
run clippy on our doc code examples

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust-clippy#1364]
see #1362 for a funny one

**Comment by mcarton** [comment]
Find a way to integrate clippy into rustdoc?

Most of our example are not complete, so they wouldn't compile anyway.

**Comment by oli-obk** [comment]
It's not rustdoc, it's libtest. We might be able to inject clippy as a plugin.

**Comment by phansch** [comment]
This is now doable and partly done with https://github.com/rust-lang/rust-clippy/pull/3845 :tada:
