### ISSUE TITLE
Nit re `unnnecessary_map_or` message

### ISSUE THREAD

**Issue by smoelius** [rust-lang/rust-clippy#13704]
I recently started getting suggestions to replace `.map_or(false, ...)` with `is_ok_and(...)`/`is_some_and(...)`:
```
warning: this `map_or` is redundant
 --> src/main.rs:6:20
  |
6 |     println!("{}", c.map_or(false, char::is_alphabetic));
  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use is_some_and instead: `c.is_some_and(char::is_alphabetic)`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or
  = note: `#[warn(clippy::unnecessary_map_or)]` on by default
```

I like the suggestions :pray:, but I'm not sure "is redundant" is the right phrase to use in the warning.

Maybe "can be simplified"?

[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=bed99dc9da3845162405ea0a5a5534aa) for those who haven't come across this yet.

**Comment by samueltardieu** [comment]
Agreed. The "can be simplified" is already used in other places and this makes sense.
