### ISSUE TITLE
lint type `&Option<&T>`

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust-clippy#1377]
since `&` is `Copy`, just suggest to use `Option<&T>`

**Comment by clarcharr** [comment]
This applies to `&mut Option<&mut T>` too, because `as_ref` and `as_mut` exist.

**Comment by shepmaster** [comment]
> This applies to `&mut Option<&mut T>` too

Does it though? With a `&mut Option<T>`, I could `mem::replace` or `mem::swap` it with a completely different option, or call `Option::take` on it, which does the same thing internally.

**Comment by clarcharr** [comment]
@shepmaster I think you misunderstood; `&mut Option<&mut T>` should be written as `Option<&mut T>`, not `&mut Option<T>`. This is very similar to writing `&&T` instead of `&T`.

**Comment by Manishearth** [comment]
> I think you misunderstood; `&mut Option<&mut T>` should be written as `Option<&mut T>`, not &mut Option<T>.

@shepmaster's comment still applies. You cannot set the shared `Option` to `None` with `Option<&mut T>`
