### ISSUE TITLE
Check if files end with a newline

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust-clippy#1378]

**Comment by mcarton** [comment]
This might be tricky to do with clippy (which does not actually read files but rather uses AST from rustc), but could be done by rustfmt.

**Comment by mrZalli** [comment]
I agree, this sounds much more like it should be on rustfmt since it is a code formatting style issue.

**Comment by phansch** [comment]
As was mentioned, this makes more sense to be in rustfmt so I'm going to close this.
