### ISSUE TITLE
Lint suggestion: function that returns an `Option` but does not return `None`

### ISSUE THREAD

**Issue by kud1ing** [rust-lang/rust-clippy#1388]
Motivation: I was wrapping the result of native function call in a Rust struct via FFI.
In case of a null pointer i wanted to return `None`. But then i forgot to check in some places, so i happily wrapped the null pointer in a Rust structure which should have been null-pointer free => crash.

Can clippy warn if a function never returns a `None`?

**Comment by oli-obk** [comment]
We obviously can't know what other functions do, so we need to bail out if you call another function that might generate a `None`

**Comment by kud1ing** [comment]
Also maybe this should not apply to trait functions. A trait might enforce an Option while only a Some might sense for the concrete type.

**Comment by camsteffen** [comment]
This is `unnecessary_wraps`
