### ISSUE TITLE
Warn about non-working null check `!foo == 0`

### ISSUE THREAD

**Issue by jhasse** [rust-lang/rust-clippy#1391]
```rust
fn main() {
	let c_pointer = 42;
	if !c_pointer == 0 {
		println!("not null");
	} else {
		println!("null");
	}
}
```

I think it's very likely that the user wanted to do

```rust
    if !(c_pointer == 0) {
```

instead and doesn't expect that `!c_pointer` becomes `-43`.

Real world example which caused a bug: https://github.com/jhasse/ears/commit/6864642918009b8c56c688c9dfd2af0a8c6a5df7#diff-6e4c08fe803681d7479de1c01cefd4f2R179

**Comment by oli-obk** [comment]
Why would youmove away from pointers and use integers in the first place? Pointers don't even have the ! Operator implemented.

We can in general suggest to change `!x == 0` to `x == !0`, which is clearer in any case

**Comment by jhasse** [comment]
> We can in general suggest to change !x == 0 to x == !0, which is clearer in any case and saves you a runtime op (which the optimizer will probably eliminate anyway)

Isn't `!0 == -1` and therefore the two expressions aren't the same?

**Comment by clarcharr** [comment]
`!0` is clearer when you're doing bitmasks IMHO.

**Comment by oli-obk** [comment]
> Isn't !0 == -1 and therefore the two expressions aren't the same?

`!x == y` is the same as `!!x == !y`, (just like `-x == y` is the same as `--x == -y`). Also `!!x` is the same as `x` (just like `--x` is the same as `x`). Thus `x == !y`.

If one side of a comparison is a constant, I'd rather do complex stuff to the constant than to the variable.

**Comment by oli-obk** [comment]
> !0 is clearer when you're doing bitmasks IMHO.

Since the current situation came from a bug, it doesn't matter if it is unclear in this situation.

Is the `!` operator for integers used outside of hand-crafted optimizations or bitmasks?

**Comment by felix91gr** [comment]
Is this issue still a thing we want linted? If so, what is the thing being linted? I got a bit confused over the comments.

**Comment by flip1995** [comment]
The thing to lint would be a integer comparison, where one integer is prefixed with `!`. In the case wher one side is constant the `!` should be moved to the constant. In other cases `!(x == y)` may or may not be the intention of the comparison. I don't know if we should lint this though, since this suggestion would change the semantics drastically.

**Comment by felix91gr** [comment]
> I don't know if we should lint this though, since this suggestion would change the semantics drastically.

Could we then maybe, lint it without a suggestion? Or would it be too useless then?

**Comment by flip1995** [comment]
> Or would it be too useless then?

Since this is totally valid code, if we lint this, this would only qualify as a restriction lint or at most a pedantic lint. I don't think many people will discover / use this lint in that case.

**Comment by felix91gr** [comment]
> I don't think many people will discover / use this lint in that case.

Should we close this then? Or maybe we just leave it here for the moment at which someone implements it :thinking:

**Comment by flip1995** [comment]
I close this, since I think the only thing that could be linted here would be `!x == CONST` -> `x == !CONST`. But this is not really a benefit regarding readability, since `!` with an integer is never obvious, no matter if it is in front of the constant or the var.
