### ISSUE TITLE
Shared Library issue with Nightly

### ISSUE THREAD

**Issue by CryZe** [rust-lang/rust-clippy#1395]
Well, this seems to be happening again.

```
C:/Users/Christopher/.cargo/bin/cargo-clippy.exe: error while loading shared libraries: rustc_driver-36e125fb8252217f.dll: cannot open shared object file: No such file or directory
```

rustc 1.15.0-nightly (8f02c429a 2016-12-15)
rustup 1.0.0 (17b6d21 2016-12-15)
clippy 0.0.104

Could be caused by the .multirust -> .rustup change.

**Comment by Manishearth** [comment]
You need to make sure clippy is compiled with the nightly that is installed. If you update your nightly you must recompile clippy.

**Comment by CryZe** [comment]
I did compile it like 10 times, still happens.

**Comment by Manishearth** [comment]
Does a library with that filename exist in the rustup folder somewhere?

You may need to set the sysroot env var when running clippy.

It usually picks up the sysroot from RUSTUP_HOME or MULTIRUST_HOME, but if it doesn't it looks for the SYSROOT var.

https://github.com/Manishearth/rust-clippy/blob/master/src/main.rs#L228

https://github.com/Manishearth/rust-clippy#as-a-cargo-subcommand-cargo-clippy

**Comment by CryZe** [comment]
The file exists and none of these environment variables seem to do anything that fixes it. rustup seems to appropriately react to those environment variables, but the shared library issue persists.

**Comment by CryZe** [comment]
If I put that folder into my PATH it seems to work. So I guess rustup has the PATH issue again it used to have some time ago.

**Comment by CryZe** [comment]
rustfmt-nightly has the same problem.

**Comment by driftluo** [comment]
The some problem on linux:
```shell
$ cargo +nightly clippy
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/home/luoc/.cargo/bin/clippy-driver rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro` (exit code: 127)
--- stderr
/home/luoc/.cargo/bin/clippy-driver: error while loading shared libraries: librustc_driver-44c8832b145e50f7.so: cannot open shared object file: No such file or directory
```
I can't find the so file on my machine:
```bash
$ pwd
/home/luoc/.multirust
$ fd librustc_driver
toolchains/nightly-2018-05-23-x86_64-unknown-linux-gnu/lib/librustc_driver-1bfecc00300166b0.so
toolchains/nightly-2018-05-23-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_driver-1bfecc00300166b0.so
toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-16a0e7b01ae08fc0.so
toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_driver-16a0e7b01ae08fc0.so
toolchains/stable-x86_64-unknown-linux-gnu/lib/librustc_driver-2d4297d0ae6fcf70.so
toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_driver-2d4297d0ae6fcf70.so
```
```bash
$ uname -a
Linux driftluo 4.15.0-30-generic #32-Ubuntu SMP Thu Jul 26 17:42:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by lnicola** [comment]
@driftluo `clippy` is now available in `rustup`:

```bash
rm ~/.rustup/bin/{cargo-clippy,clippy-driver}
rustup install clippy-preview
```

You might also need to update `rustup` beforehand.

**Comment by mati865** [comment]
@lnicola it's better to use `cargo uninstall clippy` than `rm`. This way there is no junk left in `~/.cargo/.crates.toml`.

**Comment by lnicola** [comment]
@Manishearth Maybe this issue can be closed now?

**Comment by driftluo** [comment]
`rm ~/.rustup/bin/{cargo-clippy,clippy-driver}` and rm clippy on `~/.cargo/.crates.toml` is right.
and then `rustup self update`, install with `rustup component add clippy-preview --toolchain=nightly`
run with `cargo-clippy +nightly` or `cargo +nightly clippy` is ok

**Comment by Manishearth** [comment]
You shouldn't remove anything, rustup handles that on its own

**Comment by phansch** [comment]
Thanks for all your reports. Since this issue seems to be resolved, I'm going ahead and close it. Feel free to open a new issue if you still encounter similar errors.
