### ISSUE TITLE
Add topics to GitHub

### ISSUE THREAD

**Issue by mcarton** [rust-lang/rust-clippy#1499]
See https://github.com/blog/2309-introducing-topics.
Looks like only the owner can do that @Manishearth :smile:

We should have *Rust* and *linter* at least.

**Comment by BO41** [comment]
If only the owner can do this, is it really a "good first issue"?

Also, is there something blocking the issue from being fixed and closed? :smiley:

**Comment by phansch** [comment]
Good point, I removed the label =)

> something blocking

I guess just limited time and priorities

**Comment by mcarton** [comment]
Actually, I have rights for this now. I've added Rust and Lint.
