### ISSUE TITLE
Panic when compiling redis-rs with clippy

### ISSUE THREAD

**Issue by Eijebong** [rust-lang/rust-clippy#1517]
redis-rs uses the "RUSTC" environment variable to determine the current rustc version by calling `$RUSTC --version`.
Since clippy sets this to "/home/user/.cargo/bin/cargo-clippy", the version is not the expected format at all and it just panics because there is no error handling in the build.rs

@mitsuhiko @badboy

**Comment by mitsuhiko** [comment]
Not sure what to do about that. How else can we get the version?

**Comment by badboy** [comment]
I'm inclined to say "Just don't do it then", but that would be not so nice.
We could bail out and simply not set the `with-system-unix-sockets` if we can't parse output from `$RUSTC --version`. That atleast would enable a clippy run.

**Comment by oli-obk** [comment]
Alternatively you can build clippy as a library and use RUSTFLAGS to enable clippy. Unfortunately I see no way to get `cargo clippy` working without either the ability to install libraries or using RUSTC

**Comment by Eijebong** [comment]
Same error with rocket_contrib @SergioBenitez

**Comment by mitsuhiko** [comment]
I wonder if clippy could not ship a RUSTC wrapper that makes it behave more the same. Parsing RUSTC output is not unpopular.

**Comment by SergioBenitez** [comment]
@Eijebong Rocket should be emitting a warning if it can't retrieve the current version; the build script should not panic in this case.

**Comment by Eijebong** [comment]
Ok, I got no warning whatsoever... I guess it was redis again but it panicked under the « compile rocket_codegen » line... Sorry :p

**Comment by SergioBenitez** [comment]
@Eijebong That's caused by https://github.com/rust-lang/cargo/issues/3777. If you pass `-vv`, you should see the warning.
