### ISSUE TITLE
Lint for Vec::new, should suggest vec![]

### ISSUE THREAD

**Issue by malbarbo** [rust-lang/rust-clippy#1542]
Care must be taken if the turbo fish operator is used, replacing `Vec::<T>::new()` with `vec![]` can cause the type inference to fail.

Now I think that my old list of lints suggestions has ended...

**Comment by clarcharr** [comment]
I think the opposite, actually; usually people prefer `Vec::new()` over `vec![]`.

**Comment by pengowen123** [comment]
I prefer using `Vec::new()` over `vec![]`. The lint could be allow by default to let people choose what style they prefer. Or if there is a style RFC for this the lint could follow it instead.

**Comment by Manishearth** [comment]
I don't think there is really an agreement on the style here. Most repos I've worked with use a mixture. It could be an allow lint, but I'm not fond of allow lints for completely-undecided lints like these where the exact opposite lint is just as valid and just as accepted by the community.

**Comment by clarcharr** [comment]
FWIW I opened a rustfmt RFC and perhaps the discussion on this could be moved to there.

**Comment by oli-obk** [comment]
> I'm not fond of allow lints for completely-undecided lints like these where the exact opposite lint is just as valid and just as accepted by the community.

isn't that the definition of a restriction lint?

**Comment by Manishearth** [comment]
Well, not really, restriction lints are more like "the lint makes sense for some folks and doesn't for others", but not "the *opposite* lint makes sense for others"

**Comment by oli-obk** [comment]
Ok, then I wrote a wrong restriction lint. The one forbidding assign ops.

**Comment by Manishearth** [comment]
Oh, like that. Hm, that one sounds okay. I guess my issue is with the fact that there's no clear preference here (and both lints would be restrictions), whereas with assign ops folks seem to unanimously prefer assign ops. Also, there's a decent motivation to the "no assign op" lint about folks from other languages, this seems to be a style decision that we don't really need to weigh on.

**Comment by clarcharr** [comment]
So I was thinking about this later and have decided upon a compromise.

I think that it'd be reasonable to have a lint for a mix of both styles, i.e. if a crate has both styles somewhere in the code then it should suggest to make them match. This way, it doesn't force a particular style, but can tell people to be consistent. Also, we could count occurrences of both and suggest to replace with the more prevalent style if possible.

**Comment by Manishearth** [comment]
idk I feel like this is one of those irrelevant things that's not worth enforcing. sometimes there are two ways to do things, and it's not harmful to use both

**Comment by AndreKR** [comment]
Would it be possible to warn about the few places where one style is used if the majority of the places in the project uses the other style?

**Comment by Manishearth** [comment]
We don't typically do global lints

**Comment by AndreKR** [comment]
I still meant to show the lint for the places where the problem exists, I was just suggesting to do some kind of pre-pass where it would determine what the dominant style for the project is.

**Comment by Manishearth** [comment]
Right, we don't typically do things like that

**Comment by frewsxcv** [comment]
Thoughts on closing this? Doesn't seem like we're converging on a solution here
