### ISSUE TITLE
Lint direct calls to `deref` or `deref_mut`

### ISSUE THREAD

**Issue by clarfon** [rust-lang/rust-clippy#1566]
Instead of calling `x.deref()` or `x.deref_mut()`, `&*x` and `&mut *x` should be recommended instead.

**Comment by ishitatsuyuki** [comment]
+1. This should tagged as easy (and attract some bored people from TWiR).

**Comment by oli-obk** [comment]
Probably should not lint if it's part of a method chain

**Comment by tommilligan** [comment]
I'd like to take this if still valid

**Comment by ThibsG** [comment]
Can we consider this one done?
Seems that trigger failed on 'Closes' in the PR

**Comment by oli-obk** [comment]
The PR was closed due to inactivity, so this hasn't been merged yet.
