### ISSUE TITLE
Warn on `let _ = x.lock();`

### ISSUE THREAD

**Issue by mcarton** [rust-lang/rust-clippy#1574]
See #40096.

**Comment by ishitatsuyuki** [comment]
Which #40096?

**Comment by mcarton** [comment]
Fortunately Clippy isn't at 40096 (yet :smile:)!

**Comment by FaultyRAM** [comment]
Note that rustc has a lint `unused-results` that could conflict with this (as one way to resolve that lint is via a `let _` binding).

**Comment by mcarton** [comment]
@FaultyRAM the rustc lint does not lint on `_name`.
