### ISSUE TITLE
new_without_default_derive help is confusing

### ISSUE THREAD

**Issue by wfraser** [rust-lang/rust-clippy#1579]
The current help text implies it's only for trivial cases that can be solved by typing `#[derive(Default)]`, but the lint really fires for any struct that has a `pub fn new() -> Self`, even ones that have logic inside them (which can't be replaced with a `#[derive(Default)]`).

Help text should indicate that it means either doing the `derive`, or implementing `Default` by hand.

**Comment by rail-rain** [comment]
This is essentially a duplicate of #3697, which is younger; but got a detailed comment. The proposed change is slightly different form that one though.

**Comment by wfraser** [comment]
This lint has been long since improved.
