### ISSUE TITLE
Derived PartialOrd and implemented Ord

### ISSUE THREAD

**Issue by stjepang** [rust-lang/rust-clippy#1621]
Suggestion: if a user writes `#[derive(PartialOrd)]` and then implements `Ord` manually, we should issue a warning. This is almost certainly wrong and will lead to problems.

The same applies to `PartialEq` and `Eq`.

See rust-lang/rust#40192 for an example.

**Comment by theemathas** [comment]
I'm going to try doing this. I should be able to reuse code in `clippy_lints/src/derive.rs`.

**Comment by xfix** [comment]
Derived `PartialEq` and implemented `Eq` is mostly harmless, I don't think it should be linted on. It's necessary for having floating types in a struct (as long it can be proved they will never store floating point numbers), and is harmless otherwise (there is no code in `Eq` trait).

**Comment by xfix** [comment]
Specifically, I think this is the best approach about it:

- `impl PartialEq`, `#[derive(Eq)]` - No warnings, deriving `Eq` is always fine as it has no extra methods.
- `#[derive(PartialEq)]`, `impl Eq` - Unnecessary warning, if it's not necessary (it's considered necessary if struct has generic parameters without `Eq` bound or has `PartialEq`-only types).
- `impl PartialOrd`, `#[derive(Ord)]` - Correctness warning.
- `#[derive(PartialOrd)]`, `impl Ord` - Correctness warning if `Ord` implementation isn't trivial (an example of trivial implementation would be `self.partial_cmp(other).unwrap()`). Unnecessary warning if it's not necessary (it's considered necessary if struct has generic parameters without `Ord` bound or has `PartialOrd`-only types).

**Comment by Ryan1729** [comment]
I would like to work on this. Specifically, I would like to create a new `derive_ord_xor_partial_ord` lint which would work analogously to the `derive_hash_xor_partial_eq` lint.
