### ISSUE TITLE
Lint `HashMap<T, ZST>` where ZST is any zero sized type

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust-clippy#1641]
The user should be using `HashSet<T>` instead and magically create the ZSTs out of thin air when needed (since they are all the same value anyway).

**Comment by clarcharr** [comment]
One exception I can think of for this: ZSTs not located in the same crate.

For example, if a dependency defines `struct MyError(())` then this lint shouldn't trigger because the user can't necessarily create the value out of thin air, and it might not be a ZST in the future.

**Comment by korrat** [comment]
Hi, I would like to take a shot at this.

**Comment by ebroto** [comment]
Hey @korrat, it's all yours!

If you have any question, don't hesitate to ask here, in Zulip, or open a draft PR.
