### ISSUE TITLE
Lint null function pointers

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust-clippy#1644]
https://github.com/rust-lang/rust/issues/40913 showed a real world case of assuming that `fn()` can be null.

patterns that should be linted are

```rust
std::mem::transmute::<Anything, SomeFnPtrType>(std::ptr::null())
```

```rust
(fn_ptr as *mut something).is_null()
```

**Comment by rillian** [comment]
I think also
```rust
(fn_ptr as *const something).is_null()
```

**Comment by rillian** [comment]
I think also
```rust
(fn_ptr as *const something).is_null()
```
And perhaps suggest `as {*mut, *const} Option<fn_ptr>` instead.

I guess we can't lint a bare fn_ptr in a `#[repr(C)]` struct because if it's only created on the Rust side, C code could read it safely relying on it being non-null.

**Comment by Manishearth** [comment]
I don't see why you want to cast to a `*const Option<fn>`?

**Comment by rillian** [comment]
I don't properly understand the difference between `*mut` and `*const` with function pointers. `(fn_ptr as *const something)` compiles, so I figured the lint should take both into account.

**Comment by Manishearth** [comment]
Sure, my issue is with the `Option` being beind a pointer. You probably want to transmute the C void pointer to an `Option<fn>`, not `*Option<fn>`

**Comment by rillian** [comment]
Oh, right. Sorry! Yes that. :)

**Comment by oli-obk** [comment]
I would not transmute (cast is not possible anyway) to `Option<fn()>`, since that gives the wrong idea. You need to do `Some(fn_ptr)` if you want a nullable fn pointer.

Anyway, this is a clear bug-case, so we should not suggest anything, since that will totally depend on the use case and it will be incredibly hard to create a good suggestion.
