### ISSUE TITLE
Lint unannotated transmutes

### ISSUE THREAD

**Issue by clarfonthey** [rust-lang/rust-clippy#1660]
I'm thinking of something where you have to either have:

1. Both types fully annotated
2. It be the only part of a function body, potentially including an `unsafe` block.

**Comment by oli-obk** [comment]
related: #715

**Comment by ndmitchell** [comment]
The first of these rules seems super useful, and I came to request.

The second doesn't seem so useful. Once you have annotated both types, the requirement to put it in its own function is reduced.

**Comment by clarfon** [comment]
My reasoning for the second part is that you should have dedicated functions for these transmutes that are marked as either safe or unsafe depending on the situation, and use those instead of the transmutes directly.

**Comment by ndmitchell** [comment]
@clarfon I have that for some functions, but not others - sometimes exposing that function would make the invariants I'd like to encode harder. Not that your request is unreasonable, just that I'd want to turn on the first lint, and off the second, so they can be treated independently.

**Comment by clarfon** [comment]
That's very fair, I'd agree with making them separate lints. Curiously, do you have any examples of cases where it makes sense to not have the second?

**Comment by ndmitchell** [comment]
I have a structure that reads:

```
struct Foo {
   bar: SomeReferenceContainingType
   baz: SomePointerWrapper<'bar>
}
```

Where the pointer wrapper `baz` points into `bar`, but that is behind a reference. This pattern might even be supported in Polonius: https://nikomatsakis.github.io/rust-belt-rust-2019/#95

For the moment I encode that with:

```
struct Foo {
   bar: SomeReferenceContainingType
   baz_wrong: SomePointerWrapper<'static>
}

impl Foo {
   fn baz<'x>(&'x self) -> SomePointerWrapper<'x> {
       transmute(&self.baz_wrong)
   }
}
```

The transumute both pulls out the field and converts it, which is a nice single atomic operation. Whereas casting any arbitrary `SomePointerWrapper` would be wrong. Also, missing the types on transmute makes you likely to type `transmute(self)` and get a segfault (which I did!).

**Comment by croker89** [comment]
Restablecer facebook

**Comment by xFrednet** [comment]
Hey @croker89, was your comment added on purpose here? :) To me, it's not clear what you mean

**Comment by lukaslueg** [comment]
[`missing_transmute_annotations`](https://rust-lang.github.io/rust-clippy/master/index.html#/missing_transmute_annotations), added in 1.79, resolves this?!
