### ISSUE TITLE
Lint test functions which aren't marked as `cfg(test)`

### ISSUE THREAD

**Issue by clarfonthey** [rust-lang/rust-clippy#1719]
We could also potentially lint test functions which aren't in a module that's marked `cfg(test)`.

**Comment by Alexendoo** [comment]
A restriction lint [for tests outside test modules](https://rust-lang.github.io/rust-clippy/master/index.html#/tests_outside_test_module) was added

`#[test]` implies `#[cfg(test)]` so a lint wouldn't be needed for this particular case
