### ISSUE TITLE
Lint usage of Result<T, ()>

### ISSUE THREAD

**Issue by clarfonthey** [rust-lang/rust-clippy#1721]
A more-descriptive error type should be used instead.

This could probably be limited to just traits like `FromStr`.

**Comment by clarcharr** [comment]
Note: servo/rust-url#299 is an example of this in the wild.

**Comment by TedDriggs** [comment]
For FromStr implementations for enums with unit variants, what would the more useful error here be?

**Comment by clarcharr** [comment]
@TedDriggs a unit error struct that implements `Error`
