### ISSUE TITLE
single_match should suggest plain `if` when possible

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust-clippy#173]
Currently, for things like:

```
match foo
  Enum::Variant => {...}
  _ => {...}
}
```

we suggest using `if let Enum::Variant = foo {...}`. However, in many cases, the enum implements `PartialEq`, so we can just suggest `if Enum::Variant == foo`.

This involves checking if the patterns in the match are simple `PatIdent`s or `PatEnum`s with empty pat-vecs (http://manishearth.github.io/rust-internals-docs/syntax/ast/enum.Pat_.html), and then checking if the type implements `Eq` (not sure how this can be done, probably needs some mucking about in `middle::ty`)

**Comment by llogiq** [comment]
Is there any downside in using if let as opposed to equality? Performance-wise?

Also equality may be implemented differently (e.g. broader than a match) – we should probably tread carefully here.

**Comment by birkenfeld** [comment]
I agree, we should not propose changes that could alter semantics.

**Comment by llogiq** [comment]
We could note the alternative but caution that semantics may be different depending on the `PartialEq` implementation.

I note that there is a case where this tripped me in eq_op.

**Comment by llogiq** [comment]
Also the same blacklist approach as in #181 could apply.
