### ISSUE TITLE
Lint usage of negative feature names in Cargo.toml

### ISSUE THREAD

**Issue by kennytm** [rust-lang/rust-clippy#1746]
(Only works with `cargo clippy`, may not be in scope with clippy. See #1614)

Features are supposed to be additive, and negatively-named features violate it. Lint when the crate declares a feature named `no_std` / `no-std`, and suggest using `default-features = ["std"]` instead.

(Main motivation in rust-lang/rfcs#1841.)

**Comment by clarcharr** [comment]
Perhaps we could also suggest common conventions, like `nightly` => `unstable`.
