### ISSUE TITLE
Crashes on Windows

### ISSUE THREAD

**Issue by vasily-kirichenko** [rust-lang/rust-clippy#1777]
```
cargo install clippy
cargo-clippy
```
![image](https://cloud.githubusercontent.com/assets/873919/26355470/8042f3e0-3fd1-11e7-8605-fb0937ef72f4.png)

rustc 1.19.0-nightly (14f30da61 2017-05-21)
cargo 0.20.0-nightly (397359840 2017-05-18)

**Comment by oli-obk** [comment]
I think you need to add `.rustup/toolchain/nightly/bin` to your PATH on windows.

**Comment by johnthagen** [comment]
Clippy hasn't worked for me in Windows for a few months. Just checked again today and it still doesn't run on the latest nightly.

```
> rustc +nightly --version
rustc 1.22.0-nightly (4750c1ec0 2017-10-19)

> cargo +nightly install clippy --force
...
Downloading clippy v0.0.166
  Installing clippy v0.0.166
...
> >cargo clippy
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `C:\Users\User\.cargo\bin\clippy-driver rustc - --crate-name ___ --print=fil
e-names --target x86_64-pc-windows-msvc --crate-type bin --crate-type proc-macro --crate-type rlib` (exit code:
3221225781)
```

Is this a known issue on Windows, or should currently be running on Windows?

**Comment by oli-obk** [comment]
@Manishearth can we get appveyor on the nursery? I'll fix it when we have appveyor again. No point in fixing it if it's just gonna regress again

**Comment by Manishearth** [comment]
@nrc can you set this up?

**Comment by nrc** [comment]
Hmm, well I'm not sure how AppVeyor works with regards to orgs, I have Clippy CI running at https://ci.appveyor.com/project/nrc/rust-clippy, but not at rust-lang-nursery (it is running the rust-lang-nursery branch, not my fork). AppVeyor will let me login as rust-lang, but not rust-lang-nursery, despite me being an owner. I'll try and get this working properly...

**Comment by nrc** [comment]
OK, AppVeyor should be back with the next PR: https://ci.appveyor.com/project/rust-lang-libs/rust-clippy

**Comment by phansch** [comment]
Going to close this as it's an older issue and Clippy on AppVeyor has been working for a few months now. Please open a new issue if there are still problems on windows.
