### ISSUE TITLE
Rust API Guidelines: Cargo.toml includes all common metadata

### ISSUE THREAD

**Issue by mcarton** [rust-lang/rust-clippy#1793]
As per [Cargo.toml includes all common metadata](https://github.com/brson/rust-api-guidelines#cargotoml-includes-all-common-metadata-c-metadata).

**Comment by ysimonson** [comment]
The section moved to here: https://rust-lang-nursery.github.io/api-guidelines/documentation.html#cargotoml-includes-all-common-metadata-c-metadata

**Comment by ysimonson** [comment]
It seems like [cargo_metadata](https://docs.rs/cargo_metadata/0.5.4/cargo_metadata/) does not expose this. Would it be best then to just parse `Cargo.toml` directly?

**Comment by oli-obk** [comment]
Maybe. Ask on the cargo repository whether it is expected that the cargo metadata subcommand exposes this info. The cargo_metadata crate can only give information it gets from the subcommand

**Comment by ysimonson** [comment]
I'm working on updating cargo now to include the necessary fields.

**Comment by oli-obk** [comment]
And it's already merged! Awesome. With the next nighlty containing the new cargo we should be able to add these fields to the cargo_metadata crate, too.

**Comment by ysimonson** [comment]
Opened a PR to add the fields to `cargo_metadata`

**Comment by ysimonson** [comment]
^ fix for this issue

**Comment by phansch** [comment]
This was done in #3419
