### ISSUE TITLE
Make elision better

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust-clippy#18]
I wonder if we can catch cases like [these](http://www.reddit.com/r/rust/comments/2n5mua/help_with_rust_lifetime_and_borrowing_rules/) where elision breaks things.

Basically, when the returned value has no relation to the inputs, lint that elision might not be wanted.

Exact heuristics would be tough to figure out, but I think it's doable (I've got a rough idea)

Ideally this should go into the compiler, but we can start it as a lint.

**Comment by felix91gr** [comment]
Since lifetime elision's gone a long way from 2014 to today, is this still an issue?

**Comment by camsteffen** [comment]
Closing in favor of #305
