### ISSUE TITLE
linkedlist false positive

### ISSUE THREAD

**Issue by clarfon** [rust-lang/rust-clippy#1800]
For [`len-trait`](https://docs.rs/len-trait) I use `LinkedList` solely to implement traits for it. This shouldn't trigger if you're implementing traits for `LinkedList` and nothing else.

**Comment by clarcharr** [comment]
Adding onto this, this also flags the inherent impls on `LinkedList` in liballoc, which is probably a bug.

**Comment by Areredify** [comment]
This was presumably fixed in #605 and there are (now?) tests for this issue. Lint also doesn't fire in liballoc as of now. I think this issue can now be closed @flip1995

**Comment by flip1995** [comment]
Yes, thanks! [Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=a4d8458ac1489d099dfe61a864a5f5f6)
