### ISSUE TITLE
Lint floating point literals with excessive precision

### ISSUE THREAD

**Issue by clarfon** [rust-lang/rust-clippy#1806]
Example:

```
const TAU: f64 = 6.283185307179586476925286766559005768394338798750211641949;
```

We should show the user exactly where the representation would be cut off, i.e. if this gets cut off at:

```
const TAU: f64 = 6.283185307179586476925286766559005768394338798750211641949;
                                  | only before the bar is used
```

Then we should suggest changing this to:

```
const TAU: f64 = 6.283185307179586;
```

Additionally, it'd be nice to indicate on `f32` literals with excessive precision that they could be made into `f64` literals, and point out where they'd get cut off there.

**Comment by gbip** [comment]
I will try to implement this lint !

**Comment by llogiq** [comment]
Just one thing: In const arithmetic, the compiler *should* calculate with highest precision (though the results will be rounded to the target type anyway), so rounding may well make a difference, even if it's just on ULP.

So if it's just a literal, I don't see a problem, but if we have some constant calculation, we better be careful.

**Comment by oli-obk** [comment]
The const evaluator simulates the target. You get the same result that the target has (minus some rounding issues). Constant calculations with `f32` do not use `f64` or `BigNum` internally. They use `f32` internally.

**Comment by hellow554** [comment]
This has been implemented, correct?

```
warning: float has excessive precision
 --> src/main.rs:1:18
  |
1 | const TAU: f64 = 6.283185307179586476925286766559005768394338798750211641949;
  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider changing the type or truncating it to: `6.283_185_307_179_586`
  |
  = note: `#[warn(clippy::excessive_precision)]` on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#excessive_precision
```

@oli-obk or @lcarfon can you close this?

**Comment by phansch** [comment]
> This has been implemented, correct?

Yes, thanks for noticing!
