### ISSUE TITLE
installing clippy via rustup gives missing DLLs on Windows

### ISSUE THREAD

**Issue by olson-dan** [rust-lang/rust-clippy#1815]
Could be that I'm doing something wrong, but I've never once gotten clippy to work on Windows after several tries.

From a Windows command prompt I do this:

> rustup update nightly
> rustup run nightly cargo install clippy

These complete without error, at least some of the time.

Moving into a project I normally compile with stable, I run:
> rustup run nightly cargo clippy

And I see several dialog boxes along the lines of

"cargo-clippy.exe - System Error

The program can't start because rustc_driver-0612f2a9be8d3aa.dll is missing from your computer.  Try reinstalling the program to fix this problem."

Any idea what is going wrong here?

**Comment by oli-obk** [comment]
Unfortunately you need to set the PATH variable to the rustc's directory on windows.. we really need to document this

**Comment by olson-dan** [comment]
I'd expect this to be taken care of by `rustup run`, perhaps that's a valid feature request for that program.

**Comment by oli-obk** [comment]
I think it een used to do that... but it got removed

**Comment by olson-dan** [comment]
Having run into a similar issue on rustfmt-nightly (https://github.com/rust-lang-nursery/rustfmt/issues/2343) I believe it's a fundamental problem with the ecosystem and a better solution than simply documenting it needs to be investigated.  However this solution is likely not something that either project can do on their own.

**Comment by olson-dan** [comment]
I'm closing this, as I believe it's now irrelevant due to clippy being a rustup component.
