### ISSUE TITLE
`needless_range_loop` could suggest using `clone_from_slice` in some cases

### ISSUE THREAD

**Issue by mcarton** [rust-lang/rust-clippy#1831]
See [How do I fix Clippy's `needless_range_loop` for loops that copy between slices with an offset?](https://stackoverflow.com/questions/44564772/how-do-i-fix-clippys-needless-range-loop-for-loops-that-copy-between-slices-wit).

**Comment by marcusklaas** [comment]
I'm currently looking into this. If nothing is reported after this weekend, I've probably failed and moved on.

**Comment by rail-rain** [comment]
I'm certain the PR #2021 fixed this issue; this can be closed now.
