### ISSUE TITLE
Lint request: unnecessary pass-by-reference

### ISSUE THREAD

**Issue by Vurich** [rust-lang/rust-clippy#1854]
It's pretty easy as a newbie to use `to_vec` on, for example, a boxed slice, when `into_vec` would be possible. These functions have very similar names and it's not immediately clear which one is correct (especially since the type mismatch compiler hints recommend both). It would be great if there was a lint to recommend `into_*` conversions when a `to_*` conversion is used on a type that is not used afterwards. This is based on [an issue found in the Parity codebase](https://github.com/paritytech/parity/pull/5944), where `to_vec` was being used on boxed slices and causing unnecessary cloning.

**Comment by camsteffen** [comment]
Closing in favor of #7908
