### ISSUE TITLE
missing_docs_in_private_items does not honor allow statements

### ISSUE THREAD

**Issue by darnir** [rust-lang/rust-clippy#1895]
I tried to enable the `missing_docs_in_private_items` lint. I have a coupe of modules that are not documented since they don't require it. The existing rustc lint for `missing_docs` also flags it, but I set a `#[allow(missing_docs)]` to silence the lint on just that module.

Turns out `clippy` does not heed this specific exception and still warns me about the missing docs. Would it be possible to check if the user has tried to silence the warning on that part of the code?

**Comment by oli-obk** [comment]
Implementable by using `cx.current_level(MISSING_DOCS) == Level::Allow`.

Prerequisite is to make `rustc_lint::builtin::MISSING_DOCS` public in rustc.

**Comment by mcarton** [comment]
IIRC, this lint is copied from rustc and merely removes the check about `pub`licity. Does rustc suffers the same problem with public non-documented modules with `missing_docs`?

**Comment by darnir** [comment]
@mcarton As I mentioned in the original report, I have a couple of public modules which are non-documented. `rustc` does not complain about them once I add the `#allow[missing_docs]` flag to the module, but `clippy` still does.

**Comment by oli-obk** [comment]
clippy will stop complaining if you add `#[allow(missing_docs_in_private_items)]`

**Comment by andrewbanchich** [comment]
Here's [a playground reproduction](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=15524a15f1dae7cb1d7af97343f0acc7) of this issue.

To paraphrase: `missing_docs` only affects public items, while `clippy::missing_docs_in_private_items` affects both private and public items. It should just stick to private items as the name suggests.
