### ISSUE TITLE
mem::forget on !Drop

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust-clippy#1897]
We should warn if you call `mem::forget` on:

 - a generic type known to be `Copy`
 - a non generic type known to not be `Drop`

since it's a no op, and likely means you `mem::forgot` the wrong thing.

(I hit this issue today)

**Comment by oli-obk** [comment]
https://github.com/rust-lang-nursery/rust-clippy/wiki#drop_copy ;)

There's a use case for types that are not `Drop`: if the type is `!Copy`, then you just got rid of it. But we might prefer to suggest `let _ = foo;` instead, not sure?

**Comment by Manishearth** [comment]
Yeah, that makes sense
