### ISSUE TITLE
Rename `logic_bug`

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust-clippy#1916]
http://rust-lang-nursery.github.io/rust-clippy/master/#logic_bug

Probably should be called "logical_op_bug" or something.

"logic bug" is a more general term that has to do with a bug in the higher level logic of a program.

**Comment by oli-obk** [comment]
* `broken_bool_expr`
* `inconsistent_bool_expr`

**Comment by phansch** [comment]
The lint only seems to be about checking non-simplified boolean expressions, right? How about `non_simplified_bool_expr` or `non_minimized_bool_expr`?

**Comment by dwijnand** [comment]
There's already another lint called [nonminimal_bool](http://rust-lang-nursery.github.io/rust-clippy/master/#nonminimal_bool), which is categorised as "complexity", while this one is categorised as "correctness".

If a name can be found I'd be happy to resolve this and move 1.0 that little bit closer.

**Comment by guerinoni** [comment]
What is the status of this? Can I rename to `non_minimized_bool_expr`?

**Comment by xFrednet** [comment]
I think there is no real status. If we find a better name we can just rename the lint. (We have a command for that in `clippy dev`)

The suggested lint name sounds like a double negotiation with `non_minimalized..` what do you think about `overly_complex_bool_expr`. Even if that's not perfect jet. It might be good to ask the on our zulip, there are some magicians  when to comes to finding lint names :)
