### ISSUE TITLE
Lint potential uses of `non_exhaustive`

### ISSUE THREAD

**Issue by clarfon** [rust-lang/rust-clippy#2017]
Once rust-lang/rust#44109 merges, instances like this:

```
struct Test {
    pub val: u32,
    _priv: (),
}
```

Can be better worded as:

```
#[non_exhaustive]
struct Test {
    pub val: u32,
}
```

Additionally, having a unit variant at the end of an enum which is `doc(hidden)` should be marked as well.

**Comment by clarcharr** [comment]
This has been implemented upstream, so, I updated the title for the issue

**Comment by oli-obk** [comment]
Do you have a link? When will it become stable?

**Comment by Luro02** [comment]
This feature became stable with version 1.40 https://blog.rust-lang.org/2019/12/19/Rust-1.40.0.html
[RFC-2008](https://github.com/rust-lang/rfcs/blob/master/text/2008-non-exhaustive.md)
