### ISSUE TITLE
Suggest eprintln!(…) instead of writeln!(io::stderr(), …)

### ISSUE THREAD

**Issue by killercup** [rust-lang/rust-clippy#2083]
The error versions of `print!` and `println!` have been stable [since Rust 1.19](https://github.com/rust-lang/rust/blob/7a9cdc4c2a98c3a889604762dccd463757079798/RELEASES.md#libraries-1). We should suggest using them!

Basically, this:

```rust
writeln!(&mut io::stderr(), "foo: {:?}", bar).unwrap();
```

can be replaced by

```rust
eprintln!("foo: {:?}", bar);
```

We should take care to only suggest this for the default `stderr` handle, and not, e.g., for one the programmer called `.lock()` on.

(Inspired by <https://github.com/rust-lang/rust/pull/44822>)

**Comment by ykrivopalov** [comment]
Maybe generalize it on both stdout/stderr:
io::stdout().write_fmt(format_args!(...)).unwrap(); => println!(...);
io::stderr().write_fmt(format_args!(...)).unwrap(); => eprintln!(...);

**Comment by oli-obk** [comment]
Reopening for adding a structured suggestion to the lint in the future
