### ISSUE TITLE
A script to update rustc only if clippy would compile

### ISSUE THREAD

**Issue by vorner** [rust-lang/rust-clippy#2108]
Hello

As I discussed with @llogiq during the RustFest, I'm sharing a script that conditionally updates the rust compiler.

It tries to install it first into a separate directory and tries compiling clippy against it. If it succeeds, it then does the same on the „real“ installation. This avoids the occasional breakage when rustc's internals changed and clippy doesn't compile. It may be of some help to other users.

```sh
#!/bin/sh

set -ex

renice -n 10 -p $$

export CARGO_INCREMENTAL=0
export RUSTC_FLAGS='-C target-cpu=native'

try_out() {
	export RUSTUP_HOME=$HOME/.rustup-attempt
	test -d $RUSTUP_HOME || (rustup toolchain add nightly && rustup default nightly)
	rustup update
	cargo install --force clippy
	unset RUSTUP_HOME
	export RUSTUP_HOME
}

[ "$1" = '-f' ] || try_out

rustup update
cargo install --force clippy

```

**Comment by llogiq** [comment]
Great! This might be really helpful to a lot of folks! Would you set up a PR with the script and a small paragraph in the README.md?

Also writing the usage if `$1 == -h` would be an easy usability win.

**Comment by Xanewok** [comment]
@vorner I don't see `RUSTC_FLAGS` used here directly, doesn't rustc use `RUSTFLAGS` instead?

**Comment by phansch** [comment]
Closing this as Clippy is now available via Rustup where it should always work.
