### ISSUE TITLE
Lint negative constants as positive types

### ISSUE THREAD

**Issue by clarfon** [rust-lang/rust-clippy#2170]
For example, `-1 as usize` could be better worded as `!0` or `usize::max_value()`.

If someone casts `-5 as usize` it's probably more clear as `usize::max_value() - 4`.

**Comment by oli-obk** [comment]
Do you have a real use case? I can't reproduce

```
error[E0600]: cannot apply unary operator `-` to type `usize`
 --> src/main.rs:3:22
  |
3 |     println!("{:?}", -5 as usize);
  |                      ^^
```

**Comment by HMPerson1** [comment]
`-5_isize as usize` works, but is pretty convoluted.

**Comment by felix91gr** [comment]
I'm taking a peek over the older issues labeled as "good-first-issue"... this one seems like it'd best be closed? Will it ever be needed, if the only way to invoke it is with `-5_isize as usize`?

**Comment by Manishearth** [comment]
Yeah, probably.
