### ISSUE TITLE
Multiline URLs

### ISSUE THREAD

**Issue by stanislav-tkach** [rust-lang/rust-clippy#2190]
```rust
//! [eee][1]
//! [1]: <https://docs.rs/exonum/0.2.0/exonum/blockchain/config/
//!struct.StoredConfiguration.html#method.hash>

fn main() {
}
```
[This code](https://play.rust-lang.org/?gist=7b7c8e56dacc5251d32dfec049486552&version=stable) generates "you should put bare URLs between `<`/`>` or make a proper Markdown link" warning, but rust-doc produces valid documentation.

(URL is split into several lines because of "line exceeded maximum length" rust-fmt issue.)

**Comment by gnzlbg** [comment]
This code does so as well:

```rust
//! * [Overal tracking issue for SIMD support]
//!   (https://github.com/rust-lang/rust/issues/27731)
```

**Comment by detrumi** [comment]
I'll look into this, though I'm not sure how easy it is to parse this correctly.

**Comment by oli-obk** [comment]
Maybe we need to start using a real markdown parser and check the AST it produces

**Comment by gnzlbg** [comment]
> Maybe we need to start using a real markdown parser and check the AST it produces

Ideally the same markdown parses as rustdoc.

**Comment by mcarton** [comment]
> > Maybe we need to start using a real markdown parser and check the AST it produces
>
> Ideally the same markdown parses as rustdoc.

[We already do.](https://github.com/rust-lang-nursery/rust-clippy/blob/1ecce2d803dbae76b2956012c3213ce7448cceae/clippy_lints/src/doc.rs#L2)

**Comment by Alexendoo** [comment]
These no longer seem to be interpreted as valid links by rustdoc
