### ISSUE TITLE
Do not suggest to use the closed interval syntax

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust-clippy#2217]
I suggest to remove or disable this:
https://rust-lang-nursery.github.io/rust-clippy/master/index.html#range_plus_one

Because in some cases the ..= closed intervals are slower (less efficient) than regular intervals.

**Comment by oli-obk** [comment]
Do you have any sources about the slowdown?

**Comment by leonardo-m** [comment]
An example here:
https://github.com/rust-lang/rust/issues/45222

**Comment by dalcde** [comment]
This issue still persists. It would be helpful to at least note this in the "Known problems" section.
