### ISSUE TITLE
lint `Iterator::fold`s that can be one of the special methods

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust-clippy#2237]
I just found `.fold(false, |acc, x| acc || x.starts_with("--target"));` in rustc. That should obviously be `.any(|x| x.starts_with("--target"))`

**Comment by clarcharr** [comment]
Also `.fold(1, |acc, x| acc * x)` and `.fold(0, |acc, x| acc + x)` should be replaced with `.sum()` and `.product()` respectively.

**Comment by clarcharr** [comment]
Bonus points: `.rfold(1, |acc, x| acc * x)` and `.rfold(0, |acc, x| acc * x)` could be `.rev().product()` and `.rev().sum()`.

**Comment by theotherphil** [comment]
I'd like to give this a go. Any pointers to get started?

**Comment by oli-obk** [comment]
@theotherphil 

There are already many iterator method lints in

https://github.com/rust-lang-nursery/rust-clippy/blob/master/clippy_lints/src/methods.rs#L718

You should be able to add a new branch for `fold`. You'll need to extract some info from the closure (if there is one). Have a look at

https://github.com/rust-lang-nursery/rust-clippy/blob/f9682ca563ad9ec6bc2da520ad92970d30d5c1e0/clippy_lints/src/map_clone.rs#L34

which does this for the `|x| *x` closure

**Comment by theotherphil** [comment]
Great, thanks!

**Comment by ivfranco** [comment]
.any and .all are not always safe replacements of .fold: those two are short-circuiting, while .fold evaluates every element in the iterator. If the iterator incurs side effects the two methods will have different behaviour.
Imho clippy should at least warn the user for the possible difference instead of suggest .all and .any indifferently.

**Comment by camsteffen** [comment]
Fixed by #2350. We also have #2401 for more `fold` cases.
