### ISSUE TITLE
lint `#[inline]` on generic functions

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust-clippy#2253]
To best of my knowledge, adding `#[inline]` to generic functions does not actually anything, because the generic function is translated at the use site anyway.

**Comment by Manishearth** [comment]
It still encourages inlining; if a specific monomorphization is used a lot it may end up not being inlined, whereas `#[inline]` has a slight inlining hint in addition to the "include function AST in metadata" bit.

**Comment by Lokathor** [comment]
Related: The description for `missing_inline_in_public_items` should be updated to note that a generic function does not need LTO or `#[inline]` to be inlinable.

**Comment by camsteffen** [comment]
This seems misguided. Generic functions are not inlined or translated at *every* use site.

**Comment by Manishearth** [comment]
> This seems misguided. Generic functions are not inlined or translated at _every_ use site.

I wouldn't say this is _misguided_, neither are `#[inline]` functions. I think there is legitimately no benefit to marking generic functions as  `#[inline]`; both include AST in the metadata and have a mild inlining hint. But I also don't think it's worth linting about it here.
