### ISSUE TITLE
Set doc-valid-idents in clippy.toml without removing defaults

### ISSUE THREAD

**Issue by clarfonthey** [rust-lang/rust-clippy#2292]
Right now, the given value replaces the existing list, rather than adding onto it.

**Comment by phansch** [comment]
This might be easy to do considering the closed PR and the comments there: https://github.com/rust-lang/rust-clippy/pull/2321

**Comment by nbigaouette** [comment]
According to https://rust-lang.github.io/rust-clippy/master/index.html#/doc_markdown, one can use `".."` as a `doc-valid-idents` value to "expand" to the default value.

This ticket can probably be closed.

**Comment by xFrednet** [comment]
Good call, thank you @nbigaouette
