### ISSUE TITLE
Access violation exception with nightly-msvc (x86 only)

### ISSUE THREAD

**Issue by pravic** [rust-lang/rust-clippy#2310]
Funny thing: it works in **debug** build, but crashes in the release one.

It looks like the failing code is in [EarlyLintPass::check_block](https://github.com/rust-lang-nursery/rust-clippy/blob/1ecce2d803dbae76b2956012c3213ce7448cceae/clippy_lints/src/returns.rs#L147) (according to windows debugger).

https://github.com/rust-lang-nursery/rust-clippy/blob/1ecce2d803dbae76b2956012c3213ce7448cceae/clippy_lints/src/returns.rs#L106-L128

Project which causes this crash: https://github.com/sciter-sdk/rust-sciter (run `cargo +nightly clippy`).

Env:
> rustc 1.25.0-nightly (29c8276ce 2018-02-07), host: i686-pc-windows-msvc
> clippy v0.0.186

**Comment by pravic** [comment]
Still the same error with 0.0.184.

**Comment by pravic** [comment]
It does not crash with x64 compiler, but does with the x86 one. How is it possible?

**Comment by pravic** [comment]
@oli-obk could you add a bug label here?

**Comment by oli-obk** [comment]
Thanks for looking into this more closely.

So a debug clippy works but a release clippy fails? Or is it whether the crate is built in release mode?

**Comment by pravic** [comment]
Yes, it was about the clippy compiled in debug mode.

Only release and only x86 version crashes.

**Comment by mati865** [comment]
It looks like https://github.com/rust-lang/rust-clippy/issues/3345 which should be fixed with current nightly.
@pravic could you retry?
