### ISSUE TITLE
Rustc panic when invalid `mod super::foo` syntax is present.

### ISSUE THREAD

**Issue by Rantanen** [rust-lang/rust-clippy#2327]
https://play.rust-lang.org/?gist=3075e5a1ebf3b17ecc5c3e16d197289a&version=stable

Without clippy the code fails to compile as expected, with clippy it results in a panic.

**Comment by phansch** [comment]
This now results in a compilation failure for Clippy, too. Feel free to re-open should this still happen :heart_decoration:
