### ISSUE TITLE
Do not suggest replacing simple `if let Some(_) / None` with methods

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust-clippy#2353]
This lint I don't quite agree with, and I realize opinions will differ on this.

Lint link: https://rust-lang-nursery.github.io/rust-clippy/v0.0.177/index.html#if_let_redundant_pattern_matching

Existing code in removed (red) and the proposed change by clippy in added (green) lines:

```diff
         // clear edges without touching the free list
         for node in &mut self.g.nodes {
-            if let Some(_) = node.weight {
+            if node.weight.is_some() {
                 node.next = [EdgeIndex::end(), EdgeIndex::end()];
             }
         }
```

```diff
-        if let None = node_weight {
+        if node_weight.is_none() {
             return None;
         }
```

etc with similar examples.

I think that using `if let` is fundamental to Rust, is general, works with any enum and is just as easy to understand as the alternative. I prefer general over Option-specific methods.

**Comment by oli-obk** [comment]
Advantages of `Option` methods:

* can chain with other bool operations
    * thus trigger more clippy lints down the road
* fewer characters
* left to right reading order

Disadvantages of `Option` methods

* methods calls can be anything
* ~~method calls are not fundamental to Rust~~ (😆)
* more code for the optimizer to handle

I don't have a strong opinion either way. I just do what clippy says

We could make it a restriction lint, but then I'd also like to see the opposite lint.

----

Side note:

```diff
-        if let None = node_weight {
+        if node_weight.is_none() {
             return None;
         }
```

shouldn't that simply be `node_weight?;`

**Comment by mikerite** [comment]
Please suggest replacing `o.is_some()` with `o.iter().count() == 1` and `o.is_none()` with `o.iter().count() == 0`. 

I think that using collections is fundamental to Rust. This method is general, works with any collection and is just as easy to understand as the alternative. I prefer general over Option-specific methods.

**Comment by Manishearth** [comment]
No trolling, please.

**Comment by camsteffen** [comment]
Given that this hasn't received any "me too"s, I think people are generally satisfied with the current behavior. To me `is_some` easily carries its weight because Option is just so ubiquitous to Rust.
