### ISSUE TITLE
Suggest replacing `if option.is_none() { return None; }` with `option?;`

### ISSUE THREAD

**Issue by shssoichiro** [rust-lang/rust-clippy#2358]
See https://github.com/rust-lang-nursery/rust-clippy/issues/2353#issuecomment-357735632

**Comment by oli-obk** [comment]
There's probably more complex cases. Not sure what to do about those and what they even are. The base lint is a good first issue, everything else E-medium

**Comment by camsteffen** [comment]
This is now linted by `question_mark`.
