### ISSUE TITLE
Idea: FIXME lints

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust-clippy#2360]
*I am unsure of whether this is the right place for this issue.*

The idea was originally brought up at: https://github.com/rust-lang/rfcs/issues/2281#issuecomment-355986157

> I haven't seen it personally yet (I'm still in college after all), but I've heard plenty of stories about how kludges and temporary workarounds end up being permanent simply because no one got around with putting a more robust fix in place. We can't fix developer laziness, but perhaps something like this could help people not forget tasks they defer to later, in general.

   >> warning: FIXME not resolved for 2 years

One could perhaps write:

```rust
#[cfg_attr(feature = "cargo-clippy", FIXME("2018-01-15", "<description of what to fix>"))]
```

**Comment by eaglgenes101** [comment]
When I wrote of my original suggestion, I was thinking of it being rolled together with the RFC I suggested it on, based on time rather than availability or stability of features. But since it's been split off, I'll go along with it. 

That said, giving it a fresh look, the most obvious problem would be to get people on board the new format, or to make the tools smart enough to figure things out for the end user. This might need some more thought than I first imagined.

**Comment by shaleh** [comment]
If clippy learned Git, you could find when the FIXME was added and compare that to current time. Which means the developer does not need to use a new format.

**Comment by clarcharr** [comment]
Perhaps adding a fixme attribute to the compiler itself is a good idea?

**Comment by shaleh** [comment]
I used Git as an example. A similar solution would work with other revision systems.

Teaching clippy about revision control is not that hard.

**Comment by Manishearth** [comment]
I think this is out of scope for Clippy, at least the integration with VCSes

**Comment by shaleh** [comment]
I can understand that.

**Comment by theduke** [comment]
This might be somewhat controversial, but apart from a FIXME attribute, I'd actually love a lint that detects `FIXME` in comments. 
If you run on CI you can ensure that you never merge a branch with pending `FIXME`s.

Is this something that would be accepted?

**Comment by shaleh** [comment]
I am a fan of those @theduke. Emacs marks FIXME, TODO, and XXX in bold, bright colors for me.

**Comment by flip1995** [comment]
> Is this something that would be accepted?

Yes, this could be implemented as a restriction lint.

**Comment by phansch** [comment]
It's worth noting that only doc comments are accessible to Clippy.
(Unless we parse all source files ourselves, but that's not a good idea for various reasons)

**Comment by theduke** [comment]
@phansch that sadly means the idea is void, since most `FIXME` s would be in non-doc comments.

**Comment by martin-t** [comment]
Something similar could be achieved using rustfmt's [report_fixme](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#report_fixme). You should be able to set it to "Unnumbered", to force people to create issues for FIXMEs, then filter your project's issues by date.

The question is how to get more projects to discover and use it.

>It's worth noting that only doc comments are accessible to Clippy.
>(Unless we parse all source files ourselves, but that's not a good idea for various reasons)

@phansch Then how does rustfmt get access to comments? It seems to just use libsyntax,

**Comment by flip1995** [comment]
IIUC, `rustfmt` checks the text of files directly to find `FIXME`s/`TODO`s, without parsing the file. This is not something Clippy should do IMO. 

I think we can close this, since rustfmt implements this already?

**Comment by DeltaF1** [comment]
rustfmt has removed `FIXME` support https://github.com/rust-lang/rustfmt/issues/5102.

Now that [Span has access to the source text](https://doc.rust-lang.org/stable/proc_macro/struct.Span.html#method.source_text) "including spaces and comments", is this a viable thing to build into clippy?

**Comment by Manishearth** [comment]
The span thing has nothing to do with clippy capabilities. We can get the source text already.

But I'm not sure if we should be relexing everything to get the comments. It feels a bit weird in clippy, I'm not convinced this is the right place for it.

**Comment by DeltaF1** [comment]
Makes sense, thanks :) So if in a hypothetical future `syn` gave access to (non-doc) comments programmatically then that would be a viable path to doing this, but for now it's not clippy's job to re-parse the source files.

**Comment by Manishearth** [comment]
syn also has nothing to do with clippy's capabilities. we are not a proc macro, we do not use the user facing infra for operating on rust code, we use that of the compiler
