### ISSUE TITLE
A script to conditionally install (or reinstall) clippy

### ISSUE THREAD

**Issue by azriel91** [rust-lang/rust-clippy#2463]
Hiya, related to https://github.com/rust-lang-nursery/rust-clippy/issues/2108, I wrote a script to 

* Install clippy if it is not already installed
* If it is installed, check compatibility with current nightly. If it is compatible, do nothing.
* If it is not compatible install it with `--force`.

Script: https://gist.github.com/azriel91/6d7ab1d865d266d50dabfc8da78f6490

Do you think this repo is where that script should live?

Oh, I've only tested it on Ubuntu, so if we were to combine this with the `rust-update` script, it would need to be adapted for Windows and OSX (I don't have one, so can't test).

---

Part of me is waiting for clippy to be released as a Rustup component: :eyes:

* https://github.com/rust-lang-nursery/rust-clippy/issues/1358
* https://github.com/nrc/dev-tools-team/issues/4

**Comment by TheIronBorn** [comment]
There is already a similar script https://github.com/rust-lang-nursery/rust-clippy#updating-rustc. Perhaps there are improvements to be made?

**Comment by phansch** [comment]
Thanks for the report and the script. Since we now ship Clippy only via rustup and only if it works, I'm going ahead and close this issue.
