### ISSUE TITLE
Wrong needless_return suggestion with blocks

### ISSUE THREAD

**Issue by lnicola** [rust-lang/rust-clippy#2472]
Clippy suggests changing `return { e } + 10;` to `{ x } + 10` instead of `({ x }) + 10` or `({ x } + 10)`, and that doesn't compile.

I'm not sure what it should do, always parenthesise the inner span? `rustfmt` doesn't fix that, and it would be a bit ugly. Should it recurse into the expression to see if there are any blocks?

**Comment by oli-obk** [comment]
huh? this feels more like a rustc bug that it doesn't accept `{ x } + y` as a trailing return expression

**Comment by lnicola** [comment]
Apparently, the block is a statement, not an expression. I wasn't aware of the difference until running into this.

**Comment by birkenfeld** [comment]
It's good that this is a compile error, consider `-` instead of `+`:
```
fn x() -> i32 {
    { 1 } - 1
}

fn y() -> i32 {
    { 1 }
    -1
}
```
Does it return `0` or `-1`?

**Comment by steffahn** [comment]
So the right thing to suggest here would be to remove the `return` but add parentheses.

**Comment by GnomedDev** [comment]
Seems to be fixed, `({ e } + 10)` is the emitted suggestion nowadays which does compile.
