### ISSUE TITLE
Lint using |_| () instead of drop

### ISSUE THREAD

**Issue by clarfonthey** [rust-lang/rust-clippy#2523]
Basically, any occurrence of `|_| ()` as a closure could be more clearly worded as `drop`.

**Comment by birkenfeld** [comment]
I don't agree. To me, `drop` signals that the important point is to destroy the value while `|_| ()` says that the important point is to *ignore* it. Especially with a primitive type like an integer, it'd be a "huh?" moment.

**Comment by clarcharr** [comment]
@birkenfeld Do you have a good example of a case like that?

Something like `Some(5).map(|_| ())` makes more sense as `Some(5).map(drop)` to me.

**Comment by CryZe** [comment]
drop is definitely much more readable imo and other people seem to be confused by "the toilet closure" too: https://www.reddit.com/r/rust/comments/bdqxch/actixweb_what_map_err_is_really_doing/

**Comment by Manishearth** [comment]
I don't find drop to be readable in an error context. The toilet closure is confusing too, but at least it's become a norm.

**Comment by lzutao** [comment]
People in https://github.com/rust-lang/rust/issues/67672 prefer `map(drop)`.

**Comment by kpp** [comment]
> To me, drop signals that the important point is to destroy the value while |_| () says that the important point is to ignore it.

The same for me. How about alias for drop:

```
fn ignore<T>(_x: T) { }

fn main() {
    dbg!(Some(5).map(ignore));
}
```

**Comment by llogiq** [comment]
I may be weird, but I think dropping is empathically not the same as ignoring it. And in Rust, we don't tend to ignore things anyway.

**Comment by clarfon** [comment]
I'm very much not in favour of things doing exactly the same thing but having different names. Toilet closures are unnamed, although I still find drop easier to read. If we were to make an actual exported alias for drop I'd be against that.

**Comment by Manishearth** [comment]
Folks discussed this a bunch in Zulip, feeling rather opposed to the idea of this lint but open to a lint that replaced such closures with more specific named functions.

https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/.E2.9C.94.20Toilet.20Closures
