### ISSUE TITLE
Underscores only every 2^n digits in non-decimal numbers

### ISSUE THREAD

**Issue by l0b0** [rust-lang/rust-clippy#2538]
What it does: Warns if an integral or floating point **non-decimal** number is split somewhere other than between n^2 and (n^2)+1 (for constant n≥1). Hexadecimal, octal and binary numbers are used when dealing with 2^n fractions or multiples of bytes.

Examples:

- `0xabc_def`. Probably what was meant was `0xab_cdef`, `0xab_cd_ef` or there's a missing nibble in the second half.
- `0xa_b_c_d_e_f` is more verbose but no clearer than `0xabcdef`.

**Comment by Manishearth** [comment]
I see use cases for splitting this at other points (e.g. a bit mask with different groups of masks) but that seems minor in this case and there aren't other issues so this seems fine.

Though the description isn't quite accurate, it should be between powers of four.

**Comment by l0b0** [comment]
> Though the description isn't quite accurate, it should be between powers of four.

In most cases I'd agree, but I guess a fairly common pattern would be splitting hexadecimal between bytes, as in `0xab_cd_ef`.

**Comment by Manishearth** [comment]
Sorry, powers of eight. Not n^2

**Comment by l0b0** [comment]
Ah, we meant the same thing. I meant the most natural splits are nibbles (`0b1111_0000`) or bytes (`0b11111111_00000000`) for binary, and bytes (`0xff`) or words for hex.
