### ISSUE TITLE
regex_macro false positive

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust-clippy#2586]
When defining a custom `regex!` macro to use the lazy_static pattern more easily, the regex_macro picks it up.

This occurs with nom and any of it's `re_*_static!` macros, as they all expand to use an internal (hidden) `regex!` macro, which then expands to the `lazy_static!` macro.

**Comment by oli-obk** [comment]
uuuuh... Not sure how to solve this. We do detect the regex macro via its name... We might be able to not trigger the lint if there is a `#[macro_use] extern crate regex;` anywhere

**Comment by pickfire** [comment]
Oh, look like we implement our own `regex!` macro to use lazy_static too but it have this false positive. Maybe we could check for `#[macro_use]` or the newer `use regex::regex;`?

**Comment by CAD97** [comment]
Or even just deprecate the lint, honestly. The regex crate hasn't provided the old regex macro for a long time.
