### ISSUE TITLE
needless_borrow suggests bad code when reference-to-reference is required

### ISSUE THREAD

**Issue by scurest** [rust-lang/rust-clippy#2610]
````rust
struct S<'a>(&'a str);

impl<'a> std::fmt::Debug for S<'a> {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match *self {

            // This suggests changing `ref s` to `s`, which won't compile
            // (`field` takes a `&Debug`).
            S(ref s) => f.debug_tuple("S").field(s).finish()

            // I'm aware you can do this.
            //S(s) => f.debug_tuple("S").field(&s).finish()
        }

    }
}
````

Playground link: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=21db39fed7d5b0778b382e206fa45f1b

**Comment by Manishearth** [comment]
I think the idiomatic way of doing that is `field(&s)`, but this is still a bug

**Comment by phansch** [comment]
This doesn't seem to trigger anymore: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6e306800d5f8f6d63aa19fa55bffae9c

**Comment by taiki-e** [comment]
@phansch: I don't think this has been fixed yet. (Note that needless_borrow is not currently enabled by default)
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=21db39fed7d5b0778b382e206fa45f1b

**Comment by phansch** [comment]
Thanks for catching my mistake :sweat_smile:
