### ISSUE TITLE
clippy fails on missing eh_personality although panic-strategy is defined in custom target

### ISSUE THREAD

**Issue by andre-richter** [rust-lang/rust-clippy#2621]
When working with `no_std` crates that have a custom target, it is possible to to define `"panic-strategy": "abort"` in the custom target .json file, and xargo will happily compile your crate without a definition of the `eh_personality` lang item.

However, clippy will fail:
```bash
xargo clippy 
[...]
error: language item required, but not found: `eh_personality`

error: aborting due to previous error
```

One workaround is:
```
RUSTFLAGS="-C panic=abort" xargo clippy
Compiling core v0.0.0 ...
```
but that causes recompilation of core.
Another one would be adding the item to your source, although it is not needed.

I'm not really sure which of all the involved tools is the culprit here, I'm happy to raise the bug elsewhere if needed.

**Comment by Areredify** [comment]
This is a tad late, but maybe it will help someone who finds this via search. In order for `xargo clippy` to work with a custom target, you either do `xargo clippy --target=your_target" or set a default target in `.cargo/config` and invoke `cargo clippy`. Either that or I can't reproduce this bug ¯\_(ツ)_/¯

**Comment by andre-richter** [comment]
That actually makes sense, hehe.

Closing this since solution is now posted.
