### ISSUE TITLE
Lint against Rc<String> (and Rc<Vec<T>>)

### ISSUE THREAD

**Issue by birkenfeld** [rust-lang/rust-clippy#2623]
Now that it's easy to construct `Rc<str>` and `Rc<[T]>` using `into()`, we should advise people to use them.

Especially `Rc<String>` is often advised to avoid cloning strings, but has no advantages (except if you want to use `get_mut`) and is a) larger, b) has one more pointer to chase, and c) doesn't implement `Borrow<str>`.

**Comment by rcoh** [comment]
I assume "advise people to use them" is a typo and you meant the opposite? I might try this.

**Comment by compressed** [comment]
Agreed! The lint should also apply for `Arc` since the [change](https://github.com/rust-lang/rfcs/blob/master/text/1845-shared-from-slice.md) does as well.

**Comment by jrlusby** [comment]
I'd like to pick this issue up if nobody else is working on it.

**Comment by rudyardrichter** [comment]
Could I take on this issue? Would love to start contributing somewhere :)

**Comment by oli-obk** [comment]
All yours. Please put it in the nursery group for now

**Comment by rudyardrichter** [comment]
@oli-obk I took a crack at this last weekend and have a better understanding now of what should be required, but I definitely have some questions for implementation—anyone in particular I could bug about it?

**Comment by oli-obk** [comment]
@rudyardrichter you can bug me ;) or anyone in the #clippy irc channel

Or just ask here. Or open a half finished PR.

Lots of possibilities. Choose the one that's most convenient for you

**Comment by pickfire** [comment]
is this affected by https://github.com/rust-lang/rust/pull/61953/?
