### ISSUE TITLE
README.md should specify the nightly version to use

### ISSUE THREAD

**Issue by spease** [rust-lang/rust-clippy#2705]
Seems like every time I try to build clippy, it's broken with the current nightly. Probably because the instructions fetch from crates.io, and crates.io doesn't seem to be updated as frequently as it needs to be to keep pace with nightly.

Assuming the current release cadence remains constant, I'd start specifying the version of nightly that clippy needs, or remove the instructions altogether and recommend that people build from source as the only supported method. Rather than outlining a method that does not seem to work most of the time because the official version is usually behind nightly.

**Comment by jonalencar** [comment]
Yeah `cargo +nightly install clippy` seems to fail quite often. Hopefully they fix this issue.

**Comment by JoshLambda** [comment]
> and recommend that people build from source

Not sure that would help since building from source is currently broken too (see #2704).

**Comment by mozillazg** [comment]
@josephDunne "build from source" is mean build the `clippy` with the latest source code from github instead of install `clippy` with `cargo` that fetch `clippy` from crates.io.

**Comment by oli-obk** [comment]
You can still use `cargo install`, but you'd need to pass the address of this repo via the appropriate flag

**Comment by phansch** [comment]
Closing this as Clippy can now be installed via Rustup. If you still want to use Clippy on nightly, this website can be helpful: https://mexus.github.io/rustup-components-history/
