### ISSUE TITLE
ICEs should point to the clippy repo, not the rustc repo

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust-clippy#2734]
Frequently ICEs in clippy are reported in the rustc repo. It would probably be better to collect them only here. This might need changes to rustc_driver to allow custom drivers to inject a repo name to report ICEs to.

**Comment by phansch** [comment]
Maybe we could use [human-panic](https://github.com/yoshuawuyts/human-panic)?

**Comment by oli-obk** [comment]
well... rustc could use it and then all drivers would benefit from it. I think all drivers should use a common infrastructure

**Comment by kennytm** [comment]
Well *this* particular issue should be reported to the rustc repo instead 😛

**Comment by phansch** [comment]
It's now possible to provide our own ICE hook. We currently use the rustc one via

https://github.com/rust-lang/rust-clippy/blob/a5e568bcc87fa8ce4c04a95b2441167e28e9458f/src/driver.rs#L250

To do that we only have to provide our own hook that calls rustc's `report_ice` function, similar to the one in rustc:

https://github.com/rust-lang/rust/blob/66bf391c3aabfc77f5f7139fc9e6944f995d574e/src/librustc_driver/lib.rs#L1172-L1178

Then we'lll also have to initialize our hook, like rustc:

https://github.com/rust-lang/rust/blob/66bf391c3aabfc77f5f7139fc9e6944f995d574e/src/librustc_driver/lib.rs#L1253-L1255

All this would happen in `src/driver.js`.
