### ISSUE TITLE
Clippy doesn't honour #![allow(shadow_reuse)]

### ISSUE THREAD

**Issue by darnir** [rust-lang/rust-clippy#2745]
I have the `shadow_reuse` lint explicitly enabled in my crates.

However, in a couple of places, I would like to be able to shadow an existing variable. In such cases, I have an explicit `#![allow(shadow_reuse)]` right before the statement. However, clippy still emits an error for this case.

Short example: https://play.rust-lang.org/?gist=62855503c6e8760c3a419792ee56440e&version=nightly&mode=debug

**Comment by oli-obk** [comment]
Side note: `#![allow(shadow_reuse)]` actually disables the lint. `#[allow(shadow_reuse)]` doesn't, because the lint works on functions.

Needs a fine grained lint check. Not sure if we can do that in a reasonable way atm.

**Comment by brightly-salty** [comment]
This seems to me to have been fixed? When I run the playground code, changing `shadow_reuse` to `clippy::shadow_reuse`, it compiles without errors.
