### ISSUE TITLE
Massive clippy breakage incoming

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust-clippy#2785]
When https://github.com/rust-lang/rust/issues/50050#issuecomment-390685906 is implemented, we lose all ability to detect macro expansions.

No ETA on getting them back, but there's a plan outlined in the link above.

**Comment by phansch** [comment]
oh my. Won't that also break some rustc lints?

Once that's on nightly, we should probably put the last working nightly/clippy version combination at the top of the readme, as https://github.com/rust-lang-nursery/rust-clippy/issues/2705 suggests.

**Comment by phansch** [comment]
@oli-obk I think this will be fully fixed by using `in_external_macro` from https://github.com/rust-lang/rust/pull/52467, right?

**Comment by oli-obk** [comment]
Probably. I think we'll see some changes in tests

**Comment by phansch** [comment]
IIRC this breakage didn't turn out too bad, so I'm going to close this issue.
