### ISSUE TITLE
Lint request: warn when variable declared in match pattern shadows other variable

### ISSUE THREAD

**Issue by PieterPenninckx** [rust-lang/rust-clippy#2890]
"The Book" (TRPL) [warns](https://doc.rust-lang.org/book/second-edition/ch18-03-pattern-syntax.html#matching-named-variables) about variables declared in match patterns shadowing other variables. I have once been hit by this myself, so this seems to be a good idea for a lint.

**Comment by ojeda** [comment]
This was closed because the existing `shadow_*` lints catch it, but those lints catch also other many cases at the same time. It would be nice to have a lint only for `match`.
