### ISSUE TITLE
Switch cargo-clippy over to use rustup's clippy-driver

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust-clippy#2901]
Currently cargo-clippy calls the associated `cargo install`d clippy-driver. Now that we ship clippy-preview, we can instead make it call the one from rustup!

Currently I have to hack this together to run clippy with clippy-preview: https://twitter.com/ManishEarth/status/1015818090548944896

```
$ CARGO_MANIFEST_DIR=. ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/clippy-driver src/main.rs --emit=dep-info,metadata 
```

We can use `${RUSTUP_HOME}/toolchains/${RUSTUP_TOOLCHAIN}` to find the driver. Alternatively, we perhaps can do something like rustfmt so that it's in the path (not sure how this works)

Perhaps we should be shipping cargo-clippy via rustup too? This is what rustfmt does, and it's one fewer step for installing clippy.

cc @kennytm @oli-obk

**Comment by oli-obk** [comment]
Yea, seems like the most sensible thing to just ship cargo-clippy

**Comment by kennytm** [comment]
I agreed with @oli-obk that we should just ship `cargo-clippy`, like `cargo-fmt`. 

@Manishearth  The rustfmt support in rustup was added in rust-lang-nursery/rustup.rs#1294. You'll need to add `cargo-clippy` (and maybe `clippy-driver` too) to the `DUP_TOOLS` array in `src/rustup-cli/self_update.rs` and `TOOLS` array in ` rc/rustup-win-installer/src/lib.rs`, and have `rustup` release a new version.

**Comment by Manishearth** [comment]
FWIW it should be okay if preexisting cargo-clippy is overwritten since clippy is going to break anyway

**Comment by camsteffen** [comment]
Looks like this is completed by https://github.com/rust-lang/rustup/pull/1461?
