### ISSUE TITLE
Clippy downloads dependencies for unnecessary targets

### ISSUE THREAD

**Issue by Emerentius** [rust-lang/rust-clippy#2915]
Winapi has some target-specific dependencies. From its Cargo.toml:
```
[target.i686-pc-windows-gnu.dependencies]
winapi-i686-pc-windows-gnu = { version = "0.4", path = "i686" }
[target.x86_64-pc-windows-gnu.dependencies]
winapi-x86_64-pc-windows-gnu = { version = "0.4", path = "x86_64" }
```

These are never needed under linux when not cross-compiling. Yet, when you run `cargo clippy` in a project that depends on winapi, they are nevertheless downloaded.

Minimal example:
```
cargo new foo
cd foo
cargo add winapi
cargo clippy
```

Now check `ls -l ~/.cargo/registry/src/github-*/ | grep winapi`. There'll now be 3 folders, 1 is winapi and 2 are the target specific dependencies mentioned at the top. They are pretty large:

```
du -sh ~/.cargo/registry/src/github.com-*/winapi*           
6,3M	/home/<me>/.cargo/registry/src/github.com-1ecc6299db9ec823/winapi-0.3.5
52M	/home/<me>/.cargo/registry/src/github.com-1ecc6299db9ec823/winapi-i686-pc-windows-gnu-0.4.0
54M	/home/<me>/.cargo/registry/src/github.com-1ecc6299db9ec823/winapi-x86_64-pc-windows-gnu-0.4.0
```

Edit: `cargo build` or `cargo check` do also download `winapi` but not the target specific subcrates.

**Comment by retep998** [comment]
I believe `cargo fetch` is another command that has the issue of downloading target specific subcrates. I was very careful to make the target specific import library crates target specific because they are so large, so it would be nice to save users the bandwidth.

**Comment by camsteffen** [comment]
Couldn't reproduce this today.

**Comment by Emerentius** [comment]
Yeah, I don't see it either anymore with `clippy 0.1.56 (59eed8a 2021-11-01)`
