### ISSUE TITLE
Performance: Suggest String::new() over "".to_string()

### ISSUE THREAD

**Issue by phansch** [rust-lang/rust-clippy#2972]
From https://github.com/rust-lang/rust/pull/52805#discussion_r205945647. `String::new()` is faster than `""::to_string()`

[Benchmark](https://github.com/phansch/bench_string_new): 
```rust
#[bench]
fn bench_string_new(b: &mut Bencher) {
    b.iter(|| String::new());
}

#[bench]
fn bench_to_string(b: &mut Bencher) {
    b.iter(|| "".to_string());
}
```
```
running 2 tests
test tests::bench_string_new ... bench:           0 ns/iter (+/- 0)
test tests::bench_to_string  ... bench:           8 ns/iter (+/- 0)
```

**Comment by matthiaskrgr** [comment]
The lint should probably also catch ````String::from("")````

````
test tests::bench_string_from ... bench:          11 ns/iter (+/- 0)
test tests::bench_string_new  ... bench:           0 ns/iter (+/- 0)
test tests::bench_to_string   ... bench:          11 ns/iter (+/- 2)
````

**Comment by H2CO3** [comment]
as well as `"".into::<String>()`

**Comment by matthiaskrgr** [comment]
Hm, interestingly, when looking in godbolt ````print!("{}", String::new());```` seems to generate more instructions than ````print!("{}", "");````

**Comment by flip1995** [comment]
Probably because `String::new()` is of type `String` and `""` is of type `&str`

**Comment by mikerite** [comment]
I vote for `slow_empty_string_creation` as the name.

The suggestions of `useless_format` should to be changed as well.

```
warning: useless use of `format!`
 --> src/main.rs:2:13
  |
2 |     let _ = format!("");
  |             ^^^^^^^^^^^ help: consider using .to_string(): `"".to_string()`
  |
  = note: #[warn(useless_format)] on by default
```
Should this lint be written as `PreExpansionPass`?

**Comment by nagisa** [comment]
We should just fix this in liballoc instead.

**Comment by phansch** [comment]
That seems like a preferable solution. If the allocation is fixed, this could still be a style lint.

**Comment by weiwei** [comment]
For people who aren't aware: It appears that the issue has been fixed. This is my test result on an Intel Mac:

```
test tests::bench_string_from  ... bench:           0 ns/iter (+/- 0)
test tests::bench_string_new   ... bench:           0 ns/iter (+/- 0)
test tests::bench_to_string    ... bench:           0 ns/iter (+/- 0)
```

**Comment by xFrednet** [comment]
Thank you for the benchmarks! Even if this no longer affects performance, I think having a lint that suggest `String::new()` over `"".to_string()` would be good for code consistency. It should probably be a lint in the `pedantic` category to be Allow-by-default.

@rustbot label -L-perf +L-pedantic +good-first-issue

**Comment by H2CO3** [comment]
`String::new()` over `"".to_string()` or `String::from("")` should even be a warn-by-default `style` lint. It's not pedantic by any measure – the alternatives are unnecessarily complicated.

**Comment by xFrednet** [comment]
I was considering if this should be a `style` lint, but I've also seen repos that preferred using `"".to_string()`. Therefore, I'm unsure if we really want this to be warn-by-default. The best way to determine this is probably to create an implementation and then check how often it triggers in normal projects with our lintcheck tool

**Comment by H2CO3** [comment]
> I've also seen repos that preferred using `"".to_string()`

I'd be curious what their rationale is. It's less clear, up until recently it was slower, and it's one character longer (even if that's probably an insignificant difference).

I regularly have my code "broken" by new Clippy lints being introduced that I have to admit are correct, and then I have to fix them. The purpose of linters is to guide people to write better code; I think adjusting the linter to the questionable but maybe somewhat common choices of style is backwards. If one disagrees with the lint, it can still be turned off, so there's no real risk in warning by default.
