### ISSUE TITLE
Make `clippy.toml` an unstable feature

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust-clippy#3013]
We could simply place it behind some sort of `CLIPPY_UNSTABLE_CONFIG_TOML=1` flag that users can use but would need to be aware that we'd deprecate the support for it at some point and move to another file at which point the use of the env var would become an error (and the clippy.toml would get ignored)

discussion https://github.com/rust-lang/rfcs/pull/2476#issuecomment-404271010

**Comment by phansch** [comment]
Update: It was decided at the time that `clippy.toml` should be unstable in the RFC: https://github.com/rust-lang/rfcs/pull/2476#issuecomment-428333483

However, I do fear that it might be too late to make it unstable now?

**Comment by flip1995** [comment]
I mean we could make it unstable in an edition (if also tools can use editions for such things). But only if we replace it with something stable, like a `lints.toml` file (I want to write a RFC for this soon).

Or we just introduce a warning for the `clippy.toml` file and provide tooling to convert it to the new configuration and support both for a few releases.

**Comment by tgross35** [comment]
Options for a config file are discussed more in depth on #6625 - since there isn't much discussion here, could this be closed as a duplicate?

**Comment by flip1995** [comment]
We'll probably won't turn this into an unstable feature now. We're way past this point.

**Comment by tgross35** [comment]
> We'll probably won't turn this into an unstable feature now. We're way past this point.

I was kind of hoping it wouldn't go away 🙂 thanks for confirming
