### ISSUE TITLE
lint against String.repeat(1)

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-clippy#3028]
````rust
    let x = String::from("hello world").repeat(1);
````
or
````rust
    let x = String::from("hello");
    let y = x.repeat(1);
````
does just clone the String.

**Comment by einashaddad** [comment]
I'll pick this up!

**Comment by flip1995** [comment]
Great! If you have any questions, feel free to ask here or opening a WIP PR. We're happy to help!

**Comment by einashaddad** [comment]
Awesome, thanks! 

https://github.com/rust-lang-nursery/rust-clippy/pull/3060

**Comment by HarrisonMc555** [comment]
@einashaddad Are you still interested in taking care of this lint? I'm looking for an issue or two to pick up, I'd be willing to help out here if you're no longer available.

**Comment by flip1995** [comment]
I think the PR #3060 was nearly finished, except of some review comments, that need to be addressed. You could go from there.

**Comment by HarrisonMc555** [comment]
Ok, will do. Thanks!

**Comment by einashaddad** [comment]
Hey y'all - sorry for the late reply, I've been traveling. I can address
the comments in a week when I'm back from vacation!

**Comment by giraffate** [comment]
Hi! If nobody is interested in this, could I try this?

**Comment by flip1995** [comment]
Yes, take a look at #3060, which is nearly finished

**Comment by giraffate** [comment]
@flip1995 Thank you for your infomation.

And I am sorry for the question immediately, why is `String.repeat(1)` bad?
I couldn't understand the hidden intention behind the repeat(1) call in [this comment](https://github.com/rust-lang/rust-clippy/pull/3060#discussion_r211055048) well.

**Comment by flip1995** [comment]
Oh `String.repeat(1)` is the same as `String.clone()`.  See the [documentation](https://doc.rust-lang.org/std/string/struct.String.html#method.repeat):

> Creates a new `String` by repeating a string `n` times.

with `n=1` this is the same as cloning the string. If that is **really** the intention behind this, `clone` should be used.
