### ISSUE TITLE
Idea: Unintentional borrowing with &str return.

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust-clippy#305]
This can happen, where the user uses string literals but unintentionally borrows self.

``` rust
fn foo(&self) -> Result<(), &str> { Err("error") }
```

The lint should suggest `&'static str` in the return type to avoid false borrowing, if the function body uses `&'static str`. I guess `Error::description(&self) -> &str` is an exception, the borrowing is mandated by the trait.

**Comment by Manishearth** [comment]
This might be nontrivial to catch, it involves walking the AST for returns, and then ensuring that all returned strings originate from static strings.

**Comment by llogiq** [comment]
This could be a by-product of the Cow lint I'm currently writing.
