### ISSUE TITLE
lint `identity_conversion` name is misleading

### ISSUE THREAD

**Issue by imp** [rust-lang/rust-clippy#3106]
The lint `identity_conversion` has a somewhat misleading name. It feels like it suggests the identity conversion is being actually done somewhere in the code. In reality, however, this lint checks for useless conversion from some type to the very same type. Indeed, the error that is reported by this lint is `error: identical conversion`, which points exactly to the issue in hand.
I want to suggest renaming the lint to match the error report.
I.e. `identity_conversion` -> `identical_conversion`
Or, perhaps, to `useless_identity_conversion` (which is admittedly longer name).

What is the policy on lint renaming? Is it something that may be done at all? Supported?
Encouraged/discouraged?

**Comment by oli-obk** [comment]
Maybe just `useless_conversion`?

**Comment by ExpHP** [comment]
I'd rather propose the opposite and change the text to read `identity conversion`.  I find "identical conversion" to be confusing language.

> The lint `identity_conversion` has a somewhat misleading name. It feels like it suggests the identity conversion is being actually done somewhere in the code. In reality, however, this lint checks for useless conversion from some type to the very same type.

I don't see the difference.
