### ISSUE TITLE
AppVeyor 'stderr: error: unable to unlink old fallback exe' error in dogfood tests

### ISSUE THREAD

**Issue by phansch** [rust-lang/rust-clippy#3118]
This error started appearing after https://github.com/rust-lang-nursery/rust-clippy/pull/3115, but no idea why.

**Comment by flip1995** [comment]
Especially https://github.com/rust-lang-nursery/rust-clippy/pull/3115#issuecomment-418010630

**Comment by mikerite** [comment]
We fixed this in #3701.
