### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by dee-y** [rust-lang/rust-clippy#3158]
Hello there, i am a graphic designer and open-source is my habit lol. I would love to contribute a logo to clippy that's if you don't already have one.

**Comment by Turbo87** [comment]
I got a little bored and created one... 😅 

![clippy](https://user-images.githubusercontent.com/141300/129923805-0d3b7409-bb73-4835-bd31-0ed80538280d.png)

Let me know if you like it, I also have it as an SVG file, but GitHub won't let me attach that here.

**Comment by Manishearth** [comment]
cc @rust-lang/rust-clippy Should we include something like this in the README?

(the clippy logo used is apache 2.0 https://icon-icons.com/icon/clippy/136771 )

**Comment by xFrednet** [comment]
That, a very interesting proposal. I personally like the proposed image and think that it would give the repo some more personality. Clippy also seems friendly and inviting in the image, which is also very good IMO. However, I'm not sure on the license part.

@Turbo87 Could you try to export the icon part of the logo in the size of a favicon (48x48)? It would be interesting to see it in that size, and we could maybe also use it as a favicon for our lint list.

@Manishearth FYI, I've updated your comment to ping `@rust-lang/clippy`

**Comment by camsteffen** [comment]
> Clippy also seems friendly and inviting in the image, which is also very good IMO. 🙃

Have you actually met Clippy? He's a total jerkface.

**Comment by xFrednet** [comment]
> > Clippy also seems friendly and inviting in the image, which is also very good IMO. :upside_down_face: 
> 
> Have you actually met Clippy? He's a total jerkface.

Yes, I have, at least a bit in my childhood. Clippy might have been a prankster, however a good first impression can go along way. Besides that, wasn't *Clippy* just an acronym for *"Clippy Loves Insulting People's Programming, Yelling"* anyways? :wink:

**Comment by Manishearth** [comment]
https://office-watch.com/2021/why-has-microsoft-finally-trademarked-clippy/


the image is trademarked (the name itself, also I checked, is not)
