### ISSUE TITLE
shadow lint should use visitor or ExprUseVisitor

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust-clippy#318]
We're duplicating a lot of the work Visitor does.

ExprUseVisitor might work, but there's no way of handling scopes.

cc @birkenfeld thoughts?

**Comment by llogiq** [comment]
The ExprUseVisitor could at least work for the contains-check.

**Comment by llogiq** [comment]
#449 at least uses the Visitor for the contains check.
