### ISSUE TITLE
Needs an Easter egg that makes a paperclip give you your lint messages.

### ISSUE THREAD

**Issue by icefoxen** [rust-lang/rust-clippy#3181]
If Ansible can do it with cowsay, why can't we?

Willing to create a PR if nobody objects.

**Comment by mikerite** [comment]
Duplicate of #2454

**Comment by icefoxen** [comment]
Never have I been so happy to find that an issue I opened was a duplicate.

**Comment by phansch** [comment]
Closing as duplicate (we should really implement the easter egg mode, though :rabbit: )
