### ISSUE TITLE
error: component 'clippy-preview' for 'i686-pc-windows-msvc' is unavailable for download

### ISSUE THREAD

**Issue by mcandre** [rust-lang/rust-clippy#3193]
Trying to use clippy with 32-bit Windows, Visual Studio compiler integration but I am getting this error:

```console
> rustup component add clippy-preview --toolchain=nightly
error: component 'clippy-preview' for 'i686-pc-windows-msvc' is unavailable for download
```

**Comment by mati865** [comment]
It does work with latest nightly for windows-gnu toolchain.
Have you updated `rustup` and toolchain?

**Comment by mcandre** [comment]
Yes. I am seeing this error for Windows 32-bit as well as for FreeBSD 64-bit.

```
error: toolchain 'nightly-x86_64-unknown-freebsd' does not contain component 'clippy-preview' for target 'x86_64-unknown-freebsd'
```

As for FreeBSD, looks like rustup is stuck with rust v1.26.0-nightly :/

**Comment by mati865** [comment]
To use `clippy-preview` you need **latest** rustup and fairly recent nightly (I think 1.28+ will work). According to [this page](https://mexus.github.io/rustup-components-history/i686-pc-windows-msvc.html) msvc should work.

What are yours:
```
rustup -V
rustc -V
```
