### ISSUE TITLE
Why does Clippy not suggest removing an  `Option::map` call with an "identity"

### ISSUE THREAD

**Issue by mandx** [rust-lang/rust-clippy#3236]
Playing around with the following code, I accidentally left an `map()` call on the `Option` type (originally, the closure was dereferencing the parameter, or calling `clone()` on it, something like that). But I noticed that Clippy doesn't suggests that using `map()` like this is unnecessary:

```rust
fn fib(n: usize, memo: &mut [Option<usize>]) -> usize {
    memo[n].map(|v| v).unwrap_or_else(|| {
        let result = {
            if n > 1 {
                fib(n - 1, memo) + fib(n - 2, memo)
            } else {
                1
            }
        };
        memo[n] = Some(result);
        result
    })
}

fn main() {
    let number = 46;
    let mut memo: Vec<Option<usize>> = vec![None; number + 1];
    println!("{}", fib(number, &mut memo));
}
```

And if I turn on "pedantic" mode, the suggestion I get is to use [`map_or_else`](option_map_unwrap_or_else).

[Play link](https://play.rust-lang.org/?gist=a99ac85e40e36200c9cb1fb79be8fec6&version=beta&mode=debug&edition=2018)

**Comment by camsteffen** [comment]
Today this lints as expected.
