### ISSUE TITLE
New lint: slow or unsafe vector initialization

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang/rust-clippy#3237]
Cross post of https://github.com/rust-lang/rust/issues/54628. See the thread for more details. The content below is a dumb summary.

**Bad example**

```
// resize
let mut vec1 = Vec::with_capacity(len);
vec1.resize(len, 0);
// extend
let mut vec2 = Vec::with_capacity(len);
vec2.extend(repeat(0).take(len))
```

Also some unsafe approaches exist, but it's TBD.

**Good example**
```
// vec! macro
let mut vec3 = vec![0; len];
```

**Comment by mcarton** [comment]
Bit of context for people interested on that one: https://medium.com/@shnatsel/how-ive-found-vulnerability-in-a-popular-rust-crate-and-you-can-too-3db081a67fb
