### ISSUE TITLE
rustfmt incompatibility: possibly missing a comma here

### ISSUE THREAD

**Issue by Dushistov** [rust-lang/rust-clippy#3244]
```rust
pub fn f(a: i16, b: f64) -> [f64; 3] {
    const C: f64 = 100.;
    [
        b,
        -b,
        match a {
            0x17 => 1.,
            0x18 => 2.,
            _ => 3.,
        } * C
            / 60.,
    ]
}
```

for such code clippy (from rustup/stable | 0.0.212) clippy show error:
```
error: possibly missing a comma here
  --> src/lib.rs:10:14
   |
10 |         } * C
   |              ^
   |
```

the problem that this is default coding style from rustfmt that comes with rustup/stable compiler,
it is possible to fix if reformat code like this `* C / 60.` , but `rustfmt` doesn't allow such coding style by default. 

Not sure is this rustfmt issue or clippy, but clippy and rustfmt runs on CI,
and clippy fails.

**Comment by mcarton** [comment]
I would say `rustfmt` is the one that's wrong on this one. The style it proposes it really ugly.
Alternatively, I'd suggest you use a variable for the `match`, as I don't think using `match` as an expression like this will ever look really nice.

**Comment by Areredify** [comment]
Fixed by [this pr](https://github.com/rust-lang/rust-clippy/pull/3407), can be closed @flip1995
