### ISSUE TITLE
Travis Windows: Secret ENV vars break the build

### ISSUE THREAD

**Issue by phansch** [rust-lang/rust-clippy#3306]
The previous build issues are resolved. Now the UI tests are failing: 

https://travis-ci.org/rust-lang-nursery/rust-clippy/jobs/440797682#L746

I'm not sure what the problem is. The stderr diffs look the same on the first glance.

**Comment by mati865** [comment]
I bet it's the line endings conversion (CLRF <-> LF).
Git for Windows can be configured to leave them intact or convert them to chosen format. Repository is already checked out so you can play with `dos2unix` and `unix2dos` from `C:\Program Files\Git\usr\bin` to get matching endings.

**Comment by phansch** [comment]
It was worth a try, but using `unix2dos` didn't seem to make a difference.

Some thoughts:
- Why does it work on AppVeyor? (Are they not using WSL?)
- Maybe related to the path normalization?
- Maybe I [didn't use unix2dos correctly](https://github.com/rust-lang-nursery/rust-clippy/pull/3374/files#diff-ce18faa8208e5babb77318549d5c101fR18)?

I'm not really sure how to effectively debug this without a windows machine, so I'll leave this to someone else.

**Comment by mati865** [comment]
* Appveyor runs build script in Powershell while Travis Windows does it in Git for Windows BASH. WSL would give Linux like environment.
* I diffed the expected and actual outputs on Travis and they are identical but test diff prints all likes like they were different.
* LGTM

Have you tried with `dos2unix`?

**Comment by mati865** [comment]
Just tested on Windows and all tests pass.

**Comment by phansch** [comment]
Maybe adding `YARN_GPG=no` fixes the problem, too: https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288/8

**Comment by phansch** [comment]
This particular issue seems to be fixed now and the build continues further
