### ISSUE TITLE
clippy::identity-op triggering on 1 << 0

### ISSUE THREAD

**Issue by cramertj** [rust-lang/rust-clippy#3445]
When writing bitflags it's convenient to structure code like this:

```rust
const X: usize = 1 << 0;
const Y: usize = 1 << 1;
const Z: usize = 1 << 2;
```

Clippy lints against the `1 << 0` because it has no effect. This is a fairly common structure-- it'd be nice to perhaps make an exception for this specific case.

**Comment by hcpl** [comment]
Duplicate of https://github.com/rust-lang/rust-clippy/issues/3430?

**Comment by cramertj** [comment]
Yup! I searched but didn't see it. Thanks!
