### ISSUE TITLE
Clippy not available on latest nightly with rustup

### ISSUE THREAD

**Issue by alex** [rust-lang/rust-clippy#3448]
```shell
$ rustc --version
rustc 1.32.0-nightly (0b9f19dff 2018-11-21)
$ rustup --version
rustup 1.14.0 (1e51b07cc 2018-10-04)
$ cargo --version
cargo 1.32.0-nightly (b3d0b2e54 2018-11-15)
$ rustup component add rustfmt-preview
info: downloading component 'rustfmt-preview'
info: installing component 'rustfmt-preview'
$ rustup component add clippy-preview
error: component 'clippy-preview' for 'x86_64-unknown-linux-gnu' is unavailable for download
```

**Comment by mati865** [comment]
It's fixed already: https://github.com/rust-lang/rust/commits/dae6c9364108847393075b57a17fd7eaf3f37600
Tomorrow's nightly should be fine.

**Comment by alex** [comment]
I'm a day late and a dollar short! Thanks!

**Comment by matthiaskrgr** [comment]
Yes, there should be a new nightly released in ~10 hours and if nothing breaks in between it should feature clippy again :)

**Comment by flip1995** [comment]
A really good website to lookup the status of the current nightly is https://mexus.github.io/rustup-components-history/
