### ISSUE TITLE
appveyor is missing

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-clippy#3451]
Since the move from `rust-lang-nursery` to `rust-lang`, pull requests and branches are no longer checked by appveyor.

**Comment by flip1995** [comment]
I added the project to appveyor again. But it seems that it now builds under my account: https://ci.appveyor.com/project/flip1995/rust-clippy-p2u9r/

We probably want to run appveyor under the rust-lang organization. I think on rust-lang-nursery appveyor ran under @Manishearth account?

**Comment by phansch** [comment]
Closing this as AppVeyor as been back for a long time (under the `rust-lang-libs` project)
