### ISSUE TITLE
Fix URL

### ISSUE THREAD

**Issue by dwijnand** [rust-lang/rust-clippy#3454]
The repo URL currently points to https://rust-lang-nursery.github.io/rust-clippy, which doesn't work.

Ideally, that would redirect.  See:

* https://internals.rust-lang.org/t/end-of-days-for-the-rust-lang-nursery/8750/7, and
* https://internals.rust-lang.org/t/end-of-days-for-the-rust-lang-nursery/8750/8

for some details on that.

**Comment by dwijnand** [comment]
Given Clippy's warnings show:

```
help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#trivially_copy_pass_by_ref
```

I think it's probably best to setup the redirects.

**Comment by mati865** [comment]
cc https://github.com/rust-lang/rust-clippy/pull/3446

**Comment by matthiaskrgr** [comment]
What version of clippy are you using?

When I try with clippy of latest nightly (`clippy 0.0.212 (754b4c0 2018-11-23)`) , the url does not link to the nursery:
````
    = note: #[warn(clippy::unnecessary_mut_passed)] on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_mut_passed
````

**Comment by mati865** [comment]
@matthiaskrgr stable and beta releases still have old clippy.

**Comment by dwijnand** [comment]
Any even older releases have old clippy.

I know clippy is just in preview and all, but I think putting that 404 page in place would go a long way helping users.

**Comment by phansch** [comment]
This has been partially fixed, but we are still missing redirects for older versions. I'm going to close this in favor of https://github.com/rust-lang-nursery/rust-lang-nursery.github.io/issues/1.

**Comment by dwijnand** [comment]
Thanks!
