### ISSUE TITLE
Run rustfmt before Clippy 1.0

### ISSUE THREAD

**Issue by flip1995** [rust-lang/rust-clippy#3460]
`cargo fmt --all` currently changes 133/139 files in `clippy_lints/src` and 145 in total. Maybe we should run `rustfmt` before 1.0 and add `cargo fmt --all -- --check` to the CI.

We currently have 27 open PRs where about 20 are stale PRs. This would interfere with pretty much all of them. But once we ran `rustfmt`, we won't have to do it again if we enforce it with the CI.

**Comment by waynr** [comment]
Maybe this was intended anyway, but I would suggest running `cargo fmt --all -- --check` in a test case similar to the way the dogfood tests are being run as of #3444 to ensure that users who run `cargo test` have a chance to make the suggested changes without waiting for CI to fail.

**Comment by oli-obk** [comment]
Seems good to me, last time we stopped using rustfmt because of nightly/crates differences, but all that should be fine now.
