### ISSUE TITLE
Documentation for `implicit_hasher` is not very helpful

### ISSUE THREAD

**Issue by dpc** [rust-lang/rust-clippy#3475]
It is not clear how exactly to convert `HashSet<Foo>` into a form that would be " generalization over different hashers", and the fact that if you go to https://doc.rust-lang.org/std/collections/hash_map/struct.HashMap.html you see:
```
pub struct HashMap<K, V, S = RandomState> { /* fields omitted */ }
```

is not helping. "Where is this Hasher thing?"

It would be great if https://rust-lang.github.io/rust-clippy/master/index.html#implicit_hasher could show the wrong code and then the right one, to make it clear.

**Comment by hcpl** [comment]
`S` represents a hasher here. When implementing something generic over hashers, you then need to add a `S: BuildHasher` bound (e.g. [`HashMap::with_hasher`](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.with_hasher)).

But yes, the docs could at least mention the third type parameter at all.

**Comment by dpc** [comment]
I did figure it out, but the first reaction was "oh dear, I wish clippy just told me what to do".
