### ISSUE TITLE
Clippy fails with latest master rustc

### ISSUE THREAD

**Issue by phansch** [rust-lang/rust-clippy#3500]
Caused by this rollup: https://github.com/rust-lang/rust/pull/56557
Not sure which PR exactly.

**Comment by matthiaskrgr** [comment]
Probably https://github.com/rust-lang/rust/commit/08f8faedd0e30f45762afbb8d4873f7041e7462c
I'll have a look...

**Comment by mati865** [comment]
@matthiaskrgr 
```
-        name.name == keywords::SelfValue.name()
+        name.name == keywords::SelfUpper.name()
```
Shouldn't it be:
```
-        name.name == keywords::SelfValue.name()
+        name.name == keywords::SelfLower.name()
```
?

**Comment by matthiaskrgr** [comment]
RIght, thanks, I just found out by trial error :P
Will prep PR in a couple of minutes.
