### ISSUE TITLE
Unable to install on Rust 1.31.0 with rustup

### ISSUE THREAD

**Issue by ashthespy** [rust-lang/rust-clippy#3503]
Don't seem be to be able to install clippy via rustup.

```
C:\Users\Ash> rustup show
Default host: x86_64-pc-windows-msvc

stable-x86_64-pc-windows-msvc (default)
rustc 1.31.0 (abe02cefd 2018-12-04)
C:\Users\Ash> rustup component add clippy
error: toolchain 'stable-x86_64-pc-windows-msvc' does not contain component 'clippy' for target 'x86_64-pc-windows-msvc'
```

**Comment by Manishearth** [comment]
cc @nrc @alexcrichton

**Comment by nrc** [comment]
could you try `rustup self update` and then try re-installing please?

**Comment by ashthespy** [comment]
No luck:
```
C:\Users\Ash> rustup self update
info: checking for self-updates
info: downloading self-update
info: rustup updated successfully to 1.14.0
C:\Users\Ash> rustup component add clippy
error: toolchain 'stable-x86_64-pc-windows-msvc' does not contain component 'clippy' for target 'x86_64-pc-windows-msvc'
```

**Comment by mati865** [comment]
`rustup component add clippy-preview` will work.

**Comment by alexcrichton** [comment]
I've found the issue and am working on it!

**Comment by fominok** [comment]
Same for x86_64-unknown-linux-gnu

**Comment by ashthespy** [comment]
After the last comment just checked on WSL, and can confirm it's the same for `stable-x86_64-unknown-linux-gnu` as well.

**Comment by yoursvivek** [comment]
Same for `clippy` on `x86_64-apple-darwin`. `rustfmt` too.
``` 
~ $ rustup component add clippy
error: toolchain 'stable-x86_64-apple-darwin' does not contain component 'clippy' for target 'x86_64-apple-darwin'
~ $ rustup component add rustfmt
error: toolchain 'stable-x86_64-apple-darwin' does not contain component 'rustfmt' for target 'x86_64-apple-darwin'
~ $ rustup component list | grep -e clippy -e rustfmt
clippy-preview-x86_64-apple-darwin
rustfmt-preview-x86_64-apple-darwin
~ $ rustup show 
Default host: x86_64-apple-darwin

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.31.0 (abe02cefd 2018-12-04)
```

**Comment by CryZe** [comment]
The solution is to completely wipe your toolchain and reinstall it.

**Comment by ianthetechie** [comment]
@CryZe that's one heck of a solution, but I can confirm it worked for me on macOS Mojave. `rustup self uninstall` is the way to uninstall btw.

**Comment by phansch** [comment]
Thanks everyone for the workarounds! I'm going to go ahead and close this issue, as it's not directly in the power of Clippy to fix this. Although not ideal, the above workarounds should work if you're running into the problem :heart_decoration:

**Comment by liamdawson** [comment]
This bit me, and I suspect it could bite others too (I almost opened an issue). Maybe add a note to the readme around the install instructions?

**Comment by sorenmortensen** [comment]
I just had to do this (run `rustup self uninstall` and then reinstall) in order to be able to install `clippy` on stable, after being able to install it on nightly and attempting to fix it on stable by running `rustup self update`, which didn't work.

**Comment by wimblemine** [comment]
> * `rustup self uninstall`

Solved my problem on WSL
