### ISSUE TITLE
lint request: unnecessary extern crate

### ISSUE THREAD

**Issue by Maxgy** [rust-lang/rust-clippy#3513]
With the release of Rust 2018, many uses of `extern crate` are useless.  Could there be a lint to recommend removing these occurrences?

**Comment by sondr3** [comment]
Isn't this something that `cargo fix` should take care of?

**Comment by Maxgy** [comment]
@sondr3 , I agree.  This would be an easy `cargo fix` lint.

**Comment by mati865** [comment]
Rustfix already does it but it's buggy.

**Comment by oli-obk** [comment]
The compiler already has the `rust_2018_idioms` lint group. You can try if that already solves most of what you want. If not, please open an issue for concrete problems against rustc.
