### ISSUE TITLE
"stutter" could be considered ableist language?

### ISSUE THREAD

**Issue by klausi** [rust-lang/rust-clippy#3521]
Hi,

thanks for clippy, a great tool!

I just discovered the "stutter" lint at https://rust-lang.github.io/rust-clippy/master/#stutter and found the naming quite disturbing. Repeating names in source code is by no way comparable to people with a stuttering disability. The Rust code of conduct is committed to a friendly environment for people with a disability and I think the "stutter" wording violates that.

Proposed solution: rename the "stutter" lint to "module_name_repeat", which is more descriptive.

2 disclaimers: I'm not a native English speaker and I don't have a stuttering disability.

**Comment by Manishearth** [comment]
We could rename the lint and keep the old name as a redirect, if possible.

"stutter" in English can just mean "repetition", but I don't see a big reason to not change this.

**Comment by mati865** [comment]
CC https://github.com/rust-lang/rust-clippy/issues/2845

**Comment by klausi** [comment]
I disagree a bit on the simple repetition meaning, everything I could find about stutter online would point me to the speech disorder first.

Put another way: I would not call the DRY principle (Don't Repeat Yourself) in software development  equivalent to calling it the DS principle (Don't Stutter). I think that would be quite offensive.

**Comment by Manishearth** [comment]
I'm specifically talking of repetition of words; DRY is different.

**Comment by klausi** [comment]
Now that @oli-obk has added the "good first issue" tag I will try to come up with a PR to change this. I see some confused/thumbs down emojis here, please let me know if we missed any reasons not to change this.

**Comment by klausi** [comment]
My PR was completed by @flip1995 and merged, so I think we are done here. Thanks everyone!
