### ISSUE TITLE
Warn for Vec<Box<T>> where T: Sized

### ISSUE THREAD

**Issue by Kampfkarren** [rust-lang/rust-clippy#3530]
A fellow Rust programmer pointed me to this mistake in my code:

![image](https://user-images.githubusercontent.com/3190756/49775692-cd609200-fcad-11e8-8299-bfa5acb0cb79.png)

I'm quite new to Rust, but is there ever a point where Vec<Box<T: Sized>> is correct?

**Comment by sinkuu** [comment]
For example, it might make sense when `T` is a very large type. Calling `.swap(0, 1)` on `Vec<T>` will memcpy `size_of::<T>() * 3`, but it would be `pointer_size * 3` for `Vec<Box<T>>`.

**Comment by benma** [comment]
Another example: reallocation of the vector when growing it is slower and copies more bytes when the size of `T` is large.

**Comment by wiiznokes** [comment]
Could this warning be deactivate when the struct is large ?

**Comment by y21** [comment]
@wiiznokes The lint already checks that the type's size is lower than a threshold to avoid linting on large types. You can override `vec-box-size-threshold` to a lower value in config.toml (default is 4096 bytes)
