### ISSUE TITLE
unit tests: error if there is a .stderr without matching .rs

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-clippy#3572]
Right now we have a `./tests/ui/map_unit_fn.stderr` but on matching `./tests/ui/map_unit_fn.rs` which is going to be cleaned up by https://github.com/rust-lang/rust-clippy/pull/3570 .

Maybe have some tests that assures that all .rs files have a matching .stderr?

**Comment by flip1995** [comment]
> Maybe have some tests that assures that all .rs files have a matching .stderr?

I guess this is a typo, since you wrote it correctly in the title. But just to clarify: It should only warn on a `*.std[err|out]` file without a matching `*.rs` file. A `*.rs` file without a `*.std[err|out]` file is valid and means "No output expected".

**Comment by mati865** [comment]
Fixed by https://github.com/rust-lang/rust-clippy/pull/3669
