### ISSUE TITLE
new_ret_no_self should allow Result<Self, E>

### ISSUE THREAD

**Issue by Riateche** [rust-lang/rust-clippy#3620]
`new_ret_no_self` currently triggers if `new()` returns `Result<Self, E>`. I think `new()` is still an idiomatic name for a constructor even if it can fail, so `Result<Self, E>` should be permitted.

**Comment by flip1995** [comment]
This was already fixed in #3338: [Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015)

```rust
struct A;

impl A {
    fn new() -> Result<Self, ()> {
        Err(())
    }
}
```

Feel free to reopen if I misunderstood the issue.

**Comment by jplatte** [comment]
> This was already fixed in #3338: [Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015)

Your link just opens the Playground without any specific code. Seems like you just copied the URL instead of using the share button.

**Comment by scottjmaddox** [comment]
I'm not sure how to test it in the playground, but it's definitely not fixed in the latest release of clippy. It looks like the last release was Oct 5, though, so it's possible that pull request from Oct 19 fixes it.

When is the next release planned?

**Comment by mati865** [comment]
@scottjmaddox Clippy doesn't have releases, you should install it with rustup: https://github.com/rust-lang/rust-clippy#step-1-install-rustup

**Comment by scottjmaddox** [comment]
@mati865 I was basing the "releases" on the versions posted at https://crates.io/crates/clippy. I did install through rustup, and it stills says up to date. Perhaps the question I should ask is, when will the version that includes the stated fix be available for install through rustup?

**Comment by flip1995** [comment]
> Your link just opens the Playground without any specific code.

Oh sorry it was late. There you go: [Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=6640c0c6ab327c9609c5480b01136012) You can test it via Tools -> Clippy in the top right corner

> "releases" on the versions posted at https://crates.io/crates/clippy

This is deprecated and is only there to point people to rustup

The Clippy version shipped with rustup depends on the toolchain you are using when running `rustup component add clippy`. If you're using the latest stable toolchain (1.31) you'll get
```
clippy 0.0.212 (2e26fdc 2018-11-22)
```
with beta
```
clippy 0.0.212 (b2601be 2018-11-27)
```
and nightly
```
clippy 0.0.212 (c63b634 2019-01-05)
```

So if you use rustc 1.31 and above this fix should be included.
