### ISSUE TITLE
failed to compile `clippy v0.0.212 (https://github.com/rust-lang/rust-clippy/#c63b6349)`

### ISSUE THREAD

**Issue by novakov-alexey** [rust-lang/rust-clippy#3636]
Trying to add clippy on

nightly-x86_64-apple-darwin (default)
rustc 1.33.0-nightly (f381a9625 2019-01-04)

**Verbose output:**

   Compiling clippy_lints v0.0.212 (https://github.com/rust-lang/rust-clippy/#c63b6349)
     Running `rustc --edition=2018 --crate-name clippy_lints /Users/aa/.cargo/git/checkouts/rust-clippy-4b72815e96774b3d/c63b634/clippy_lints/src/lib.rs --color always --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=16fda1167959b253 -C extra-filename=-16fda1167959b253 --out-dir /var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps -L dependency=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps --extern cargo_metadata=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/libcargo_metadata-824ca83f626fed14.rlib --extern if_chain=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/libif_chain-8e706b091a57b965.rlib --extern itertools=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/libitertools-7ce4f810d924003e.rlib --extern lazy_static=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/liblazy_static-b35deac8cddf0ef1.rlib --extern matches=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/libmatches-56966a767407a56e.rlib --extern pulldown_cmark=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/libpulldown_cmark-d3b2c115a95fa18f.rlib --extern quine_mc_cluskey=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/libquine_mc_cluskey-8440a756accd2cb1.rlib --extern regex_syntax=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/libregex_syntax-6d2034966b5517ca.rlib --extern semver=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/libsemver-9fa7423275842e1f.rlib --extern serde=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/libserde-fbda8130fa1ff666.rlib --extern serde_derive=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/libserde_derive-8674d82ed717fa89.dylib --extern smallvec=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/libsmallvec-da8c9f1a7850df03.rlib --extern toml=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/libtoml-b86b35bfb6be901c.rlib --extern unicode_normalization=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/libunicode_normalization-94ac635f8c736299.rlib --extern url=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/liburl-ac472c41904fac56.rlib --cap-lints allow`
error[E0308]: mismatched types
   --> /Users/aa/.cargo/git/checkouts/rust-clippy-4b72815e96774b3d/c63b634/clippy_lints/src/len_zero.rs:306:20
    |
306 |             if let Some(principal) = tt.principal() {
    |                    ^^^^^^^^^^^^^^^ expected struct `rustc::ty::Binder`, found enum `std::option::Option`
    |
    = note: expected type `rustc::ty::Binder<rustc::ty::ExistentialTraitRef<'_>>`
               found type `std::option::Option<_>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: failed to compile `clippy v0.0.212 (https://github.com/rust-lang/rust-clippy/#c63b6349)`, intermediate artifacts can be found at `/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw`

Caused by:
  Could not compile `clippy_lints`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name clippy_lints /Users/aa/.cargo/git/checkouts/rust-clippy-4b72815e96774b3d/c63b634/clippy_lints/src/lib.rs --color always --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=16fda1167959b253 -C extra-filename=-16fda1167959b253 --out-dir /var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps -L dependency=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps --extern cargo_metadata=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/libcargo_metadata-824ca83f626fed14.rlib --extern if_chain=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/libif_chain-8e706b091a57b965.rlib --extern itertools=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/libitertools-7ce4f810d924003e.rlib --extern lazy_static=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/liblazy_static-b35deac8cddf0ef1.rlib --extern matches=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/libmatches-56966a767407a56e.rlib --extern pulldown_cmark=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/libpulldown_cmark-d3b2c115a95fa18f.rlib --extern quine_mc_cluskey=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/libquine_mc_cluskey-8440a756accd2cb1.rlib --extern regex_syntax=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/libregex_syntax-6d2034966b5517ca.rlib --extern semver=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/libsemver-9fa7423275842e1f.rlib --extern serde=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/libserde-fbda8130fa1ff666.rlib --extern serde_derive=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/libserde_derive-8674d82ed717fa89.dylib --extern smallvec=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/libsmallvec-da8c9f1a7850df03.rlib --extern toml=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/libtoml-b86b35bfb6be901c.rlib --extern unicode_normalization=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/libunicode_normalization-94ac635f8c736299.rlib --extern url=/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installKZ39fw/release/deps/liburl-ac472c41904fac56.rlib --cap-lints allow` (exit code: 1)

**Comment by mati865** [comment]
Clippy doesn't build with nightly because it has to keep up with Rust. If you want to build Clippy yourself you'll need toolchain newer than nightly, see `rustup-toolchain-install-master` part of [contributing guide](https://github.com/rust-lang/rust-clippy/blob/master/CONTRIBUTING.md#fixing-build-failures-caused-by-rust).

**Comment by mati865** [comment]
You should run it with `cargo +master clippy`.
Once Rust bug is fixed Clippy will be again [available via rustup](https://github.com/rust-lang/rust-clippy#step-2-install-clippy) which will simplify the process.

**Comment by novakov-alexey** [comment]
I am lost now 😕 . There is another issue if run `cargo install clippy`:

```
cargo install clippy                                                                                                                                                                                

  Updating crates.io index
  Downloaded clippy v0.0.302
  Downloaded 1 crates (1.7 KB) in 0.71s
  Installing clippy v0.0.302
  Downloaded term v0.5.1
   Compiling byteorder v1.2.7
   Compiling term v0.5.1
   Compiling clippy v0.0.302
error: failed to compile `clippy v0.0.302`, intermediate artifacts can be found at `/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installZ2laGL`

Caused by:
  failed to run custom build command for `clippy v0.0.302`
process didn't exit successfully: `/var/folders/kd/3gqh_qlj0cb7r6gb1pydqrbc0000gn/T/cargo-installZ2laGL/release/build/clippy-f99b6b05b40015e7/build-script-build` (exit code: 1)
--- stderr

error: Clippy is no longer available via crates.io

help: please run `rustup component add clippy-preview` instead
```

**Comment by novakov-alexey** [comment]
Ok, I have switched to nightly release which has available 'clippy'. In my case of MacOs: https://mexus.github.io/rustup-components-history/x86_64-apple-darwin.html
I then run:

```
rustup update
rustup component add clippy
```

and then: cargo clippy command started to work 👍

**Comment by flip1995** [comment]
Thanks for reporting this! We don't support Clippy installed over cargo (with the newest nightlies) anymore. For future reference (as @novakov-alexey already discovered), you can always take a look at https://mexus.github.io/rustup-components-history/ to find a nightly with Clippy/RLS/rustfmt.
