### ISSUE TITLE
Failed to build branch 1.31.0 with rustc 1.31.0

### ISSUE THREAD

**Issue by captnfab** [rust-lang/rust-clippy#3651]
Hi,

rustc is installed from distribution (Debian testing/sid) package, in version 1.31.0.

I tried to build clippy without installing it.

`git clone https://github.com/rust-lang/rust-clippy -b rust-1.31.0
cd $MYPROJECT
cargo run --bin cargo-clippy --manifest-path=$CLIPPY_PATH`

I got the following build error:

> cargo run --bin cargo-clippy --manifest-path=$HOME/perso/rust-clippy/Cargo.toml
> warning: unused manifest key: package.edition
>    Compiling memchr v2.1.2
>    Compiling proc-macro2 v0.4.24
>    Compiling ryu v0.2.7
>    Compiling idna v0.1.5
>    Compiling smallvec v0.6.7
> error[E0554]: #![feature] may not be used on the stable release channel
>   --> $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-0.6.7/lib.rs:33:32
>    |
> 33 | #![cfg_attr(feature = "union", feature(untagged_unions))]
>    |                                ^^^^^^^^^^^^^^^^^^^^^^^^
> 
> error: aborting due to previous error
> 
> For more information about this error, try `rustc --explain E0554`.
> error: Could not compile `smallvec`.
> warning: build failed, waiting for other jobs to finish...
> error: build failed

**Comment by mati865** [comment]
Clippy is not meant to build with stable. If I understand correctly this branch is for docs.

cc @oli-obk

**Comment by captnfab** [comment]
Thanks for the reply.
Ok.
However, I have the same error message with the master branch.

`git clone https://github.com/rust-lang/rust-clippy`
`cd $MYPROJECT`
`cargo run --bin cargo-clippy --manifest-path=$CLIPPY_MASTER_PATH`
> warning: unused manifest key: package.edition
>    Compiling smallvec v0.6.7
>    Compiling clippy v0.0.212 (file:///home/fgivors/perso/rust-clippy)
>    Compiling backtrace v0.3.13
>    Compiling proc-macro2 v0.4.24
>    Compiling idna v0.1.5
>    Compiling backtrace-sys v0.1.28
> error[E0554]: #![feature] may not be used on the stable release channel
>   --> $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-0.6.7/lib.rs:33:32
>    |
> 33 | #![cfg_attr(feature = "union", feature(untagged_unions))]
>    |                                ^^^^^^^^^^^^^^^^^^^^^^^^
> 
> error: aborting due to previous error
> 
> For more information about this error, try `rustc --explain E0554`.
> error: Could not compile `smallvec`.
> warning: build failed, waiting for other jobs to finish...
> error: build failed

**Comment by o01eg** [comment]
Stable rustc cann't build unstable features.

> rustc is installed from distribution (Debian testing/sid) package, in version 1.31.0.

You should to say rustc Debian maintainers to build clippy in rust.

**Comment by captnfab** [comment]
> You should to say rustc Debian maintainers to build clippy in rust.
Well, they don't have time for that atm.  ^^"

> Stable rustc cann't build unstable features.
Ok. Then, how can I build a stable version of clippy, with stable features only with my stable version of rustc? (and without using rustup)

**Comment by Manishearth** [comment]
There is no version of clippy that only relies on stable rust features
