### ISSUE TITLE
new lint: suggest ptr::eq() instead of "x as *const _ as usize == y as *const as usize"

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-clippy#3661]
Inspired by https://github.com/rust-lang/rust/pull/57547
This looks like it could be a clippy lint :)

**Comment by AB1908** [comment]
I'd like to go ahead and try this.

**Comment by i-am-g2** [comment]
I want to do this. Please assign this to me.

**Comment by flip1995** [comment]
It's all yours! If you have any questions, we're happy to help. Just ask here or open a WIP PR.

**Comment by Ambroisie** [comment]
I would like to work on this. Should I try using the previous PR as a basis?
