### ISSUE TITLE
Duplicate warnings after rustup fix

### ISSUE THREAD

**Issue by phansch** [rust-lang/rust-clippy#3710]
The `ui/deprecated.stderr` and `ui/rename.stderr` contain duplicate lint emissions in two cases after rustup to https://github.com/rust-lang/rust/pull/57726.

> I think the reason for the duplicates is this change here:
https://github.com/rust-lang/rust/blob/9b5535a6f38340d3be8fcae1822a04ba3febf82f/src/librustc/lint/context.rs#L1325
> They now run `early_lint_crate` twice. Once with the builtin lints and once with the registered lint passes. Those warnings aren't generated by a normal lint but rather when the lints are looked up from attributes which happens twice now.
> I'm not sure why only the first is duplicated though. Maybe because they filter duplicates but the first one has a note. :thinking:

_Originally posted by @mikerite in https://github.com/rust-lang/rust-clippy/pull/3705#issuecomment-457924416_

**Comment by flip1995** [comment]
> Maybe because they filter duplicates but the first one has a note.

I ran into that myself before. Can confirm that this is an issue: https://github.com/rust-lang/rust/pull/53762#discussion_r216952233

The weird thing is, that it only happens on some lints and not on all lints.
