### ISSUE TITLE
Perhaps this match_bool case could be considered idiomatic?

### ISSUE THREAD

**Issue by swfsql** [rust-lang/rust-clippy#3713]
Hello, I have a suggestion for the `match_bool` lint
https://rust-lang.github.io/rust-clippy/master/index.html#match_bool

I'm not sure if this is idiomatic, buy I often attach (`@`) matched values into variables, eg.:

```rust
match some_hash_set.insert(some_key) {
        _previously_unset @ true => (),
        _previously_unset @ false => {
                 panic!("D'oh!")
        }
}
```

I actually prefer reading this interface like this, because I can kind of simultaneously see both branches (the "total" effect of each branch) and I kind of know beforehand that such value (`_previously_unset`) won't be used anywhere else, for anything else.

---

The "literal" translation for the if-else case would be:
```rust
{ // inner scope
        let previously_unset = some_hash_set.insert(some_key);
        if (!previously_unset) {
                panic!("D'oh!")
        }
}
```

But in this case, to see the "total" effect of `previously_unset @ true`, I'd have to look past the `if` statement and see where the variable would still be used (in which, in this case, would be nowhere.. since the scope ended).

---

Both cases have 6 lines, and the first one is slightly more verbose. But I actually am more comfortable at reasoning about the first case - it feels familiar, as if the function returned an enum of two cases..

so... this is a suggestion and perhaps you could agree with!
Thanks in advance,

**Comment by oli-obk** [comment]
I think we could prevent the lint from triggering if there are bindings bound on the arms.

Although I personally still prefer

```rust
if !some_hash_set.insert(some_key) {
    panic!("D'oh!");
}
```

**Comment by swfsql** [comment]
Oh wait, I just noted that one can also do:

```
if let _previously_unset @ false = some_hash_set.insert(some_key) {
    panic!("D'oh!");
}
```

which has all the benefits!
(not that verbose; easy to infer effects; named values), (and passes on clippy!)

So perhaps this (if-let) could be a suggestion instead (for someone matching on bools)?

Thanks for the clear and quick response!

**Comment by camsteffen** [comment]
I think it's quite unusual to use `_name @` just for code clarity rather than just doing `let name =`.
