### ISSUE TITLE
`needless_borrow` was temporarily moved to `nursery` in April 2018

### ISSUE THREAD

**Issue by phansch** [rust-lang/rust-clippy#3742]
In https://github.com/rust-lang/rust-clippy/commit/0692b2bb926a12a01cd4f7362092385498ebd0d0, the `needless_borrow` lint was temporarily moved to the nursery. However, it's still in the nursery now.

@oli-obk Since you committed that, do you maybe remember why you moved it to `nursery` and if it can be moved back? I couldn't find any other issues or PRs related to this commit unfortunately.

**Comment by oli-obk** [comment]
I moved it there because we were having problems after some proc macro changes that caused the lint to trigger inside derives without us being able to detect that. If this has been resolved, there's no reason not to move it back.
