### ISSUE TITLE
catch-22 with try block, clippy::unit_arg and clippy::unused_unit

### ISSUE THREAD

**Issue by DenialAdams** [rust-lang/rust-clippy#3759]
If I don't include a `()` at the end of a `let res: Result<(), io::Error> = try` block, I get a "passing a unit value to a function" clippy warning. If I do include a `()`, I get an "unneeded unit expression" clippy warning.

Sample code:
```
let res: Result<(), io::Error> = try {
   if true {
      some_statement();
   } else {
      some_other_statement();
   }
   //()
};
```

```
$ cargo clippy --version
clippy 0.0.212 (3bda548f 2019-02-03)
```

**Comment by flip1995** [comment]
This appears to be fixed: [Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=0a0d3cd09c8c1674e74007396cf3f4ee)
