### ISSUE TITLE
redundant_closure triggers for macro

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-clippy#3791]
I was using the `get_version_info!()` macro and got warnings that the imported code contains redundant closures on places where I used it.

https://github.com/rust-lang/rust-clippy/blob/master/rustc_tools_util/src/lib.rs

Can we disable the lint for code imported via macros?

**Comment by flip1995** [comment]
Huh? Can you provide an example? The `get_version_info!` doesn't contain closures, so the lint shouldn't trigger at all. Or am I missing something?
https://github.com/rust-lang/rust-clippy/blob/027dde92e22b9058c2bd6efa4b3e47b78d991dc7/rustc_tools_util/src/lib.rs#L4-L25

**Comment by matthiaskrgr** [comment]
https://github.com/matthiaskrgr/cargo-cache/commit/81ffeeb7ea4f82a42e144e7ba42fa4ddd05adeaa

Yeah it was updated to not contain closures but the crates.io version still contains closures.

**Comment by matthiaskrgr** [comment]
Anyway, what I mean is, if we report code imported by macros, these macros could also come from third party crates and issuing a lint warning looks like a false positive since the warning cannot be fixed by modifying the root crate.

**Comment by flip1995** [comment]
Ah that makes sense. We once had an `in_external_macro` function in `utils`, but I think it isn't possible anymore to get this information from rustc.

**Comment by phansch** [comment]
rustc now has a `in_external_macro` function: https://doc.rust-lang.org/nightly/nightly-rustc/rustc/lint/fn.in_external_macro.html
