### ISSUE TITLE
`len_zero` with Range suggests code cannot compile

### ISSUE THREAD

**Issue by oxalica** [rust-lang/rust-clippy#3807]
Code like `(0..42).len() == 0` will trigger `len_zero`, but `(0..42).is_empty()` does not compile now.

Clippy version: 0.0.212 (2019-02-19)
Rustc version: 1.34.0-nightly (2019-02-22)

[Playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=0047ed1a4462bbfb0fa01186e1de4dd6)
```
  |
4 |     println!("{}", (0..42).is_empty());
  |                            ^^^^^^^^ multiple `is_empty` found
  |
  = note: candidate #1 is defined in an impl for the type `std::ops::Range<_>`
note: candidate #2 is defined in the trait `std::iter::ExactSizeIterator`
  = help: to disambiguate the method call, write `std::iter::ExactSizeIterator::is_empty(::std::ops::Range{start: 0, end: 42,})` instead
```

**Comment by mikerite** [comment]
This isn't a Clippy bug. See rust-lang/rust#48111.

**Comment by mikerite** [comment]
:thinking: On the other hand, maybe it shouldn't be suggesting unstable methods...
