### ISSUE TITLE
Slow suggestion of single_char_pattern

### ISSUE THREAD

**Issue by CryZe** [rust-lang/rust-clippy#3813]
For str::starts_with using a single char string literal generates much better code as it can just compare the single byte of the str literal, while comparing against a char involves decoding possibly multiple bytes of the text. Here is the Godbolt for it: https://rust.godbolt.org/z/V_Arel

Therefore the single_char_pattern lint should not apply for str::starts_with (and possibly ends_with) and instead it should possibly even advice against using a char.

clippy 0.0.212 (b2601beb 2018-11-27)

**Comment by kennytm** [comment]
Previously: rust-lang/rust#41993

I'd oppose reversing this lint though, it is just an implementation defect and can be fixed.

**Comment by ebroto** [comment]
I think this can be closed now according to the resolution of the linked issue. See also https://github.com/rust-lang/rust/pull/67249 and https://github.com/rust-lang/rust/pull/69481.

**Comment by CryZe** [comment]
For non-ASCII it still seems to be slightly slower, but yeah, I'd say it's fine to recommend char now.
