### ISSUE TITLE
clippy not available on nightly-x86_64-pc-windows-msvc

### ISSUE THREAD

**Issue by Jezza** [rust-lang/rust-clippy#3836]
```
> rustup component add clippy
error: component 'clippy' for target 'x86_64-pc-windows-msvc' is unavailable for download

> rustup show
Default host: x86_64-pc-windows-msvc

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

nightly-x86_64-pc-windows-msvc (default)
rustc 1.34.0-nightly (c1d2d83ca 2019-03-01)

> rustup --version
rustup 1.16.0 (beab5ac2b 2018-12-06)
```

One of the workarounds that was suggested was to uninstall the entire toolchain (rustup and all), and reinstall it, but alas, that didn't work.

**Comment by Jezza** [comment]
Quick-side note, I can install it for stable.

**Comment by flip1995** [comment]
Yeah we're currently waiting for a updated Clippy in rustc (rust-lang/rust#58807). `nightly-2019-02-27` is the latest nightly with Clippy available. See https://mexus.github.io/rustup-components-history/x86_64-pc-windows-msvc.html. 

Clippy will probably be available in the nightly tomorrow or Monday. We try to get it fixed ASAP.

**Comment by mati865** [comment]
It's blocked on https://github.com/laumann/compiletest-rs/pull/160 and a new release.

**Comment by sirxyzzy** [comment]
Still no clippy?

```
~\dev\dfaf [master ≡]> rustup component add clippy
error: component 'clippy' for target 'x86_64-pc-windows-msvc' is unavailable for download for channel nightly
~\dev\dfaf [master ≡]> rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\andy\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
beta-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc (default)

active toolchain
----------------

nightly-x86_64-pc-windows-msvc (default)
rustc 1.41.0-nightly (82cf3a448 2019-11-14)

```

**Comment by Jezza** [comment]
Nope, it was available last night though.

https://rust-lang.github.io/rustup-components-history/x86_64-pc-windows-msvc.html

**Comment by flip1995** [comment]
Closing, since this is tracked on the components site.
