### ISSUE TITLE
Docs: Create a page with info on how to do common things

### ISSUE THREAD

**Issue by phansch** [rust-lang/rust-clippy#3843]
After https://github.com/rust-lang/rust-clippy/pull/3824, it would be nice to continue adding documentation. Specifically, it would be awesome to have a page that explains some common lint writing tools:

* [x] Retrieving the type of an expression
* [ ] ~Retrieving all methods of a type~
* [x] Checking if a type implements a specific trait
* [x] Dealing with macros (`in_macro`, `in_external_macro`, `differing_macro_contexts`)
* [ ] Checking if a type defines a method or function

If someone wants to start this, it's also fine to just pick only one item from the list and create a new file in the `doc/` directory.

**Comment by ThibsG** [comment]
It remains, at least, how to explain:
- [ ] Retrieving all methods of a type

**Comment by phansch** [comment]
> It remains, at least, how to explain:
> 
>     * [ ]  Retrieving all methods of a type

In retrospect, I think that's a rather useless example. It would make more sense to explain how to check if a type defines a specific method or not. I've updated the issue for that.

**Comment by ThibsG** [comment]
Yes that makes sense. I will add this in a future PR.
