### ISSUE TITLE
Prefer `iterator.copied()` over `iterator.cloned()` where possible

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust-clippy#3870]
... and adjust our current `iterator.map(|x| *x)` lint to suggest `.copied()`

Requires https://github.com/rust-lang/rust/issues/57127 to get merged first though.

**Comment by smklein** [comment]
Hey Oli! Is this as simple as the following?

- Find all cases of `iterator.cloned()`, for `Iterator <Item = T>`,
- If `T : Copy`, take the span of `iterator.cloned()` and recommend updating that?

Are there cases where that wouldn't work?

I made the following as a test case: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=28a932471d654ec882306df36e5a7abc

(I'm interested in digging into this more if there is still interest!)

**Comment by flip1995** [comment]
Yes that should be exactly as simple as you described. This lint should fit well in the `methods` module.
