### ISSUE TITLE
use of round/floor/ceil on known integer value

### ISSUE THREAD

**Issue by llogiq** [rust-lang/rust-clippy#39]
E.g. ceil(1f32)

**Comment by Manishearth** [comment]
FWIW I don't think we'll have too many issues with constants -- I think programmers will be smart enough to not do stuff like this (but footguns like the other issues on this repo would be harder to catch manually)

Still, I don't mind having stuff like this here.

**Comment by llogiq** [comment]
I just nicked it from FindBugs. And yes, I don't think it should be high priority.

**Comment by ThomasdenH** [comment]
What should this lint catch? For example, using `std::f64::consts::PI.ceil()` would be optimized by the compiler anyway and has more explanatory value than `4`.

**Comment by alekhrycaiko** [comment]
Happy to jump in and take this :balloon:

**Comment by alekhrycaiko** [comment]
From what I can see, `ceil(1f32)` is not a valid way of calling ceil currently.

`ceil()` exists on float types (e.g. `f64` and `f32`) and would be caught by the Rust compiler if called on an int type. I'm not certain there's actually anything to catch here for reasons also brought up by @ThomasdenH 

Is there some more specific requirements for what this lint should catch @llogiq 

If not, perhaps this issue be closed?

**Comment by ThomasdenH** [comment]
Perhaps this lint is just for cases where the operation doesn't change the value?

**Comment by Manishearth** [comment]
> From what I can see, ceil(1f32) is not a valid way of calling ceil currently.

Yes, that was pseudocode

This lint is about calling `ceil` on a _known_ integer float value. So something like `1f32.ceil()`. But as I mentioned earlier this seems pretty hard to do by accident.

**Comment by botahamec** [comment]
@rustbot claim
I've been looking at this for practice, and I'd like to try it. I got it to work with literals. I'm gonna try to see it I can figure out how to make it work with constants and if variables are possible.

**Comment by xFrednet** [comment]
For constants you can take a look at [`clippy_utils::consts`](https://doc.rust-lang.org/nightly/nightly-rustc/clippy_utils/consts/index.html). However, I could see some use cases for calling these functions on constant values. Therefore, I think it might be better to only lint literals in code :upside_down_face:

**Comment by botahamec** [comment]
> However, I could see some use cases for calling these functions on constant values. Therefore, I think it might be better to only lint literals in code 🙃

@xFrednet I think that's good point. I'll start working on a PR today
