### ISSUE TITLE
Cleanup: Use `declare_lint_pass!` and `impl_lint_pass!`

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust-clippy#3917]
Introduced in https://github.com/rust-lang/rust/pull/59669, macros `declare_lint_pass!` and `impl_lint_pass!` are added to `librustc/lint/mod.rs`. These should help to remove some boilerplate from clippy as well.

cc @oli-obk

**Comment by kraai** [comment]
I'm going to try to do this.  I don't think these macros are available on nightly yet, so I'm building a new toolchain that I hope will include them.

**Comment by Centril** [comment]
The PR was merged and is in upstream :)

**Comment by oli-obk** [comment]
@kraai there's no need to build a toolchain. You can download even master toolchains via rustup by using our https://github.com/rust-lang/rust-clippy/blob/master/setup-toolchain.sh script

**Comment by kraai** [comment]
@oli-obk Thanks!  I'm trying it now.

**Comment by kraai** [comment]
I tried using `declare_lint_pass!` for `approx_const` but it triggered `lint_without_lint_pass`.  8386ad2b7ae0b9066f32df683bab2cfbb997b598 contains the changes I tried.  Is the change wrong or does `lint_without_lint_pass` need to be updated?

**Comment by flip1995** [comment]
It could be the case, that the `lint_withou_lint_pass` lint is unable to detect `LintPass`es declared by a macro. I will look into this tomorrow evening and get back to you!

**Comment by kraai** [comment]
@flip1995 Thanks!

**Comment by flip1995** [comment]
Yeah the lint was broken. You can find the fix here: flip1995/rust-clippy@87ab2e6c3d92c61d6a00c37feb4de1c4cab2a799

**Comment by kraai** [comment]
@flip1995 Thanks!

**Comment by kraai** [comment]
I've started working on this at https://github.com/kraai/rust-clippy/tree/declare_lint_pass.

**Comment by flip1995** [comment]
The current state of your branch looks good. Multiple PRs got merged yesterday/today and you should rebase on the master branch before making bigger changes.

**Comment by kraai** [comment]
When I modify `clippy_lints/src/double_comparison.rs` to use `declare_lint_pass!`, `cargo test` produces the following error:

```
error: this argument is passed by reference, but would be more efficient if passed by value
  --> clippy_lints/src/double_comparison.rs:38:20
   |
38 |     fn check_binop(&self, cx: &LateContext<'a, 'tcx>, op: BinOpKind, lhs: &'tcx Expr, rhs: &'tcx Expr, span: Span) {
   |                    ^^^^^ help: consider passing by value instead: `self`
   |
   = note: `-D clippy::trivially-copy-pass-by-ref` implied by `-D clippy::all`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#trivially_copy_pass_by_ref
```

Should I use `impl_lint_pass!` instead?  Is there a better way to fix this?
