### ISSUE TITLE
unnecessary structure name repetition in functions inside a method

### ISSUE THREAD

**Issue by LucianoBestia** [rust-lang/rust-clippy#3935]
clippy 0.0.212 (1b89724b 2019-01-15)

I have an impl block with one method "render".
Inside that method I have a function "on_click_code". I created it inside the method because it is a helper function private to that method. There is a parameter of type CardGrid.
Clippy warns "unnecessary structure name repetition clippy::use_self" .
But if I change CardGrid to Self, the code does not compile.

impl Render for CardGrid {
    fn render<'a, 'bump>(&'a self, bump: &'bump Bump) -> Node<'bump> where 'a: 'bump,{
       ...
       fn on_click_code(card_grid: &mut **CardGrid**, this_click_card_index: usize) {
          ...

The complete code is here:
https://github.com/LucianoBestia/mem2

**Comment by LucianoBestia** [comment]
Sorry, I think I found this is a duplicate of:
https://github.com/rust-lang/rust-clippy/pull/3869#issue-260000212

**Comment by flip1995** [comment]
Yes this should be fixed. Which Clippy version do you use?
```
cargo clippy --version
```
