### ISSUE TITLE
Declaring minimum Rust version for suggested replacements

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/rust-clippy#3941]
I'd love to have clippy's suggested replacements tagged with minimum Rust versions, and then a consistent way to specify a minimum Rust version supported, which should automatically disable clippy lints whose proposed replacement would not compile with that minimum Rust version.

Please note that this feature request is *not* asking for such version tags on every lint, just for the infrastructure to provide such tags.

Also, while this might potentially want to integrate with a future feature that allows specifying a minimum Rust version in `Cargo.toml`, I would nonetheless propose that this infrastructure not depend on specifying such a feature, and that clippy provide a simple way to specify that minimum version solely for clippy.

**Comment by Manishearth** [comment]
I like this idea. One way to do this would be via a crate level
`#[clippy::rust_version = foo]` directive and have clippy's `span_lint`
utilities check against that (we already have a custom function for
emitting lints since we also link to their docs).

**Comment by camsteffen** [comment]
We now have `clippy::msrv`.
