### ISSUE TITLE
Lint against #[cfg(linux)] → #[cfg(unix)]

### ISSUE THREAD

**Issue by oberien** [rust-lang/rust-clippy#3949]
There have been several instances where I wrote `#[cfg(linux)]` to feature-gate something to linux. This is wrong and will never be evaluated to true. Instead `#[cfg(unix)]` must be used.

**Comment by JamesHinshelwood** [comment]
Another possibility could be that `#[cfg(target_os="linux")]` was intended. I guess we could suggest both?

**Comment by euclio** [comment]
I also think it would be useful to lint `#![cfg(macos)]` -> `#![cfg(target_os="macos")]`.
