### ISSUE TITLE
Consider renaming clippy::all to clippy::default (or alias it)

### ISSUE THREAD

**Issue by taiki-e** [rust-lang/rust-clippy#3991]
`clippy::all` means the default warning set, but `clippy::default` is a more easily understood name.

**Comment by Manishearth** [comment]
This has been discussed at length in https://github.com/rust-lang/rust-clippy/issues/2964 already, the consensus was that what is exposed in `all` is the "stable" set of lints we wish to expose as our actual interface, the set of lints we signal support for.

**Comment by taiki-e** [comment]
Oh, I missed that, sorry.
