### ISSUE TITLE
Import mitsuhiko's "Did you mean to use a state machine?" lint

### ISSUE THREAD

**Issue by pythonesque** [rust-lang/rust-clippy#4]
Because man that thing is useful.

**Comment by Areredify** [comment]
Can anyone provide context for this? I can't really find anything about that lint on the internet or in mitsuhiko's github

**Comment by mati865** [comment]
https://github.com/mitsuhiko/rust-excessive-bools-lint
There are 2 lints inside: for excessive amount of booleans in structs and another for excessive amount of booleans in functions.

**Comment by Areredify** [comment]
Hmm, what about licensing? If we port it, do we have to include it's license?

**Comment by mati865** [comment]
> Hmm, what about licensing? If we port it, do we have to include it's license?

I'll defer that question to somebody who understands licensing.

**Comment by flip1995** [comment]
We would have to rewrite it, without looking at the source code. Or we'd have to include the copyright notice of the project. Or mitsuhiko surrenders his copyright to us (the Clippy project) and we can reimplement it here in Clippy.

**Comment by Areredify** [comment]
Ok, I'll rewrite it without looking at the source code then
