### ISSUE TITLE
Warn for non-scalar const values

### ISSUE THREAD

**Issue by jdm** [rust-lang/rust-clippy#400]
https://github.com/servo/servo/pull/8086#issuecomment-149347157

This seems like an easy thing to mess up.

**Comment by Manishearth** [comment]
Perhaps for sufficiently large arrays, at least (if not for all arrays)

**Comment by Manishearth** [comment]
To do this, you'll need to add a new lint (Somewhere in https://github.com/Manishearth/rust-clippy/blob/master/src/misc.rs), with a [`check_item`](http://manishearth.github.io/rust-internals-docs/rustc/lint/trait.LateLintPass.html#method.check_item), that checks if the type (via [this](http://manishearth.github.io/rust-internals-docs/rustc/middle/ty/struct.ctxt.html#method.expr_ty)) is a `TyArray` with large size (http://manishearth.github.io/rust-internals-docs/rustc/middle/ty/enum.TypeVariants.html).

**Comment by llogiq** [comment]
We have something similar in [src/loops.rs, line 320](https://github.com/Manishearth/rust-clippy/blob/master/src/loops.rs#L320).
