### ISSUE TITLE
[lint request] mul_add

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust-clippy#4001]
Floating-point code of the form `a * b + c` can be better optimized when written as `a.mul_add(b, c)`, but this might change its result because instead of first computing `a * b`, rounding that, and then adding `c` to it, and rounding that, `a.mul_add(b, c)` computes `a * b + c` with infinite precision, and only rounds the end result.

I think it makes sense to recommend people by default that, if they don't care about their result being computed with higher-precission (and their results changing), they should prefer to use `a.mul_add(b, c)` instead of `a * b + c` (otherwise they can ignore the lint).

**Comment by oli-obk** [comment]
I think it's fine for a perf lint to change corner case semantics slightly. If the change is truly undesired, the lint can be allowed and a comment placed as to why the change is not desirable at the given location.

**Comment by EthanTheMaster** [comment]
I would like to make this lint. This seems like a cool first lint to make.

**Comment by rye** [comment]
I think this was closed by #4602?
