### ISSUE TITLE
warning: redundant closure found without filename and line info

### ISSUE THREAD

**Issue by Matrix-Zhang** [rust-lang/rust-clippy#4052]
![图片](https://user-images.githubusercontent.com/1751829/57010944-cf61c800-6c31-11e9-9cbd-8b4057dbbf76.png)

**Comment by flip1995** [comment]
Can you give a short code example or a repository where this occurs?

**Comment by Matrix-Zhang** [comment]
sorry, it's my company's private project, i can't....

**Comment by Manishearth** [comment]
Could you see if you can reduce the test case? We can't really debug this as is.

**Comment by matthiaskrgr** [comment]
Maybe it's related to macros?
I have seen a similar finding in mdbook where the source location provided would point to `<::pretty_assertions::assert_eq macros>:6:6`

**Comment by flip1995** [comment]
These issues are most of the time related to (proc-)macros (Something, which produces the `DUMMY_SP`). But if we have to guess if it is a proc-macro, an internal macro (in the same file) or an external macro, we can't really debug this.
