### ISSUE TITLE
Clippy attributes have no effect on struct fields

### ISSUE THREAD

**Issue by spease** [rust-lang/rust-clippy#4075]
Example:

```use failure::Error;

struct MyTest {
    a: &'static [u64],
}

fn main() -> Result<(), Error> {
    let b = MyTest {
        #[allow(clippy::unreadable_literal)]
        a: &[1234567890],
    };

    Ok(())
}
```

The #[allow] directive must be placed on the variable assignment to have an effect - where it is now does not seem to cover the field value.

**Comment by Manishearth** [comment]
This is functionality from the compiler itself, please file an issue there.
