### ISSUE TITLE
Suggest `resize` rather when pushing same item to vec

### ISSUE THREAD

**Issue by pickfire** [rust-lang/rust-clippy#4078]
Example in https://github.com/Gymmasssorla/finshir/blob/eae5d0c6761f5558c8ed33ef098d8bd13a07e64f/src/testing/helpers.rs#L55-L61

When pushing the same item to vec.

```rust
fn gen_portions() -> Vec<Vec<u8>> {
    let mut spaces = Vec::with_capacity(EMPTY_SPACES_COUNT);
    for _ in 0..EMPTY_SPACES_COUNT {
        spaces.push(vec![b' ']);
    }
    spaces
}
```

Could be.

```rust
fn gen_portions() -> Vec<Vec<u8>> {
    let mut spaces = Vec::with_capacity(EMPTY_SPACES_COUNT);
    spaces.resize(EMPTY_SPACES_COUNT, vec![b' ']);
    spaces
}
```

Maybe we could even use `vec![b''].repeat(EMPTY_SPACES_COUNT)` after stabilization of`repeat_generic_size`? https://github.com/rust-lang/rust/issues/48784

**Comment by giraffate** [comment]
Was this attached PR https://github.com/rust-lang/rust-clippy/pull/4647 closed just because the conflict was not resolved? If so, and if no one is interested, can I take over?

**Comment by pickfire** [comment]
@giraffate I believe no one is working on this, sure please go ahead.

**Comment by flip1995** [comment]
@giraffate All issued marked with [`S-inactive-closed`](https://github.com/rust-lang/rust-clippy/pulls?q=is%3Apr+is%3Aclosed+label%3AS-inactive-closed) are "free for all" and can be picked up and completed anytime.
