### ISSUE TITLE
'extern location for serde does not exist' error on CI

### ISSUE THREAD

**Issue by phansch** [rust-lang/rust-clippy#4108]
For some reason, some of our Travis CI builds are failing with this error since today:

```
error: extern location for serde does not exist: target/debug/deps/libserde-61a62cbc4921f441.rmeta

error: aborting due to previous error
```
https://travis-ci.com/rust-lang/rust-clippy/jobs/201008591#L882

Clippy is building just fine, it's two tests depending on serde that are failing.

cc #4107, #4100

**Comment by phansch** [comment]
Notably this didn't happen in the beta backport PR: https://github.com/rust-lang/rust-clippy/pull/4104

**Comment by flip1995** [comment]
We could test in one of the PRs if it also occurs with the current nightly (Clippy should be buildable with it ATM). If that's the case the fault is with the master toolchain.

**Comment by oli-obk** [comment]
it's in nightly now

**Comment by oli-obk** [comment]
I guess https://github.com/rust-lang/rust/pull/60190 looks *very* much like the cause

**Comment by mikerite** [comment]
Can this issue be closed? It looks like the issue was resolved.
