### ISSUE TITLE
Error during Writing New Lint for Clippy 

### ISSUE THREAD

**Issue by saarshah** [rust-lang/rust-clippy#4127]
I am following your help to write a new ling foo_functions.rs . Although, you did’t mentioned, but i have added following code at top of my foo_functions.rs, otherwise my file is showing errors.

use syntax::visit::FnKind;
use syntax::ast::FnDecl;
use syntax::source_map::Span;
use syntax::ast::NodeId;
use crate::utils::span_help_and_lint;
When i run cargo test in my directory c:\master_clippy, then i faced this error .

52 |             ident.name == "foo"
   |                           ^^^^^ expected struct `syntax_pos::Symbol`, found reference
   |
   = note: expected type `syntax_pos::Symbol`
              found type `&'static str`
Whats going wrong ?

**Comment by oli-obk** [comment]
You need to use `ident.name.as_str()`, since names aren't strings, but `Symbol`s. Have a look at the docs of `Symbol` for more details: https://doc.rust-lang.org/nightly/nightly-rustc/syntax/symbol/struct.Symbol.html
