### ISSUE TITLE
FN needless_return: "return" at end of void-function

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-clippy#4181]
If we have a function that does not return a type and has `return` as last statement, we could suggest that that return could be omitted:
````rust
pub fn a() {
	println!("blurb");
	return; // unneeded
}

pub fn b() {
	println!("blarb");
	return // unneeded
}
````
=>

````rust
pub fn a() {
	println!("blurb");
}

pub fn b() {
	println!("blarb");
}
````

**Comment by phansch** [comment]
I guess this could be part of [`needless_return`](https://rust-lang.github.io/rust-clippy/master/index.html#needless_return)?

**Comment by matthiaskrgr** [comment]
yeah, that's why I put it in the title :p
