### ISSUE TITLE
Error return style

### ISSUE THREAD

**Issue by Byter09** [rust-lang/rust-clippy#4212]
Hello :)
I would like to suggest a new style-related lint.

If a function returns a `Result<T, E>`, there's two ways to return an error:
- `Err(E)?`
- `return Err(E)`

As far as I can see there's no lint for this and I'm sure some people prefer either way. So enforcing it in a project to keep code consistent would help immensely.

**Comment by oli-obk** [comment]
`Err(E)?` :scream: 	

I think we can just create a lint that suggests changing `Err(E)?` to `return Err(E)` or `return Err(e.into())` depending on whether adjustments are needed.

**Comment by jfrikker** [comment]
Hi! This is my first time contributing to the project, and I'd like to work on this issue if it's all right. I should have something up in the next couple of days.

**Comment by flip1995** [comment]
Thanks! You should have a look at https://github.com/rust-lang/rust-clippy/blob/master/doc/adding_lints.md. If you have any questions, just ask here or open a WIP PR.

**Comment by jfrikker** [comment]
I've opened a PR here: https://github.com/rust-lang/rust-clippy/pull/4222

I'd appreciate any feedback you have. I'm a little worried that it's tied too closely to how the `?` operator is de-sugared, but I'm not sure how else to do it.

**Comment by glts** [comment]
Hello, I wonder if there has been a wider discussion of this somewhere?

I’ve been seeing the `Err(E)?` notation in some widely used crates, and have adopted this as a Rust idiom in my own code.

**Comment by glts** [comment]
Never mind, am unadopting it now.
