### ISSUE TITLE
Suggested Lint: Uncalled pub items

### ISSUE THREAD

**Issue by kentfredric** [rust-lang/rust-clippy#4237]
One downside of using "pub" items is you no longer know if anything is using them ( as opposed to private/pub(crate) where the compiler will tell you if its unused or not)

While of course, removing a pub item after its shipped in a release would be bad, what would also be bad is accidentally creating a pub item that you didn't actually need for anything, and not noticing until you shipped.

As mitigation, it might be useful to have a lint that identifies `pub` items that aren't invoked from either `examples` or `tests` in the same project, so that, in order to appease this lint, all public items (and thus, all elements of your public API) must have *some* kind of mechanism to test they function, or *some* kind of mechanism to demonstrate how a consumer uses them.

(And the presence of these mechanisms ensures items that become intentional API, stay intentional API).

Ideally this would also have some transitive properties, eg: enum discriminants that are : 
a: never used via some function that ultimately gets called from a public context
and b: not directly used in a public context, would be flagged as "possibly unused", prompting to either remove them, or write a test/example that uses them.

While I admit this sounds a bit like "coverage" testing, this diverges from coverage testing in that it doesn't care about branches and soforth, or internal lines being fired, it only cares about presenting a coherent external API and discourages making items "pub" that don't need to be.

You should see some vague similarities between this request and #3907, however, implementation would be by necessity, more complicated, as simply making the advice "use `<lesser-visibility>` instead of `<visibility>`" would be useless, as much of the time, using `<lesser-visibility>` would then transform the `pub` code into `unused` code.

Instead, the advice would be "Consider deprecating/removing this in a future version, or write code that uses it outside the crate to guarantee its future"

**Comment by Manishearth** [comment]
This is a global analysis, which we don't really have the capability of doing, sadly. 

This sounds easier to integrate as an additional check into https://github.com/rust-dev-tools/rust-semverver but that's not quite maintained at the moment

**Comment by kentfredric** [comment]
My quick reading of semverver says its probably also the wrong place for it, the goal here is not to compare `<vprev>` with `<vnext>`, merely ensure that the current logical unit has the right stuff in place to enforce coherence.

Changes one makes based on this "lint" would possibly trip semverver, but in my current usecase, semverver can't do anything for me (I'm still working on getting 0.1.0 into a state I'm comfortable with shipping, as I'm proactively trying to avoid future cases of API change)

**Comment by Manishearth** [comment]
Right, but it has all of the information necessary to calculate this. Clippy ... doesn't. It's an additional check you can build into it, but it's not really possible to build into Clippy.

You could alternatively use save-analysis and build your own tool for this.

Clippy can't do global analyses.
