### ISSUE TITLE
Clippy not available on rustup for any recent Tier 2 platforms

### ISSUE THREAD

**Issue by asomers** [rust-lang/rust-clippy#4267]
Recent nightly builds are missing the clippy component (and several others) for all Tier 2 architectures. They've been missing since at least july-3-2019, and probably earlier.
https://rust-lang.github.io/rustup-components-history/x86_64-unknown-freebsd.html

**Comment by Manishearth** [comment]
cc @pietroalbini any idea where the build logs for tools for tier two machines are? I can't find `clippy` in any of the Azure build logs for those platforms.

**Comment by mati865** [comment]
I'll instigate it.

**Comment by mati865** [comment]
Let's move to https://github.com/rust-lang/rust/issues/62558

**Comment by phansch** [comment]
Going to close this one as the discussion is happening in https://github.com/rust-lang/rust/issues/62558 and it can't be fixed on the Clippy side.
