### ISSUE TITLE
New lint: taking a double reference and immediately passing it to a function that takes a single reference

### ISSUE THREAD

**Issue by lopopolo** [rust-lang/rust-clippy#4271]
I often run into this when refactoring and dealing with `Rc`. When transitioning an argument from consumed to a reference, I often forget to change function calls that take a reference. The code still compiles, but upon inspection later, the double reference causes confusion.

**Comment by mikerite** [comment]
Doesn't the [needless borrow](https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow) lint cover this?

**Comment by lopopolo** [comment]
The following program passes the clippy linter in pedantic mode with no errors.

```
▶ rustc --version --verbose
rustc 1.38.0-nightly (6e310f2ab 2019-07-07)
binary: rustc
commit-hash: 6e310f2abae97323ca1d5469657b83aa1a9407e0
commit-date: 2019-07-07
host: x86_64-apple-darwin
release: 1.38.0-nightly
LLVM version: 8.0
[18:42] [~/Desktop/boom] [100%] ⚡
▶ cargo clippy -- -V
clippy 0.0.212 (316da7eb 2019-07-07)
[18:42] [~/Desktop/boom] [100%] ⚡
▶ cargo clippy
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
```

```
#![deny(clippy::all, clippy::pedantic)]

use std::rc::Rc;

fn dependent<T>(this: &Rc<T>) {
    let _ = this;
}

fn perform<T>(this: &Rc<T>) {
    dependent(&this);
}

fn main() {
    let rc = Rc::new(5);
    perform(&rc);
}
```

**Comment by mikerite** [comment]
The lint is in nursery so you need to enable it.
```
#![warn(clippy::needless_borrow)]

use std::rc::Rc;

fn dependent<T>(this: &Rc<T>) {
    let _ = this;
}

fn perform<T>(this: &Rc<T>) {
    dependent(&this);
}

fn main() {
    let rc = Rc::new(5);
    perform(&rc);
}
```
Generates this
```
    Checking playground v0.0.1 (/playground)
warning: this expression borrows a reference that is immediately dereferenced by the compiler
  --> src/main.rs:10:15
   |
10 |     dependent(&this);
   |               ^^^^^ help: change this to: `this`
   |
note: lint level defined here
  --> src/main.rs:1:9
   |
1  | #![warn(clippy::needless_borrow)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

    Finished dev [unoptimized + debuginfo] target(s) in 0.43s
```

[Playground Link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5066d53417bfea57fa38f5dc5897d1c1)

**Comment by lopopolo** [comment]
@mikerite, thanks for helping me to see how to enable this lint. Now that you mention that the lint is in nursery, I understand why it was not detecting there error.

I did not see the nursery tag in the docs and even if I had I don’t think I would have known that I had to explicitly enable the lint.

Thanks for your help. I’ll close this issue. Happy weekend.
