### ISSUE TITLE
Cargo Clippy failed with SIGABRT and SIGSEGV Errors

### ISSUE THREAD

**Issue by saarshah** [rust-lang/rust-clippy#4279]
I have build my rust project successfully with latest update of rust. When I run `cargo clippy` it show these errors

> --cap-lints allow` (signal: 6, SIGABRT: process abort signal)

> --cap-lints allow --cfg memchr_runtime_simd --cfg memchr_runtime_sse2 --cfg memchr_runtime_sse42 --cfg memchr_runtime_avx` (signal: 6, SIGABRT: process abort signal)

> --cap-lints allow --cfg memchr_runtime_simd --cfg memchr_runtime_sse2 --cfg memchr_runtime_sse42 --cfg memchr_runtime_avx` (signal: 11, SIGSEGV: invalid memory reference

my system info is as follow;
> rustc --version : rustc 1.36.0 (a53f9df32 2019-07-03)
> cargo --version : cargo 1.36.0 (c4fcfb725 2019-05-15)
> cargo clippy --version : clippy 0.0.212 (082cfa7 2019-06-07)
> Windows 10 Pro for WSL ; OS Build 18362.239

**Comment by flip1995** [comment]
Does this happen also when you run `cargo check`?

Can you share the `Cargo.toml` or even better your code / an example repo?

**Comment by saarshah** [comment]
actually i build the project then run clippy cargo.. when i again run clippy without building, it has no problem.. i think , may be its due to my C drive not enough memory... or something else... anyhow, now its running.. thanks

**Comment by flip1995** [comment]
Thanks for reporting back.
Feel free to reopen, when this happens again.
