### ISSUE TITLE
`deref_addrof` checks across external macro boundary

### ISSUE THREAD

**Issue by uHOOCCOOHu** [rust-lang/rust-clippy#4289]
The code below suggests `[$(($x, stringify!(x)),)*]` to change the macro, even though it is from another crate.

[Playground (one crate)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5abfb2703d21a714ed40568b5d39428a)
```rust
macro_rules! m {
    ($($x:tt),*) => { &[$(($x, stringify!(x)),)*] };
}

pub fn f() -> [(i32, &'static str); 3] {
    *m![1, 2, 3]
}
```

Well, I don't think it should check across macro boundary no matter where it is from.

**Comment by flip1995** [comment]
Just needs a macro check.
