### ISSUE TITLE
How to resolve extra_unused_lifetimes?

### ISSUE THREAD

**Issue by sunng87** [rust-lang/rust-clippy#4291]
clippy -V: `clippy 0.0.212 (b029042 2019-07-12)`

I'm getting clippy warnings for unused lifetime in function definition like:

```
warning: this lifetime isn't used in the function definition
  --> src/helpers/helper_with.rs:13:13
   |
13 |     fn call<'_reg: '_rc, '_rc>(
   |             ^^^^^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#extra_unused_lifetimes
```

The function is defined in [a trait](https://github.com/sunng87/handlebars-rust/blob/master/src/helpers/mod.rs#L88), and here in [it's implementation](https://github.com/sunng87/handlebars-rust/blob/master/src/helpers/helper_lookup.rs#L15) some unused lifetimes in argument types were omitted and compiler think it's ok. However, removing these will cause compilation error that compiler finds the definition was incompatible with trait.

Also by prefixing the unused lifetimes with `_` doesn't work for clippy. 

So is there a recommended solution for this case other than add all lifetime specifiers to argument types?

**Comment by flip1995** [comment]
I can't reproduce this on my machine. Also your link to the implementation isn't the function in the warning message.

Have you changed anything else? Can you push a reproducer in a separate branch/fork to the repo and link it here?

**Comment by sunng87** [comment]
Sorry, I fixed by adding lifetime to those types, which I don't think is a perfect fix.  You can checkout tag 2.0.1 and reproduce.

The trait at 2.0.1:
https://github.com/sunng87/handlebars-rust/blob/2.0.1/src/helpers/mod.rs#L88

The impl:
https://github.com/sunng87/handlebars-rust/blob/2.0.1/src/helpers/helper_lookup.rs

**Comment by flip1995** [comment]
Quite minimal reproducer:
```rust
#[derive(Debug)]
pub struct Foo<'a>(&'a std::marker::PhantomData<u8>);

#[derive(Debug)]
pub struct Bar<'a: 'b, 'b>(Foo<'a>, &'b std::marker::PhantomData<u8>);

trait LT {
    fn test<'a: 'b, 'b>(foo: &Foo<'a>, bar: &Bar<'a, 'b>);
}

pub struct Baz;

impl LT for Baz {
    fn test<'a: 'b, 'b>(_foo: &Foo, _bar: &Bar) {
        
    }
}
```
[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=b54fd420bb0e9cd85faafd68436d8c85)

We shouldn't lint trait implementations
