### ISSUE TITLE
Should `wrong_self_convention` apply to `self: Box<Self>`,  `self: Rc<Self>` and `self: Arc<Self>`?

### ISSUE THREAD

**Issue by taiki-e** [rust-lang/rust-clippy#4293]
The current `wrong_self_convention` warns `self: Box<Self>`,  `self: Rc<Self>` and `self: Arc<Self>`, but they take `self` argument and consume `self`, so I think it makes sense to not warn them.

```rust
#![warn(clippy::wrong_self_convention)]

pub struct Foo;

pub struct Bar(Foo);

impl Bar {
    pub fn into_inner(self: Box<Self>) -> Foo { //~ WARNIG methods called `into_*` usually take self by value; consider choosing a less ambiguous name
        self.0
    }
}
```

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=70e741dc4e3ebbf298172045c29a88b6)

**Comment by mikerite** [comment]
Here is an example from the standard library:

`pub fn into_vec(self: Box<[T]>) -> Vec<T>`
https://doc.rust-lang.org/std/primitive.slice.html#method.into_vec
