### ISSUE TITLE
Probably Typo in Pedantic (`cast_possible_truncation`) Lint

### ISSUE THREAD

**Issue by izik1** [rust-lang/rust-clippy#4317]
https://rust-lang.github.io/rust-clippy/master/index.html#cast_possible_truncation
> Checks *for on* casts between numerical types that may truncate large values. This is expected behavior, so the cast is Allow by default.

emphasis added by me

Gotta be pedantic about typos in pedantic lints, right?

**Comment by phansch** [comment]
Yup, that's a typo, thanks! Would you like to open a PR? The text to change can be found here: https://github.com/rust-lang/rust-clippy/blob/d1b4fc9853d80b3953dd5f2bae9d5d70ef7665ab/clippy_lints/src/types.rs#L693
