### ISSUE TITLE
[Doc] Ignore lines starting with # in the example code

### ISSUE THREAD

**Issue by flip1995** [rust-lang/rust-clippy#4353]
[`rustdoc`](https://doc.rust-lang.org/rustdoc/documentation-tests.html#hiding-portions-of-the-example) hides lines starting with `#`.

The Clippy documentation still shows these lines:
https://rust-lang.github.io/rust-clippy/master/index.html#boxed_local

It would be great if we could detect those lines and also hide them in the Clippy documentation.

**Comment by phansch** [comment]
This would have to happen somewhere in this loop:

https://github.com/rust-lang/rust-clippy/blob/7bd7d40789d510eba782fdf86c4a2fdd90084568/util/export.py#L29

`lint.doc` contains the whole doc comment in the lines before `pub LINT_NAME`.

We will have to track if we're inside a code block within that loop and then skip the lines starting with `\/\/\/(\s+)#`.

**Comment by flip1995** [comment]
I think we only have code blocks in the `Example` section (?). So we could limit this check to `last_section == "Example"`.
