### ISSUE TITLE
Missing "could be written as"

### ISSUE THREAD

**Issue by BO41** [rust-lang/rust-clippy#4405]
There are some lints missing a "could be written as".
If I am on a clippy page, like [manual_memcpy](https://rust-lang.github.io/rust-clippy/master/index.html#manual_memcpy), I really like to not just see what is wrong in the example but also see how to fix the example.

Is there an interest in adding some more "could be written as" like in #4404 ?

I would be happy to fill some PRs for this :)

**Comment by phansch** [comment]
Yes, that would be really nice to have! In fact, it's already part of the 'Adding Lints' docs [here](https://github.com/rust-lang/rust-clippy/blob/master/doc/adding_lints.md#documentation), but could probably be highlighted in a sentence below, too.
