### ISSUE TITLE
Cannot install on aarch64 OR installation documentation needs updating

### ISSUE THREAD

**Issue by martinellison** [rust-lang/rust-clippy#4424]
```
rustup component add clippy    
error: component 'clippy' for target 'aarch64-unknown-linux-gnu' is unavailable for download for channel 'stable'
```

*edit: if `cargo install clippy` is the way to go, you might want to  update your documentation to say so.*

**Comment by mati865** [comment]
Duplicate of https://github.com/rust-lang/rust-clippy/issues/4267

**Comment by phansch** [comment]
Thanks for the report! I'm going to close this issue, as the discussion of the fix is happening in https://github.com/rust-lang/rust/issues/62558 and it can't be fixed on the Clippy side.
