### ISSUE TITLE
Wrong suggestion in search_is_some lint

### ISSUE THREAD

**Issue by flip1995** [rust-lang/rust-clippy#4453]
It's pretty much the same as #4033. The closure argument of `any` needs one dereference less than the closure argument of `find`. 

```rust
fn main() {
    let vec = vec![1];
    let _ = vec.iter().find(|x| **x == 0).is_some();
    // let _ = vec.iter().any(|x| **x == 0); // <- this is suggested
    let _ = vec.iter().any(|x| *x == 0); // <- this should be suggested
}
``` 

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6a1ef5d4137c996d3ea4c7e4d7cf86f0)

_Originally posted by @BO41 in https://github.com/rust-lang/rust-clippy/pull/4436#discussion_r317351872_

**Comment by flip1995** [comment]
This suggestion could also be made auto applicable.

**Comment by YpeKingma** [comment]
This code still gives the wrong suggestion when clippied:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=42845deb52e66a5fb4e689782d2cd5f0

Shall I open another issue for this?
