### ISSUE TITLE
 lint emitting updating

### ISSUE THREAD

**Issue by BO41** [rust-lang/rust-clippy#4456]
if you don't run `cargo uitest` (and maybe `cargo test`) before `tests/ui/update-all-references.sh` the script won't do anything.

It would be nice if this could be made more clear. Got me really confused why `cargo run` and `cargo build` didn't trigger a change for the script.

**Comment by flip1995** [comment]
https://github.com/rust-lang/rust-clippy/blob/master/doc/adding_lints.md#testing

This chapter would need to be updated. I think adding a note to the sentence mentioning the script would be enough.
