### ISSUE TITLE
New lint: mem::replace(mem::uninitialized) is dangerous

### ISSUE THREAD

**Issue by Shnatsel** [rust-lang/rust-clippy#4485]
When working with a `&mut T` sometimes you need to turn it into `T`. This can be achieved using `mem::replace()`:

```rust
fn myfunc (v: &mut Vec<i32>) {
    let taken_v = std::mem::replace(&mut v, mem::uninitialized());
    let new_v = do_stuff(taken_v);
    let uninit = std::mem::replace(&mut v, new_v);
    std::mem::forget(uninit);
}
```
People generally assume that this is safe because the uninitialized memory is never observed. However, this code will drop uninitialized memory if `do_stuff()` panics, because mem::forget will never be reached. This is undefined behavior and potentially a security vulnerability. Example of real-world code with this issue: https://github.com/sile/libflate/issues/35

This can be fixed by using the `take_mut` crate as described [here](https://docs.rs/take_mut/0.2.2/take_mut/). AFAIK there is currently no stdlib solution.

Using `mem::zeroed()` instead of `mem::uninitialized()` is also not valid if the target type is not valid for zeroed bit pattern or in case the type is generic.

cc @RalfJung

**Comment by llogiq** [comment]
`mem::uninitialized`is going to be deprecated, so will we need that lint then, too?

**Comment by Shnatsel** [comment]
There is no migration path from this to a safe usage of MaybeUninit. The only thing compiler warnings can do is prod people to convert this to MaybeUninit followed by `.assume_init()` immediately, which is just as unsafe as the current pattern. So pointing out the unsoundness and suggesting the proper solution is still valuable.

Also, the case with mem::zeroed() and a generic parameter still applies even without use of uninitialized memory.

**Comment by RalfJung** [comment]
> AFAIK there is currently no stdlib solution.

True, but it has been proposed to basically add `take_mut`: https://github.com/rust-lang/rfcs/pull/1736.
It was [rejected](https://github.com/rust-lang/rfcs/pull/1736#issuecomment-252771880) because it has to abort-on-panic and "having a function in core::mem abort the process seems too surprising to stabilize".
