### ISSUE TITLE
cast-lossless is too strict

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust-clippy#4528]
`cast-lossless` includes issuing a warning about what might happen *if* you change your code: `warning: casting u8 to i32 may become silently lossy if you later change the type`. Given that the cast is totally safe with the code as written, this seems like it should be a pedantic lint, rather than a default one.

**Comment by flip1995** [comment]
I agree. Especially because all the other "cast on number to another"-lints are allow-by-default.
