### ISSUE TITLE
Pin<&mut self> triggers "wrong_self_convention"

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang/rust-clippy#4546]
Clippy doesn't like it when we use `Pin` over the `Self` type:

__input__
```rust
pub fn as_mut(self: Pin<&mut Self>) -> Option<&mut Fut::Output>;
```
__output__
```
error: methods called `as_*` usually take self by reference or self by mutable reference; consider choosing a less ambiguous name

  --> src/maybe_done.rs:36:19

   |

36 |     pub fn as_mut(self: Pin<&mut Self>) -> Option<&mut Fut::Output> {

   |                   ^^^^

   |

   = note: `-D clippy::wrong-self-convention` implied by `-D clippy`

   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#wrong_self_convention
```

This seems like it might be related to https://github.com/rust-lang/rust-clippy/issues/4037 and https://github.com/rust-lang/rust-clippy/issues/3414. Though it's also possible this may be working exactly as intended, but I'm not sure.

**Comment by mikerite** [comment]
The lint should probably be changed.

Example from the standard library using similar naming/signature:
https://doc.rust-lang.org/std/option/enum.Option.html#method.as_pin_mut

This is related to issue #4293.

**Comment by yoshuawuyts** [comment]
Wanted to add that what I was doing here ended up not being a great API either way because it conflicts with the built-in Pin methods.

**Comment by Darksonn** [comment]
I just ran into this issue.
