### ISSUE TITLE
Using cargo clippy with -Z build-std produces warnings inside of libcore

### ISSUE THREAD

**Issue by alex** [rust-lang/rust-clippy#4563]
If you attempt to use `cargo clippy` with the new cargo support for building the standard libraries (obsoleting cargo-xbuild and xargo), clippy will emit tons of warnings inside of libcore.

Usage: `cargo clippy -Z build-std=core,alloc --target=<anything>`

You can see an example of this failing here: https://travis-ci.com/fishinabarrel/linux-kernel-module-rust/builds/128613174

**Comment by mati865** [comment]
Could you try using `cargo clippy-preview`? Probably you will also have to use `-Z unstable-options`.

**Comment by alex** [comment]
Yes, indeed with `clippy-preview` + `-Z unstable-options` this seems resolved.

**Comment by mati865** [comment]
It doesn't seem worth fixing then, soon `cargo clippy` will work just like `cargo clippy-preview` right now: https://github.com/rust-lang/cargo/pull/7382

**Comment by alex** [comment]
Agreed.
