### ISSUE TITLE
let_and_return conditional compilation

### ISSUE THREAD

**Issue by KyleSiefring** [rust-lang/rust-clippy#4564]
Clippy will complain if I have code like this

```
pub fn calculate(param: u32) -> u32 {
  #[cfg(feature = "check_output")]
  let ref_out = ref_impl(param);

  let fast_out = fast_impl(param);

  #[cfg(feature = "check_output")]
  assert_eq!(ref_out, fast_out);

  fast_out
}
```

Example in practice (shouldn't be needed): https://github.com/KyleSiefring/rav1e/commit/a671838f10efb3f9cbacfd8e255f4f1aab564052#diff-2ba4abd592a455913d1c28725320c39dR110

**Comment by llogiq** [comment]
Yes. Clippy unfortunately cannot see the conditionally compiled code. The `#[cfg]`s work at the syntax level, so there's nothing we can do about it.

In this case, you know better than clippy, so just mark the method with `#[allow(clippy::let_and_return)]`.
