### ISSUE TITLE
Clippy built from source does not run

### ISSUE THREAD

**Issue by martinellison** [rust-lang/rust-clippy#4573]
If I build clippy from source, I get the following error:

> ~/progs/rust-clippy/target/release/cargo-clippy 
> error: failed to run `rustc` to learn about target-specific information
> 
> Caused by:
>   process didn't exit successfully: `/home/martin/progs/rust-clippy/target/release/clippy-driver rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro` (exit code: 127)
> --- stderr
> /home/martin/progs/rust-clippy/target/release/clippy-driver: error while loading shared libraries: librustc_driver-4733601dfd4464fd.so: cannot open shared object file: No such file or directory

This is using branch `rust-clippy-157edad6205fdd6a4f5932fba2675c6190746358` -- is this the correct branch to build?

Please advise what I need to do to fix this. I just want a version of clippy that works.

**Comment by flip1995** [comment]
This should be solved by setting the `$LD_LIBRARY_PATH` on linux:

```
$ export LD_LIBRARY_PATH=$(rustc +<toolchain-you-compiled-clippy-with> --print sysroot)/lib:$LD_LIBRARY_PATH
```

or setting `%PATH%` on windows:

```
$ set PATH=%PATH%;C:\path\to\.rustup\toolchains\<toolchain-you-compiled-clippy-with>\bin
```

Where `<toolchain-you-compiled-clippy-with>` is probably `master` or `nightly`.

---

If you just want a version of Clippy that works, you can use a nightly toolchain with Clippy instead. You can find a nightly here: https://rust-lang.github.io/rustup-components-history/index.html

The current nightly has Clippy.

**Comment by martinellison** [comment]
@flip1995 "you can find a nightly here": not for aarch64 on Linux.

**Comment by flip1995** [comment]
Oh yeah, Clippy only supports Tier 1 platforms.

Did the `$LD_LIBRARY_PATH` thing work?
