### ISSUE TITLE
Reenable OSX travis builds

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust-clippy#4576]
In the recentmost rustup (https://github.com/rust-lang/rust-clippy/pull/4574) I marked OSX as an allowed failure on travis, due to https://github.com/rust-lang/cargo/pull/7429. Cargo is being updated in https://github.com/rust-lang/rust/pull/64774 , but I don't think we'll get access to that till the next nightly (it seems like `rustup-toolchain-install-master` uses fallback for tools.

We should reenable this in the next nightly.

**Comment by mati865** [comment]
https://github.com/rust-lang/rust/pull/64774 is included in `nightly-2019-09-26`.
