### ISSUE TITLE
Consider switching CI to Azure Pipelines

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust-clippy#4577]
rustc has moved to it, and it seems overall nicer. It supports all three OSes, and it also supports better pipelining. So, for example, one can build clippy first, and then parallelize the integration tests based on a single clippy build (instead of having ten integration test workers all build clippy). This should be faster, and we might benefit from the Rust org's azure builders, though we'd have to check with the infra team on that (@pietro?).

thoughts? @phansch @flip1995 @oli-obk @yaahc

**Comment by yaahc** [comment]
:+1: 

I know tracing is using azure and I've only heard positive things. I bet this is a win.

**Comment by phansch** [comment]
Seems like a good idea :+1: I can't come up with anything that our current setup has that Azure doesn't have.

Some things that are currently travis specific:

- [.github/deploy.sh](https://github.com/rust-lang/rust-clippy/blob/1366629262e20560f86fe986999dc52a168ee768/.github/deploy.sh) is using some `TRAVIS_` env variables
- [ci/base-tests.sh](https://github.com/rust-lang/rust-clippy/blob/1366629262e20560f86fe986999dc52a168ee768/ci/base-tests.sh) uses `TRAVIS_OS_NAME`
- We have two encrypted variables in the Travis config UI, which I don't know what they are used for
- Our bors setup needs to be updated as well, I believe

**Comment by flip1995** [comment]
Sounds good. Especially the "supports all three OSes" part, since we tried pretty often to use the travis windows build, without success. #3418 #4004 #4320 #4324 #3306 #3484 #3486 ... (way too often 😄)

> We have two encrypted variables in the Travis config UI, which I don't know what they are used for

This type of secret key is normally used for ssh deployment from travis. We're using them here:
https://github.com/rust-lang/rust-clippy/blob/1366629262e20560f86fe986999dc52a168ee768/.github/deploy.sh#L60-L65

**Comment by mati865** [comment]
Small Rust projects mostly use Github Actions now but I don't know if it'd suffice for Clippy.

**Comment by flip1995** [comment]
Even though I think GitHub Actions is a good CI/CD tool, I don't think that it is quite there yet, to support a project like Clippy. So I'd vote for Azure, if at all possible.

**Comment by mati865** [comment]
FYI https://blog.rust-lang.org/inside-rust/2019/11/14/evaluating-github-actions.html

**Comment by Manishearth** [comment]
Yep, and when I asked infra folks they also suggested using Actions (because of the then-not-public switch linked above)
