### ISSUE TITLE
Lint against calling `to_string()` on `&&str`, `&&String`, etc.

### ISSUE THREAD

**Issue by sinkuu** [rust-lang/rust-clippy#4586]
[`ToString`](https://doc.rust-lang.org/std/string/trait.ToString.html) is specialized for string types to avoid using expensive formatting facility. This specialization can be missed by calling `to_string` on redundantly-referenced strings like `&&str` or `&&String` which may easily occur when working with iterators, for example:

```rust
// Generic implementation for `T: Display` is used (slow)
["foo", "bar"].iter().map(|s| s.to_string());

// OK, the specialized impl is used
["foo", "bar"].iter().map(|&s| s.to_string());
```

**Comment by HMPerson1** [comment]
I can work on this

**Comment by mati865** [comment]
Oh https://github.com/rust-lang/rust-clippy/pull/4595 wasn't merged.
