### ISSUE TITLE
Const generics + (blocks || if) vs. function_header_span

### ISSUE THREAD

**Issue by llogiq** [rust-lang/rust-clippy#4587]
Currently we get the `fn` header span by finding the first `{` in the item snippet. However, with const generics this may no longer be correct once `if` or blocks become allowed.

For example, `fn on_array(a: [u8; {4 * SOME_CONST}]) { .. }` will lead `function_header_span` to span `fn on_array(a: [u8;`.

A good solution would be to only reduce the span if we have a `Body` and then search backwards from it's start.

**Comment by sinkuu** [comment]
If `FnDecl` is available, something like `span.to(fn_decl.output.span())` might work too.

**Comment by llogiq** [comment]
I think this is now universally solved, so let's close it.
