### ISSUE TITLE
`0i8.abs() as u8` is not lossy

### ISSUE THREAD

**Issue by jhpratt** [rust-lang/rust-clippy#4605]
A special case for [`cast_sign_loss`](https://rust-lang.github.io/rust-clippy/master/index.html#cast_sign_loss), if the absolute value is taken, the value is guaranteed to be non-negative. As such, a cast from iX to uY where Y >= X is unquestionably safe.

I'm using clippy 0.0.212 (cd3df6b 2019-08-20), though I suspect this hasn't changed in the meantime.

**Comment by HMPerson1** [comment]
I can work on this
