### ISSUE TITLE
missing_safety_doc warning even on functions internal to crate

### ISSUE THREAD

**Issue by tspiteri** [rust-lang/rust-clippy#4608]
Functions which are public in their module, but inside a private module, are not exposed in the API docs. In fact they do not get a warning with `warn(missing_docs)`. They still get a warning with `warn(clippy::missing_safety_doc)`.

**Comment by llogiq** [comment]
Oops. On one hand, the last thing I want is people to learn to delete their docs to silence the lint. On the other hand, where are you going to document the preconditions if not on the module boundary.

I guess the best solution is to split the lint by actual visibility and make the `missing_private_safety_doc` part lint even when there's no docs at all.

**Comment by tspiteri** [comment]
I agree that the lint should be split by visibility, not by existing docs. I mentioned the `missing_docs` lint to point out that `missing_docs` itself depends on visibility.

**Comment by RustyYato** [comment]
Was `missing_private_safety_doc` ever implemented? It would be very helpful to ensure that non-exposed unsafe functions and traits' preconditions are documented.
