### ISSUE TITLE
Clippy does not honour `#[allow(clippy:all)]` for `rust-2018-idioms`

### ISSUE THREAD

**Issue by magnet** [rust-lang/rust-clippy#4609]
I've got a module with generated code that does not use rust 2018 idioms.  I would like to keep the lint enabled on the rest of my project -- and just disable Clippy on that module.  I am using `#[allow(clippy:all)]` on top of that module which seems to ignore other lints, but not `rust-2018-idioms`.

**Comment by flip1995** [comment]
`rust-2018-idioms` is a rustc lint (group), not a Clippy lint, so you have to allow it explicitly with `#[allow(rust_2018_idioms)]`
