### ISSUE TITLE
Enable rustfmt on AppVeyor again

### ISSUE THREAD

**Issue by phansch** [rust-lang/rust-clippy#4618]
https://github.com/rust-lang/rust-clippy/pull/4617 disabled running rustfmt on AppVeyor because of some cargo issues.

Specifically the error is: `error: no such subcommand: '+nightly'`.

[Link to full AppVeyor log](https://ci.appveyor.com/project/rust-lang-libs/rust-clippy/builds/27861860)

**Comment by flip1995** [comment]
#4624 found a solution with rustfmt still enabled on appveyor: https://ci.appveyor.com/project/rust-lang-libs/rust-clippy/builds/27872685#L893
