### ISSUE TITLE
Suggestion: warn if no await inside async fn or block

### ISSUE THREAD

**Issue by neoeinstein** [rust-lang/rust-clippy#4629]
In general, if you aren't `await`ing anything, then there is no reason to have an `async fn` or `async {…}`. Using `async` where it is not needed can lead to unnecessary overhead. This lint would alert users to cases where they may have started off writing something as async, but then refactored, removing all await points without deleting the `async` keyword.

**Comment by lzutao** [comment]
Does rustc lint about this? I think it is better to be linted by rustc.

**Comment by neoeinstein** [comment]
I was a bit surprised that rustc wasn't complaining about this, but figured I'd post here first. I can make a similar suggestion to the Rust project, and continue this issue only if it is rejected there.

**Comment by DevinR528** [comment]
Somewhat related, could we also lint if a future is not awaited inside of async context. I kept forgetting to add the `.await` and since its not an error it silently breaks the program.

**Comment by loyd** [comment]
https://github.com/rust-lang/rust-clippy/issues/7176

**Comment by giraffate** [comment]
I'm closing this because the [`unused_async`](https://rust-lang.github.io/rust-clippy/master/index.html#unused_async) has been implemented.

**Comment by otiv-arne-janssens** [comment]
`unused_async` only works for async fn, not async blocks?
