### ISSUE TITLE
./util/dev fmt fails

### ISSUE THREAD

**Issue by Lythenas** [rust-lang/rust-clippy#4638]
`./util/dev fmt` fails for me. I think this is cause by 20b73514395bb442fb16ce913b6c2b3965ff3156 
I think this commit changed how rustfmt is called from `rustfmt` to `$CARGO_HOME/bin/rustfmt` which is not the same on my machine.

I'm on archlinux and I installed rustup through the package manager (not sure if that makes a difference). For me the rustfmt binary is not in `~/.cargo/bin/rustfmt` but in `/usr/bin/rustfmt` and points to `/usr/bin/rustup`.

Running `./util/dev fmt --verbose` outputs:

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/clippy_dev fmt --verbose`
cd /home/ms/Repos/rust-clippy/clippy_dev && /home/ms/.cargo/bin/rustfmt +nightly --version
error: No such file or directory (os error 2)
```

`cargo` is also not in `~/.cargo/bin` for me but in `/usr/bin/cargo` which also points to `/usr/bin/rustup`.

**Comment by Lythenas** [comment]
For now just creating symbolic links in `~/.cargo/bin` to the executables `cargo`, `cargo-fmt` and `rustfmt` in `/usr/bin` is a workaround. But it is not ideal.

**Comment by mati865** [comment]
Original bug has been fixed in Cargo so Clippy should revert workaround which caused this issue once Cargo update lands in Rust.
