### ISSUE TITLE
Unneeded multiple pattern with wildcard

### ISSUE THREAD

**Issue by BO41** [rust-lang/rust-clippy#4640]
Any multiple patterns with the wildcard pattern can be removed as the wildcard will match anyway
```rust
match "foo" {
    "a" => {
        dbg!("matched a");
    }
    "bar" | _ => {
        dbg!("bar or wildcat");
    }
}
```
Should be written as
```rust
match "foo" {
    "a" => {
        dbg!("matched a");
    }
    _ => {
        dbg!("matched (bar or) wildcard");
    }
}
```

cc #1272

**Comment by Anubhav007** [comment]
In which file do we need to change this?

**Comment by BO41** [comment]
looking at this PR https://github.com/rust-lang/rust-clippy/pull/1273 , I guess `clippy_lints/src/copies.rs`

**Comment by flip1995** [comment]
I'd recommend to put this in [`clippy_lints/src/matches.rs`](https://github.com/rust-lang/rust-clippy/blob/master/clippy_lints/src/matches.rs)
