### ISSUE TITLE
ICE: thread 'rustc' panicked at 'Box<Any>' 

### ISSUE THREAD

**Issue by peterjoel** [rust-lang/rust-clippy#4643]
I originally submitted this to rust-lang, but it was closed as a clippy issue:

https://github.com/rust-lang/rust/issues/65184

**Comment by mati865** [comment]
Sorry I couldn't find it earlier but is should be fixed by https://github.com/rust-lang/rust-clippy/pull/4590
It should be included in next nightly.

**Comment by flip1995** [comment]
Thanks for the report, this is already fixed though.
