### ISSUE TITLE
Result<T, E> where size_of::<T>() < 128 and size_of::<E> >= 128

### ISSUE THREAD

**Issue by llogiq** [rust-lang/rust-clippy#4652]
Those will cause LLVM to issue `memcpy` calls to copy them around. Boxing the error type will push them below LLVM's size threshold, thus possibly improving performance, unless the Err case is more likely than the Ok case.

**Comment by andjo403** [comment]
feels like the [large_enum_variant](https://rust-lang.github.io/rust-clippy/master/#large_enum_variant) check but with a limit of 128 by default instead of 200.

**Comment by llogiq** [comment]
Sort of, but specialized to `Result`, because in most cases the `Err` case isn't quite as hot as the `Ok` case, so the wins on the latter can outweigh the losses from boxing on the former.

**Comment by thomcc** [comment]
Also large_enum_variant doesn't fire on Result<T, E>, since (I think?) it's looking at the definition of the enum.
