### ISSUE TITLE
Installation from *.tar.gz?

### ISSUE THREAD

**Issue by mkpankov** [rust-lang/rust-clippy#4665]
Hi,

I'm building a container for CI and I'd like to use clippy there.

I'm not using rustup to leverage container builder caching of raw .tar.gz downloads.

So, the question is, is an archive with built clippy binaries available anywhere? I think it is, since rustup uses it, but I couldn't quite figure out where that is.

For Rust itself, I'm pulling archives from URLs like
https://static.rust-lang.org/dist/rust-1.38.0-x86_64-unknown-linux-gnu.tar.gz

**Comment by flip1995** [comment]
The Clippy binaries are included in the archive, along with the RLS and rustfmt binaries. Can you use them?

**Comment by mkpankov** [comment]
I've tried passing `install.sh` script the components it should install, but it says it doesn't know such components. I tried to copy component name from `rustup component list` output.

**Comment by llogiq** [comment]
Does `cargo clippy` work?

**Comment by mati865** [comment]
All additional components are called `{component}-preview` in tarballs. For Clippy it's `clippy-preview`.

**Comment by mkpankov** [comment]
Okay turns out `install.sh` has installed `cargo-clippy` by default somehow. Didn't expect that.
