### ISSUE TITLE
Check Ordering used for Atomic*::store and Atomic*::load 

### ISSUE THREAD

**Issue by Kampfkarren** [rust-lang/rust-clippy#4679]
Atomic*::store and Atomic*::load have similar notes in the documentation about incorrect ordering causing a panic:

https://doc.rust-lang.org/std/sync/atomic/struct.AtomicUsize.html#method.store

https://doc.rust-lang.org/std/sync/atomic/struct.AtomicUsize.html#method.load

It would be neat if clippy caught these statically.

**Comment by oli-cosmian** [comment]
ping @hellow554 do you still want this assigned to you?

**Comment by hellow554** [comment]
Not sure if I have time this year anymore, so I unassigned myself. Thanks for the ping.
If I have time in the next year, I'll take a look again.

Thanks
