### ISSUE TITLE
Extend `cast_ptr_alignment` lint for `pointer::cast` method

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust-clippy#4708]
Extend https://rust-lang.github.io/rust-clippy/master/index.html#cast_ptr_alignment lint for `pointer::cast` method.

**Comment by hellow554** [comment]
I think one could go one step further:
forbid using `as` to cast between pointers (because it allows you to cast a `*const` to `*mut` without complaining, which is hilarious. `cast` firbids that, because of the signature of the method.

**Comment by jfrimmel** [comment]
> forbid using `as` to cast between pointers

I think, maybe that should be a new lint in the restriction group then. What do you think?

**Comment by hellow554** [comment]
> that should be a new lint 

Which can deprecate the old one? Sounds good
