### ISSUE TITLE
[cargo fix] `unit_arg` removes calls to functions with side-effects

### ISSUE THREAD

**Issue by soruh** [rust-lang/rust-clippy#4741]
When running `cargo fix --clippy -Z unstable-options` the following happens:

```rust
fn function_with_side_effects_but_unit_return() {
    print("This is a side-effect!");
}
```
This
```rust
fn some_function() -> Result<()> {
    // ...
    Ok(function_with_side_effects_but_unit_return())
}
```
will be turned into this
```rust
fn some_function() -> Result<()> {
    // ...
    Ok(())
}
```

but it should either be turned into this
```rust
fn some_function() -> Result<()> {
    // ...
    function_with_side_effects_but_unit_return();
    Ok(())
}
```
or not be changed at all.

This behavior results from the [unit_arg](https://rust-lang.github.io/rust-clippy/master/index.html#unit_arg) Lint, so that probably should be changed to no longer being `MachineApplicable` or it's "fixing" logic should be adjusted to produce the above result.

I don't know if the "Known problems" section is used for problems when using `cargo fix`, but I think while this is being looked into it might make sense to add this there.

Only tested on this version:
```bash
$ cargo clippy -V
clippy 0.0.212 (e8d5a9e 2019-10-22)
$ cargo -V
cargo 1.40.0-nightly (3a9abe3f0 2019-10-15)
$ rustc -V
rustc 1.40.0-nightly (4a8c5b20c 2019-10-23)
```

**Comment by flip1995** [comment]
Fix is in #4455, but is awaiting review.

**Comment by soruh** [comment]
Ah sorry, I seem to have missed that.
Do you think It would make sense to note this under the  "Known Problems" section of the doc, while your PR is being reviewed?

**Comment by flip1995** [comment]
Yeah, I think it would make sense to turn this into `MaybeIncorrect` and add a note to the documentation, until #4455 is reviewed.
