### ISSUE TITLE
Lint docs: Deprecated lints don't expand

### ISSUE THREAD

**Issue by phansch** [rust-lang/rust-clippy#4748]
reported in Discord by @evanjs: Deprecated lints in the docs don't expand:  
https://rust-lang.github.io/rust-clippy/master/#misaligned_transmute

This is _probably_ because the doc comments need to be moved above the `pub LINT_NAME` line so that the lintlib.py script picks them up again.

**Comment by euclio** [comment]
This should've been caught by rustc. Looks like `deprecated_lints.rs` is missing an associated `mod deprecated_lints;` in `clippy_lints/src/lib.rs`.

I would submit a PR to fix this, but it looks like the lint infrastructure has drifted away from working with what's currently in `deprecated_lints.rs`, so I'm not sure what needs to change to register the passes properly.
