### ISSUE TITLE
Extend `cast_ptr_alignment` for type alias

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust-clippy#4754]
This snippet only trigger `cast_ptr_alignment` lint non type-alias: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=bc9b2dfb6c7d2a37f96028e60b2abc1b
```rust
pub type HANDLE = *mut ::std::os::raw::c_void;
pub type PHANDLE = *mut HANDLE;

pub fn foo(_token: PHANDLE) {}

pub fn bar() {
    let mut token: HANDLE = ::std::ptr::null_mut();
    foo(token as *mut _);
    foo(&mut token);
    
    let a: *const u8 = ::std::ptr::null();
    let _ = a as *const *const u8;
}
```

cc #4708

**Comment by JohnTitor** [comment]
We already catch that case but ignore `c_void`, see #2677. ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=c119491f5afc94b26950fdd38729585a))
