### ISSUE TITLE
deploy lint docs failed on master branch unexpectedly

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust-clippy#4785]
See https://travis-ci.com/rust-lang/rust-clippy/jobs/253872386 for an example
I cannot trace why deploying step fail. It just stop unexpectedly.
* It could be a caching
   Someone with CI permission could delete Travis cache.

**Comment by flip1995** [comment]
I deleted the master branch cache. Let's see, if that helped

**Comment by flip1995** [comment]
That didn't help. I now tried to delete all caches. Let's see if that helped.

**Comment by flip1995** [comment]
I restarted the latest build on master: https://travis-ci.com/rust-lang/rust-clippy/builds/136493404

**Comment by lzutao** [comment]
I will enable Travis in my fork and investigate it.

**Comment by lzutao** [comment]
I could run well the script `.github/deploy.sh` locally. But on Travis it always being stuck at 
`python ./util/export.py out/master/lints.json` step. Maybe we should contact with Travis
support.

**Comment by flip1995** [comment]
Could you try disabling the output of the `export.py` script? Maybe it's too much output to the travis console, since it always fails at another point with every run. :thinking:

**Comment by lzutao** [comment]
There are only 555 log lines in my fork bulid: https://travis-ci.com/lzutao/rust-clippy/jobs/258469386.
So I don't think it because the log is too long.

**Comment by mati865** [comment]
Maybe it hangs somewhere like in this loop https://github.com/rust-lang/rust-clippy/blob/15d1731ce8d3782ba93b0fd583307240fc814ef3/util/lintlib.py#L50-L56
Or doesn't flush stdout/stderr.
Also it could be worth to try it with `python3` instead of `python`.

**Comment by lzutao** [comment]
> try it with `python3`

It failed the same way: https://travis-ci.com/lzutao/rust-clippy/jobs/258639369

**Comment by lzutao** [comment]
> hangs somewhere like in this loop

It always runs fine on my local machine.

**Comment by mati865** [comment]
> It always runs fine (to the end) on my local machine.

Right, I should have checked for how long it does run.

Have you tried to print exit code of that python script?
Running `echo $?` afterwards should do the trick.

**Comment by lzutao** [comment]
It run successfully and exit with status code 0.
