### ISSUE TITLE
New lint: let _ binding of must use function

### ISSUE THREAD

**Issue by flip1995** [rust-lang/rust-clippy#4812]
Extracted from #4655

A lint that detects `let _` bindings of functions, that are `must_use`:
```rust
#[must_use]
fn foo() -> u32 { 42 }

fn bar() -> Result<(), ()> { Ok(()) }

let _ = foo();
let _ = bar();
```

On how to detect must use https://github.com/rust-lang/rust-clippy/issues/4655#issuecomment-544104531:
>We have a check for `#[must_use]` types in functions.rs already (IIRC `is_must_use_ty(cx, ty)`, we best move this to `utils/mod.rs`), that you can call with the result of an `expr_ty(cx, _)` on the initializer.

_Originally posted by @flip1995 in https://github.com/rust-lang/rust-clippy/issues/4655#issuecomment-541024037_

**Comment by Areredify** [comment]
I would like to tackle this.

**Comment by llogiq** [comment]
Great, go ahead. Tell us if you need anything.

**Comment by Areredify** [comment]
Should we not lint `Result<T, !>` and `Result<T, Infallible>`? Also, is `#[must_use]` something like a type modifier, like mut?

**Comment by llogiq** [comment]
No, `#[must_use]` is an annotation that is only used by rustc's `unused_must_use` lint. And it's easy enough to `unwrap()` those results; in fact it shouldn't even generate code (I think we should be able to check if the `Err` type is uninhabited and give a suitable suggestion in those cases).

**Comment by Areredify** [comment]
I just realized I assumed a bunch of things. 1. This issue does not talk about `Result`, even though it's parent does. If we do lint `Result`, do we lint against `let _ = <expr_with_result_ty>` or against `let _ = <fn_call_returning_result>`?. 2. Same goes for `#[must_use]`, issue talks about against `let _ = <fn_call_returning_result>`, we could also lint against `let _ = <expr_with_must_use_ty>`

**Comment by llogiq** [comment]
Exactly. The lint checks `hir::Local`s (= `let ..`) with a wildcard `pat` and an init expression whose type (via `expr_ty`) has a `must_use` annotation.

This will catch, among other things, `Result` and `MutexGuard`.

If we want, we could extend the lint to also cover functions/methods directly marked as `#[must_use]`.
