### ISSUE TITLE
Euclidean operations combined with sign casting cannot result in loss of a sign

### ISSUE THREAD

**Issue by jhpratt** [rust-lang/rust-clippy#4818]
`.rem_euclid` and `.div_euclid` always results in a non-negative value, so casting to the same or larger size (except unsigned) should be allowed.

```rust
(-1_001).rem_euclid(1_000 as i16) as u16
```

There are also checked versions of these functions (`.checked_rem_euclid` and `.checked_div_euclid`) which should also be handled.

Version: `clippy 0.0.212 (c8e3cfb 2019-10-28)`

Related: #4605 (`.abs`), #4743 (`.checked_abs`)

**Comment by krishna-veerareddy** [comment]
I would like to work on this if nobody else started working on it.

**Comment by flip1995** [comment]
It's all yours. If you have any questions just ask here or open a WIP PR.

**Comment by krishna-veerareddy** [comment]
@jhpratt Hey the result of `.div_euclid` can be non-negative so I am not white-listing it in my PR. Please let me know if I got that wrong and Ill white-list it.

**Comment by jhpratt** [comment]
Ah, apparently I didn't check the docs on that one. You're absolutely right that it can result in a negative number.
