### ISSUE TITLE
Give "corrected" code in examples

### ISSUE THREAD

**Issue by ChrisJefferson** [rust-lang/rust-clippy#4829]
clippy recently pointed me to this: https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes

This tells me I should make use of "lifetime elision". I can see an example at the bottom, which does indeed show me something which looks like my code, but nothing seems to tell me how to make use of "lifetime elision". Perhaps every example should also come with a "fixed" version, so readers can see the intended outcome of the suggestion?

**Comment by flip1995** [comment]
I think, that most of the documentation comes with a _good_ and _bad_ example. But old lints (like this one) may only have a _bad_ example, because back then, this was the standard way of writing lint documentation. So we still need to catch up.

**Comment by phansch** [comment]
Reopening because there's still other lints without 'fixed' versions.
