### ISSUE TITLE
Clippy errors and says to use `Read::read_exact` inside implementations of `Read::read_exact` that don't directly use the output of `Read::read`

### ISSUE THREAD

**Issue by slightlyoutofphase** [rust-lang/rust-clippy#4836]
Given the following `read_exact` implementation:

    #[inline(always)]
    fn read_exact(&mut self, buf: &mut [u8]) -> io::Result<()> {
      //Our implementation of `read` always returns `Ok(read_length)`, so we can unwrap safely here.
      self.read(buf).unwrap();
      Ok(())
    }

Clippy gives the following error:

    error: handle read amount returned or use `Read::read_exact` instead
        --> src/lib.rs:1331:7
         |
    1331 |       self.read(buf).unwrap();
         |       ^^^^^^^^^^^^^^^^^^^^^^^
         |
         = note: `#[deny(clippy::unused_io_amount)]` on by default
         = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unused_io_amount

**Comment by flip1995** [comment]
Hmm. Suggesting to use `read_exact` inside `read_exact` is definitely wrong. But I would rewrite this function as:
```rust
#[inline(always)]
fn read_exact(&mut self, buf: &mut [u8]) -> io::Result<()> {
  //Our implementation of `read` always returns `Ok(read_length)`, so we can unwrap safely here.
  let buf_len = buf.len();
  let bytes_read = self.read(buf).unwrap();
  assert_eq!(bytes_read, buf_len); // Or `debug_assert_eq!` or return an `Err`
  Ok(())
}
```

**Comment by slightlyoutofphase** [comment]
Good point! I adjusted it on my end.

On a general note I don't really get why `read_exact` doesn't just return `io::Result<usize>` like `read` does instead of `io::Result<()>` anyways, but obviously that's kind of a moot point.

**Comment by flip1995** [comment]
I guess this is because by definition it would always return `Ok(buf.len())`, panic (not recommended) or return an `Err`.
