### ISSUE TITLE
Please make `unreadable_literal` configurable in clippy.toml

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust-clippy#4843]
As far as I can tell you can't turn it off using `clippy.toml`

**Comment by mikerite** [comment]
Clippy lints work the same way the rustc lints do. It's not possible to disable them in Cargo.toml. You need to add `#[allow(<lint>)]` in your code or pass `-A ...` on the command line.

**Comment by Lokathor** [comment]
I said _clippy.toml_, which does allow some lints to be configured.

**Comment by mikerite** [comment]
Same story. 
#3164

**Comment by flip1995** [comment]
As @mikerite pointed out, lints cannot be disabled in the `clippy.toml`. This was discussed in multiple other issues, e.g. the clippy 1.0 RFC. This functionality may be implemented in cargo directl.

**Comment by Lokathor** [comment]
interesting, please at least document this more clearly
