### ISSUE TITLE
Disable needless_main_doctest by default

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust-clippy#4858]
This lint is recommending me to remove the `fn main()` in jemalloc-ctl doctests, e.g., see these ones at the top-level: https://docs.rs/jemalloc-ctl/0.3.3/jemalloc_ctl/#examples

I personally think that the `fn main()` significantly increases the clarity of these particular doctests. 

Also, one does not have to write `fn main()`, one explicitly must opt into writing it. Warning by default when one has explicitly opted into doing so feels like a bad idea.

So IMO this lint should not even be enabled when `clippy::pedantic` is enabled.

Looking at the lint PR, I can't find an issue or a discussion about the "need" for this lint. Which crate authors were writing `fn main()` in doctests out of ignorance that it could be left out, to the point that doing so warrants a lint ? The book and rust-by-example all omit `fn main`, so I'm skeptical that anybody learning Rust from any official resource would have picked up the habit of writing `fn main()` in doctest "by accident". In my experience, one has to go deep into the rustdoc documentation to figure out that this is even possible.

**Comment by gnzlbg** [comment]
cc @llogiq

**Comment by flip1995** [comment]
A fix for this (only empty `fn main() {}`s get linted) is in #4729. But some weird errors occur because of the `syn` dep.

**Comment by llogiq** [comment]
I must add that this is not a complete fix. However, once I have the `syn` dependency sorted out, I can omit linting when I encounter e.g. a `static` item.

**Comment by gnzlbg** [comment]
Could we maybe temporarily disable the lint until this is fixed ?
