### ISSUE TITLE
New lint: Suggest usage of `mem::take`

### ISSUE THREAD

**Issue by krishna-veerareddy** [rust-lang/rust-clippy#4871]
`mem::take` is being [stabilized](https://github.com/rust-lang/rust/pull/64716) in v1.40 so I was wondering if we should add a lint to detect occurences of `mem::replace(&mut T, T::default())` and suggest usage of `mem::take(&mut T)` instead.

Let me know if this is something that's useful and I can start working on it.

**Comment by Shnatsel** [comment]
I believe #4485 could benefit from this

**Comment by fisherdarling** [comment]
Hi! I'd like to try and tackle this.

**Comment by krishna-veerareddy** [comment]
Fixed in #4881. Closing.
