### ISSUE TITLE
precedence should not warn for unary minus before odd function

### ISSUE THREAD

**Issue by mad-s** [rust-lang/rust-clippy#4892]
The `clippy:precedence` list currently warns on every instance of the form `-literal.method()`, as precedence looks ambiguous. However, for an *odd function*, i.e. a function `f(x)` where `f(-x)=-f(x)`, the precedence doesn't matter. Many functions have this property, such as `sin()`, `atan()`, `cbrt()`, `to_radians()` (and `round()` i think).

**Comment by flip1995** [comment]
Basically only a whitelist of functions has to be added.

**Comment by logan-dev-oss** [comment]
Hi! Can I work on this issue ? (first issue/contribution). Thanks.

**Comment by flip1995** [comment]
Sure! To get started with Clippy development you can read up in https://github.com/rust-lang/rust-clippy/blob/master/doc/adding_lints.md. If you have any questions, just ask here or open a WIP PR.

**Comment by logan-dev-oss** [comment]
Fix was merged. Is it possible to close this issue pls ?
