### ISSUE TITLE
`missing_inline_in_public_items` triggers on derived Debug::fmt with seemingly no way to prevent it.

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust-clippy#4895]
Interestingly, it doesn't fire on any other derived trait methods (clone, default, etc).

**Comment by flip1995** [comment]
Do you have a reproducer?

**Comment by Lokathor** [comment]
I upgraded everything via rustup with the 1.40 release, and this seems to no longer be a problem in `clippy 0.0.212 (374db5c0 2019-12-04)`, so I'm going to close it as "the user probably just had some old version of clippy installed but it's fine now".
