### ISSUE TITLE
Disable range_minus_one when type is explicity RangeInclusive

### ISSUE THREAD

**Issue by rawler** [rust-lang/rust-clippy#4898]
Clippy gives me the hint;

```
warning: an exclusive range would be more readable
  --> src/main.rs:55:21
   |
55 |         init_range: 0..=(sidx_offset - 1),
   |                     ^^^^^^^^^^^^^^^^^^^^^ help: use: `0..sidx_offset`
   |
   = note: `#[warn(clippy::range_minus_one)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#range_minus_one
```

However, `init_range` in the struct in question, is defined as an `InclusiveRange`. (By design, matching HTTP-Range).

It would be great if clippy could use the type-info from the context to disable inappropriate hints like this.

**Comment by rawler** [comment]
Basically, the equivalent of https://github.com/rust-lang/rust-clippy/issues/3307, but for RangeInclusive.

**Comment by flip1995** [comment]
Let's track this in #3307
