### ISSUE TITLE
New lint: suggest using fs::{read,read_to_string} over File counterparts

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust-clippy#4916]
In specific, we recommend to use:
* `std::fs::read_to_string` over `File::read_to_string`
* `std::fs::read` over `File::read_to_end`

But only when buffer is empty.

**Comment by flip1995** [comment]
https://doc.rust-lang.org/std/fs/fn.read.html

> This is a convenience function for using File::open and read_to_end with fewer imports and without an intermediate variable.

https://doc.rust-lang.org/std/fs/fn.read_to_string.html

> This is a convenience function for using File::open and read_to_string with fewer imports and without an intermediate variable.

**Comment by jmeyers35** [comment]
Hi, could I work on this? I'd like to get started contributing to Clippy. Thanks!

**Comment by flip1995** [comment]
Yeah sure! If you have any questions, just ask here or open a WIP PR. A good read to get started is this document: https://github.com/rust-lang/rust-clippy/blob/master/doc/adding_lints.md
