### ISSUE TITLE
Lint for using Option::as_deref

### ISSUE THREAD

**Issue by jan-auer** [rust-lang/rust-clippy#4918]
With Rust 1.40.0, [`Option::as_deref`](https://doc.rust-lang.org/stable/std/option/enum.Option.html#method.as_deref) has landed. 

It would be great to have a clippy lint that detects `Option::as_ref` chained by `Option::map<F> where F: FnOnce(&T) -> &<T as Deref>::Target`. This would then automatically account for cases where `AsRef::as_ref` or a custom method like `String::as_str` are used.

By far the most compelling case is to apply it to `Option<String>` or `Option<PathBuf>`, with probably lots of code bases now containing `opt.as_ref().map(String::as_str)` or similar constructs.

**Example in:**

```rust
let opt = Some(" hello ".to_owned());
let trimmed = opt.as_ref().map(String::as_str).map(str::trim);
```

**Example out:**

```rust
let opt = Some(" hello ".to_owned());
let trimmed = opt.as_deref().map(str::trim);
```

There are probably more cases that could be detected, like `?` chaining or `match` statements, but I think those will get gradually less useful to be worth the effort.

Icing on the cake would be compatibility to rustfix :)

**Comment by jan-auer** [comment]
I have to say that I'm highly interested in attempting to implement this if someone agrees that this is useful. Realistically though, I might not get to it as I know myself, so I guess this is up for grabs.

**Comment by mikerite** [comment]
> It would be great to have a clippy lint that detects Option::as_ref chained by Option::map<F> where F: FnOnce(&T) -> &<T as Deref>::Target. This would then automatically account for cases where AsRef::as_ref or a custom method like String::as_str are used.

Aren't we going to get false positives if we check based on the signature of the closure? The code for `as_def` is `self.as_ref().map(|t| t.deref())`. IMO, we lint should only generate warnings for this code or special cases that are equivalent.

**Comment by jan-auer** [comment]
You’re right. Especially with closures, there could be false positives. I missed that. 

I wonder if there is a nice way to avoid whitelisting all well-known cases...
