### ISSUE TITLE
needless_doctest_main suggestion wrong with explicit extern crate

### ISSUE THREAD

**Issue by HeroicKatora** [rust-lang/rust-clippy#4927]
In `edition = 2015` there is a difference between `extern crate _` in global scope and within a main function. The `extern crate` and `use` declarations depend on order when occurring within a function but are order independent when in global scope. This means that letting rust doc automatically generate the wrapping `fn main() { }` can change the compilation success.

*  This is fine.
    ```rust
    use playground::*;
    extern crate playground;
    ```

* This is not
    ```rust
    fn main() {
        use playground::*;
        extern crate playground;
    }
    ```

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=3671dff33040dfe65bc3eee0ae4de719)

A doc-test can have the former form and include an explicit `fn main() { }` to avoid automatic transformation by cargo doc. But when the clippy lint is applied this is transformed into the latter and no longer compiles.

**Comment by llogiq** [comment]
Ok, let's add a check for `extern crate`, too.
