### ISSUE TITLE
New Lint: Explicit ranges with `p0 | ... | p_n` => range pat

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust-clippy#4931]
Category: Complexity

Consider:

```rust
match x {
    1 | 2 | 4 | 3 => 0,
     _ => 1,
}
```

Ostensibly the or-pattern would be more clearly written as `1..=4`.

I would suggest making the analysis on HAIR.

cc @oli-obk cc https://github.com/rust-lang/rust/issues/67488

**Comment by mikerite** [comment]
I thought HAIR was something used internally by the MIR crates. How do you access it from a lint?

**Comment by Centril** [comment]
Not sure; HIR probably works as well but is less desugared.
