### ISSUE TITLE
Automatic new lint boilerplate generation

### ISSUE THREAD

**Issue by Areredify** [rust-lang/rust-clippy#4942]
When creating new lints that don't fit in the old lint categories, I usually go through kinda samey hoops of creating new files and copypasting LateLintPass/EarlyLintPass boilerplate from existing lints. Is there a script or something I can use to generate them for me (if that's possible?). I didn't find anything related in utils.

**Comment by flip1995** [comment]
Nope, this has to be written by hand ATM. It could be an addition to `clippy_dev` though. I can think of a `./util/dev new_{late,early}_lint <LINT_NAME>` which then creates a file with the boilerplate for a lint with the name `<LINT_NAME>.rs` and the lint definition in it.

**Comment by bradsherman** [comment]
I'd like to try and do this

**Comment by llogiq** [comment]
A good addition might be a hi test file with an empty main method and a TODO comment asking to add things that should (not) be linted.
