### ISSUE TITLE
clippy::missing_safety_doc triggers on macro generated code

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust-clippy#4949]
See https://github.com/rust-embedded/cortex-m-rt/issues/225, the `#[interrupt]` and `#[entry]` proc-macros from `cortex-m-rt` generate `pub unsafe fn` without safety documentation, which triggers the `missing_safety_doc` lint. @jonas-schievink suggests that since these are generated by external macros the lint shouldn't be triggering on them.

**Comment by llogiq** [comment]
I'm fine with adding a macro check. On the other hand, it might be a good idea to fix this in `cortex-m-rt`.

**Comment by llogiq** [comment]
In general, I see a category of lints we disable in external macros, but we might want to let the user enable to help them audit their proc-macro dependencies.

**Comment by flip1995** [comment]
> I see a category of lints we disable in external macros, but we might want to let the user enable to help them audit their proc-macro dependencies

If someone has a lot of spare time, a lint audit which puts lints in categories like
- should lint in all macros
- should not lint in external macros
- should not lint in macros at all
- configurable if it should run in (external) macros

**Comment by llogiq** [comment]
I've started a table with the lints (and have looked up the first 50 or so), hopefully I'll find the time to finish it during the holidays.

**Comment by llogiq** [comment]
Current status: https://docs.google.com/spreadsheets/d/1k3uKeCaOBRbXV9ahxNQvT8orTgNbot0QQHQAmqoiFy0/edit?usp=sharing
