### ISSUE TITLE
redundant_clone in Rc context ?

### ISSUE THREAD

**Issue by o0Ignition0o** [rust-lang/rust-clippy#4982]
We had a small discussion on it here: https://github.com/mozilla/neqo/pull/374#discussion_r362395224. 
I wonder if we could tell a user to use `Rc::clone(&foo)` if the linter warns about a redundant clone in Rc context ?

If so I would love to work on it, but that would be my first PR to clippy, so it would probably require someone to mentor me.

Thanks for your time :)

**Comment by flip1995** [comment]
The lint is implemented in [`redundant_clone.rs`](https://github.com/rust-lang/rust-clippy/blob/master/clippy_lints/src/redundant_clone.rs), so somewhere in there `Rc` could be special cased. Probably somewhere inside this `if`:

https://github.com/rust-lang/rust-clippy/blob/05b46034ea734f2b4436b700452771652ecc0074/clippy_lints/src/redundant_clone.rs#L211

Since @sinkuu completely rewrote this lint, maybe he can give a little bit more insight.

---
For how to write tests in Clippy, you can read this part of the documentation: https://github.com/rust-lang/rust-clippy/blob/master/doc/adding_lints.md#testing

**Comment by sinkuu** [comment]
The type of the value being `.clone()`d is available here as `arg_ty`, so you could add something like `if is_rc(arg_ty) { continue; }` below that.

https://github.com/rust-lang/rust-clippy/blob/05b46034ea734f2b4436b700452771652ecc0074/clippy_lints/src/redundant_clone.rs#L115

I think `Rc::clone` suggestion is orthogonal to this lint and should be a new lint.

**Comment by o0Ignition0o** [comment]
> The type of the value being .clone()d is available here as arg_ty, so you could add something like if is_rc(arg_ty) { continue; } below that.

Pretty cool I'll try to work on it tomorrow or next week :D 

> I think Rc::clone suggestion is orthogonal to this lint and should be a new lint.

Would it make sense to create a redundant_rc_clone.rs file ? 
maybe that ought to be part of an other commit / PR ?

**Comment by sinkuu** [comment]
> *redundant*\_rc\_clone

Do you mean to suggest `Rc::clone` only when it is actually redundant? Then it may be fine to include the feature in `redundant_clone`.

(I don't see the point in doing so though. I was thinking of a lint that replaces all `rc.clone()` with `Rc::clone(&rc)`...)

**Comment by o0Ignition0o** [comment]
> Do you mean to suggest Rc::clone only when it is actually redundant? Then it may be fine to include the feature in redundant_clone.

That's what I initially thought of but the lint you mention (replacing rc.clone() with Rc::clone(&rc)) would be a great improvement IMO, it would make things explicit, and still allow redundant_clone to do its job in RC context.

I'm however not aware of the actual process to discuss a new lint and create a consensus among the clippy contributors ^^'.

**Comment by flip1995** [comment]
> I'm however not aware of the actual process to discuss a new lint and create a consensus among the clippy contributors

You can do 2 things:

1. Open an issue for a (style) lint `rc.clone()` -> `Rc::clone(&rc)` and wait for someone to take this issue or
2. Just implement it yourself and refer to this issue.

If you decide to do (2.) and need any help with that, just ask here or open a WIP PR :)

About the consensus: If people disagree with the lint, we can still move it to a `allow-by-default` group.

**Comment by o0Ignition0o** [comment]
I would love to try to implement it myself !

I have a couple of things to finish before I tackle it though, but feel free to assign me to it :)

**Comment by lengyijun** [comment]
`clone_on_ref_ptr` lints on it.
