### ISSUE TITLE
must_use_candidate: Consider ignoring `#[no_mangle]` functions

### ISSUE THREAD

**Issue by jplatte** [rust-lang/rust-clippy#4984]
Hi! I've just tried `-W clippy::pedantic` on a codebase that exposes a C API and found that the must_use_candidate lint triggers on many functions that are only ever called from C. Adding `#[must_use]` to these would be absolutely pointless. Would it be reasonable to adjust the lint to not trigger on `#[no_mangle]` functions, as these are almost always for use from non-Rust code which can't see `#[must_use]` attributes anyway?

**Comment by llogiq** [comment]
That's a good idea. Thank you. Will implement soon-ish.
