### ISSUE TITLE
let_and_return suggestion causes errors macro_rule

### ISSUE THREAD

**Issue by elichai** [rust-lang/rust-clippy#4997]
Hi, the following code: https://play.rust-lang.org/?gist=0f26eb7594df37138a8ff964c50cc3ab
says the let binding is unnecessary but the suggestion causes the code to not compile with the following error: 
`error: attempted to repeat an expression containing no syntax variables matched as repeating at this depth`

**Comment by JohnTitor** [comment]
Maybe we should not trigger this lint on macros.
