### ISSUE TITLE
Disable Travis Windows build?

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust-clippy#5005]
Somethings on Travis Windows environment change lead to Clippy
cannot be built on it anymore. Here is the relevant part in [log](https://api.travis-ci.com/v3/job/272779719/log.txt):

```
  = note: C:\Users\travis\.rustup\toolchains\master\lib\rustlib\x86_64-pc-windows-gnu\lib\crt2.o:crtexe.c:(.rdata$.refptr.__onexitbegin[.refptr.__onexitbegin]+0x0): undefined reference to `__onexitbegin'
          C:\Users\travis\.rustup\toolchains\master\lib\rustlib\x86_64-pc-windows-gnu\lib\crt2.o:crtexe.c:(.rdata$.refptr.__onexitend[.refptr.__onexitend]+0x0): undefined reference to `__onexitend'
          collect2.exe: error: ld returned 1 exit status
```

So should we remove that Windows job or just disable it?

**Comment by flip1995** [comment]
I don't think we ever fix the windows build on travis, but rather move to GHA or Azure. So I guess we can remove it.

**Comment by mati865** [comment]
In case you want to fix it for now, add this line after Rust is installed:
```
cp -f /c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/x86_64-w64-mingw32/lib/{*.a,*.o} `rustc --print sysroot`/lib/rustlib/x86_64-pc-windows-gnu/lib
````

**Comment by lzutao** [comment]
I wonder how rustup choose windows-gnu target on Travis Windows.
Does Travis Windows have Visual C++ ?

**Comment by mati865** [comment]
No idea, I don't use msvc at all.
