### ISSUE TITLE
Extend `invalid_atomic_ordering` lint to memory fence calls

### ISSUE THREAD

**Issue by krishna-veerareddy** [rust-lang/rust-clippy#5026]
`core::sync::atomic::{fence, compiler_fence}` functions [will panic](https://doc.rust-lang.org/std/sync/atomic/fn.fence.html#panics) when called with `Relaxed` ordering so we should lint such calls under the `invalid_atomic_ordering` lint. I can start working on this issue if nobody has any objections.

**Comment by JohnTitor** [comment]
It seems reasonable to me.
