### ISSUE TITLE
clippy 1.40 release missing

### ISSUE THREAD

**Issue by curiousleo** [rust-lang/rust-clippy#5037]
[Rust 1.40 was released on 2019-12-19](https://blog.rust-lang.org/2019/12/19/Rust-1.40.0.html). But the [latest release of clippy](https://github.com/rust-lang/rust-clippy/releases) is 1.39 (as of 2020-01-10).

My assumption here is that clippy is generally released together with rustc. There is also a [changelog entry for clippy 1.40](https://github.com/rust-lang/rust-clippy/blob/master/CHANGELOG.md#rust-140).

So the question is: is this just an oversight, or is there something stopping the team from releasing clippy 1.40?

Context: I'm looking into https://github.com/NixOS/nixpkgs/issues/77358 right now.

**Comment by flip1995** [comment]
Just an oversight, thanks for the hint! I just pushed the tag https://github.com/rust-lang/rust-clippy/releases/tag/rust-1.40.0

The Clippy releases are always the Clippy commit, which is in the stable rust compiler.

**Comment by flip1995** [comment]
I marked the next 2 rust stable release dates in my calendar, so I don't forget about it again. If I should forget it, just open an issue like this one again 👍
