### ISSUE TITLE
use_debug in Debug implementation

### ISSUE THREAD

**Issue by jsim2010** [rust-lang/rust-clippy#5039]
In my opinion, `clippy::use_debug` should allow the debug format `"{:?}"` within `Debug` trait implementations. This seems to be backed up by the comment in the test here: https://github.com/rust-lang/rust-clippy/blob/da7aebc342b7dae444912b98dedbab22bf2a224c/tests/ui/print.rs#L15-L20

However, the expected output actually expects an error in this case https://github.com/rust-lang/rust-clippy/blob/da7aebc342b7dae444912b98dedbab22bf2a224c/tests/ui/print.stderr#L9-L13

I propose that this error be removed from the test and the code adjusted to allow for debug formatting in `Debug`. If this is not desired, then the comment in tests/ui/print.rs should be removed to avoid confusion.

**Comment by JohnTitor** [comment]
I think it's a regression caused by #2949.
