### ISSUE TITLE
unify some line names

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-clippy#5052]
Right now we have lints that start with `unneeded_`, `needless_`, `unused_` and `redundant_`

I feel like most of these prefixes are trying to express the same so perhaps we could make this more consistent somehow?

**Comment by flip1995** [comment]
cc #2845 This was already mentioned there. When we do this, we should address most of what is raised in that issue, so we don't have multiple mass rename waves, raising `clippy::unknown_clippy_lints` warnings. (is this lint auto applicable? :thinking: )

**Comment by phansch** [comment]
Going to close this in favor of #2845
