### ISSUE TITLE
Incorrect clippy::borrowed_box warning.

### ISSUE THREAD

**Issue by wdanilo** [rust-lang/rust-clippy#5073]
Hi, consider the following code:

```rust
    pub fn add(&mut self, pass:&Box<dyn RenderPass>) {
        let pass = RenderPassRunner::new(&self.context,&self.variables,pass,self.width,self.height);
        self.passes.push(pass);
    }
```

However, if I remove the `Box`, I cannot use the argument anymore, because as a trait object it is not Sized.

**Comment by llogiq** [comment]
Could it be that you accidentally removed the `&` with the Box?

**Comment by wdanilo** [comment]
Oh well, I'm sorry, you are of course right!

**Comment by llogiq** [comment]
Happens to the best of us. 🙏
