### ISSUE TITLE
Allow use_self at function level

### ISSUE THREAD

**Issue by martinthomson** [rust-lang/rust-clippy#5078]
Like #5053, the `use_self` lint cannot be denied or allowed at the function level.

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=83e755c4b3697bc39c85292353727a86)

As it is sometimes necessary to suppress this (e.g., #3410), it would be very useful to be able to target a specific function.

**Comment by Xk0nSid** [comment]
I would like to work on this issue as my first contribution to the project.

**Comment by flip1995** [comment]
Great! You can take a look at #5063 for some inspiration. If you have any questions, feel free to ask here or open a WIP PR.

**Comment by montrivo** [comment]
@Xk0nSid are you working on this one? I'd like to take it on if you're not.
