### ISSUE TITLE
Internal lint: check if `span_lint_and_then` and `span_*` are collapsable

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/rust-clippy#5095]
When `span_lint_and_then` and `span_*` have the same span, we can replace them with `span_lint_and_*` in most cases. It'd be nice that we have an internal lint for this.
It's a follow-up for [this comment](https://github.com/rust-lang/rust-clippy/pull/5084#discussion_r370936810).

**Comment by flip1995** [comment]
Also only if the `db.span_*` is the only Expr/Stmt in the closure of `span_lint_and_then`.
