### ISSUE TITLE
Improve documentation for `iter_nth_zero` lint

### ISSUE THREAD

**Issue by e-oz** [rust-lang/rust-clippy#5115]
> iter.nth(0) is unnecessary, and iter.next() is more readable.

`iter.nth(0)` says that I want to fetch exactly first element. In case of iter.next() I have no idea how many times  "next()" has been called before.

**Comment by mikerite** [comment]
They are equivalent. `nth(0)` consumes elements just like `next()` does.

```rust
fn main() {
    let v = vec![1, 2, 3];
    
    let mut i1 = v.iter();
    println!("nth(0)");
    println!("{:?}", i1.nth(0));
    println!("{:?}", i1.nth(0));
    println!("{:?}", i1.nth(0));
    
    let mut i2 = v.iter();
    println!("next");
    println!("{:?}", i2.next());
    println!("{:?}", i2.next());
    println!("{:?}", i2.next());
}
```

produces
```
nth(0)
Some(1)
Some(2)
Some(3)
next
Some(1)
Some(2)
Some(3)
```

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=be88fe7b20b5bf97d5cd76b2dc7355e3)

**Comment by flip1995** [comment]
What @mikerite said. We should document this.

**Comment by e-oz** [comment]
But when you are reading "next()", you have no idea how many times "next()" has been called before. You need to find all previous cases. You call it "more readable"?
