### ISSUE TITLE
Cannot install rust 1.39.0 on a raspberry 3b+ / 4

### ISSUE THREAD

**Issue by Suniron** [rust-lang/rust-clippy#5136]
Hello,

I have to install an old version of rust: the 1.39.0.

I can't install it on a raspberry 3b+ (same problem on a raspberry 4).

When i try `rustup toolchain install 1.39.0`, i got this:

```
pi@raspberrypi:~/developpement/prisma-engine$ rustup toolchain install 1.39.0
info: syncing channel updates for '1.39.0-armv7-unknown-linux-gnueabihf'
info: latest update on 2019-11-07, rust version 1.39.0 (4560ea788 2019-11-04)
error: some components unavailable for download for channel 1.39.0: 'clippy', 'rustfmt'
If you require these components, please install and use the latest successful build version,
which you can find at <https://rust-lang.github.io/rustup-components-history>.

After determining the correct date, install it with a command such as:

    rustup toolchain install nightly-2018-12-27

Then you can use the toolchain with commands such as:

    cargo +nightly-2018-12-27 build
```
(`rustup install 1.39.0` give exactly same issue).

I use `rustup 1.21.1 (7832b2ebe 2019-12-20)`.

Thanks :D

**Comment by JohnTitor** [comment]
The cause is rust-lang/rust#62558, could you try to install the latest stable(1.41.0)? It should be fine.

**Comment by Suniron** [comment]
Thanks for your answer @JohnTitor ,

I need the version `1.39.0` to build some NodeJS library binaries ..

I had tried with the stable version `1.41.0` and i got the error which is mentionned in my issue  https://github.com/prisma/prisma-engine/issues/447


PS: Sorry for my english, i'm learning to improve it ;-)

**Comment by JohnTitor** [comment]
Then you should set rustup profile to minimal, it doesn't require Clippy and rustfmt. You can set it with `rustup set profile minimal`.

**Comment by flip1995** [comment]
Yeah, the solution is to not install clippy and other components, by setting `rustup set profile minimal`, before `rustup toolchain install 1.39.0`.

**Comment by Suniron** [comment]
Ok.. It's ok !!! Thank's a lot...
