### ISSUE TITLE
Adding lint for "return Ok(...?)"

### ISSUE THREAD

**Issue by bonzini** [rust-lang/rust-clippy#5161]
Writing `return Ok(x?)` is redundant, as it can be replaced simply with `return x`. Likewise for `Ok(x?)` if it is the last statement in the function.

**Comment by flip1995** [comment]
`Ok(x?)` will either return `Ok(Err(y))` or `Ok(z)`. I guess you mean `Ok(x)` which always return `x`?

This should be an easy enhancement (/new lint with similar code) of [`try_err`](https://rust-lang.github.io/rust-clippy/master/index.html#try_err)

**Comment by bonzini** [comment]
I don't understand:

* If `x` is `Err(y)`, then `x?` will return the error, so `return Ok(x?)` will be the same as `return Err(y)` which is `return x`

* If `x` is `Ok(z)`, then `x?` is just `z` and `return Ok(x?)` is the same as `return Ok(z)`, which again is `return x`

**Comment by flip1995** [comment]
Oh yeah, your right! Thanks for the clarification :)

**Comment by dtolnay** [comment]
`return Ok(x?)` is a reasonably common idiom to get `?`'s From-coercion on the error type and is not equivalent to `return x`.
Example: https://play.rust-lang.org/?edition=2018&gist=eb76ec0cd7846914398df3c59cac0478

**Comment by bonzini** [comment]
Sure, but you can detect that based on the types.
