### ISSUE TITLE
Option::map(_).flatten()  => Option::and_then(_)

### ISSUE THREAD

**Issue by lopopolo** [rust-lang/rust-clippy#5175]
The `map_flatten` lint seems to only apply to iterators:

https://github.com/rust-lang/rust-clippy/blob/41d90d3b8e633ab53005b8f7459dd10e4526bd41/clippy_lints/src/methods/mod.rs#L406-L422

For `Option`, map + flatten can be replaced with and_then.

see for example this code:

```rust
captures.get(index).map(Option::as_deref).flatten()
```

which can be more succinctly written as:

```rust
captures.get(index).and_then(Option::as_deref)
```

**Comment by flip1995** [comment]
This is only the case, when `get(..)` returns an `Option<Option<_>>` type, right?

More general:

```rust
let x: Option<Option<_>> = Some(Some(42));
x.map(|_: Option<_>| {
    // ...
    y // Option<_>
}).flatten()
```

**Comment by lopopolo** [comment]
In this case get returns an `Option<&Option<Vec<u8>>>`

**Comment by Toxyxer** [comment]
Hi, Could I take a look at this issue?

**Comment by flip1995** [comment]
Sure, go ahead!
