### ISSUE TITLE
Suggest `Option::map_or`(_else) for `if let Some { y } else { x }`

### ISSUE THREAD

**Issue by Luro02** [rust-lang/rust-clippy#5203]
This code:
```rust
if let Some(v) = optional {
    v == &"hello"
} else {
    false
}
```

could be optimized to

```rust
optional.as_ref().map_or(false, |v| v == &"hello")
```

[[playground]](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=%23!%5Bwarn(clippy%3A%3Aall)%5D%0A%0Afn%20is_hello(optional%3A%20%26Option%3C%26str%3E)%20-%3E%20bool%20%7B%0A%20%20%20%20if%20let%20Some(v)%20%3D%20optional%20%7B%0A%20%20%20%20%20%20%20%20v%20%3D%3D%20%26%22hello%22%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20false%0A%20%20%20%20%7D%0A%7D%0A%0Afn%20is_hello_opt(optional%3A%20%26Option%3C%26str%3E)%20-%3E%20bool%20%7B%0A%20%20%20%20optional.as_ref().map_or(false%2C%20%7Cv%7C%20v%20%3D%3D%20%26%22hello%22)%0A%7D%0A%0Afn%20main()%20%7B%0A%20%20%20%20let%20optional%20%3D%20Some(%22hello%22)%3B%0A%20%20%20%20dbg!(is_hello(%26optional))%3B%0A%20%20%20%20dbg!(is_hello_opt(%26optional))%3B%0A%7D)

**Comment by JarredAllen** [comment]
I can take care of implementing this.
