### ISSUE TITLE
false positive on blacklisted_name (bar)

### ISSUE THREAD

**Issue by djugei** [rust-lang/rust-clippy#5225]
https://rust-lang.github.io/rust-clippy/master/index.html#blacklisted_name

bar is actually a good name for a progressbar, maybe only disallow bar as name if a foo is also found in the same file.

**Comment by flip1995** [comment]
-1 (still)

This already came up in #4366.

I'm still against allowing it by default, with the same reasoning I gave in #4366. But since this came up  again, I leave this issue open for discussion.

**Comment by djugei** [comment]
yeah thats exactly my usecase too. i think removing the lint on bar, but leaving it on foo and baz would be good.

**Comment by ijijn** [comment]
I just came across this issue today too. I'm writing music software, where `bar` is a very natural word to use for a division of time. It's certainly not a `progress_bar`, while `measure` is too long and distinctly American to use comfortably. I have no problem with blacklisting those other nonsensical ones.

**Comment by flip1995** [comment]
Alright, Î think this was requested enough now, so that we can allow it by default.

**Comment by ijijn** [comment]
Hooray, thank you!

**Comment by flip1995** [comment]
If someone wants to take this issue, the only thing to do here is:

1. Remove `bar` from here:
https://github.com/rust-lang/rust-clippy/blob/742706511c9f33c6a0d4380392e513e5249057e3/clippy_lints/src/utils/conf.rs#L110

2. Adapt the tests:
    Remove this (or add a comment, that links this issue and bar shouldn't be linted):
    https://github.com/rust-lang/rust-clippy/blob/742706511c9f33c6a0d4380392e513e5249057e3/tests/ui/blacklisted_name.rs#L15
    Replace every other occurrence of `bar` in the test file with `quux`:
    https://github.com/rust-lang/rust-clippy/blob/742706511c9f33c6a0d4380392e513e5249057e3/tests/ui/blacklisted_name.rs#L28
    https://github.com/rust-lang/rust-clippy/blob/742706511c9f33c6a0d4380392e513e5249057e3/tests/ui/blacklisted_name.rs#L33
    https://github.com/rust-lang/rust-clippy/blob/742706511c9f33c6a0d4380392e513e5249057e3/tests/ui/blacklisted_name.rs#L38

**Comment by ijijn** [comment]
Many thanks for the detailed steps, @flip1995. How does this look?
