### ISSUE TITLE
Shared code in if and else

### ISSUE THREAD

**Issue by Luro02** [rust-lang/rust-clippy#5234]
The lint would trigger if the `if`, `else if` and `else` clasues have the same code in all branches.

---

```rust
let mut result = "";
let is_something = 20;

if is_something == 20 {
    result = "hello";

    println!("yes");
} else {
    result = "hello";

    println!("nope!");
}

println!("{}", result);
```

could be optimized to

```rust
let mut result = "";
let is_something = 20;

result = "hello";

if is_something == 20 {
    println!("yes");
} else {
    println!("nope!");
}

println!("{}", result);
```

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=%23!%5Bwarn(clippy%3A%3Aall)%5D%0A%0Afn%20main()%20%7B%0A%20%20%20%20let%20mut%20result%20%3D%20%22%22%3B%0A%20%20%20%20let%20is_something%20%3D%2020%3B%0A%20%20%20%20let%20other%20%3D%20true%3B%0A%0A%20%20%20%20%2F%2F%20this%20if%20is%20to%20silence%20some%20compiler%20warnings%0A%20%20%20%20if%20other%20%7B%0A%20%20%20%20%20%20%20%20if%20is_something%20%3D%3D%2020%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20result%20%3D%20%22hello%22%3B%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20println!(%22yes%22)%3B%0A%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20result%20%3D%20%22hello%22%3B%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20println!(%22nope!%22)%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%0A%20%20%20%20println!(%22%7B%7D%22%2C%20result)%3B%0A%7D%0A)

**Comment by xFrednet** [comment]
I would like to work on this 🙃.

@rustbot claim
