### ISSUE TITLE
all options passed after the '--' are ignored

### ISSUE THREAD

**Issue by YruamaLairba** [rust-lang/rust-clippy#5251]
Hi, i'm just starting to use clippy and i have trouble to configure lint from CLI. On a project, i get exactly the same result when i'm doing:
- `cargo clippy`
- `cargo clippy -- -D warnings` (i was expecting warnings treated as error)
- `cargo clippy -- -A clippy::all` (i was expecting no warning at all)
- `cargo clippy -- WhatEverIPutHereItHasNoEffect` (i was expecting an error saying my option is wrong)
Do i something wrong ?

rustup toolchain list
stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

cargo clippy -V
clippy 0.0.212 (69f99e7 2019-12-14)

**Comment by matthiaskrgr** [comment]
This is probably https://github.com/rust-lang/cargo/issues/7862
If you
`find  | grep \.rs$ | xargs touch` and then run your clippy command again, do you get the expected behaviour?

**Comment by YruamaLairba** [comment]
I looked at rust-lang/cargo#7862, seems it's the same issue. Using `find | grep \.rs$ | xargs touch` between clippy works.

**Comment by flip1995** [comment]
Closing in favor of rust-lang/cargo#7862
