### ISSUE TITLE
Remove/Deprecate the REPLACE_CONSTS lints

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust-clippy#5346]
The associated constants `MIN/MAX` on integer primitives is prefered and stabilized in Rust 1.43.
The module constants and `::{min,max}_value` is soft-deprecated now and will be deprecated
in the next few releases.
As such, the `REPLACE_CONSTS` lints is deprecated. It could be removed and move to deprecated group.

cc #2380.

**Comment by flip1995** [comment]
cc rust-lang/rust#68952
