### ISSUE TITLE
comparison_chain suggestion can be a performance regression

### ISSUE THREAD

**Issue by sourcefrog** [rust-lang/rust-clippy#5354]
clippy 0.0.212 (23549a8c 2020-03-16)
rustc 1.44.0-nightly (f509b26a7 2020-03-18) on macos

clippy suggests rewriting some chained if/else blocks in my code, like so 

```diff
-    let y = l[0];
-    if y > x {
-        return 0;
-    } else if y == x {
-        b = 0;
-    } else {
-        a = 1;
-        c = 1;
-    }
+    match l[0].cmp(&x) {
+        Ordering::Greater => return 0,
+        Ordering::Equal => b = 0,
+        Ordering::Less => {
+            a = 1;
+            c = 1;
+        }
+    };
```

This is semantically the same and arguably cleaner. But, according to a Criterion microbenchmark, Clippy's suggestion is significantly slower than the chained comparisons.

It looks like this might be related to the simple comparison being inline, versus the `cmp` remaining as 

        call    core::cmp::impls::<impl core::cmp::Ord for i32>::cmp

Probably in many cases the performance difference isn't noticeable and it's better style, but perhaps there should at least be a caveat in the Clippy docs.

(Also, ideally the compiler should be smart enough to make it just as fast.)

**Comment by xtqqczze** [comment]
https://github.com/rust-lang/rust-clippy/pull/6390 did not fix this issue, it only flagged it in the documentation.

@sourcefrog is there still a performance regression with latest rustc?

**Comment by xtqqczze** [comment]
> ```
>     call    core::cmp::impls::<impl core::cmp::Ord for i32>::cmp
> ```

Looks like this is still an issue: [goldbolt.org](https://godbolt.org/z/s6j3WKnjG)

**Comment by scottmcm** [comment]
That godbolt link doesn't run the optimizer, so of course it's different, but isn't relevant.  If worse perf in debug was a reason to not lint, then all the "use an iterator" lints would have to be removed too.

Here's a better link: https://godbolt.org/z/6dP4je7Eb

Looks like LLVM's middle-end optimizes that perfectly well -- it gives exactly the `llvm.ucmp.i8.i8` intrinsic and the `switch` as you'd expect -- but LLVM's x64 backend doesn't optimize it as well as it could.  You might want to file an LLVM issue about it.

**Comment by xtqqczze** [comment]
@sourcefrog It looks look codegen improved in Rust 1.87: https://godbolt.org/z/ETaa5W6s4

It may be the case that there is not currently significant performance issue and that the statement:

```
The match statement may be slower due to the compiler not inlining the call to cmp. See issue #5354
```

can be removed from comparison_chain docs.

**Comment by xtqqczze** [comment]
> It looks like this might be related to the simple comparison being inline, versus the `cmp` remaining as
> 
> ```
>     call    core::cmp::impls::<impl core::cmp::Ord for i32>::cmp
> ```

@scottmcm This `cmp` call appears to have always been inlined in _optimised_ builds.

**Comment by xtqqczze** [comment]
Codegen still could be significantly improved on aarch64:

https://www.diffchecker.com/obdkjHd2/

**Comment by Jarcho** [comment]
https://godbolt.org/z/Tcre6Per6 shows off the inability to optimize better. The call to `cmp` isn't terrible, but it also isn't good.

**Comment by xtqqczze** [comment]
> https://godbolt.org/z/Tcre6Per6 shows off the inability to optimize better. The call to `cmp` isn't terrible, but it also isn't good.

@Jarcho I don't think the codegen is so bad as to require a note in docs, removed the note in https://github.com/rust-lang/rust-clippy/pull/16422

**Comment by Jarcho** [comment]
https://godbolt.org/z/3j5snjoEW It's always been marginally worse.

Note I don't trust that the original benchmark was done well. It is very hard to run micro benchmarks in a way that actually shows the perf difference. Criterion doesn't go anywhere near far enough to demonstrate the difference between theses two asm listings. See the large difference something like (BOLT)[https://github.com/llvm/llvm-project/tree/main/bolt] can make for one reason why this is difficult.

**Comment by sourcefrog** [comment]
From memory (it has been 6 years) I originally noticed a regression in a larger benchmark on a release build of my code, and then localized it to this change. 

Was it a really rigorous benchmark, I don't know, maybe not. 

If rustc and LLVM improved enough in the meantime that there's unlikely to be a disadvantage to using `match` that's great.

**Comment by scottmcm** [comment]
My guess is that it improved in 1.87 thanks to https://github.com/rust-lang/rust/pull/133984

We previously didn't have a reliable way to communicate to LLVM what `cmp` was.  They then added new intrinsics for signed and unsigned integer `Ord::cmp` (see https://discourse.llvm.org/t/rfc-add-3-way-comparison-intrinsics/76685?u=scottmcm if you're curious), which rustc now emits.  There are probably some small imperfections in how that intrinsic is actually codegenned, but there shouldn't be any major differences any more.  In particular, it's *much* better at things like the `cmp(x, y) == Greater` ⇒ `x > y` transformations than it used to be.

**Comment by scottmcm** [comment]
Oh, and a fix PR is already open in LLVM to address the remaining assembly issue: https://github.com/llvm/llvm-project/pull/176582 🙂
