### ISSUE TITLE
match_single_binding triggers in generated code

### ISSUE THREAD

**Issue by znewman01** [rust-lang/rust-clippy#5362]
Hi! I'm using [rust-derivative](https://github.com/mcarton/rust-derivative), which appears to generate code that triggers `match_single_binding`; see [rust-derivative#58](https://github.com/mcarton/rust-derivative/issues/58) for a full report (version info, etc.).

The developer considers this a Clippy bug, and I'm inclined to agree: the cited reason for this lint is "readability and needless complexity", which seems okay for macro-generated code. The discussion in #4949 seems to back me up.

P.S. Thanks for a great tool!

**Comment by flip1995** [comment]
This lint should be disabled for external macros. cc @ThibsG

**Comment by ThibsG** [comment]
Issue has been fixed on rust-derivative in https://github.com/mcarton/rust-derivative/pull/71.

I believe we can close this issue.

**Comment by flip1995** [comment]
This lint should still not trigger in external macros.

**Comment by ThibsG** [comment]
Oh right, it should be extended, it only checks for `check_expr` case
