### ISSUE TITLE
idea: put link to github ticket search into "known problems" field

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-clippy#5386]
In a perfect world, the `Known problems` section of a lint at 
https://rust-lang.github.io/rust-clippy/master/index.html would reflect issues we have about that lint (false positives / false negatives, limitations etc) but it rarely gets updated.

I wonder if we could put a link there which automatically finds all open issues about that lint, like this:
[Known problems](https://github.com/rust-lang/rust-clippy/issues?q=is%3Aissue+is%3Aopen+cognitive_complexity)

`[Known problems](https://github.com/rust-lang/rust-clippy/issues?q=is%3Aissue+is%3Aopen+${LINT_NAME})`

**Comment by flip1995** [comment]
cc #5049 would maybe help. But I didn't got back to it, since I'm not sure anymore where exactly I want to go with that.

**Comment by xFrednet** [comment]
This is a nice idea 👍 

I think the link should also include closed issues in case someone has reported a issue which is actually working as intended. That could reduce duplicate reports. The new link template would be
* `[search on Github](https://github.com/rust-lang/rust-clippy/issues?q=is%3Aissue+${LINT_NAME})`

@rustbot claim
