### ISSUE TITLE
Integer division lint should allow non-zero constant denominators

### ISSUE THREAD

**Issue by hrydgard** [rust-lang/rust-clippy#5391]
The major driver behind the `clippy::integer_division` lint is presumably to enforce use of checked_div, which makes division-by-zero exceptions impossible.

However, clippy::integer_division also bans code like this:

    triangle_count = (indices.len() as u32) / 3;

Since the denominator is constant, this is fine - it'll never divide by zero. Plus, it'll end up a multiplication anyway in the optimized code, since any division by an integer constant can be turned into a multiplication at compile time.

So either `clippy::integer_division` should be relaxed to allow constant non-zero denominators, or an alternative `clippy::integer_division_by_non_const` or something should be added.

**Comment by Wodann** [comment]
Apart from division by zero, there is also the loss of the _remainder_ when doing integer division. That's the purpose of this lint, as far as I can tell:

```What it does
Checks for division of integers

Why is this bad
When outside of some very specific algorithms, integer division is very often a mistake because it discards the remainder.
```

Source: https://rust-lang.github.io/rust-clippy/master/index.html#integer_division

**Comment by flip1995** [comment]
The lint works as intended. It is a restriction lint, that _restricts_ the language, by disallowing all integer divisions.

**Comment by hrydgard** [comment]
I do realize it works as intended, I just felt it would be useful to have the same thing but accepting constant denominators too, since those are safer. Of course not a critically important thing though.
