### ISSUE TITLE
Ubuntu 32 bit CI build is failing with broken apt packages

### ISSUE THREAD

**Issue by phansch** [rust-lang/rust-clippy#5477]
Since around 12:00 UTC today, the Ubuntu 32 bit build started consistently failing with the following error while installing apt packages:

<pre>
The following packages have unmet dependencies:
 libgit2-dev:i386 : Depends: libgit2-26:i386 (= 0.26.0+dfsg.1-1.1ubuntu0.2) but it is not going to be installed
                    Depends: libz-dev:i386
                    Depends: libcurl4-gnutls-dev:i386 but it is not going to be installed
                    Depends: libssh2-1-dev:i386 but it is not going to be installed
                    Depends: libhttp-parser-dev:i386 but it is not going to be installed
 libssl-dev:i386 : Depends: libssl1.1:i386 (= 1.1.1d-1+ubuntu18.04.1+deb.sury.org+2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
</pre>

This is reproducible in a fresh VM with: `sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install libgit2-dev:i386` so it's not an issue with GHA, but with the Ubuntu packages.

I can't tell much from that apt error and I don't have time to dig further into this now, so if someone wants to have a look, that would be great!

For now I've closed the tree, but we may just want to disable the 32 bit build and re-open the tree if the issue persists.

[Full CI Log](https://github.com/rust-lang/rust-clippy/runs/592220856#step:3:92)

cc @matthiaskrgr @flip1995

**Comment by matthiaskrgr** [comment]
Testing if a system upgrade somehow solves the problem in https://github.com/rust-lang/rust-clippy/pull/5478 
I don't have a lot of different ideas right now though :/

**Comment by flip1995** [comment]
Since this CI bug should be temporary, we could disable the 32 bit check, since lints that depend on this check are rare and no PR currently touches such a lint.

**Comment by flip1995** [comment]
"Fixed" in https://github.com/rust-lang/rust-clippy/pull/5517
