### ISSUE TITLE
Detecting equivalent code paths

### ISSUE THREAD

**Issue by srikwit** [rust-lang/rust-clippy#5502]
Hi Team,
I wanted to know if there is a way to detect equivalent code paths such as following:
```
fn add1(a: i32, b: i32) -> i32 {
    a + b
}

fn add2(a: i32, b: i32) -> i32 {
    a + b
}

fn main() {
    println!("{}", add1(1, 2));
    println!("{}", add2(1, 2));
}
```
If you run `clippy`, it will not complain but only a manual review is needed for even a simple case.
Can such a detection also be implemented across crates?

**Comment by flip1995** [comment]
This (especially cross-crate) would be a global analysis, which Clippy does and will not do. In your example, Clippy would have to compare functions, which is easy if there are only 2, but is combinatorially complex in general.

Do you have other examples, where such a lint would trigger?

**Comment by srikwit** [comment]
@flip1995 I have shared the example based on the following lint that I had performed:
```
pub fn make_stats(&mut self, time: DateTime<Utc>) {
        let rounded_time = time.timestamp() - time.timestamp() % 3600;
        self.stats
            .entry(rounded_time)
            .and_modify(|e| *e += 1)
            .or_insert(1);
    }
    pub fn make_stats_from_timestamp(&mut self, timestamp: i64) {
        let rounded_time = timestamp - timestamp % 3600;
        self.stats
            .entry(rounded_time)
            .and_modify(|e| *e += 1)
            .or_insert(1);
    }
```
The two functions perform similar operations on an i64 with different parameter types (DateTime<Utc> and i64). I have shared a simpler variant of this where the types are the same so it could be easier to detect. In the case that I encountered, It is possible to detect the type and further reduce the lines but that can be a different issue.

I was hoping for a warning regarding the functions doing similar transformations.

**Comment by flip1995** [comment]
Yeah, Clippy can't do this, since this would require a global analysis of the code. Sorry.
