### ISSUE TITLE
--fix fails sometimes if clippy and sccache used: "error: Unrecognized option: \'E\'\n\n

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-clippy#5507]
https://github.com/rust-random/rand
When checking the rand crate for example with `cargo clippy -Zunstable-options --fix` while using sccache-git, the following error is thrown:
```
    Checking ppv-lite86 v0.2.6
    Checking rand_core v0.5.1 (/home/matthias/vcs/github/rand/rand_core)
error: failed to execute compile
caused by: Compiler not supported: "error: Unrecognized option: \'E\'\n\n"
error: could not compile `rand_core`.

To learn more, run the command again with --verbose.
```
The strange thing is that `-E` is never passed according to `--verbose`.

Discord logs of when we tried to find out what is going on:
https://discordapp.com/channels/442252698964721669/459149871191031810/701833971608059906

**Comment by phansch** [comment]
@matthiaskrgr I believe this can be closed with https://github.com/mozilla/sccache/pull/728 being merged?

**Comment by matthiaskrgr** [comment]
Right, I forgot to check back on that.
