### ISSUE TITLE
redundant_field_names can't be allowed

### ISSUE THREAD

**Issue by e-oz** [rust-lang/rust-clippy#5515]
Hello.

I do like to write `Foo { bar: bar }` and I don't like to write `Foo { bar }`.
So I'm trying to turn off the "redundant_field_names" lint:

```
#![cfg_attr(feature = "cargo-clippy", allow(redundant_field_names))]
```
but it has no effect, I'm still getting spammed by this lint.

Please help.

Rust version: 1.44.0-beta.752

**Comment by dtolnay** [comment]
Duplicate of #5356.

**Comment by e-oz** [comment]
Please merge this, 1.44.0-beta.4 and still this bug.

**Comment by e-oz** [comment]
Thank you very much, works fine in 1.45.0-beta.3359
