### ISSUE TITLE
Is it OK that `perf` lints' suggestion implicitly fix broken original code?

### ISSUE THREAD

**Issue by rail-rain** [rust-lang/rust-clippy#5532]
The suggestion of `manual_memcpy` fixes a bug when the range's `end` is the length of a slice and `offset` is added to the index that indexes that slice.

For example, when `manual_memcpy` is given this:

https://github.com/rust-lang/rust-clippy/blob/07dd5fada91b3a3219febb91c4dd0932c384f9c7/tests/ui/manual_memcpy.rs#L16-L19

… it will print this:

https://github.com/rust-lang/rust-clippy/blob/07dd5fada91b3a3219febb91c4dd0932c384f9c7/tests/ui/manual_memcpy.stderr#L19

Since the applicability of `manual_memcpy` is `Unspecified`, it won't fix it automatically; however, I feel a little bit odd to suggest the code whose behaviour differ from the original.

**Comment by flip1995** [comment]
If the suggestion changes the semantics, it is a bug in the suggestion generation. In this case, it doesn't change the semantics IMO. Both the original code and the suggestion will panic, even though for slightly different reasons. What am I missing?

**Comment by rail-rain** [comment]
Oh, sorry __I__ missed the fact that the suggested code will panic because of 'destination and source slices have different lengths' somehow. Although I'm a bit unsure if the semantics doesn't change, I think it's fine as Clippy can not know the author's actual intention. Thank you for the answer. I will close this issue.

**Comment by flip1995** [comment]
If you want, you can open an issue requesting a new lint, that warns on such for loops, that loops up to `i in y..x.len()`, but then index `x[i + o]` with an offset `o`.

**Comment by rail-rain** [comment]
That would be nice. I'll think about it. Thanks.
