### ISSUE TITLE
mem::replace -> mem::take lint is too aggressive 

### ISSUE THREAD

**Issue by benesch** [rust-lang/rust-clippy#5586]
Clippy will suggest replacing

```rust
let x = mem::replace(&mut thing, Thing::default());
```

with:

```rust
let x = mem::take(&mut thing);
```

This is great! But it will also suggest replacing

```rust
mem::replace(&mut thing, Thing::default());
```

with:

```rust
mem::take(&mut thing);
```

This is not great. The construction using `mem::replace` in the second case is much clearer IMO as it indicates that the function is being executed for its side effects. The construction using `mem::take` looks like a mistake.

Would you folks be open to making the lint not apply in the second case?

**Comment by flip1995** [comment]
So basically only suggest using `mem::take` when the replaced `thing` is not assigned to anything?

**Comment by benesch** [comment]
Exactly. Arguably clippy should suggest `*thing = Thing::default()` in the latter case.

**Comment by Luro02** [comment]
> This is great! But it will also suggest replacing
>
> ```rust
> mem::replace(&mut thing, Thing::default());
> ```
> 
> with:
> 
> ```rust
> mem::take(&mut thing);
> ```

It might be useful to have a clippy lint that suggests replacing the latter with the former, because like you said the latter looks like a mistake (it is harder to read, because there is an implicit replacement of the field with default that is not obvious by the method name).

**Comment by taiki-e** [comment]
> ```rust
> mem::replace(&mut thing, Thing::default());
> ```

Given that `mem::replace` is `#[must_use]` (https://github.com/rust-lang/rust/pull/71256), the usage that ignores `mem::replace`'s return value is probably not the recommended way.

**Comment by benesch** [comment]
Yeah, looks like the upstream recommended way is just to assign:

```
*thing = Thing::default()
```

**Comment by camsteffen** [comment]
Since `mem::replace` was given `#[must_use]`, perhaps the `mem_replace_with_default` lint should simply ignore cases where the result isn't used. The `#[must_use]` lint will provide the correct suggestion.
