### ISSUE TITLE
Recommending `.to_owned()` instead of `.to_string()`

### ISSUE THREAD

**Issue by ClementNerma** [rust-lang/rust-clippy#5600]
I currently have a place in my code when I accidently converted an `&str` to a `String` using the `format!` macro, which is not the best thing to do. So when I run Clippy it reported this:

```
warning: useless use of `format!`
   --> mrvm_tools/src/exceptions/native.rs:137:42
    |
137 |             Self::DivisionOrModByZero => format!("<long message>"),
    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using `.to_string()`: `"<long message>".to_string()`
```

The problem here is the recommandation of `.to_string()`. As you can find in many explanations on vairous forums, `.to_owned()` is preferred to `.to_string()` as the latter may result in additional allocations to perform the conversion, while `.to_owned()` directly converts the value to a `String`.

So I think the lint should display this instead:

```
warning: useless use of `format!`
   --> mrvm_tools/src/exceptions/native.rs:137:42
    |
137 |             Self::DivisionOrModByZero => format!("<long message>"),
    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using `.to_owned()`: `"<long message>".to_owned()`
```

If I miss a reason that makes Clippy recommend `.to_string()` over `.to_owned()` please let me know, I might be mistaken here but I think it would be better to recommend `.to_owned()`.

**Comment by ebroto** [comment]
If I'm not mistaken that *used* to be the case, but now it's equally performant and the "officially recommended" way (in the book) to convert to `String`.

See this thread [comment](https://users.rust-lang.org/t/to-string-vs-to-owned-for-string-literals/1441/5), [PR](https://github.com/rust-lang/rust/pull/32586) and the [book](https://doc.rust-lang.org/1.43.0/book/ch08-02-strings.html#creating-a-new-string)

**Comment by ClementNerma** [comment]
Alright it seems I indeed overlooked that.
Thanks for your comment :)
