### ISSUE TITLE
Consider reinstating str_to_string and string_to_string

### ISSUE THREAD

**Issue by ndmitchell** [rust-lang/rust-clippy#5610]
The rules `str_to_string` and `string_to_string` have both been removed, so things like `"foo".to_string()` can no longer be warned for. I find those warnings very valuable, and have been "manually" linting them in code reviews. In particular, it's useful to distinguish between converting something to a string (relatively rare. deserves special attention in code review) and managing memory so it has the right form (very common, can mostly be glossed over). I think it's reasonable that these hints are off-by-default, and in the pedantic category, but they are certainly something I'd turn on.

FWIW, I went through clippy to try and implement the above hints, while is when I found they had previously been implemented and removed.

**Comment by flip1995** [comment]
The intentions of those lints were, that `to_owned`/`clone` should be used, since they are more efficient. This isn't the case anymore and which function to use doesn't matter.

`redundant_clone` exists to detect unnecessary clones of strings besides others. Do you have an example in mind, where `to_string` is not necessary?

**Comment by ndmitchell** [comment]
There's no performance benefit. But `to_string` does a multitude of things - I don't know if I'm converting an `isize` or cloning a string. In contrast, `to_owned`/`clone` do relatively specific things. Therefore, for human readability, I often ask in code reviews for `foo.to_string()` to be replaced with `foo.clone()` if that's the underlying effect of the operation. It's never not necessary, just easier to follow if you use a function that only does a small subset of what to_string does.

**Comment by flip1995** [comment]
Fair point. I think we can re-add these as  `restriction` lints

**Comment by PunitLodha** [comment]
I would like to work on this. From what I can gather from the conversation, I have to add the two lints to the restriction lints. I found the PR #795 which deprecated the lints, but i can't find the lint files itself for both the lints. I also tried looking through git history for any file named str_to_string, but no success. Any way i can find those files, so that i can add them to the restriction lints?

**Comment by flip1995** [comment]
You won't have much luck finding those files, since the repo was at least restructured 2 times since then. You will have to reimplement those lints.

**Comment by PunitLodha** [comment]
I think i am missing something but I can't find any variant for String in `ty::TyKind`. There's a `Str` variant for string slice, but no variant for the String type. So is there any way to know if method is being called on a String?

**Comment by flip1995** [comment]
See https://github.com/rust-lang/rust-clippy/blob/6b01c39e644dbe8b358e6c02a51169aa1fbef561/clippy_lints/src/methods/mod.rs#L1903

**Comment by julianskartor** [comment]
> There's no performance benefit. But `to_string` does a multitude of things - I don't know if I'm converting an `isize` or cloning a string. In contrast, `to_owned`/`clone` do relatively specific things. Therefore, for human readability, I often ask in code reviews for `foo.to_string()` to be replaced with `foo.clone()` if that's the underlying effect of the operation. It's never not necessary, just easier to follow if you use a function that only does a small subset of what to_string does.

Interesting. I actually thought about this the other way around. i.e. `to_string` tells me clearly I receive a `String` but I have no such information around `clone`.

**Comment by ndmitchell** [comment]
> to_string tells me clearly I receive a String but I have no such information around clone.

Generally I use the inlay type hints in Rust Analyzer to figure that out. You can think of `clone` as being a set of very narrow pipes (one for each type), whereas `to_string` is a big funnel (all types in, always `String` out). Anything that acts like a funnel tends to allow more programs to type check than you might like, whereas separate pipes keep things separate and don't have that issue.
