### ISSUE TITLE
False positive in should_implement_trait

### ISSUE THREAD

**Issue by djugei** [rust-lang/rust-clippy#5617]
It tells me to impl Iterator. Iterator does not support my use-case.:

    pub fn next<'b>(&'b mut self) -> Option<&'b mut S> { }

Rust iterators are not streaming, i.e. an item can live even after .next() has been called a second time. This is a streaming iterator. As such i think the name is perfectly fine.

Maybe check for life-times in the signature to avoid this false positive.

**Comment by montrivo** [comment]
I'd like to take a stab at this one.
