### ISSUE TITLE
lint iterator.map(|x| x)

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-clippy#5626]
This was most likely left over after some refactoring and can be removed entirely (at least I can't think of a reason to have `.map(|x| x)` in the code right now..)

**Comment by llogiq** [comment]
Note that this will apply type adjustments on `x` where applicable. However, the `redundant_closure` lint already has a check for adjustments which can be copied to this new lint.

**Comment by wangtheo** [comment]
I'd like to try my hand at this!

**Comment by giraffate** [comment]
Hi, is this issue already resolved? If so, it would be better to close this.

**Comment by JohnTitor** [comment]
Closing in favor of #5694.
