### ISSUE TITLE
Support '--features' in virtual workspace?

### ISSUE THREAD

**Issue by kaiwk** [rust-lang/rust-clippy#5649]
It seems `--features` flag work in crate #4860, but doesn't work in the root of virtual workspace.

**Comment by flip1995** [comment]
See https://github.com/rust-lang/cargo/issues/5364

Clippy does not handle features at all, but just passes every feature flag to cargo and lets cargo handle this. If you get different behavior from `cargo check --features abc` than `cargo clippy --features abc`, please report back.
