### ISSUE TITLE
Lint suggestion: use .collect() instead of ::from_iter()

### ISSUE THREAD

**Issue by NieDzejkob** [rust-lang/rust-clippy#5679]
When the user writes, say, `HashMap::from_iter($iter_expr)`, suggest `$iter_expr.collect()`.

This would be primarily beneficial to beginners. In fact, I've just seen this in the wild on Exercism ;)

**Comment by flip1995** [comment]
See also the documentation of `FromIterator`: https://doc.rust-lang.org/std/iter/trait.FromIterator.html

**Comment by NieDzejkob** [comment]
True, the documentation already mentions this, but it is not visible when you find the method in the list of traits a type implements.

Actually, I just realized that this is more general. I have also seen people explicitly use `std::ops::Add::add`, without realizing that this is equivalent to using the `+` operator.

**Comment by siyopao** [comment]
Would it be okay if I gave this one a try?

**Comment by NieDzejkob** [comment]
Go ahead!

**Comment by pitiK3U** [comment]
@siyopao Still working on it or can I give it a try?

**Comment by siyopao** [comment]
Hi @pitiK3U, sorry, yes, please go ahead.
