### ISSUE TITLE
New lint: Suggest `str::strip_*` over `str::{starts,ends}_with` and slicing it

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust-clippy#5734]
### Categories: Performance, Correctness, complexity

Using [`str::strip`] removes the panic code inserted by slicing with pattern length.
Also it removes the need for duplicating/storing pattern used by `str::{starts,ends}_with` and (`str[len..]` or `str[..len]`).
Which it may removes the typing mistakes (do not repeat yourself).

### Auto-apply suggestion ability

- [Unspecified](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/enum.Applicability.html#variant.Unspecified)
- It's hard to make correct suggestion because:
  * it requires changing code/block structure.
  * it introduces a new binding which you have to give a name.

### What it does

Suggest using `strip_{prefix,suffix}` over  `str::{starts,ends}_with` and slicing by pattern's length.

### Known problems

None.

### Example

```rust
let s = "hello, world!";
if s.starts_with("hello, ") {
    // Or s[7..] ...
    assert_eq!(s["hello, ".len()..].to_uppercase(), "WORLD!");
}
```

Could be written as:

```rust
let s = "hello, world!";
if let Some(tail) = s.strip_prefix("hello, ") {
    assert_eq!(tail.to_uppercase(), "WORLD!");
}
```

[`str::strip`]: https://doc.rust-lang.org/nightly/std/primitive.str.html#method.strip_prefix

**Comment by mikerite** [comment]
I started on this. I should have a pull request ready sometime soon.
