### ISSUE TITLE
Some(_) is not equivalent to is_some()

### ISSUE THREAD

**Issue by josh65536** [rust-lang/rust-clippy#5746]
I found a situation in which `if let Some(_) = func()` and `if func().is_some()` don't do the same thing. In particular, the latter deadlocks while the former doesn't. This is relevant for the redundant_pattern_matching lint. I replicated this behavior in debug and release mode with rustc 1.44.0.

[Here is the situation](https://github.com/josh65536/rust-is-some-deadlock/blob/master/src/main.rs)

**Comment by flip1995** [comment]
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3041ab662259926c141ac1e47875c80e) so it can be run directly.

I think the best thing you can do here is to just allow the lint in this case. This will probably be a really hard fix, but we should definitely document this.

**Comment by mikerite** [comment]
The way I see this...
`if let Some(_) = func()` keeps the clone around until the end of the block which the code gets to finish the drop.
`if let func.is_some()` immediately drops the clone. Now the drop runs for the clone you just created but the cache lock hasn't been released yet. 
I'm not 100% sure to be honest....

According to the mutext docs "The exact behavior on locking a mutex in the thread which already holds the lock is left unspecified. However, this function will not return on the second call (it might panic or deadlock, for example)." If you're going to lock in a drop _and_ make clones you need to be really careful.

In any case, maybe we can check if the type of `func()` implements drop and not lint in this case.

**Comment by mikerite** [comment]
Thinking a little more. It would have to be a _temporary_ value that implements drop.
