### ISSUE TITLE
clippy redundant pattern matching suggestion not compiling

### ISSUE THREAD

**Issue by BenjaminRi** [rust-lang/rust-clippy#5766]
I ran ` cargo clippy` on the following piece of code:

```rust
fn main() {
	let s = "foo";
	if let Ok(_) = &s[1..s.len()].parse::<u32>() {
	}
}
```

Clippy (correctly) detects a redundant pattern matching and (incorrectly) suggests replacing `if let Ok(_) = &s[1..s.len()].parse::<u32>()` with `if &s[1..s.len()].parse::<u32>().is_ok()`. But that snippet does not compile if you insert it. It should be replaced with `if s[1..s.len()].parse::<u32>().is_ok()` (dropping the reference), that is the correct suggestion.

### Meta

Tested on `clippy`:
0.0.212 (bb37a0f9 2020-06-16)

**Comment by JarredAllen** [comment]
I can fix this.

**Comment by JarredAllen** [comment]
I believe this issue can be closed, as it has been fixed.
