### ISSUE TITLE
Lint suggestion: Replace `.chars().enumerate()` with `.char_indices()` for `str` slices

### ISSUE THREAD

**Issue by ansimita** [rust-lang/rust-clippy#5779]
### What it does

Suggest instances where `.chars().enumerate()` should be replaced with `.char_indices()` instead for `str` slices

### Categories

- Kind: `clippy::style`

### Drawbacks

None.

### Example

```rust
for (i, c) in s.chars().enumerate() {
    println!("{}: {}", i, c);
}
```

Could be written as:

```rust
for (i, c) in s.char_indices() {
    println!("{}: {}", i, c);
}
```

### Links

- [`Iterator.enumerate()`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.enumerate)
- [`str.chars()`](https://doc.rust-lang.org/std/primitive.str.html#method.chars)
- [`str.char_indices()`](https://doc.rust-lang.org/std/primitive.str.html#method.char_indices)

**Comment by mikerite** [comment]
These are only equivalent if the chars are all one byte each.
[Playground example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=964d4c920b840dee32f7879b63e84bb5)

**Comment by messense** [comment]
I think this is relevant when the index is used by subsequent string slice like `s[i..]` or `s.split_at(i)`, here is a real world example https://github.com/RustPython/RustPython/pull/4444.

Can someone re-open this issue? cc @Jarcho @flip1995

**Comment by not-my-profile** [comment]
I think the check would have to be more sophisticated since there are legitimate use cases for `.chars().enumerate()`.

I am not sure if clippy is sophisticated enough to track data flow (which would be necessary to detect the RustPython panic you mention).

**Comment by Jarcho** [comment]
That's different enough that it should be a new issue.

**Comment by messense** [comment]
@Jarcho Thanks for the suggestion, opened https://github.com/rust-lang/rust-clippy/issues/10202
