### ISSUE TITLE
Lint double negation `!count != 0`

### ISSUE THREAD

**Issue by idubrov** [rust-lang/rust-clippy#5794]
### What it does

I think, clippy should lint the following code:
```rust
if !count != 0 {
}
```

My brain melts trying to read this expression. It's not _that_ difficult to read, just something immediately throwing me off.

### Drawbacks

None.

### Example

```rust
if !count != 0 {
}
```

Could be written as:

```rust
if count == 0 {
}
```

**Comment by mikerite** [comment]
This should probably be an enhancement to [nonminimal_bool](https://rust-lang.github.io/rust-clippy/master/index.html#nonminimal_bool)

**Comment by sim031999** [comment]
Hello, I want to work on this ! But I'm new to open source and would need help getting started

**Comment by flip1995** [comment]
Hey @sim031999, welcome to Clippy! We have documentation in the `doc` directory of this repository on how Clippy works. For this issue the [`adding_lints`](https://github.com/rust-lang/rust-clippy/blob/master/doc/adding_lints.md) documentation (especially the first three sections, Setup -> Testing) explains best how to get started with hacking on Clippy.

https://github.com/rust-lang/rust-clippy/blob/master/doc/common_tools_writing_lints.md This document explains some reoccurring patterns you'll find in Clippy with code examples.

If you have any questions, feel free to ask here, in discord, or open a WIP PR.

**Comment by sim031999** [comment]
Hi @flip1995, I have figured out that the following file ( after line 115) needs changes: https://github.com/rust-lang/rust-clippy/blob/master/clippy_lints/src/booleans.rs#L115. But the quine_mc_cluskey technique which is used in it, is not there for !=, can you suggest how do I proceed further?

**Comment by flip1995** [comment]
You can't use the `quine_mc_clusky` check for this. Just implement a check based on the AST/HIR structure after this line: https://github.com/rust-lang/rust-clippy/blob/bb67423577de689256483881ee9a8a0df34f7cd7/clippy_lints/src/booleans.rs#L68

Maybe not in the `check_fn`, but in the `check_expr` method.

**Comment by mikerite** [comment]
I think I was mistaken about extending `nonminimal_bool` because I mistook `!count != 0` for `!(count != 0)`. I don't think any code in nonminimal_bool will help with this.

Maybe a better fit would be to add this to [bit_mask](https://github.com/rust-lang/rust-clippy/blob/c493090a8a601baea39a592fdbe199bd64d6db22/clippy_lints/src/bit_mask.rs) module since there is a lot of bit comparison logic in there.

**Comment by flip1995** [comment]
I think the issue meant `!(count != 0)`, which I get from the example.

Replacing `!count != 0` with `count == 0` would change the semantics, whereas replacing `!(count != 0)` with `count == 0` wouldn't.

@idubrov can you clarify here?

**Comment by idubrov** [comment]
Right, in my case it was an integer variable, so I made an assumption that expression was parsed as `!(count != 0)` (and this definitely was implied meaning in our code). However, now I'm totally confused:

```rust
fn main() {
    let count = 0;
    // Original expression
    if !count != 0 {
        eprintln!("hello!");
    }
    // This is what I thought it means to compiler
    if !(count != 0) {
        eprintln!("hello!");
    }
    // This compiles? Why???
    if (!count) != 0 {
        eprintln!("hello!");
    }
    // This does not compile (makes sens; count is not a `bool`)
    if (!count) && true {
        eprintln!("hello!");
    }
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a141aa1438ec32ef629a9a68638b8739

**Comment by flip1995** [comment]
`!count` returns the bitwise inverse of `count` (Ones' complement).

I just saw that `!(x != y)` already gets linted by `nonminimal_bool`. [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2cdabf399e63e29cd1171ff6c0490103)

I think there is already an issue open for suspicious uses of the `Not`/`!` operations in integer comparisons, but I can't find it.

**Comment by idubrov** [comment]
Ah, got it! The fact that `!` works for bitwise operators was a surprise (though, know I remember I knew that before...).

**Comment by flip1995** [comment]
Anyway, this is a new lint. The behavior of the lint would be: Lint when there is `!var` inside a comparison (`!=`/`==`) of integral types, but not if it is on a literal (i.e. `count != !0` is fine).

**Comment by idubrov** [comment]
Yeah; now that I understand how it works, it actually turned out to be a logic error in our case!

Branch was intended to do `count == 0`, but effectively, it was doing `if count != 0xffff_ffff_ffff_ffff_usize`, which didn't make sense.

**Comment by GuillaumeGomez** [comment]
Opened #12248.
