### ISSUE TITLE
Notice unused code in a workspace

### ISSUE THREAD

**Issue by stevenroose** [rust-lang/rust-clippy#5828]
### What it does

A lot of projects have a workspace with multiple crates. This means that they will define most of their types as `pub` instead of `pub(crate)`. However this means that all crates are libraries and thus cargo won't warn you for unused code within the crate.

So it would be useful if we'd have a way to find unused code within a workspace instead of just within a crate.

### Categories (optional)

- Kind: clippy::nursery

### Drawbacks

Could point out unused code in some crates that are intended for usage outside the workspace.

**Comment by flip1995** [comment]
This is impossible to do for Clippy, since it would require a global analysis. 

In addition to that, Clippy (also cargo and rustc) can't know, if a `pub` function is unused, since there could be some other crate out there, not in the workspace, that uses this `pub` function.
