### ISSUE TITLE
Lint for soft-deprecated `{integer}::max_value` and `min_value`

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust-clippy#5841]
### What it does

Currently, Rust have three way to getting min/max of an integers: 
 1) module constants: `std::i32::MAX`
 2) type constants: `i32::MAX`
 3) const methods: `i32::max_value()`

(3) is soft-deprecated and replaced by 2) when possible.

[T-libs](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Deprecate.20.7Binteger.7D.3A.3A.7Bmin.2Cmax.7D_value.20methods) doesn't want to deprecate 1) and 3) now until next Rust edition,
but we have no tools to enforce style for 2),
it is great to have such a lint in Clippy.

### Categories (optional)

- Kind: style

### Drawbacks

None.

**Comment by kangalioo** [comment]
I'll try to do this

**Comment by kangalioo** [comment]
I'm a bit stuck because I can't properly figure out a way to detect "indirect" `min_value()`/`max_value()` calls.

```rust
impl Foo {
    type Int = i32;
    fn min_value() -> Int {
        Self::Int::min_value() // lint
    }
}
Foo::min_value(); // shouldn't lint!
Foo::Int::min_value(); // lint

type Int = i32;
let _ = Int::min_value(); // lint
```

I'm helpless with the rustc internals and its documentation is hardly helping.

**Comment by flip1995** [comment]
You have to compare the path of the functions. You can search the Clippy codebase for `match_qpath` to find out how it is used.

**Comment by kangalioo** [comment]
As far as I can tell, match_qpath is for matching a path 1:1. However, I need a way to "resolve" paths to the actual function and call against that. I don't see any way of using match_qpath that would catch all three cases I've lined out above

**Comment by flip1995** [comment]
Ah I see. This may work with 
https://github.com/rust-lang/rust-clippy/blob/2e0f8b6cc61c1673991120639d6b104a195f755e/clippy_lints/src/utils/mod.rs#L1358

which you can then compare to the `def_id` of the `min_value` function. This can be done with

https://github.com/rust-lang/rust-clippy/blob/2e0f8b6cc61c1673991120639d6b104a195f755e/clippy_lints/src/utils/mod.rs#L1184

**Comment by phansch** [comment]
There has been some progress on the Rust side of things ([tracking issue](https://github.com/rust-lang/rust/issues/68490)). Rust has recently added support for 'soft-deprecation' of items: https://github.com/rust-lang/rust/pull/79877. The next step will be to soft-deprecate the old items in std directly.

Considering that, I don't think it makes sense to implement this in Clippy anymore and I'm going to go ahead and close this issue.

Thanks everyone for your interest in working on this lint :blue_heart:
