### ISSUE TITLE
wildcard import rule not fired

### ISSUE THREAD

**Issue by yihuang** [rust-lang/rust-clippy#5860]
- macOS 10.15.6
- ```
   $ cargo clippy --version
   clippy 0.0.212 (6c8927b0c 2020-07-26)
  ```

```
$ cargo new test1
$ cd test1
$ cat > src/main.rs << EOF
use std::cmp::*;

fn main() {
    println!("Hello, world! {:?}", Ordering::Equal);
}
EOF
$ cargo clippy
    Checking test1 v0.1.0 (/private/tmp/test1)
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
```

**Comment by flip1995** [comment]
This lint is in the `pedantic` group and has, therefore, to be enabled explicitly: [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8a719ff5bf573702cd4b2db9ae7c38d6)

```
#![warn(clippy::wildcard_imports)]
```
