### ISSUE TITLE
discussion: move from discord to zulip

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-clippy#5943]
I'm wondering if we should move the clippy channel from discord to zulip.
As for myself, I find that the clippy channel is the only discord channel that I check out from time to time, everything else happens on zulip already and major dev channels have made the move already.

Pro/con list regarding zulip (feel free to edit)

Pros:
*Zulip has topics so you can discuss several topics in one channel at a time without things getting too confusing. (matthiaskrgr)
*A lot of channels have moved already (matthiaskrgr)

Cons:
*Discords mobile app is better  (It took a week or two for me to get used to the zulip app but now it's fine) (matthiaskrgr)
*Discord is more widespread (I guess..) But then again, you can register for zulip with your github account that you need anyway in order to contribute (matthiaskrgr)

Also nothing prevents us from "moving" to zulip and simply keeping the discord channel alive for people who want to use discord.

**Comment by yaahc** [comment]
big +1 on having only one channel

**Comment by lzutao** [comment]
What is the consensus here ? Do we need something like FCP or MCP ?

**Comment by flip1995** [comment]
Consensus is, that we don't want to have 2 channels. Regarding the move itself, some are in favor of it, none are completely against it. Many are pretty indifferent (including me).

In conclusion, I would say that we'll move to zulip and that we don't need a FCP. Someone has to take the wheel for this though.

1. Setting up a Zulip #clippy channel
2. announcing, that Clippy is moving to Zulip on the Discord server
3. after a period (~1 week), closing the discord server to complete the move

**Comment by Manishearth** [comment]
Seems good to me!

**Comment by phansch** [comment]
I took the liberty to request a Clippy stream here: https://rust-lang.zulipchat.com/#narrow/stream/122653-zulip/topic/Clippy.20stream.3F

**Comment by phansch** [comment]
We have a stream now: https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy :tada:

**Comment by flip1995** [comment]
Thanks @phansch! To finalize the move, we also have to adapt the documentation in the Clippy repo and remove every mention of `Discord` and replace it with `Zulip`.

**Comment by giraffate** [comment]
Hi, updating the documentation in the rust-lang/rust-clippy was finished at https://github.com/rust-lang/rust-clippy/pull/6057.
Also, the link to Discord in https://www.rust-lang.org/governance/teams/dev-tools looks like it needs to be fixed. Is there anything else we need to fix?

**Comment by flip1995** [comment]
Good catch! We need the equivalent of https://github.com/rust-lang/team/commit/aea2ca51e8e83252831a43394fd9cea31b3626b0#diff-2e2a46b4746ad4454414ee9fb7640557 done in the clippy.toml in the rust-lang/team repo.

**Comment by giraffate** [comment]
Thanks! I opened https://github.com/rust-lang/team/pull/428.

**Comment by flip1995** [comment]
The discord server is now closed, the documentation is done and The Zulip channel is working. => We completed the move 🎉
