### ISSUE TITLE
Reconsider #5656 after Range::is_empty stabilization

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust-clippy#5956]
I don't want to make clippy logic changes as part of a stabilization PR, so I'm filing this to remind myself to follow up with a better clippy change.

Stabilization PR: https://github.com/rust-lang/rust/pull/75132
Clippy change to potentially revert: https://github.com/rust-lang/rust-clippy/pull/5656

**Comment by ebroto** [comment]
I can take care of fixing this so it lands with 1.47.

**Comment by flip1995** [comment]
The rust PR may not even hit beta. And if it does we can still make those changes and backport them.

**Comment by scottmcm** [comment]
Ok, the stabilization did hit beta.

I've not changed clippy before; what's the best update to make here?  Maybe revert #5656, but then put back the `Range`/`RangeInclusive`-specific tests?

**Comment by flip1995** [comment]
I will do the backport after the release on Thursday 👍

**Comment by flip1995** [comment]
https://github.com/rust-lang/rust/pull/76051
