### ISSUE TITLE
Warn when compiling regexes in a loop

### ISSUE THREAD

**Issue by killercup** [rust-lang/rust-clippy#598]
In #587, @BurntSushi says:

> The biggest most important thing for regexes is to make sure you aren't compiling them every time you execute a search. I see it a lot in beginner code. Usually sticking them in lazy_static! is sufficient. But I suspect that might also be hard to detect.

**Comment by llogiq** [comment]
An easy way would be detecting an `ExprLoop` containing a regex compile which does not use the iterated variable directly.

This could still have false positives, but should be good enough as a starting point.
