### ISSUE TITLE
New lint: to_string() on a temporary Cow<'_, str>

### ISSUE THREAD

**Issue by Veetaha** [rust-lang/rust-clippy#5987]
### What it does

The lint is meant to detect calling `.to_string()` on a temporary `Cow<'_, str>`.
This is not a rare case when a beginner makes such a mistake.

### Categories (optional)

- Kind: `clippy::perf`

*What is the advantage of the recommended code over the original code*:
- Avoid wasting a potentially owned string inside of the temporary `Cow<'_, str>`.

### Drawbacks

None.

### Example

```rust
let path_str: String = path.to_string_lossy().to_string();
```
Could be written as:

```rust
let path_str: String = path.to_string_lossy().into_owned();
```

**Comment by camsteffen** [comment]
Why only apply it to a temporary `Cow`?

Scanning the implementors of `ToOwned`, you could similarly lint on `OsStr::to_os_string` and `Path::to_path_buf`.

Another case is `(*cow).to_owned()`. But maybe that's too contrived?

**Comment by Kixunil** [comment]
How about `into()` or `String::from()`? One advantage of such conversion is that it keeps working when the type changes a bit. Also useful for `Box<str>`.

Also why only temporary? I think doing the same when the `cow` is no longer used even when it's bound should be doable. (I realize this is kinda reimplementing part of borrow checking, but I hope it's simple enough.)

In general any conversion of `Cow<'_, Foo>` into `Foo::Owned` when the original value is not used later should be linted.

**Comment by Veetaha** [comment]
This is a duplicate of https://github.com/rust-lang/rust-clippy/issues/5987
I suggest proceeding with discussions there
