### ISSUE TITLE
Suggest `vec.truncate(vec.len() - 1)` instead of `vec.pop;`

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust-clippy#6017]
### What it does

It suggests improving performance by turning a pop() into a truncate().

### Categories (optional)

- Kind: `clippy::perf`

*What is the advantage of the recommended code over the original code*

The first requires copying the element to the stack, the second does not. This lint should only warn when the popped value is unused.

[Playground](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=81e72a7e4ecc1c76585d60dc68434189)

<details><summary>Assembly</summary>

Not sure if I've labeled these exactly right, but this seems approximately like what I'd expected: pop() copies from 8(%rbx) to a register, truncate() doesn't. See playground (above) to reproduce.

```asm
.LBB4_3: ; pop()
	testq	%rdi, %rdi
	je	.LBB4_6
        ; pop
	movq	8(%rbx), %rsi
	testq	%rsi, %rsi
	je	.LBB4_6
        ; truncate
	movl	$1, %edx
	callq	*__rust_dealloc@GOTPCREL(%rip)
```

</details>

### Drawbacks

The code is slightly harder to read and write.

### Example

```rust
vec.pop();
```
could be written as
```rust
vec.truncate(vec.len() - 1);
```

**Comment by jyn514** [comment]
This should probably go under `pedantic` too, I'd expect the performance difference to be pretty small in most cases.

**Comment by taiki-e** [comment]
The suggested code will panic if `vec` is empty...

**Comment by jyn514** [comment]
Oh ... that's unfortunate there's not a way to do this. I guess just depend on LLVM for optimizations? :/

**Comment by seritools** [comment]
Seems like LLVM does just fine: https://rust.godbolt.org/z/W9197s

(Although `pop` seems to have one more check still)
