### ISSUE TITLE
The word "error" in float_cmp can be confusing

### ISSUE THREAD

**Issue by fvsch** [rust-lang/rust-clippy#6040]
E.g. when following the "rustlings" exercise "clippy1":
https://github.com/rust-lang/rustlings/blob/4.0.0/exercises/clippy/clippy1.rs

The initial state shows this output:

```
error: strict comparison of `f32` or `f64`
  --> clippy1.rs:14:8
   |
14 |     if y != x {
   |        ^^^^^^ help: consider comparing them within some error: `(y - x).abs() > error`
   |
   = note: `#[deny(clippy::float_cmp)]` on by default
   = note: `f32::EPSILON` and `f64::EPSILON` are available for the `error`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#float_cmp
```

It might just be my ignorance, but I was puzzled by what "error" means in those fragments:
- "consider comparing them within some error"
- `(y - x).abs() > error`
- note: `f32::EPSILON` and `f64::EPSILON` are available for the `error`

I expected "error" to refer to an object or message, not to a f64 value.
Part of the confusion might be that the whole message in an "error", so that's two uses of the same word with very different meanings in the same output.

It sounds like "error" might be short for "margin of error"?
Would it help to change the output? to something like:

```
error: strict comparison of `f32` or `f64`
  --> clippy1.rs:14:8
   |
14 |     if y != x {
   |        ^^^^^^ help: consider comparing them within some margin of error: `(y - x).abs() > error_margin`
   |
   = note: `#[deny(clippy::float_cmp)]` on by default
   = note: `f32::EPSILON` and `f64::EPSILON` are available for the `error_margin`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#float_cmp
```

Note: this seems to participate in the confusion in https://github.com/rust-lang/rustlings/issues/390

**Comment by flip1995** [comment]
This is a easy to fix issue: First the message has to be changed here: https://github.com/rust-lang/rust-clippy/blob/f253dd06f91a496580d30dea45b669beaa9e1def/clippy_lints/src/misc.rs#L414

After that the [test files need to be updated](https://github.com/rust-lang/rust-clippy/blob/master/doc/adding_lints.md#testing)

And that's it. A great (first) contribution.

**Comment by HaramanJohal** [comment]
Hi, first time contributor here :wave: 
I have made this change and fixed the tests but cannot make a PR as I do not have the correct permissions to push my branch up with `git push -u origin margin_of_error`. Would I get appropriate permissions if this issue was assigned to me?

**Comment by ebroto** [comment]
Hey @HaramanJohal, you should fork this repo instead of cloning it. 

See [this link](https://github.community/t/the-difference-between-forking-and-cloning-a-repository/10189) for an explanation of the difference, and [this other link](https://guides.github.com/introduction/flow/) for a guide on the Github flow.

**Comment by HaramanJohal** [comment]
thanks will do
