### ISSUE TITLE
Lint default numeric type fallback

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust-clippy#6064]
### What it does

Lint any integer or floating point constants that have their type determined by the default fallback rather than inference

### Categories (optional)

- Kind: pedantic

*What is the advantage of the recommended code over the original code*

Avoids unintended use of the numeric default types, forcing the author to think about what type is appropriate.

### Drawbacks

Forcing the author to think about what type is appropriate.

### Example

```rust
let (x, y) = (5, 6.0);
```

Could be written as:

```rust
let (x, y): (i32, f32) = (5, 6.0);
let (x, y) = (5i32, 6.0f32);
```

**Comment by memoryruins** [comment]
It could be helpful to know when under-constrained inference has used a default numeric type, and I agree that pedantic makes sense for the category. Users who want this lint can optionally enable it, while minimizing friction with users that enjoy the current `i32` and `f32` fallback. Considerations from [rfc #212](https://rust-lang.github.io/rfcs/0212-restore-int-fallback.html#experience-with-lack-of-fallback) "restore int fallback" likely still apply here.

> Experience with lack of fallback
> Unfortunately, when doing the measurements that led us to decide to remove the int fallback, we neglected to consider coding "in the small" (specifically, we did not include tests in the measurements). It turns out that when writing small programs, which includes not only "hello world" sort of things but also tests, the lack of integer inference fallback is quite annoying. This is particularly troublesome since small program are often people's first exposure to Rust. The problems most commonly occur when integers are "consumed" by printing them out to the screen or by asserting equality, both of which are very common in small programs and testing.

For an example outside of Rust, Glasgow Haskell Compiler (GHC) has [`-Wtype-defaults`]( https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/using-warnings.html#ghc-flag--Wtype-defaults), which is an off by default warning.

> -Wtype-defaults
> Have the compiler warn/inform you where in your source the Haskell defaulting mechanism for numeric types kicks in.
> This is useful information when converting code from a context that assumed one default into one with another

**Comment by flip1995** [comment]
I would rather categorize this lint as `restriction`.

**Comment by memoryruins** [comment]
Ah right, `restriction` ^^; it would definitely fit there.

**Comment by Y-Nak** [comment]
Can I take this issue if no one working on it?

**Comment by flip1995** [comment]
Yeah sure! If you have any questions don't hesitate to ask here, on Zulip or open a WIP PR.

@rustbot assign @Y-Nak

**Comment by Stargateur** [comment]
I would clearly put this as warning, specially for integer.
