### ISSUE TITLE
redundant_pattern_matching: `Option` and `Result` methods stabilized as const

### ISSUE THREAD

**Issue by CDirkx** [rust-lang/rust-clippy#6067]
With [rust#76135](https://github.com/rust-lang/rust/pull/76135) and [rust#76136](https://github.com/rust-lang/rust/pull/76136) the methods `is_some`, `is_none`, `is_ok` and `is_err` will be stabilized as const. This makes them valid replacement suggestions again for Clippy within a const context, which was disabled in #5724.

The tests `redundant_pattern_matching` and `redundant_pattern_matching_const_result` thus need to be updated. I'm opening up this issue to reference in those modified tests.

Theses changes will be applied to the rustc in-tree version, as it currently blocks the stabilization of these methods.

**Comment by RalfJung** [comment]
In-tree changes to clippy are synced back periodically, so I am not sure this issue is even necessary (but maybe I am out of date wrt. clippy processes).

**Comment by flip1995** [comment]
Thanks for the heads up! Issues like this are not really necessary, since our CI currently already screams at us, if we haven't synced a Clippy change from rustc.

On bigger Clippy changes it is always nice to get pinged (`@rust-lang/clippy`), though.

cc #6071
