### ISSUE TITLE
catch `assert!` `assert_eq!` `assert_ne!` and variants in ResultFN

### ISSUE THREAD

**Issue by thefallentree** [rust-lang/rust-clippy#6082]
### What it does

catch `assert!` `assert_eq!` `assert_ne!` and variants in ResultFN

in a function that returns result , it is very likely the use of these macros are plain wrong.

### Categories (optional)

similar to https://rust-lang.github.io/rust-clippy/master/#panic_in_result_fn

**Comment by flip1995** [comment]
@nahuakang This seems like a good first issue to me.

A similar lint is already implemented and code can probably shared with that lint. So what you would have to do is to look at the `panic_in_result_fn` lint, understand how it works and implement the same (optimally sharing code) for `assert` macros. And obviously write tests for them.

**Comment by nahuakang** [comment]
Thanks Phil. I'll pick up on your hints!

**Comment by dp304** [comment]
@nahuakang are you still working on this issue?

**Comment by nahuakang** [comment]
@dp304 Yes I intend to. However if you are active and can send a PR in a few days, feel free to take it over.

**Comment by dp304** [comment]
@nahuakang I haven't noticed your comment edit, so I've made a PR. Sorry about that.

**Comment by nahuakang** [comment]
Cool, then I'll read your PR and learn from you!

**Comment by daxpedda** [comment]
Why was `debug_assert` & co included into this list?
I consider `debug_assert` just a helper to do sanity checks during debug builds that go away during production, this lint would discourage that kind of use and instead would recommend creating new error types to enable debug errors?

I would like to make a PR that removes `debug_assert` & co from the list of macros that triggers this lint.
@thefallentree & @flip1995 what you think?

**Comment by flip1995** [comment]
@daxpedda You're right, this lint shouldn't trigger on debug macros. It would be great if you could open a PR fixing that.

**Comment by daxpedda** [comment]
Will do!
