### ISSUE TITLE
Lint against `panic!(format!(...))` and `assert!(..., format!(...))`

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust-clippy#6259]
### What it does

`assert!` and `panic!` have built-in support for formatting, but they also accept arguments of type `String`, so one could use `format!` instead.

Using `format!` here is entirely unnecessary, and yet [happens in the wild](https://github.com/clap-rs/clap/blob/0c7da9f5b32bcd6968a70258a4868d439fbc1fc3/src/app/parser.rs#L181-L184), so this seems like a useful target for a Clippy lint. Also the [long-term plan](https://github.com/rust-lang/rust/pull/78343#issuecomment-716167134) is to not support `String` arguments any more, so such code might not work in future editions.

Cc @m-ou-se

### Example

```rust
panic!(format!("hello {}", var))
assert!(x, format!("hello {}", var))
```

Could be written as:

```rust
panic!("hello {}", var)
assert!(x, "hello {}", var)
```

**Comment by m-ou-se** [comment]
It will probably be very soon that rustc itself has a lint for `panic!(not-a-string-literal)` and `assert!(expr, not-a-string-literal)` (to warn about the potential upcoming edition change), so it might not be worth it to add this to Clippy now.

**Comment by giraffate** [comment]
related issue: https://github.com/rust-lang/rust-clippy/issues/5013

**Comment by giraffate** [comment]
https://github.com/rust-lang/rust-clippy/issues/3155 is also a related issue.

**Comment by camsteffen** [comment]
Added in #7743
