### ISSUE TITLE
Use len() instead of iter().count()

### ISSUE THREAD

**Issue by camsteffen** [rust-lang/rust-clippy#6262]
### What it does

Suggests using `collection.len()` instead of `collection.iter().count()`.

### Categories (optional)

- clippy::complexity

*What is the advantage of the recommended code over the original code*

Simpler, idiomatic.

### Drawbacks

None.

### Example

```rust
vec.iter().count()
```

Could be written as:

```rust
vec.len()
```

### Notes

* Should work with all collections in std, and slices
* Should also work with `into_iter`
* Should also work with `ExactSizeIterator::len`

**Comment by TaKO8Ki** [comment]
Hi. I'm interested in this so I'd like to tackle it.
