### ISSUE TITLE
Compiler unexpectedly panicked

### ISSUE THREAD

**Issue by royster57** [rust-lang/rust-clippy#6283]
thread 'rustc' panicked at 'Box<Any>', compiler/rustc_errors/src/lib.rs:945:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.0.212 (ffa2e7a 2020-10-24)

query stack during panic:
#0 [typeck] type-checking `<rexapi::latest::VolumeCreateInternal as validation::VolumeCreateBasicValidation>::onboarded_device_not_primary`
#1 [typeck_item_bodies] type-checking all item bodies
end of query stack

**Comment by giraffate** [comment]
Could you provide a minimal example where this happen?

@rustbot modify labels: +L-crash

**Comment by matthiaskrgr** [comment]
I'm closing this; with the little information given in the ticket we won't be able to do anything about this crash.
