### ISSUE TITLE
lint creating a &str (or String) from invalid UTF-8 bytes

### ISSUE THREAD

**Issue by llogiq** [rust-lang/rust-clippy#629]
This is also undefined behavior (according to the rust book), calling `std::str::from_utf8_unchecked(..)` on something which is not UTF-8.

**Comment by Manishearth** [comment]
I don't see why someone would ever use from_unchecked on a literal?

**Comment by llogiq** [comment]
Perhaps within a macro?

**Comment by John-Steidley** [comment]
Perhaps because of a refactor. Perhaps because they passed the literal into a function.
