### ISSUE TITLE
Lint for calculating remainder with divisor of -1

### ISSUE THREAD

**Issue by mlegner** [rust-lang/rust-clippy#6321]
While for remainder with 1 there is the [modulo_one](https://rust-lang.github.io/rust-clippy/master/index.html#modulo_one) lint, a remainder with -1 is only caught by the [integer_arithmetic](https://rust-lang.github.io/rust-clippy/master/index.html#integer_arithmetic) lint, which is disabled by default ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=46cc562dba8887fa743d6aacf683228c)). The issue has been discussed briefly in #663 but not resolved.

As there are only two possible outcomes when calculating the remainder with -1 (overflow/panic or 0), this should definitely be linted in my opinion. I suggest modifying the [modulo_one](https://rust-lang.github.io/rust-clippy/master/index.html#modulo_one) lint to also be triggered by -1 (potentially with a different warning).

**Comment by mlegner** [comment]
If maintainers agree that this is worthwhile, I'm happy to create a PR.

**Comment by camsteffen** [comment]
I'm not a maintainer but I say go for it. The `-1` case is very similar to the `1` case in terms of uselessness.
