### ISSUE TITLE
clippy_lints compile error due to unresolved import

### ISSUE THREAD

**Issue by pro-grammer1** [rust-lang/rust-clippy#6387]
I would like to contribute, so I cloned the repo and ran setup-toolchain.sh, which worked. I then tried building clippy_lints, but ran into this error:
```
error[E0432]: unresolved import `rustc_ast::util::lev_distance`
 --> clippy_lints/src/attrs.rs:8:22
  |
8 | use rustc_ast::util::lev_distance::find_best_match_for_name;
  |                      ^^^^^^^^^^^^ could not find `lev_distance` in `util`
```
I haven't changed any code and I followed the Basics documentation, so I expected it to work. What am I doing wrong?

Also, is this the right place to ask this question?

**Comment by giraffate** [comment]
Oh, it's not your fault. We seem to need the sync process from `rust-lang/rust`.

**Comment by giraffate** [comment]
The sync process will be done by https://github.com/rust-lang/rust-clippy/pull/6389. So, please wait until this is merged.

**Comment by pro-grammer1** [comment]
Ok, everything seems to be working now. Thank you.
