### ISSUE TITLE
Lint Suggestion: reimplementing .and_then with Some(x?)

### ISSUE THREAD

**Issue by NoraCodes** [rust-lang/rust-clippy#6410]
### What it does

Suggest `option.and_then(|value| value.inner_option)` instead of `option.and_then(|value| Some(value.inner_option?))`

### Categories (optional)

- Kind: style or complexity

*What is the advantage of the recommended code over the original code*

There's no reason to take an option, wrap it in another option, and use ? to short-circuit. `and_then` will work fine without it, and it's needlessly difficult to read.

### Drawbacks

None.

### Example

```rust
struct Outer {
    inner: Option<String>
}

let a = Some(Outer { inner: Some("hello".into()) });
a.and_then(|a| Some(a.inner?))
```

Could be written as:

```rust
struct Outer {
    inner: Option<String>
}

let a = Some(Outer { inner: Some("hello".into()) });
a.and_then(|a| a.inner)
```

**Comment by camsteffen** [comment]
Nice. This can include any case of `return Some(option?)` or `return Ok(result?)`. Maybe call it `needless_question_mark`.

**Comment by bengsparks** [comment]
If no one has attempted this yet, I'd like to give it a shot.

**Comment by bengsparks** [comment]
Ok, so let me see if I've understood this correctly.

What needs to be recognized; 
`Option<T>` and `Result<T, E>`, i.e. types for which the question mark operator are implemented for.

How can it be matched: 
By matching `Some(instance_of_option?)`  and `Ok(instance_of_result?)`.

What help can be suggested:
The `instance_of_*` parameter be kept and the rest discarded. 

Have I overseen anything?

**Comment by mikerite** [comment]
You have to worry about the early exit of `?`. This is probably only applicable on the expression of a body or in a return statement.

**Comment by bengsparks** [comment]
Ok, I think I've got it done. I'll go open a PR.
