### ISSUE TITLE
-A clippy::unknown_clippy_lints should apply to lints passed on the command line as well

### ISSUE THREAD

**Issue by khuey** [rust-lang/rust-clippy#6411]
Allowing clippy::unknown_clippy_lints is great for environments with heterogeneous rustc/clippy versions but it only applies to lints mentioned in attributes, not those mentioned on the command line.

I can't actually find the code that generates the message that appears on the command line when I pass in `-A clippy::nonexistent_lint`. Perhaps it's not in clippy at all?

**Comment by flip1995** [comment]
@khuey This sounds, as if it is related to this: https://github.com/rust-lang/rust/issues/69453 Currently passing clippy lints over the command line is broken.

**Comment by khuey** [comment]
Yeah I think that's right.

**Comment by flip1995** [comment]
Ok, closing this then, because this is something that has to be fixed in rustc. Not much we can do in Clippy, sorry :neutral_face:
