### ISSUE TITLE
New lint: missing_panic_doc

### ISSUE THREAD

**Issue by vanillajonathan** [rust-lang/rust-clippy#6430]
### What it does

Checks for missing documentation.

### Lints

- Module not documented.
- Trait not documented.
- Trait method not documented.
- Enum not documented.
- Enum variant not documented.
- Struct not documented.
- Struct method not documented.
- Function not documented.
- Panic not documented.
- README.md missing.

**Comment by giraffate** [comment]
FYI rustc has a [`missing_doc`](https://doc.rust-lang.org/rustdoc/lints.html#missing_docs) lint and Clippy has a [`missing_docs_in_private_items`](https://rust-lang.github.io/rust-clippy/master/#missing_docs_in_private_items).

**Comment by taiki-e** [comment]
> * Panic not documented.

As Clippy has [a similar lint for functions that return errors](https://rust-lang.github.io/rust-clippy/master/#missing_errors_doc), I think it makes sense to have a lint for functions that may panics.

> * Module not documented.
> * Trait not documented.
> * Trait method not documented.
> * Enum not documented.
> * Enum variant not documented.
> * Struct not documented.
> * Struct method not documented.
> * Function not documented.

I think these are detected by `missing_doc` and `missing_docs_in_private_items` that @giraffate mentioned.

> * README.md missing.

I think this is covered by `cargo_common_metadata`. (aside from whether it will be used for this purpose)

**Comment by ebroto** [comment]
>I think these are detected by missing_doc and missing_docs_in_private_items that @giraffate mentioned.

Yep, you can check this in the [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=68c52942d399fa0ac2630bd53577457e).

>>Panic not documented.

>As Clippy has a similar lint for functions that return errors, I think it makes sense to have a lint for functions that may panics.

There's also [missing_safety_doc](https://rust-lang.github.io/rust-clippy/master/#missing_safety_doc). I think it makes sense to add a lint for this. Since it's the only remaining case that it's not currently linted, I will change also the description of the issue to reflect that.

**Comment by camsteffen** [comment]
Duplicates #1974

**Comment by brightly-salty** [comment]
Hey, I'm a would-be first-time contributor. Could I tentatively claim this? Thanks

**Comment by camsteffen** [comment]
@brightly-salty Go ahead and claim #1974 which this issue duplicates. Closing this issue.
