### ISSUE TITLE
thread 'rustc' panicked at 'assertion failed: bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32

### ISSUE THREAD

**Issue by abdelmonem17** [rust-lang/rust-clippy#6454]
when I run cargo clippy on my project the command does it's job and finally gives the following error but I don't know why this error comes from.

thread 'rustc' panicked at 'assertion failed: bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32', compiler\rustc_span\src\source_map.rs:950:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug

**Comment by matthiaskrgr** [comment]
Is your repo public?

The assertion failure has been popping up in the upstream rust repo a couple of times already: https://github.com/rust-lang/rust/issues?q=is%3Aissue+%22assertion+failed%3A+bpos.to_u32%28%29%22+

**Comment by abdelmonem17** [comment]
no I am working on private repo

**Comment by ebroto** [comment]
Thanks for your issue report!

Could you run clippy with `RUST_BACKTRACE=1` and paste the backtrace here?. That would give us some information we can work with.

Ideally you would provide a minimum reproducible example, but that can be more challenging.

**Comment by abdelmonem17** [comment]
thank you for help I fixed it, it was because a non char in documentation comment.
