### ISSUE TITLE
new lint: find unneccessary Some(x).and_then(|y| Some(y ..))

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-clippy#6472]
### What it does
Catch `Some(..).and_then(|..| Some(..))` patterns.

*What does this lint do?*
Suggest to simplify the statement to `Some(do something with x and y)`
For example `Some(3).and_then(|x| Some(x+4));` could be simplified to `Some(3+4)`

### Categories (optional)
Complexity, maybe pedantic.

*What is the advantage of the recommended code over the original code*
It's way easier to understand

### Drawbacks

None.

### Example

```rust
Some(3).and_then(|x| Some(x+4));
```

Could be written as:

```rust
Some(3+4)
```

**Comment by alex-700** [comment]
@matthiaskrgr 
`.and_then(|x| Some(..))` perfectly triggers `bind_instead_of_map` [lint](https://rust-lang.github.io/rust-clippy/master/index.html#bind_instead_of_map). So it seems this lint idea should be about `Some(x).map(|x| foo(x))`, which should be replaced with `Some(foo(x))` for every expression `foo`.

**Comment by matthiaskrgr** [comment]
Yes, `Some(..).map()` could be futher simplified if we know that we will have `Some(x..)` at the beginning of the statement.
