### ISSUE TITLE
README: cargo run --manifest path unlikely to work, should we remove it?

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-clippy#6489]
in the [readme](https://github.com/rust-lang/rust-clippy#running-clippy-from-the-command-line-without-installing-it), we state that it is possible to run clippy on any repo via `cargo run --bin cargo-clippy --manifest-path=path_to_clippys_Cargo.toml`
This would build clippy and then run it on the repo.

The problem is that this does not apply because `cargo run` will use the rustc version specified in the "host" repo (or a rustup default set  nightly/beta etc) instead of the clippy set in its own repo.

tldr; when using `cargo run .. --manifest-path=clippys_cargo.toml`, our `rust-toolchain` file is not used and clippy will most likely not compile.

Any ideas how to handle this?
Should we just remove the paragraph?
Is it still needed anyway, since nightly should ship a clippy by default now and clippy is also in beta/stable?

I think the paragraph was added in a time where clippy would get "fixed" to build with nightly on most days, but since we pin the repo to a specific version, this is no longer the case.

**Comment by flip1995** [comment]
Yeah I think removing this makes sense. No one has to compile Clippy to use it, since it is shipped with rustup.

**Comment by matthiaskrgr** [comment]
Hmm, alternatively, if we copied  clippys `rust-toolchain` file into the repo we want to run clippy in and then ran the command, I think that should work..?

**Comment by flip1995** [comment]
Yeah, but then we copied a file to another project. Running Clippy should never modify files in another directory IMO (except the `--fix` command of course).
