### ISSUE TITLE
pin clippy version number to rustc version number?

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-clippy#6499]
Clippy has been on version `0.0.212` for quite some time now, and the version number has become quite irrelevant now that we always ship a `-git` version with nightly/beta/stable.

Should we pin the clippy to the respective rustc version like cargo does?
cargo 0.49.0 corresponds to rustc 1.49.0.
Equally, we could bump clippy to 0.1.49 for beta, and 0.1.50 for nightly.

**Comment by flip1995** [comment]
I'm in favor of this

cc @rust-lang/clippy

**Comment by Manishearth** [comment]
+1
