### ISSUE TITLE
Needless Return at the end of function inside a closure suggests invalid code

### ISSUE THREAD

**Issue by fee1-dead** [rust-lang/rust-clippy#6501]
This code:

```rust
fn foo(bar: Result<(), ()>) {
    bar.unwrap_or_else(|_| return)
}
```

is suggested to remove the return, like this:

```rust
fn foo(bar: Result<(), ()>) {
    bar.unwrap_or_else(|_| )
}
```

Which is invalid rust code.

### Meta

- `cargo clippy -V`: clippy 0.0.212 (bb1fbbf 2020-12-22)
- `rustc -Vv`:
```
rustc 1.50.0-nightly (bb1fbbf84 2020-12-22)
binary: rustc
commit-hash: bb1fbbf84455fbad9afd26c17e0f725019322655
commit-date: 2020-12-22
host: x86_64-unknown-linux-gnu
release: 1.50.0-nightly
```

**Comment by ThibsG** [comment]
@fee1-dead commented (by email):
> Hey, I am the issue reporter, and I think it is still incorrect behavior in some cases, because when the result is Result<(), ()>, it is fine to use an empty closure, but when I use unwrap_or_else on an actual result with type (Result<Foo, u8>), I can't use |_| {} because that would return () instead of Foo, but return works.

**Comment by ThibsG** [comment]
@fee1-dead If I understand correctly, you have something like:
```rust
struct Foo;
fn bar(foo: Result<Foo, u8>) -> Foo {
    foo.unwrap_or_else(|_| return Foo)
}
```
the suggestion would be to remove the `return` statement like this:
```rust
    foo.unwrap_or_else(|_| Foo)
```
[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=760dc2d242e4048c6517dcb733cf75ff)

Is that the correct situation you are referring to?

**Comment by fee1-dead** [comment]
@ThibsG, I first commented on the PR, but after some experimenting I realized I can’t return from closure so I just removed the comment.
