### ISSUE TITLE
Optional warning on module dependency cycles

### ISSUE THREAD

**Issue by kangalioo** [rust-lang/rust-clippy#6541]
### What it does

Rust allows modules to depend on each other in a cycle: module A depends on module B and B depends on A. This may be useful sometimes, but it may introduce significant avoidable cognitive load. This issue proposes an opt-in lint that warns on module dependency cycles.

### Categories (optional)

- Kind: `clippy::complexity` or `clippy::pedantic` (ideally an allow-by-default complexity lint)

*What is the advantage of the recommended code over the original code*

Eliminating module dependency cycles makes code much easier to refactor and understand.

### Drawbacks

None.

### Example

```rust
//! dependency cycle:
//!
//!  crate <--> calculation module

mod calculation {
   fn calculate_foo_value(foo: crate::Foo) -> u32 {
       /* ... */
   }
}

struct Foo { /* ... */ }

fn main() {
    let foo = Foo { /* ... */ };
    println!("Foo value: {}", calculation::calculate_foo_value(foo));
}
```

Could be written as:

```rust
//! no dependency cycles (directed acyclic graph "DAG"):
//!
//!  crate --> calculation module
//!  |           /
//!  V          /
//!  common  <--


mod common {
    struct Foo { /* ... */ }
}

mod calculation {
   fn calculate_foo_value(foo: crate::common::Foo) -> u32 {
       /* ... */
   }
}

fn main() {
    let foo = common::Foo { /* ... */ };
    println!("Foo value: {}", calculation::calculate_foo_value(foo));
}
```

**Comment by areveny** [comment]
Duplicate of #5782

**Comment by kangalioo** [comment]
Ah, you're right
