### ISSUE TITLE
Is there a mechanism for loading new lints at run time?

### ISSUE THREAD

**Issue by nikclayton-dfinity** [rust-lang/rust-clippy#6595]
Is there a mechanism for loading local lints that are project-specific, and don't make sense for contribution upstream, at run time?

E.g., for a project that wants to enforce local code style rules that are too specific to make sense in a general purpose tool like clippy?

For example: "If an enum name ends `Error` then none of the enum variants should end `Error`".

I couldn't find one, so I think the answer is "Fork clippy, write project-specific lints in the local fork, periodically sync with upstream", but I wanted to double check.

[aside: Ordinarily I'd ask a question like this on a mailing list, or IRC, Gitter, Slack, etc, but I couldn't find anything like that in the documentation either, hence the issue -- apologies if there's some other preferred place to ask this question]

**Comment by xFrednet** [comment]
I don't believe that clippy currently has any support for this. We have some lints that are configurable, so Clippy would probably take a more generic approach of having a lint that forbids a configured suffix. Maybe similar to the [`blacklisted_name`](https://rust-lang.github.io/rust-clippy/master/index.html#blacklisted_name) lint.

That being said I believe that your example is very specific and could as you suggest very well be implemented as a project-specific lint. The problem I see is the configuration. Clippy/Rust uses a register pattern for linting. The lints are registered in code and therefor linked at compile time. Here is the file with all registrations: [`clippy_lints/src/lib.rs`](https://github.com/rust-lang/rust-clippy/blob/master/clippy_lints/src/lib.rs). `cargo dev update_lints` automatically generates the code. Having a generic interface to connect external lints seems difficult for me, but I also have only worked very little with dynamic or other linking so far.

For your side node. Rust-lang team and therefor Clippy use zulip there you might also get some more input. :upside_down_face: 
- [Rust-lang Zulip](https://rust-lang.zulipchat.com)
- [Clippy Channel](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy)

**Comment by nikclayton-dfinity** [comment]
Thanks for the info. I'll close this, as not actionable on your side.
