### ISSUE TITLE
Add XOR swap algorithm detection to (existing) clippy::manual_swap

### ISSUE THREAD

**Issue by AccessViolation95** [rust-lang/rust-clippy#6598]
### What it does

*This would warn the user that there is a better alternative to using a XOR swapping algorithm to swap the values of two variables*

### Categories (optional)

- Kind: *clippy::complexity*

*The std::mem::swap function exposes the intent better (this is somewhat the same reason for the warning for swapping using a temporary variable)*

For example:
- People reading the recommended code will see that it likely swaps two variables, as opposed to if they see a XOR swap algorithm and are unfamiliar with it.

### Drawbacks

None.

### Example

```rust
fn main() {
    let mut a = 5;
    let mut b = 10;
    
    // Swap them.
    a ^= b;
    b ^= a;
    a ^= b;
    
    println!("a: {}, b: {}", a, b);
}
```

Could be written as:

```rust
fn main() {
    let mut a = 5;
    let mut b = 10;
    
    // Swap them.
    std::mem::swap(&mut a, &mut b);
    
    println!("a: {}, b: {}", a, b);
}
```

**Comment by hrishisd** [comment]
Hello! I would love to attempt this issue. I am a rust beginner and this would be my first open source contribution so I may be a little slow if that's ok. I can take a look this weekend.

**Comment by xFrednet** [comment]
Hey @hrishisd it's no problem if you take some time to implement this. Feel free to ask in the issue or on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy) if you're stuck during the implementation 🙃.

Could you maybe comment `@rustbot claim` in this issue to assign it to you? This makes it easier for others to see that someone is working on it. You can unassign yourself at any point if you don't want to finish the implementation.

**Comment by hrishisd** [comment]
Thank you for your help @xFrednet!

@rustbot claim
