### ISSUE TITLE
New restriction lint: exhaustive_enums

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust-clippy#6616]
### What it does

This lint forces all enums in the project to be non-exhaustive

### Categories (optional)

- Kind: Restriction

*What is the advantage of the recommended code over the original code*

There is no advantage in the general case, but some projects may wish to use this to ensure they never accidentally stabilize enum APIs they wish to change in the future, silencing the lint as an opt-in to stabilized enums/

### Drawbacks

None.

### Example

```rust
enum Foo {
    Bar, Baz
}
```

Could be written as:

```rust
#[non_exhaustive]
enum Foo {
    Bar, Baz
}
```

**Comment by robertbastian** [comment]
Enum variants have to be tagged as `#[non_exhaustive]` separately from the enum itself, and this lint doesn't enforce that:

```rust
#[non_exhaustive]
enum Foo {
  Bar(u8),
  Baz,
}
```

should/could be 
```rust
#[non_exhaustive]
enum Foo {
  #[non_exhaustive] Bar(u8),
  Baz,
}
```

Is this something that should be done by this lint, or by a new `exhaustive_enum_variants` lint?
