### ISSUE TITLE
New lint: `filter_map_identity`

### ISSUE THREAD

**Issue by camsteffen** [rust-lang/rust-clippy#6643]
### What it does

It's the same as `flat_map_identity`, but with `filter_map`.

### Example

```rust
vec![Some(1)].into_iter().filter_map(|x| x)
```

Could be written as:

```rust
vec![Some(1)].into_iter().flatten()
```

**Comment by magurotuna** [comment]
Hi! I'm interested in this so I'd like to give it a shot.
