### ISSUE TITLE
Nothing in the documentation mentions that clippy only works on first compilation

### ISSUE THREAD

**Issue by autarch** [rust-lang/rust-clippy#6655]
I thought I was going crazy until I asked about this in the Rust Discord and was told that this was a known issue.

This really needs to be highlighted somewhere in the docs, along with some recommendation on how to deal with this. I'm happy to contribute a patch to the `README.md` if that's the place to put this.

**Comment by giraffate** [comment]
Can you provide a minimal reproduction or the link to discussion in Rust Discord? Or  do you mean https://github.com/rust-lang/rust-clippy/issues/4612 ?

**Comment by autarch** [comment]
The thread in the Discord starts with my question at https://discord.com/channels/442252698964721669/448238009733742612/805198569506078741

I created a bash script to reproduce this but I could not reproduce it in a script. That led me to realize that this must be something about how Emacs is interacting with my rust code. I'm guessing that maybe flycheck is running `cargo check` on save, or perhaps rust-analyzer does this, so maybe it is the same as #4612.

I wasn't able to reproduce this by editing the same file in the same way using vim, so it's definitely something in my emacs config.

**Comment by autarch** [comment]
I closed this but on further reflection it still seems like a doc issue. Reading #4612 it's not clear if this is really fixed in nightly, and given that this is still a problem anyone not using nightly is definitely affected by, it seems worthwhile to document the issue until it's fully fixed.

**Comment by autarch** [comment]
I _think_ this is fixed in stable now. Can someone who knows more than I confirm and close this if that's the case?

**Comment by giraffate** [comment]
Yes, this is fixed at currently stable, so I'm closing this. Thanks for your comment!
