### ISSUE TITLE
Replace `std::mem::size_of<T>()` with `::BITS` constant

### ISSUE THREAD

**Issue by nindalf** [rust-lang/rust-clippy#6670]
### What it does

Starting in Rust 1.51, all integer types will have a ::BITS constant for the number of bits in the type. `std::mem::size_of::<usize>() * 8` can be replaced with `usize::BITS` and similarly for all signed and unisigned integers. This lint suggests such a change.

### Categories (optional)

- Kind: clippy::style

*What is the advantage of the recommended code over the original code*

For example:

- One fewer function call (saving several nanoseconds)
- Easier to read

### Drawbacks

None.

### Example

```rust
std::mem::size_of::<usize>() * 8
```

Could be written as:

```rust
usize::BITS
```

**Comment by m-ou-se** [comment]
> Starting in Rust 1.51

Note that we're reverting stabilization because of some breakage: https://github.com/rust-lang/rust/pull/81727. So this will probably be 1.52 rather than 1.51.

**Comment by nindalf** [comment]
That sounds fine. 

I’d be happy to work on this issue. Does anyone know what’s the deadline to make it for 1.51.0 or 1.52.0?

**Comment by paolobarbolini** [comment]
I'd like to work on this issue

@rustbot claim
