### ISSUE TITLE
lint panics (allow)

### ISSUE THREAD

**Issue by llogiq** [rust-lang/rust-clippy#668]
We may want to know if some code is panic-free – so while we cannot be sure if a function from another crate that this crate calls panics, we can at least check for panics locally, which means checking for calls of divergent functions (which the type system should give us a hint). We also should probably ignore `unreachable!()` calls.

**Comment by Areredify** [comment]
This issue can now be closed, this lint was (recently?) implemented.

**Comment by flip1995** [comment]
Yeah, for every directly panicking macro a separate lint is implemented by know. Thanks for noticing!
