### ISSUE TITLE
Tracking Issue for refactoring `types.rs`

### ISSUE THREAD

**Issue by Y-Nak** [rust-lang/rust-clippy#6724]
While refactoring `types.rs` in #6680, I found that `types.rs` contains not only the `types` group but also other groups like the `cast` group.
This issue is a tracking issue for refactoring `types.rs` to avoid a too large PR and split them into small PRs.

* [x] `types` group(#6725):
    * `BOX_VEC`
    * `VEC_BOX`
    * `OPTION_OPTION`
    * `LINKEDLIST`
    * `BORROWED_BOX`
    * `REDUNDANT_ALLOCATION`
    *  `RC_BUFFER`
* [x] `casts` group(#6873):
    * `CAST_PRECISION_LOSS`
    * `CAST_SIGN_LOSS`
    * `CAST_POSSIBLE_TRUNCATION`
    * `CAST_POSSIBLE_WRAP`
    * `CAST_LOSSLESS`
    * `UNNECESSARY_CAST`
    * `CAST_PTR_ALIGNMENT`
    * `FN_TO_NUMERIC_CAST`
    * `FN_TO_NUMERIC_CAST_WITH_TRUNCATION`
    * `CHAR_LIT_AS_U8`
    * `CAST_REF_TO_MUT`
    * `PTR_AS_PTR`
 * [x] `unit_type` group (#6889):
    * `LET_UNIT_VALUE`
    * `UNIT_CMP`
    * `UNIT_ARG`
* [ ] another:
    * `ABSURD_EXTREME_COMPARISONS`
    * `INVALID_UPCAST_COMPARISONS`
    * `IMPLICIT_HASHER`
    * `TYPE_COMPLEXITY`: I think this lint should be grouped into `types`  but the implementation of  `LateLintPass` seems slightly different from that of `Types`. needs further discussion.

**Comment by flip1995** [comment]
+1 for splitting that module up further.
