### ISSUE TITLE
`cargo dev bless` doesn't work

### ISSUE THREAD

**Issue by Y-Nak** [rust-lang/rust-clippy#6757]
`cargo dev bless` command seems not to work since the version of `compiletest-rs` is updated in #6743.

I think this is because the updated `compiletest` joins `stage_id` to output file names like `zero_div_zero.stage-id.stderr`, while `bless.rs` doesn't take it into account. (I don't know why the former version of `compiletest` doesn't join it although the codes related to file names seem unchanged).

I suppose we could explicitly specify `config.stage_id = ""` in [here](https://github.com/rust-lang/rust-clippy/blob/ddeea9771408295cefb21d97aff52257095fb894/tests/compile-test.rs#L68) as a quickfix.

ref: #5394

**Comment by camsteffen** [comment]
We may want to just migrate to the bless feature that is now available in compiletest itself.

**Comment by Y-Nak** [comment]
Yeah, it's most desirable, but I suppose it's worth doing a quick-fix since it seems the transition to new `bless` needs more discussion.
