### ISSUE TITLE
Config for public API changes

### ISSUE THREAD

**Issue by camsteffen** [rust-lang/rust-clippy#6806]
Sometimes we turn off lints in cases where the suggestion would change the public API of a crate. This is a reasonable default, but I believe this should be an opt-out configuration option for all Clippy lints. Oftentimes, a crate has a public API but it is still "private" in the sense that it is only used within a single project (e.g. `clippy_utils`), and so API changes are not as much of a concern.

**Comment by mikerite** [comment]
I'm against silencing lints on public items. The default should be to lint everywhere. Silencing should only be done in exceptional cases and there should be an easy way to turn it back on. I actually would prefer a lint to be moved to restriction entirely than crippled in that way.

**Comment by camsteffen** [comment]
> I'm against silencing lints on public items.

Just to be clear, we are not silencing lints on public items altogether, but silencing lints that would suggest changing the public API in a non-backward-compatible way (i.e. changing a function signature).

> The default should be to lint everywhere.

That seems more preferable to me as well, by the principle of least surprise.

**Comment by mikerite** [comment]
> Just to be clear, we are not silencing lints on public items altogether, but silencing lints that would suggest changing the public API in a non-backward-compatible way (i.e. changing a function signature).

Yes. Aware of that.

**Comment by camsteffen** [comment]
Config name idea: `suppress_public_api_changes`

**Comment by llogiq** [comment]
Yeah, we added the exported check to many lints for exactly that reason: Clippy should not break people's code. Having a flag to allow linting those items for the outlined reasons is a good idea, though (when we decided to not lint those cases, we didn't have any config).

**Comment by Manishearth** [comment]
A thing I mentioned there that I want to make sure is mentioned here: this shouldn't actually change our calculus of whether we break public APIs. Sometimes a lint is more severe and needs to be able to suggest breaking changes, even if the result is just that the lint is silenced.

**Comment by Manishearth** [comment]
Put differently, "we shouldn't use the existence of this config as a reason to avoid writing lints that _always_ suggest breaking changes".

So like, I think we have some lints currently that _do_ suggest breaking changes to pub and _should_, we shouldn't change that.

**Comment by llogiq** [comment]
Yeah, we should also probably document this facet of the respective lints.
