### ISSUE TITLE
Substitute logical folds to any() or all()

### ISSUE THREAD

**Issue by totikom** [rust-lang/rust-clippy#6827]
### What it does

Some uses of [`.fold()`](https://doc.rust-lang.org/stable/std/iter/trait.Iterator.html#method.fold) can be substituted to existing methods on iterators like [`.all()`](https://doc.rust-lang.org/stable/std/iter/trait.Iterator.html#method.all) and [`.any()`](https://doc.rust-lang.org/stable/std/iter/trait.Iterator.html#method.any).

### Categories (optional)

- Kind: `clippy::complexity`

*What is the advantage of the recommended code over the original code*

- Dramatically improves code readability
- In average work faster, as `.any()` and `.all()` are short-circuiting (see the docs)

### Drawbacks

None.

### Examples

`all`:
```rust
some_iterator.fold(true, | acc, x| {
    acc & x
});
```

Could be written as:

```rust
some_iterator.all(|x| x);
```
`any`:
```rust
some_iterator.fold(false, | acc, x| {
    acc | x
});
```

Could be written as:

```rust
some_iterator.any(|x| x);
```

More over, `rustfmt` will remove curly brackets in the original code, so closure in the `.any()` case will be formatted to completely unreadable and confusing `|acc, x| acc | x`

**Comment by totikom** [comment]
Actually, the things are a bit more complicated.
`.fold()` will always consume the whole iterator, while `.all()` (and `.any()`) exits after the first `false` (`true`).
If the iterator has side-effects, the behavior of the original and the linted code may differ.

Maybe it should be moved to `clippy::perf` with warning about side-effects.

**Comment by totikom** [comment]
And one more note:
It is highly possible, that the iterator over `bool`s was obtained via `.map()`.
In that case: 
```rust
some_iterator.map(| item | {
// a closure which returns bool
})
.fold(false, | acc, x| {
    acc | x
});
```
Could be written as:
```rust
some_iterator.any(| item | {
// a closure which returns bool
});
```

Or:
```rust
some_iterator.map(| item | {
// a closure which returns bool
})
.fold(true, | acc, x| {
    acc & x
});
```
Could be written as:
```rust
some_iterator.all(| item | {
// a closure which returns bool
});
```

**Comment by camsteffen** [comment]
Isn't this `unnecessary_fold`?

**Comment by totikom** [comment]
Actually, it is. Didn't checked that.
I don't understand, if this lint is currently active?
 I've created this issue, because clippy didn't show any warnings even with `pedantic` flag.

**Comment by camsteffen** [comment]
You are using bitwise operators `&` and `|` instead of `&&` and `||`. I'll keep this open since we probably should lint that. We could either lint any unnecessary bitwise operators, or just enhance `unnecessary_fold`, or both! But I think I'd prefer just adding a new lint `bitwise_bool`.

**Comment by totikom** [comment]
Yes, `bitwise_bool` sounds like an important lint.
