### ISSUE TITLE
error: unknown `doc` attribute `hide`

### ISSUE THREAD

**Issue by cquintana-verbio** [rust-lang/rust-clippy#6832]
We've encountered a possible regression on the latest nightly in our CI pipelines. Clippy does not recognize the pattern `#[doc(hide)]`, such as this one: https://github.com/kubo/rust-oracle/blob/master/src/connection.rs#L854

In the currently stable version, clippy is able to proceed.

I expected to see this happen: Clippy is able to check the code.

Instead, this happened: Clippy compains with:

```
error: unknown `doc` attribute `hide`
```

### Meta

```
λ cargo +nightly clippy -V  
clippy 0.1.52 (35dbef2 2021-03-02)

λ rustc -Vv
rustc 1.52.0-nightly (35dbef235 2021-03-02)
binary: rustc
commit-hash: 35dbef235048f9a2939dc20effe083ca483c37ff
commit-date: 2021-03-02
host: x86_64-unknown-linux-gnu
release: 1.52.0-nightly
LLVM version: 11.0.1
```

**Comment by giraffate** [comment]
It seems to be an enhancement of Rustdoc: https://github.com/rust-lang/rust/issues/82652.

**Comment by jyn514** [comment]
This is not a clippy bug, it would also happen with rustc. See https://github.com/rust-lang/rust/pull/82702 for the current discussion.
