### ISSUE TITLE
Warn on serializing C-like enums with no explicit discriminants

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust-clippy#684]
Can be a footgun:  https://twitter.com/Jonathan_Blow/status/697888374766440448

Not sure if any of our serialization libs are hardened against this. Needs some investigation.

**Comment by camsteffen** [comment]
The tweet is deleted so I think context is needed to keep this open.

**Comment by Manishearth** [comment]
I think the context was that this is a stability hazard, but TBH I don't think the Rust community has settled on strong stability of serialization without additional effort.
