### ISSUE TITLE
Replace unused fields in a pattern with the .. syntax.

### ISSUE THREAD

**Issue by nsabovic** [rust-lang/rust-clippy#6875]
### What it does

Replace unused (_) fields in a pattern with the .. syntax.

### Categories (optional)

- Kind: style

*What is the advantage of the recommended code over the original code*

- Simplifies and shortens the code.
- Prevents code from breaking when new fields are added to the struct.

### Drawbacks

None.

### Example

```rust

enum Object {
  Point { p: Vec2, notes: String, id: i32},
  Line { a: Vec2, b: Vec2, notes: String, id: i32},
}

let s = Object::Line {a: Vec2::zero(), b: Vec2::zero(), notes: String::default(), id: 0};
match s {
  Point{p, notes: _, id_ } => println!("Point {}", p),
  Line{a, b, notes: _, id: _ } => println!("Line from {} to {}", a, b),
}
```

Could be written as:

```rust
match s {
  Point{p, ..} => println!("Point {}", p),
  Line{a, b, ..} => println!("Line from {} to {}", a, b),
}
```

**Comment by mikerite** [comment]
[unneeded_field_pattern](https://rust-lang.github.io/rust-clippy/master/index.html#unneeded_field_pattern) does this.

**Comment by nsabovic** [comment]
Amazing. Thanks for pointing it out!
