### ISSUE TITLE
dark mode for "ALL the Clippy Lints" page

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-clippy#6877]
It might be neat to have a dark mode for https://rust-lang.github.io/rust-clippy/master/index.html which is a bit lighter on the eyes during nightly clippy delinting sessions.

**Comment by matthiaskrgr** [comment]
cc @xFrednet

**Comment by xFrednet** [comment]
I plan to change some things on the website in the coming month. I'll include this as well 🙃 

@rustbot claim

**Comment by xFrednet** [comment]
I thought about copying the mdbook or docs style to have it more unified among projects. Completely using that project is a new Idea to think of. This might be worth a try :)
