### ISSUE TITLE
Remove `cargo dev ra_setup`

### ISSUE THREAD

**Issue by Y-Nak** [rust-lang/rust-clippy#6883]
#6869 obsoleted `cargo dev ra_setup`, so we can remove it now!
Also, we need to update [`Getting code-completion for rustc internals to work`](https://github.com/rust-lang/rust-clippy/blob/master/CONTRIBUTING.md#getting-code-completion-for-rustc-internals-to-work) to reflect the changes.

**Comment by matthiaskrgr** [comment]
I have been holding off on doing that because I think the rust-analyzer version that provides the feature is not in nightly yet.

**Comment by matthiaskrgr** [comment]
The current nightlly ra-version is d54e1157b66017e4aae38328cd213286e39ca130 / 2021-03-08.
The support for #6869 has been merged in d57c9f79801762aa23adc21adbb638678268e96b which landed afterwards.

The next RA sync will probably be filed around the 15th so perhaps it's save to remove it on 17th-20th when the sync has landed inside the rustc repo.

**Comment by matthiaskrgr** [comment]
Apparently `cargo dev ra-setup` [is still important for people using intellij-rust](https://github.com/rust-lang/rust-clippy/pull/6888#issuecomment-797298142) so we can't just remove that!
