### ISSUE TITLE
Suggest 'const' for functions

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust-clippy#6897]
I'd like a Clippy lint to tell me to what functions in my code I can add the 'const':

```rust
const SIDE: usize = 8;

fn idx(r: usize, c: usize) -> usize {
    r * SIDE + c
}

fn item(m: &[u32; SIDE * SIDE], r: usize, c: usize) -> u32 {
    m[idx(r, c)]
}
```

==>

```rust
const SIDE: usize = 8;

const fn idx(r: usize, c: usize) -> usize {
    r * SIDE + c
}

const fn item(m: &[u32; SIDE * SIDE], r: usize, c: usize) -> u32 {
    m[idx(r, c)]
}
```

Once Rust 'const' becomes more powerful, this lint could support those new possibilities too.

**Comment by Y-Nak** [comment]
[`missing_const_for_fn`](https://rust-lang.github.io/rust-clippy/master/index.html#missing_const_for_fn) already exists for this purpose.

**Comment by leonardo-m** [comment]
Very nice, thank you, closed.
