### ISSUE TITLE
False positive for used_underscore_binding

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust-clippy#696]
Using variable names like `let mut _x` will also suppress unused_mut warnings. I've used this in a macro, so I thought I should report this here, since it's a kind of a false positive (following clippy's suggestions leads to new warnings for the use cases of the macro where the mut is unused).

**Comment by bluss** [comment]
I'm just reporting what I see, I don't know what you want to do, of course. Found in relation to PR bluss/maplit/pull/3.

**Comment by llogiq** [comment]
So we could

* limit the lint to immutable values
* somehow check if the unused_mut lint would fire and avoid minting those matches

**Comment by oli-obk** [comment]
We should probably just ensure that the lint doesn't trigger inside macros

**Comment by phansch** [comment]
This was fixed at some point and should be covered by the tests added in https://github.com/rust-lang/rust-clippy/pull/4011.
