### ISSUE TITLE
(Possibly) confusing message in ptr_arg

### ISSUE THREAD

**Issue by ChrisJefferson** [rust-lang/rust-clippy#6964]
ptr_arg prints the message:

```warning: writing `&Vec<_>` instead of `&[_]` involves one more reference and cannot be used with non-Vec-based slices```

I was confused for a while about the "one more reference", as switching does not seem to remove any references.

After some thought, is this referring to the internal implementation of Vec requiring another indirection? In that case, perhaps replace "involves one more reference" with "may produce slower code", or something like that?

**Comment by llogiq** [comment]
Let me make that visible by showing a pointer as `o->`.

`&Vec<T>`: `o->[len, capacity, o]->[T0, T1, ...]`

`&[T]`: `[len, o]->[T0, T1, ...]`
