### ISSUE TITLE
`manual_unwrap_or` hint suggest invalid code, due to macro expansion

### ISSUE THREAD

**Issue by Urcra** [rust-lang/rust-clippy#6965]
It seems that clippy expands the macro before applying some hints resulting in invalid code suggested by the hint

I tried this code:

```rust
let a_val = match value_t!(matches, "command", f64) {
   Ok(val) => val,
   Err(_) => 0.0,
};
```

I expected to see this happen: 

Suggestion for `value_t!(matches, "command", f64).unwrap_or(0.0)`

Instead, this happened: 

The suggestion seems to expand the macro, causing the code to not compile if applying the hint

```rust
help: replace with
    |
417 |     let a_val = (if let Some(v) = $m.value_of($v) {
418 |             match v.parse::<$t>() {
419 |                 Ok(val) => Ok(val),
420 |                 Err(_) => Err(::clap::Error::value_validation_auto(format!(
421 |                     "The argument '{}' isn't a valid value",
422 |                     v
  ...
```

### Meta

- `cargo clippy -V`: clippy 0.1.52 (673d0db 2021-03-23)
- `rustc -Vv`:
  ```
  rustc 1.53.0-nightly (673d0db5e 2021-03-23)
  binary: rustc
  commit-hash: 673d0db5e393e9c64897005b470bfeb6d5aec61b
  commit-date: 2021-03-23
  host: x86_64-unknown-linux-gnu
  release: 1.53.0-nightly
  LLVM version: 12.0.0
  ```

**Comment by giraffate** [comment]
reproduction on the playground: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=367a93ab1ac4ed67817f8b611a420c22
