### ISSUE TITLE
Agressive clippy

### ISSUE THREAD

**Issue by tschuett** [rust-lang/rust-clippy#6989]
GitHub Actions:
```bash
rustc 1.51.0 (2fd73fabe 2021-03-23)
/usr/share/rust/.cargo/bin/cargo clippy -- -D warnings
```
Local installation:
```bash
rustc 1.51.0 (2fd73fabe 2021-03-23)
cargo clippy  -- -D warnings
```

On GitHub Actions, I get the following error:
```bash
error: writing `&Vec<_>` instead of `&[_]` involves one more reference and cannot be used with non-Vec-based slices.
```

My local installation never gives me that error?!? The remote clippy is much more aggressive in linting.

**Comment by llogiq** [comment]
I thought #4612 was fixed...this would have been an explanation, but we'd need to know more about your setup to say for sure.

**Comment by tschuett** [comment]
Indeed the following provides more warnings
```bash
cargo check
cargo clean
cargo clippy
```

```bash
> rustc -V -v
rustc 1.51.0 (2fd73fabe 2021-03-23)
binary: rustc
commit-hash: 2fd73fabe469357a12c2c974c140f67e7cdd76d0
commit-date: 2021-03-23
host: x86_64-apple-darwin
release: 1.51.0
LLVM version: 11.0.1
>  cargo clippy -v -V
clippy 0.1.51 (2fd73fab 2021-03-23)
```

**Comment by tschuett** [comment]
You can try it with:
https://github.com/tschuett/clippy
It need to do the check clean clippy sequence to get the lint.

**Comment by tschuett** [comment]
IIRC, this is not a rust 1.51 problem. I had the same problem with 1.50.

**Comment by tschuett** [comment]
The fix https://github.com/rust-lang/rust-clippy/pull/6687 will be in 1.52.0.
