### ISSUE TITLE
Normalize asserts

### ISSUE THREAD

**Issue by tschuett** [rust-lang/rust-clippy#6999]
### What it does

Improves readability

### Categories (optional)

- Kind: *See <https://github.com/rust-lang/rust-clippy/blob/master/README.md#clippy> for list of lint kinds*

*What is the advantage of the recommended code over the original code*

For example:
- Remove bounce checking inserted by ...
- Remove the need to duplicating/storing/typo ...

### Drawbacks

None.

### Example

```rust
assert!(result.len() == self.data.len());
assert!(result.len() != self.data.len());
```

Could be written as:

```rust
assert_eq!(result.len(), self.data.len());
assert_ne!(result.len(), self.data.len());
```

**Comment by alex-700** [comment]
Duplicate of  #6637

**Comment by giraffate** [comment]
Thanks for your suggestion!

But I'm closing this because it seems to be a duplicate of #6637.
