### ISSUE TITLE
Is there any lint to indicate more than one variable with the same name in the same scope?

### ISSUE THREAD

**Issue by Dengjianping** [rust-lang/rust-clippy#7014]
Example:
```rust
{
    let a = 1u32;
    let a = 2u32;
    let a = 3u32;
}
```
I hope there's a warning that can be showed here.

**Comment by Y-Nak** [comment]
You can use [shadow_unrelated](https://rust-lang.github.io/rust-clippy/master/#shadow_unrelated) or [shadow_reuse](https://rust-lang.github.io/rust-clippy/master/#shadow_reuse) for the purpose.

**Comment by Dengjianping** [comment]
Wow, thank you! I'm going to close it.
