### ISSUE TITLE
Clippy invalid suggestion for format!("{}", &s)

### ISSUE THREAD

**Issue by dolly-ent** [rust-lang/rust-clippy#7078]
I tried to `clippy --fix` this code

```rust
#![allow(dead_code)]

enum A {
    B(String),
    C,
}

fn main() {
    let a = A::C;
    let s: String = match a {
       A::B(s) => format!("{}", &s),
       A::C => format!("{}", "hello"),
    };
    println!("{}", s);
}
```

This fixes to:

```rust
match a {
    A(s) => &s.to_string(),
    B(_) => "hello".to_string(),
}
```

But now the different branches have different types. This highlights that the suggested fix even on stable is not correct:

```
warning: useless use of `format!`
  --> src/main.rs:11:19
   |
11 |        A::B(s) => format!("{}", &s),
   |                   ^^^^^^^^^^^^^^^^^ help: consider using `.to_string()`: `&s.to_string()`
   |
   = note: `#[warn(clippy::useless_format)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#useless_format
```

It should suggest
```
help: consider using `.to_string()`: `(&s).to_string()`
```

### Meta

- `cargo clippy -V`: clippy 0.1.51 (2fd73fab 2021-03-23)
- `cargo +nightly-x86_64-apple-darwin clippy -V`: clippy 0.1.52 (07e0e2ec 2021-03-24)
- `rustc -Vv`:
  ```
rustc 1.51.0 (2fd73fabe 2021-03-23)
binary: rustc
commit-hash: 2fd73fabe469357a12c2c974c140f67e7cdd76d0
commit-date: 2021-03-23
host: x86_64-apple-darwin
release: 1.51.0
LLVM version: 11.0.1
  ```

**Comment by basavesh** [comment]
https://github.com/rust-lang/rust-clippy/pull/7092 Fixes this.

> +error: useless use of `format!`
> +  --> $DIR/format.rs:82:19
> +   |
> +LL |        A::B(s) => format!("{}", &s),
> +   |                   ^^^^^^^^^^^^^^^^^ help: consider using `.to_string()`: `(&s).to_string()`
> +
> +error: useless use of `format!`
> +  --> $DIR/format.rs:83:16
> +   |
> +LL |        A::C => format!("{}", "hello"),
> +   |                ^^^^^^^^^^^^^^^^^^^^^^ help: consider using `.to_string()`: `"hello".to_string()`
> +
> +error: aborting due to 16 previous errors

**Comment by giraffate** [comment]
#7092 fixed this, so I'm closing this.
