### ISSUE TITLE
Suggest Iterator::count instead of collecting + len

### ISSUE THREAD

**Issue by Luro02** [rust-lang/rust-clippy#7110]
### What it does

Suggests the use of [`Iterator::count`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.count) instead of collecting into a collection and then calling its `len` function.

### Categories (optional)

- Kind: `clippy::complexity`

*What is the advantage of the recommended code over the original code*

- Simpler to read
- No Heap Allocations

### Drawbacks

None.

### Example

```rust
fn count(string: &str) -> usize {
    let buffer: Vec<&str> = string.split('/').collect();
    buffer.len()
}
```

Could be written as:

```rust
fn count_rewritten(string: &str) -> usize {
    string.split('/').count()
}
```
[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&code=%23!%5Bwarn(clippy%3A%3Apedantic%2C%20clippy%3A%3Anursery%2C%20clippy%3A%3Aall)%5D%0A%0Afn%20count(string%3A%20%26str)%20-%3E%20usize%20%7B%0A%20%20%20%20let%20buffer%3A%20Vec%3C%26str%3E%20%3D%20string.split('%2F').collect()%3B%0A%20%20%20%20buffer.len()%0A%7D%0A%0Afn%20count_rewritten(string%3A%20%26str)%20-%3E%20usize%20%7B%0A%20%20%20%20string.split('%2F').count()%0A%7D%0A%0Afn%20main()%20%7B%0A%20%20%20%20println!(%22count%3A%20%7B%7D%22%2C%20count(%22hello%2Fworld%22))%3B%0A%20%20%20%20println!(%22rewrite%3A%20%7B%7D%22%2C%20count_rewritten(%22hello%2Fworld%22))%3B%0A%7D)

**Comment by llogiq** [comment]
That should be caught by `needless_collect`.

**Comment by llogiq** [comment]
Note that this should only lint for collections where the `len()` actually equals the `count()`. `Vec` and `VecDeque` as well as `BinaryHeap`. Notably, neither the `*Set`s nor `String`s  uphold this equality.

**Comment by mgacek8** [comment]
> Note that this should only lint for collections where the `len()` actually equals the `count()`.

Yep, that's right. Currently this lint (in case of indirect usage, as in the above example) [respects Vec, VecDeque and LinkedList](https://github.com/rust-lang/rust-clippy/blob/HEAD/clippy_lints/src/loops/needless_collect.rs#L73-L75).
The problem is that it doesn't work when a type annotation is used.

**Comment by mgacek8** [comment]
>  as well as `BinaryHeap`

`BinaryHeap` is missing, so I'll add that
