### ISSUE TITLE
`missing_const_for_fn`: Known Problems should include future compatibility hazard

### ISSUE THREAD

**Issue by tspiteri** [rust-lang/rust-clippy#7121]
Marking a private function as const when possible does not cause an issue. But marking a public function as const can become a problem in the future if the implementation changes, as removing const would break API compatibility. It is true that the `missing_const_for_fn` lint is allow by default, but I feel that this future compatibility hazard should be included in the Known Problems.

**Comment by tspiteri** [comment]
Or maybe the lint should not be enabled for public functions.

**Comment by llogiq** [comment]
Not enabling the lint on exported functions would make it strictly less useful, but allowing to configure that behavior and adding a note to both the docs and lint message would improve it.
