### ISSUE TITLE
Warn when forgetting to flush stdout before calling std::process::exit.

### ISSUE THREAD

**Issue by ticki** [rust-lang/rust-clippy#713]
`std::process::exit` does not call destructors, thus the buffered standard output should be flushed before calling `exit` to avoid silencing standard output. A lint ensuring that can potentially create false positives, thus I propose adding it to `clippy-pedantic` group.

**Comment by finnbear** [comment]
Maybe this is obsolete? https://internals.rust-lang.org/t/question-what-causes-stdout-to-flush-after-main/12909

**Comment by y21** [comment]
Closing since nowadays `exit()` ends up calling `io::cleanup()` which flushes stdout, so this is no longer needed as a lint
