### ISSUE TITLE
`multiple_inherent_impl` shouldn't be triggered across files

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/rust-clippy#7131]
It is actually a good thing (IMO) to separate an implementation block into two or more files when the block is too large (+2000 lines) or the block can be logically separated (when necessary) to enhance single responsibility.

**Comment by camsteffen** [comment]
I would expect the lint to disallow multiple impls entirely by default. It could be a config option I guess. Technically, I would compare the module instead of the file.

**Comment by c410-f3r** [comment]
Closing due to the lack activeness. Feel free to open this issue if desired.
