### ISSUE TITLE
Prefer `vec.append(vec)` over `vec.extend(vec.drain(..))`

### ISSUE THREAD

**Issue by seritools** [rust-lang/rust-clippy#7209]
### What it does

This lint would suggest using the specialized `Vec::append` instead of `vec.extend(other_vec.drain(..))`.

### Categories (optional)

- Kind: `clippy::style`

*What is the advantage of the recommended code over the original code*

- Slightly more succinct code
- Potentially better perf?
- Helps raise awareness of `append` even existing :)

### Drawbacks

None that I could come up with

### Example

```rust
let mut a = vec![0u8; 1024];
let mut b = Vec::new();

b.extend(a.drain(..));
```

Could be written as:

```rust
let mut a = vec![0u8; 1024];
let mut b = Vec::new();

b.append(&mut a);
```

**Comment by Valentine-Mario** [comment]
> Hey, I've noticed that this issue is still open after the implementation was merged in #7270. @Valentine-Mario here is a neat-trick for the next time: you can close issues when a PR is merged by including a `closes #<id>` in the PR description. ([GitHub documentation for more keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)) 
> 
> cc: @flip1995 could you close this issue?

Oh. Was looking for the close issue button. Lol. Thanks
