### ISSUE TITLE
New Lint: Unsafe block in safe functions without `SAFETY` comment 

### ISSUE THREAD

**Issue by fee1-dead** [rust-lang/rust-clippy#7238]
### What it does

Detects unsafe blocks used in safe functions missing a comment explaining/justifying the use of `unsafe`.

### Categories (optional)

- Kind: `clippy::pedantic`

*What is the advantage of the recommended code over the original code*

- Explains why the use of `unsafe` in the function is okay
- Makes it easier to maintain

### Drawbacks

None.

### Example

```rust
fn get(self, slice: &[T]) -> Option<T> {
  if self < slice.len() { unsafe { Some(&*self.get_unchecked(slice)) } } else { None }
}
```

Could be written as:

```rust
fn get(self, slice: &[T]) -> Option<T> {
  // SAFETY: `self` is checked to be in bounds.
  if self < slice.len() { unsafe { Some(&*self.get_unchecked(slice)) } } else { None }
}
```

**Comment by giraffate** [comment]
From [API guidelines](https://rust-lang.github.io/api-guidelines/documentation.html), unsafe functions should be documented with a "Safety" section, so why do you want it with unsafe blocks?

FYI, Clippy has the [`missing_safety_doc`](https://rust-lang.github.io/rust-clippy/master/index.html#missing_safety_doc) lint.

**Comment by fee1-dead** [comment]
There are some requirements for a call to an unsafe function to be safe. A comment with unsafe blocks can explain how the safety contract is respected. As shown in the example, it could be easier to maintain if the developer knows that unsafe block has been checked. This new lint can help developers to make sure that all usage of unsafe is documented.

For checking comments, I don't know if there is a solution. The Rust repository does document their usage of unsafe so I thought "why not a lint?"

**Comment by fee1-dead** [comment]
Since #7748 was merged, I am closing this.
