### ISSUE TITLE
Use rustc_lint::builtin::has_doc

### ISSUE THREAD

**Issue by camsteffen** [rust-lang/rust-clippy#7247]
See https://github.com/rust-lang/rust/pull/85457#discussion_r634861596

**Comment by jyn514** [comment]
This is still not the same behavior of `has_doc`:
```rust
fn has_doc(sess: &Session, attr: &ast::Attribute) -> bool {
    if attr.is_doc_comment() {
        return true;
    }

    if !sess.check_name(attr, sym::doc) {
        return false;
    }

    if attr.value_str().is_some() {
        return true;
    }

    if let Some(list) = attr.meta_item_list() {
        for meta in list {
            if meta.has_name(sym::hidden) {
                return true;
            }
        }
    }

    false
}
```
Seems not great for them to be inconsistent.

**Comment by jyn514** [comment]
Hmm, I take it back, clippy just checks for `doc(hidden)` seperately: https://github.com/camsteffen/rust-clippy/blob/c21b965d43d5584c3e0df219e6638494d2dc3ea9/clippy_lints/src/missing_doc.rs#L87
I guess it's not a big deal; you could remove `doc_hidden_stack` if you made this cleanup though.

Also, I suspect clippy has the same bug as rustdoc when items under a hidden module are re-exported: https://github.com/rust-lang/rust/issues/59368

**Comment by camsteffen** [comment]
I'm not sure if there is something actionable here? Maybe there is still room for sharing code but it seems insignificant. I don't know how that bug would apply to the Clippy lint.

**Comment by jyn514** [comment]
@camsteffen here is how I think the false positive would show up:

```rust
#[doc(hidden)]
pub mod inner {
  pub struct MissingDocs;
}

pub use inner::MissingDocs; // should warn about an undocumented struct, but does not.
```
It doesn't matter until the rustdoc bug is fixed, though.
