### ISSUE TITLE
extend redundant_allocation to Arc

### ISSUE THREAD

**Issue by lengyijun** [rust-lang/rust-clippy#7303]
Currently redundant_allocation check Rc and Box. And it can be extended to Arc, which is quite similar to Rc.
redundant_allocation should check:
```
Arc<Arc<T>>
Arc<Box<T>>
Arc<&T>
```

If it's ok, I can give a pr.

**Comment by xFrednet** [comment]
Thanks for taking over the implementation of this issue. You can comment `@rustbot claim` to assign the issue to yourself. That also indicates to others that someone is working on it, and you can unassign yourself at any time. :upside_down_face: 

@rustbot label +C-enhancement +good-first-issue
