### ISSUE TITLE
lint on manual `Hash`, `*Ord`, `*Eq` impls that access a `*Cell`

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust-clippy#732]
even read-only access can be bad, because between two calls to `hash`, the cell might have changed its value, even if there are only immutable references present.

cc #729 

should be fairly straight forward.
1. Find impls of the above traits
2. check if the type has fields that have interior mutability
3. check if the impl-method has an ExprField for one of the interior mutability fields

bonus points for also checking inherent methods that are called in the impl method for interior mutation.

**Comment by llogiq** [comment]
we should also warn on `std::sync::atomic` types (as they also can be mutated from a `&` ref.

**Comment by llogiq** [comment]
I think that people might want those impls anyway. Especially Ord and Eq might be helpful for sorting or partitioning a collection (or a variety of other things) while having a `&mut` ref ensures no concurrent modification.
