### ISSUE TITLE
needless_bool fix suggestion can trigger nonminimal_bool lint

### ISSUE THREAD

**Issue by DoumanAsh** [rust-lang/rust-clippy#7320]
Following code:
```
let is_configured = if p.data[0] == 0 { false } else { true };
```

Triggers following warning:
```
warning: this if-then-else expression returns a bool literal
   --> src\pb1sub\mod.rs:468:37
    |
468 |                 let is_configured = if p.data[0] == 0 { false } else { true };
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: you can reduce it to: `!(p.data[0] == 0)`
    |
    = note: `#[warn(clippy::needless_bool)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_bool
```

Applying fix `!(p.data[0] == 0)` then triggers another lint:

```
warning: this boolean expression can be simplified
   --> src\pb1sub\mod.rs:469:37
    |
469 |                 let is_configured = !(p.data[0] == 0);
    |                                     ^^^^^^^^^^^^^^^^^ help: try: `p.data[0] != 0`
    |
    = note: `#[warn(clippy::nonminimal_bool)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#nonminimal_bool
```

So it would be nice if clippy would provide a better suggestion if possible?

Used version:
```
clippy 0.1.52 (88f19c6d 2021-05-03)
rustc 1.52.0 (88f19c6da 2021-05-03)
```

**Comment by hotate29** [comment]
I would like to work on this issue. I'm not very familiar with the internals of Clippy, so it may take some time...

**Comment by llogiq** [comment]
Ok, so I guess you should try checking for `ExprKind::Binary` and then invert the operation instead of surrounding with `!(..)`.

**Comment by hotate29** [comment]
Thank you for the information! I've checked ``` ExprKind::Binary```.
I'm trying to rewrite the implementation of the ```Not``` trait in ```Sugg```.

For example
```<=``` to ```>``` and ```==``` to ```!=```.
For ```&&```, ```||```, etc., we'll still use ```! (..)```. is returned.
https://github.com/rust-lang/rust-clippy/blob/53059792e9a7b7adeff387ceb995a50a6c33b3fa/clippy_utils/src/sugg.rs#L394-L399

**Comment by hotate29** [comment]
However, this measure may have an impact on other codes. In that case, I will implement a process to replace the comparison operator in ``clippy_lints/src/needless_bool.rs``.

https://github.com/rust-lang/rust-clippy/blob/48d939f5166a19529a9e4723ed3bf5bab2314563/clippy_lints/src/needless_bool.rs#L121-L123
