### ISSUE TITLE
Normalize semicolon inside/outside blocks for `()` returning expressions

### ISSUE THREAD

**Issue by ojeda** [rust-lang/rust-clippy#7322]
### What it does

For `()` returning expressions, check that the semicolon is inside/outside the block.

Either way it is fine, but consistency is best. Having the semicolon inside may be slightly nicer and more similar to, say, conditionals and loop bodies.

### Categories (optional)

- Kind: `clippy::style`

### Drawbacks

It is subjective, so perhaps we should offer both ways, one enabled by default.

### Example

```rust
unsafe { f(x) };
```

Could be written as:

```rust
unsafe { f(x); }
```

**Comment by bjorn3** [comment]
This should preferably work for all blocks, not just unsafe blocks. Maybe it should also work for if else and match.

**Comment by mbartlett21** [comment]
Having the semicolon outside means that rustfmt then doesn't make the block three lines.

E.g:
```rs
unsafe { my_fn(); }

// Helpfully formats to:
unsafe {
    my_fn();
}
```

**Comment by 1c3t3a** [comment]
@rustbot claim 
I'm going to work on this the coming week!
