### ISSUE TITLE
New lint: suggest the use of Result::unwrap_or_else over Result::map_or_else

### ISSUE THREAD

**Issue by jhscheer** [rust-lang/rust-clippy#7328]
### What it does
Suggest the use of `Result::unwrap_or_else` over `Result::map_or_else` **if** `map_or_else` is just used to unpack a successful result while handling an error.

### Categories (optional)

*What is the advantage of the recommended code over the original code*

Code will be shorter (and cleaner).

### Drawbacks

None.

### Example

```rust
.map_or_else(
    |e| handle_the_error(e),
    |n| n,
)
```

Could be written as:

```rust
.unwrap_or_else(|e| handle_the_error(e))
```

**Comment by camsteffen** [comment]
I think an enhancement to `map_identity` would do.

**Comment by KisaragiEffective** [comment]
I've found another case.

```
let res: Result<usize, usize> = foo();
let v: usize = foo.map_or_else(|x| x, |x| x);
```

can be following code:

```
let v: usize = foo.unwrap_or_else(|x| x)
```

**Comment by GuillaumeGomez** [comment]
Adding a lint for it.
