### ISSUE TITLE
As mentioned in my other comment, I believe this should be one command towards the replica and the replica itself cares about the deactivate/close order of its Peas. The CompoundPod should not need to orchestrate these calls.

### ISSUE THREAD

**Issue by 0969397110** [rust-lang/rust-clippy#7348]
As mentioned in my other comment, I believe this should be one command towards the replica and the replica itself cares about the deactivate/close order of its Peas. The CompoundPod should not need to orchestrate these calls.

_Originally posted by @maximilianwerk in https://github.com/jina-ai/jina/pull/2344#discussion_r627164704_

__Originally posted by @maximilianwerk in https://github.com/jina-ai/jina/issues/2383__

__Originally posted by @0969397110 in https://github.com/0969397110/vinh/issues/1__

**Comment by xFrednet** [comment]
Hey @0969397110, I'm not sure what you mean with this issue. Are you sure that you wanted to create it in this repository? If so, could you update the description and title to clarify what you want to say? :upside_down_face:

**Comment by maximilianwerk** [comment]
Hey, 

I am the original author of this ticket in jina-ai/jina. At the end of last week, we have seen several of such "mirror" issues in other repositories and are puzzled where they came from. Please just close this one.

I am very sorry for the disturbance. All the best!

Maximilian

**Comment by xFrednet** [comment]
Hey @maximilianwerk, thank you for getting back to us on this one. All the best to you too :upside_down_face: 

cc: @flip1995 could you close this issue for us? (I don't think that there is a rustbot command for that :upside_down_face: )

**Comment by flip1995** [comment]
Hm, I've seen some spam comments in this repo by the user @0969397110 recently. @maximilianwerk were the mirror issues opened by the same user? In that case we should probably ban that user, to avoid this in the future.



> I am very sorry for the disturbance. All the best!

No problem, that's not your fault! :)

**Comment by maximilianwerk** [comment]
> Hm, I've seen some spam comments in this repo by the user @0969397110 recently. @maximilianwerk were the mirror issues opened by the same user? In that case we should probably ban that user, to avoid this in the future.

No, it came from several users, mostly fresh accounts. We got quite some traction on reddit for our project recently. That might also have attracted some trolls... :roll_eyes:

**Comment by flip1995** [comment]
Ok, I wonder what this is then (bots?)...  Thanks for the information. I hope we don't have to deal with those things too much...
