### ISSUE TITLE
optionally enable upper_case_acronyms for pub items

### ISSUE THREAD

**Issue by M1cha** [rust-lang/rust-clippy#7384]
You recently disabled it for all public items but if you don't care about breaking changes(new major version, cargo workspace, ...) this warning can be very useful.

**Comment by camsteffen** [comment]
This is possible with the `avoid-breaking-exported-api` config option.

**Comment by M1cha** [comment]
thanks, this wasn't released yet, that's why I missed it :laughing: 
I'll be patiently waiting for 1.54 then :grin:
