### ISSUE TITLE
clippy fix fails: warning: failed to automatically apply fixes suggested by rustc to crate

### ISSUE THREAD

**Issue by chathaway-codes** [rust-lang/rust-clippy#7392]
I tried this code:

```rust
struct Player {
    hand: Vec<usize>,
}

fn main() {
    let p = Player {
        hand: vec![1, 2, 3, 4, 5],
    };
    let filter_hand = vec![5];
    let new_hand: Vec<usize> = p
        .hand
        .iter()
        .filter(|c| filter_hand.iter().find(|cc| c == cc).is_none())
        .map(|c| c.clone())
        .collect();
    println!("Hello, world!");
}
```
(this is a reduced and largely nonsensical version of the real issue I hit)

With the command: cargo clippy --fix -Z unstable-options --allow-dirty

I expected to see this happen: Clippy cleanup the source code without error.

Instead, this happened: I got a rather long error message, [output.txt] attached.

[output.txt](https://github.com/rust-lang/rust/files/6692540/output.txt)

### Meta

- `cargo clippy -V`: e.g. clippy 0.0.212 (f455e46 2020-06-20)
- `rustc -Vv`:

```
% cargo clippy -V 
clippy 0.1.54 (ce1d561 2021-06-18)
% rustc -Vv
rustc 1.55.0-nightly (ce1d5611a 2021-06-18)
binary: rustc
commit-hash: ce1d5611a28468663e275078649e7ca6eef735a8
commit-date: 2021-06-18
host: x86_64-unknown-linux-gnu
release: 1.55.0-nightly
LLVM version: 12.0.1
```

<details><summary>Backtrace</summary>
  <p>
  
  ```
N/A, no crash
  ```
  
  </p>
</details>

**Comment by chathaway-codes** [comment]
Original bug report: https://github.com/rust-lang/rust/issues/86538

**Comment by camsteffen** [comment]
Clippy is suggesting `any(|cc| c == cc)` instead of `any(|cc| c == &cc)`. `find` gives a reference to the element and `any` does not.
