### ISSUE TITLE
Lint on `loop { continue }`

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust-clippy#7417]
### What it does

`loop { continue }` is heavily used in the embedded ecosystem to sidestep an LLVM miscompilation. However, nowadays it results in the same MIR and thus LLVM IR as `loop {}`, and the miscompilation of `loop {}` has been fixed, so this is unnecessary.

### Categories (optional)

- Kind: `clippy::style` probably, since it's just a confusing way to write `loop {}`

*What is the advantage of the recommended code over the original code*

Looks clearer

### Drawbacks

None.

Linting on macros that expand to `continue;` should probably be avoided though.

### Example

```rust
loop { continue; }
```

Could be written as:

```rust
loop {}
```

**Comment by giraffate** [comment]
> However, nowadays it results in the same MIR and thus LLVM IR as loop {}, and the miscompilation of loop {} has been fixed, so this is unnecessary.

Is there the related PR or discussion? Just wondering.

**Comment by jonas-schievink** [comment]
The PRs fixing this are probably linked from somewhere in https://github.com/rust-lang/rust/issues/28728

**Comment by camsteffen** [comment]
This can be an enhancement of `needless_continue`.
