### ISSUE TITLE
Create more than 2 lint groups

### ISSUE THREAD

**Issue by mcarton** [rust-lang/rust-clippy#743]
Currently we have two lint groups, `clippy` and `clippy_pendantic`.

We’ve already discussed that we should have more.

I can think of:
- `clippy_deprecated`: group where we move lints we ultimately want to remove (ref #728);
- `clippy_non_api_breaking`: subgroup of `clippy` with only lints whose fix would not change the public API (eg. no `ptr_arg`, `type_complexity`, `wrong_pub_self_convention`, etc.). Useful for crate which did not use Clippy historically and don’t want to change their API. Or maybe `clippy_api_breaking` with only those lints? Or both and ensure any lint is in either one?

Can you think of other groups you’d want?

**Comment by llogiq** [comment]
Perhaps subgroups of `clippy` based on goals, like `clippy_style`, `clippy_performance`, `clippy_badcode` or something similar? On the other hand, there's probably not much value in having them besides documentation.

**Comment by mcarton** [comment]
Yep. While documentation is a good thing, I don’t know if that should be reflected in a lint group.

**Comment by Manishearth** [comment]
I don't think overlapping or nested groups work well.

Mostly; I was thinking of keeping pedantic, and adding three more. clippy_stable which suggests stable ways to do unstable things, clipy_restrictions for containing things which aren't style choices (see Graydon's issue), and clippy_deprecated for the deprecated ones.

I'd like to keep the Warn lints in clippy as much as possible.

**Comment by llogiq** [comment]
So cyclomatic_complexity would be our first restrictions lint, right?

**Comment by Manishearth** [comment]
idk. I think cyclomatic complexity with a sensible limit is a valid style lint.

**Comment by oli-obk** [comment]
restrictions are something like `deny(allocations)` or `deny(unsafe)` (actually when using restrictions one should use `forbid`). I'm not sure that a lint-group makes sense for restrictions, because it's unlikely you'll ever want to activate all of them.

**Comment by Manishearth** [comment]
Right, but I don't want any lints in clippy to be groupless.

**Comment by llogiq** [comment]
Perhaps we could also add a "newbie" lint group. IMHO `inline_always` and `linked_list` would happen to fall in that category. Those are lints that offer reasonable advice to newbies that experts will sometimes find good reason to act against.

**Comment by Manishearth** [comment]
I think almost all our lints have cases where experts will have good reason to act against. IMO newbie lints should be part of the regular stuff.

(note that inline_always's issues aren't common knowledge)

**Comment by clarcharr** [comment]
FWIW I think that  `clippy_incorrect` and `clippy_idiomatic` might be useful. The former lints things that are probably bugs, and the latter suggests rewording things to a more "rusty" way. Someone might not care about the latter, but still the former.

**Comment by camsteffen** [comment]
Closing since there are newer issues and a lot has changed.
