### ISSUE TITLE
`assert_eq!(sth, true)` is replaced with (literally) `assert!(..)`

### ISSUE THREAD

**Issue by duongdominhchau** [rust-lang/rust-clippy#7465]
Create a new empty binary project and change `src/main.rs` to

```rust
fn main() {
    let a = 1;
    assert_eq!(a == 1, true);
}
```

Then open this project in VSCode, that `assert_eq!` will be suggested to be replaced. When I apply the suggestion, it becomes `assert!(..)`.

https://user-images.githubusercontent.com/56427890/125624445-489a28b9-83c7-44bc-8183-911adf11b63f.mp4

### Meta

- `cargo clippy -V`: `clippy 0.1.55 (d2b04f0 2021-07-07)`
- `rustc -Vv`: 
```
rustc 1.55.0-nightly (d2b04f075 2021-07-07)
binary: rustc
commit-hash: d2b04f075c0ce010758c4c8674152ff89d1d73f3
commit-date: 2021-07-07
host: x86_64-unknown-linux-gnu
release: 1.55.0-nightly
LLVM version: 12.0.1
```

Edit: I have just run `rustup update`, the problem still persists.
- `cargo clippy -V`: `clippy 0.1.55 (3e1c75c 2021-07-13)`
- `rustc -Vv`: 
```
rustc 1.55.0-nightly (3e1c75c6e 2021-07-13)
binary: rustc
commit-hash: 3e1c75c6e25a4db968066bd2ef2dabc7c504d7ca
commit-date: 2021-07-13
host: x86_64-unknown-linux-gnu
release: 1.55.0-nightly
LLVM version: 12.0.1
```

**Comment by xFrednet** [comment]
Hey, thank you for the report. Are you sure this is a Clippy issue? Clippy is usually triggered by running `cargo clippy` and it doesn't replace any text unless ordered to.

Your video shows hints in the code itself. It looks to me like you're using rust-analyzer or a different vs-code plugin.

If you're unsure, could you run `cargo clippy` and provide the output? 🙃

**Comment by duongdominhchau** [comment]
Sorry, seems like I reported in the wrong place. I thought the suggestion is provided by clippy so I reported it here, but now I tried `cargo clippy --fix` and nothing changed.
