### ISSUE TITLE
`RefCell<u32>` -> `Cell<u32>`

### ISSUE THREAD

**Issue by lengyijun** [rust-lang/rust-clippy#7491]
### What it does

Suggest using `Cell<T>` instead of `RefCell<T>`, T=u32,i32,f32 ...

### Categories

`clippy::perf`

*What is the advantage of the recommended code over the original code*

- `RefCell` will calculate borrow at runtime, so `RefCell` has more overhead over `Cell`
- `RefCell` may panic at runtime

### Drawbacks

Maybe some problems in generic type.

### Example

```rust
struct S(RefCell<u32>);
```

Could be written as:

```rust
struct S(Cell<u32>);
```

**Comment by camsteffen** [comment]
You double submitted :)
