### ISSUE TITLE
LateContext::typeck_results` called outside of body

### ISSUE THREAD

**Issue by KaiserKarel** [rust-lang/rust-clippy#7508]
thread 'rustc' panicked at '`LateContext::typeck_results` called outside of body', src/tools/clippy/clippy_lints/src/use_self.rs:213:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.55 (2f391da 2021-07-14)

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `ink_env`

To learn more, run the command again with --verbose.

**Comment by Jarcho** [comment]
Can't repro on the latest nightly. Looks like it was fixed with #7428.

**Comment by giraffate** [comment]
Thanks for the report!

I'm closing this because of https://github.com/rust-lang/rust-clippy/issues/7508#issuecomment-890273350.
