### ISSUE TITLE
bad fix suggested for non-mut ref to a mut value

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [rust-lang/rust-clippy#7524]
For `cargo +nightly clippy`, given the following code:
```rust
let mut x = vec![0, 1, 2, 3, 5];
let ref_x = &mut x;
let mut y = Vec::new();
// manual append
y.extend(ref_x.drain(..));
```
`clippy` suggests using
```rust
y.append(&mut ref_x);
```
This fails to compile as `ref_x` itself is immutable. The correct suggestion should probably be:
```rust
y.append(ref_x);
```

### Meta
```
cargo clippy -V: 
    clippy 0.1.54 (a178d03 2021-07-26)
```
```
rustc -Vv:
    rustc 1.54.0 (a178d0322 2021-07-26)
    binary: rustc
    commit-hash: a178d0322ce20e33eac124758e837cbd80a6f633
    commit-date: 2021-07-26
    host: x86_64-unknown-linux-gnu
    release: 1.54.0
    LLVM version: 12.0.1
```

**Comment by xFrednet** [comment]
Seems like we've missed that case :). The fix can most likely just check the type of `ref_x` and then decide based on that if `&mut` has to be added. (See [`clippy_lints/src/methods/append_instead_of_extend.rs`](https://github.com/Valentine-Mario/rust-clippy/blob/44608b1857951ba82b630853da6fc6c2f40fde53/clippy_lints/src/methods/append_instead_of_extend.rs#L19-L20))

cc: @Valentine-Mario FYI and in case you're interested in fixing this :upside_down_face: 

---

@rustbot label +good-first-issue +I-suggestion-causes-error

**Comment by Valentine-Mario** [comment]
> Seems like we've missed that case :). The fix can most likely just check the type of `ref_x` and then decide based on that if `&mut` has to be added. (See [`clippy_lints/src/methods/append_instead_of_extend.rs`](https://github.com/Valentine-Mario/rust-clippy/blob/44608b1857951ba82b630853da6fc6c2f40fde53/clippy_lints/src/methods/append_instead_of_extend.rs#L19-L20))
> 
> cc: @Valentine-Mario FYI and in case you're interested in fixing this 🙃
> 
> @rustbot label +good-first-issue +I-suggestion-causes-error

Yeah sure let me give it a look

**Comment by Valentine-Mario** [comment]
@xFrednet how do I check if a variable is mutable or immutable? having a hard time figuring that out.

**Comment by xFrednet** [comment]
Hey, this depends on the object you want to check it for. In this case, we already have the source type. I believe that [`Ty::is_mutable_ptr(&self)`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.TyS.html#method.is_mutable_ptr) should work here. Could you try that? I can do some more digging if that doesn't work :upside_down_face:

**Comment by Valentine-Mario** [comment]
@xFrednet  in the case as above, the source type `src_ty.is_mutable_ptr()` would always return false as it points to the type of the value assigned not the var itself.

**Comment by xFrednet** [comment]
Ups, you're right. What you can do is first check the type of `drain_vec` without calling `.peel_refs()` on it. That preserves the fact that it's actually a `&mut T`.

I've basically tried this:
```rs
println!("{:?}", cx.typeck_results().expr_ty(drain_vec).is_mutable_ptr()); // true for &mut
println!("{:?}", cx.typeck_results().expr_ty(drain_vec).peel_refs().is_mutable_ptr()); // false due to peel_refs()
```

Is that enough @Valentine-Mario ? :upside_down_face:
