### ISSUE TITLE
never_loop in for loop

### ISSUE THREAD

**Issue by HKalbasi** [rust-lang/rust-clippy#7537]
People use a never_loop for loop for picking first element (if exists) of an iterator. It is possible without such a loop with `if let Some(elem) = x.iter().next() {` instead of `for elem in x {` but is it considered a better way? If it isn't, we should disable never_loop for `for` loops. If it is, we can provide a auto-fix suggestion so people who are not aware of this, don't disable lint.

**Comment by camsteffen** [comment]
I don't think it should be disabled for `for` loops. So add a suggestion like this? SGTM.

```text
error: this loop never actually loops
 --> src/main.rs:3:5
  |
3 | /     for first in v {
4 | |         println!("first: {}", first);
5 | |         break;
6 | |     }
  | |_____^

help: try writing

    if let Some(first) = v.into_iter().next() {
        println!("first: {}", first);
    }
