### ISSUE TITLE
Detect redundant `Default` implementations

### ISSUE THREAD

**Issue by tsoutsman** [rust-lang/rust-clippy#7550]
### What it does

Detects custom `std::default::Default` implementations that are identical to a derived implementation. This could probably be done with other derive attributes, but I think `Default` is a fairly common one that people may implement themselves.

### Categories (optional)

- Kind: `clippy::style`

*What is the advantage of the recommended code over the original code*

It is more concise.

### Drawbacks

I have no clue about the internals of Clippy, so I'm not sure how hard it would be to implement.

### Example

```rust
struct Foo {
    bar: bool
}

impl std::default::Default for Foo {
    fn default() -> Self {
        Self {
            bar: false
        }
    }
}
```

Could be written as:

```rust
#[derive(Default)]
struct Foo {
    bar: bool
}
```

**Comment by camsteffen** [comment]
Lint name idea: `derivable_impls`

Huh, I'm surprised we don't have this!
