### ISSUE TITLE
iter_skip_next creates confusion

### ISSUE THREAD

**Issue by pchampin** [rust-lang/rust-clippy#7551]
As I have [reported elsewhere](https://github.com/rust-lang/rust/issues/87911), I consider the `Iterator::nth` method to be very badly named, and so the suggestion by clippy to replace `.skip(n).next()` by `.nth(n)` is a bad idea, in my opinion.

The reader could be under the impression that `it.nth(2)` will return the second element of the iterator, while in fact it will return the third one. I think the  skip+next pattern is much more explicit and unambiguous.

**Comment by giraffate** [comment]
I have the same question as https://github.com/rust-lang/rust/issues/87911#issuecomment-896231506.

**Comment by mikerite** [comment]
I don't think it would be good for Rust if the libs team said a method was fine and the linter discouraged it's use. So I would say this issue should be closed pending the outcome of rust-lang/rust#87911. At least then all the discussion can be kept in one place.

**Comment by pchampin** [comment]
@milerite my suggestion was indeed not meant to disavow the libs team by discourageing the use of `nth`.
 It was to merely stop actively encouraging it, by disabling the `iter_skip_next` rule.

**Comment by camsteffen** [comment]
`Iterator::nth` is idiomatic Rust. It doesn't make sense to stop suggesting it based on one person's opinion. At a bare minimum, I think we would need some evidence that a significant portion of the Rust community dislikes `nth` to change Clippy. I am quite certain that is simply not the case.

**Comment by pchampin** [comment]
Apologies if it sounded like I was trying to impose a personal opinion. My goal was merely to open the discussion.
