### ISSUE TITLE
branches_sharing_code suggests code with different semantics

### ISSUE THREAD

**Issue by jorgecarleitao** [rust-lang/rust-clippy#7555]
Lint name: branches_sharing_code

I tried this code:

```rust
fn main() {
    let mut a = 9;

    let b = if a == 10 {
        a += 1;
        Some(10)
    } else {
        a += 1;
        Some(5)
    };
    println!("{:?}", b);
}
```

I expected to see this happen: No suggestions.

Instead, this happened: there is a suggestion to write the above as 

```rust
fn main() {
    let mut a = 9;

    a += 1;
    let b = if a == 10 {
        Some(10)
    } else {
        a += 1;
        Some(5)
    };
    println!("{:?}", b);
}
```

which is not semantically equivalent: one prints `Some(5)`, the other `Some(10)`.

I.e. it seems that there is a suggestion to commute two non-commutable lines.

### Meta

- `cargo clippy -V`: e.g. clippy 0.1.56 (4927238 2021-07-29)
- `rustc -Vv`:
  ```
  rustc 1.56.0-nightly (492723897 2021-07-29)
  binary: rustc
  commit-hash: 492723897e9b4db6701b3a75b72618d08a7d5319
  commit-date: 2021-07-29
  host: x86_64-unknown-linux-gnu
  release: 1.56.0-nightly
  LLVM version: 12.0.1
  ```

**Comment by xFrednet** [comment]
Related to #7452 and #7198
