### ISSUE TITLE
Deprecate the term "blacklist" from lints

### ISSUE THREAD

**Issue by rpbeltran** [rust-lang/rust-clippy#7582]
Many companies and open source projects have been transitioning phrases like "blacklist/whitelist" into "blocklist/allowlist" or similar. There is also precedent for this within Rust itself as in these changes in Rust Bindgen: https://github.com/rust-lang/rust-bindgen/issues/1812.

With that in mind, the `blacklisted_names` lint seems like it could stand to be renamed to `blocklisted_name`. I'm not very familiar with the current strategy used for deprecation within this project, but it seems like introducing `blocklisted_name` as a synonym and modifying the warning messages to use this name would be a good approach for now that preserves backwards compatibility.

**Comment by mikerite** [comment]
We had a PR for this once that went stale -  #5896 . It has instructions etc.

**Comment by rpbeltran** [comment]
@mikerite thanks! That's super useful. I'll use that as a reference and try to get a new PR started soon.

**Comment by xFrednet** [comment]
This seems like a reasonable change to me and would go along with changes in other repos. Most team members already stated their support in #5896, it should therefore be safe to continue with this.

@rpbeltran Could you mention the Clippy team in the PR once you created it? You can just add an `cc: @rust-lang/clippy` at the end of the PR description. :upside_down_face:

**Comment by yerke** [comment]
I think this issue can be closed now that https://github.com/rust-lang/rust-clippy/pull/8974 is merged.

**Comment by xFrednet** [comment]
Agreed. @yerke thank you for pointing that out and everyone else that participated. :upside_down_face:
