### ISSUE TITLE
New lint: Manual assert

### ISSUE THREAD

**Issue by camsteffen** [rust-lang/rust-clippy#7645]
### What it does

Detects `if`-then-`panic!` that can be replaced with `assert!`

### Categories (optional)

- Kind: style

*What is the advantage of the recommended code over the original code*

It is simpler

### Drawbacks

None.

### Example

```rust
if !sad_people.is_empty() {
    panic!("there are sad people: {:?}", sad_people);
}
```

Could be written as:

```rust
assert!(sad_people.is_empty(), "there are sad people: {:?}", sad_people);
```

Lint name: `manual_assert` or `if_then_panic`

**Comment by matthiaskrgr** [comment]
What about its with multiple conditions?
If we have 10-5 conditions it does probably not help a lot, to use a super big assert...

**Comment by camsteffen** [comment]
We could lint only if the condition expression currently fits on one line.
