### ISSUE TITLE
unseparated_literal_suffix is very opinion oriented `0u8` versus `0_u8`

### ISSUE THREAD

**Issue by Stargateur** [rust-lang/rust-clippy#7658]
I just found [unseparated_literal_suffix](https://rust-lang.github.io/rust-clippy/master/index.html#unseparated_literal_suffix) with https://github.com/Geal/nom/pull/1387 and I believe this have never been talk about:

- This has been advice by [unnecessary_cast](https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_cast) and so I have a problem, `0 as u8` is very clear, clippy lint to just typed the `0` make sense to me, but then advice to add an `_` to make it more clear ? when the original code is very clear ?
- `0u8` is used in a LOT in rust literature without any problem I don't think it's more unclear than `0_u8`
- `0_u8` is longer to write
- rustfmt doesn't fmt `0u8` to `0_u8`
- there is no talk about this
- never see `0_u8` anywhere before

Thus I don't understand the lint (and the consequence to other lint) come a little from nowhere in my opinion.

**Comment by mikerite** [comment]
As far as I can tell, #703  is the original issue for this lint and #1145 is the pull request that implemented it. This lint is more than 5 years old. You've probably never seen it because it's allow by default.

So regarding complaints about "there is no talk about this".
Where did you expect this discussion to happen?
How did you expect to be included in it?

**Comment by Stargateur** [comment]
I said I never see `42_u8` before, not the lint itself even if I never see the lint too before. The fact it's 5 years old make it even worse meaning I never see someone apply it in 5 years.

> Where did you expect this discussion to happen?
How did you expect to be included in it?

here ?

**Comment by mikerite** [comment]
> I said I never see `42_u8` before, not the lint itself even if I never see the lint too before.

No. You said you'd never see the lint before as well.

> I _just_found_ [unseparated_literal_suffix](https://rust-lang.github.io/rust-clippy/master/index.html#unseparated_literal_suffix) ..

..

> > Where did you expect this discussion to happen?
> > How did you expect to be included in it?
> 
> here ?

Well then this is discussion you're looking for.

..

I don't have any more time for this issue. Good luck getting this lint changed/removed.

**Comment by Stargateur** [comment]
Well you kill my wish to make thing better, don't be surprise when people complain about clippy more and more.

**Comment by mikerite** [comment]
You should reopen this issue as there may be interest in changing it from someone on the team.

I wished you luck because I don't like this lint either. Maybe you thought I was being sarcastic.

**Comment by camsteffen** [comment]
I agree - unseparated_literal_suffix is founded on a style assertion that is not well supported outside of Clippy, and one could reasonably have the opposite opinion. Such lints should be in the restriction category.

I think the ability to separate the type with an underscore is an accidental consequence of a language feature intended for grouping like `1_000_000`, but I have no proof of this.

**Comment by dswij** [comment]
I think it would be better if `unseparated_literal_sufix` enforce a consistent style throughout a project, rather than only accepting a style. (and move it to style category, if that makes sense?)

Perhaps we can have a configuration for the lint that specifies said enforced style.

**Comment by camsteffen** [comment]
I think this is an issue where multiple acceptable opinions exist, and therefore it needs to be a restriction lint. We should support the opposing opinion through a config option or another lint. Related: https://github.com/rust-dev-tools/fmt-rfcs/issues/155.

**Comment by dswij** [comment]
Makes sense. I will try to have a look on this.

@rustbot claim
