### ISSUE TITLE
Improve explanation of not_unsafe_ptr_arg_deref

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust-clippy#7714]
I pointed out in https://github.com/rust-lang/rust-clippy/issues/7666#issuecomment-919006725 that the use of `allow(clippy::not_unsafe_ptr_arg_deref)` on crates.io is shockingly high.

Here is the list: https://dtolnay.github.io/noisy-clippy/not_unsafe_ptr_arg_deref.html

I spot checked some of these and pretty much every case is unsound.

- https://github.com/dtn7/bp7-rs/issues/2
- https://github.com/UnitedTraders/aeron-rs/issues/14
- https://github.com/UnitedTraders/aeron-rs/issues/16
- https://github.com/UnitedTraders/aeron-rs/issues/17
- https://github.com/drogue-iot/drogue-ffi-compat/issues/1
- https://github.com/jni-rs/jni-rs/issues/331
- https://github.com/wiomoc/mosquitto-jwt-auth/issues/11
- https://github.com/pact-foundation/pact-reference/issues/148
- https://github.com/EmbarkStudios/spirv-tools-rs/issues/27
- https://github.com/JoNil/tm-rs/issues/1
- https://github.com/zombodb/pgx/issues/196
- https://github.com/zombodb/pgx/issues/215

If people are not understanding what this lint is attempting to tell them, it seems like the lint isn't doing its job. We should look into whether the lint's documentation or the lint's diagnostic output can be improved in a way that better comes across to people. It may be worth looping in some of the maintainers of some of the crates above about what might have been helpful for them to understand the lint.

**Comment by tgross35** [comment]
Opened #10116 with stronger wording & context

Has uplifting this lint to rustc ever been considered? It seems important enough to be considered (I'm not sure what the criteria are for that)
