### ISSUE TITLE
Lint when not all trait methods are implemented

### ISSUE THREAD

**Issue by kangalio** [rust-lang/rust-clippy#7717]
### What it does

Detect when one or more trait methods were not implemented, i.e. delegated to their default implementation.

### Categories (optional)

- Kind: `clippy::restriction`

### Why

Useful for code that needs to exhaustively implement a trait for one reason or another.

For example, the serenity crate has an EventHandler trait with dozens of optional methods, and you usually implement the methods corresponding to the events you care about. However, in my project I need to listen for _all_ events to package them into an Event enum ([link](https://github.com/kangalioo/poise/blob/5b6678a112c6cd21ff2a60819a26ab9a4aaa0f33/src/event.rs)). The ability to do `#[warn(clippy::incomplete_trait_impl)]` (lint name up for debate) would be awesome to make sure I don't miss any events.

### Possible names

- incomplete_trait_impl
- unimplemented_trait_methods
- default_implementation_used
- default_trait_impl_used
- non_exhaustive_trait_impl

### Drawbacks

Seeing as it's an opt-in clippy::restriction lint, there are no drawbacks. People can activate the lint specifically for situations where it is useful.

### Example

```rust
struct Foo;
impl some_trait::SomeTrait for Foo {
    fn a() { /* ... */ }
    fn b() { /* ... */ }
    fn c() { /* ... */ }
    // Oops, forgot to implement d() which was added in some_trait 0.13.4
}
```

Could be written as:

```rust
struct Foo;
impl some_trait::SomeTrait for Foo {
    fn a() { /* ... */ }
    fn b() { /* ... */ }
    fn c() { /* ... */ }
    fn d() { /* ... */ }
}
```

**Comment by kpreid** [comment]
Another use for this lint would be for generic implementations, particularly ones on pointers, e.g.

```rust
impl<T: Trait> Trait for Box<T> {...}
impl<T: Trait> Trait for &T {...}
impl<T: Trait> Trait for &mut T {...}
```

where you want to make sure that the generic implementations forward *all* methods to the underlying implementation. A missing method could be a semantic error, but it could also be a silent but severe performance cost, when the optional/provided methods are able to be implemented more efficiently (as in `Iterator`) but the generic implementation fails to forward to the implemented method.

The crate defining the trait can use this lint at `#[deny]` level, and other crates can use the lint at `#[warn]` level (for compatibility in case the defining crate adds a method). The documentation should specifically note not to deny it in the latter case.

**Comment by Alexendoo** [comment]
Added as https://rust-lang.github.io/rust-clippy/master/index.html#missing_trait_methods
