### ISSUE TITLE
Lint for using .copied

### ISSUE THREAD

**Issue by Milo123459** [rust-lang/rust-clippy#7751]
### What it does

*What does this lint do?*

If you do `<iter>.map(|x| *x)` or anything like that, it'll suggest using `.copied()`

### Categories (optional)

- Kind: *See <https://github.com/rust-lang/rust-clippy/blob/master/README.md#clippy> for list of lint kinds*

*What is the advantage of the recommended code over the original code*

`clippy::style`

### Drawbacks

None.

### Example

```rust
let vec = vec![1, 2, 3, 4, 5].iter().collect::<Vec<i64>>();

let vec2 = vec.iter().map(|x| *x).collect::<Vec<i64>>();
```

Could be written as:

```rust
let vec = vec![1, 2, 3, 4, 5].iter().collect::<Vec<i64>>();

let vec2 = vec.iter().copied().collect::<Vec<i64>>();
```

**Comment by camsteffen** [comment]
This is already linted by `map_clone`.
