### ISSUE TITLE
how to create project specific lints

### ISSUE THREAD

**Issue by avnerbarr** [rust-lang/rust-clippy#7754]
I'd like to create some lints for my team which are very specific to us. For instance I'd like all thread names to be styled in a specific manner and all log statements to start with a specific usage code.

How can I create these types of "custom" lints?

Thanks

**Comment by camsteffen** [comment]
May want to check out [dylint](https://github.com/trailofbits/dylint).

**Comment by giraffate** [comment]
I'm closing this because it's duplicate of https://github.com/rust-lang/rust-clippy/issues/6872.
