### ISSUE TITLE
New Lint: disallowed_macro

### ISSUE THREAD

**Issue by JamesHinshelwood** [rust-lang/rust-clippy#7790]
### What it does

Disallows certain macros, as defined in clippy.toml.
Equivalent to the `disallowed_method` lint, but for macros instead of methods.

### Drawbacks

It may be cleaner to add support for macros to the existing `disallowed_method` lint.

### Example

```toml
# clippy.toml

disallowed-macros = ["eyre::anyhow"]
```

```rust
...
let f = eyre::anyhow!("foobar");
...
```

results in a lint.

**Comment by aDotInTheVoid** [comment]
I can't figure out how to do this. With an `EarlyLintPass`  the macro's have been resolved, but `LateLintPass` is after theyve been expanded, so I'm not sure if this is possible. 

LMK if I've missed anything, and anyone wants to try this you might find [my attempt](https://github.com/aDotInTheVoid/rust-clippy/tree/disallowed_macro) usefull

@rustbot unclaim

**Comment by JamesHinshelwood** [comment]
Hi, apologies. Life has got in the way and I don't think I'll be able to work on this soon. Will unclaim in case someone else wants to.

@rustbot release-assignment
