### ISSUE TITLE
lint: needless_slice_from_ref

### ISSUE THREAD

**Issue by TennyZhuang** [rust-lang/rust-clippy#7817]
### What it does

The builtin function [`slice::from_ref`](https://doc.rust-lang.org/std/slice/fn.from_ref.html) may be applied on a reference unnecessarily.

### Categories (optional)

- Kind: *See <https://github.com/rust-lang/rust-clippy/blob/master/README.md#clippy> for list of lint kinds*

clippy::style

*What is the advantage of the recommended code over the original code*

Readability

### Drawbacks

None.

### Example

```rust
slice::from_ref(&x)
```

Could be written as:

```rust
&[x]
```

**Comment by Jarcho** [comment]
These aren't equivalent expressions. `&[x]` moves `x` into an array, then takes a reference to that temporary array. `slice::from_ref(&x)` makes a slice reference with the same lifetime as `x`.

Even for `Copy` types this is a problem in the following example:
```rust
let x = 0i32;
let y = core::slice::from_ref(&x);
println!("{}", y[0]);
```
Switching to using `&[x]` results in `error[E0716]: temporary value dropped while borrowed` as the temporary array is dropped at the end of the let binding.

There are cases where the lifetime issue doesn't matter, the different result types don't matter, and the value is a small `Copy` type, but detecting that is going to be hard.

**Comment by TennyZhuang** [comment]
Got it, so they are not same
