### ISSUE TITLE
Replace `{assert, debug_assert}` using `==` or `!=` by the `_eq` or `_ne` variants

### ISSUE THREAD

**Issue by r00ster91** [rust-lang/rust-clippy#7837]
### What it does

It checks for asserts like `assert!(1 == 1);` and suggests to replace it with `assert_eq!(1, 1);`.
As far as I know, this is more idiomatic.

### Categories (optional)

- Kind: most likely `clippy::style` or maybe `clippy::complexity`.

The advantage is idiomacy and consistency/consistent style.
It can also improve readability and the `_eq`/`_ne` variants make it much easier to search for specific kind of asserts (no regex for example needed).

### Drawbacks

None.

### Example

```rust
assert!(1 == 1);
assert!(5 != 10);
debug_assert!(1 == 1);
debug_assert!(5 != 10);
```

Could be written as:

```rust
assert_eq!(1, 1);
assert_ne!(5, 10);
debug_assert_eq!(1, 1);
debug_assert_ne!(5, 10);
```

**Comment by alex-700** [comment]
@r00ster91 there is a long story about [RFC-2011](https://github.com/rust-lang/rfcs/pull/2011). From the `clippy` side you can see #641 and #2090. IMHO, nothing happened to change the decision frpm #2090.
