### ISSUE TITLE
Clippy breaks when we change anything about the std macros

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust-clippy#7843]
Clippy recognizes macros like `panic!()` and `format_args!()` by its exact expansion, such as here:

https://github.com/rust-lang/rust-clippy/blob/389a74b31aabca4aac3289763eeb2eccedd1b988/clippy_utils/src/higher.rs#L719-L736

And here:

https://github.com/rust-lang/rust-clippy/blob/389a74b31aabca4aac3289763eeb2eccedd1b988/clippy_utils/src/higher.rs#L505-L675

This is very fragile, as it needs to be changed whenever we improve/change their implementations in std/core. For example: https://github.com/rust-lang/rust-clippy/issues/7723 removes a `&`, after which clippy doesn't Recognize the arguments to panic anymore.

Worse, since Clippy is now not a submodule but a subtree in `rust-lang/rust`, it means that we can no longer make any changes at all to those macros without it getting blocked in CI on clippy. Clippy's dependence on all these implementations details effectively blocks development on `panic`, `assert*`, and `format_args`/`fmt::Arguments` in `rust-lang/rust`.

So as a maintainer of `std`, I'd like to ask again: please do not depend on these implementation details. We change this stuff. I'm expecting some big changes to fmt::Arguments and the assert macros in the future, and the panic macros we've also repeatedly changed tiny details of over the past year, and and they will change again.

See also:

- https://github.com/rust-lang/rust/pull/88860
- https://github.com/rust-lang/rust-clippy/issues/7723
- https://github.com/rust-lang/rust/pull/78343#issuecomment-719981591
- https://github.com/rust-lang/rust/pull/79145
- https://github.com/rust-lang/rust/pull/80851#issuecomment-767436784
- https://github.com/rust-lang/rust/pull/79100
- https://github.com/rust-lang/rust/issues/76495

---

I don't know what the best solution is, but making Clippy depend heavily on every detail of our macros is just going to cause a big headache down the road for someone. We should probably work on some way in std or rustc to make it easy to for clippy to have the information without having to do these hacks to revert a macro expansion.

Maybe we can have an empty and hidden `#[inline(always)] fn macro_hint<T>(hint: &str, _: T) {}` somewhere that we can call in our macros (e.g. `macro_hint("hey clippy, this is an assert_eq", (left, right))`). Then Clippy could recognize that instead.

**Comment by camsteffen** [comment]
I think this can largely be fixed in Clippy by using a Visitor to scan the expanded HIR of a macro and collect all expressions that are not from expansion - these are the inputs. The format string details are more tricky, but we could also use a Visitor to skip to the interesting parts and not rely on the *exact* expansion. Also we have access to the DefId of the macro that was called so we should be using diagnostic items to detect when entering a given macro.
