### ISSUE TITLE
Lint doc comments on private items 

### ISSUE THREAD

**Issue by llogiq** [rust-lang/rust-clippy#786]
Since we recently started targeting comments, recently someone asked why their doc comments don't show up for a private function.

We could lint and suggest either making the function public (if intended) or make the comment a normal line comment.

I'm not sure if this should `warn`, though.

**Comment by mcarton** [comment]
> I'm not sure if this should `warn`, though.

Nah. I like to use [that trick](https://github.com/rust-lang/cargo/issues/1520#issuecomment-135360461) to generate private doc. I think this is something `cargo doc` should support.

**Comment by llogiq** [comment]
OK, but that's something a well-seasoned dev would attempt, and clippy also tries to help newbies (and forgetting `pub` is at least as likely than documenting private functions just because, then wondering why the docs fail to show).

**Comment by shepmaster** [comment]
Conversely, I'd like a lint to warn when a private function is _not_ documented.

Since rustdoc's behavior around documenting private items has changed greatly (e.g. binaries include them by default, you can use `--document-private-items`) perhaps this issue should be closed or repurposed.

**Comment by flip1995** [comment]
@shepmaster this lint already exists: [`missing_docs_in_private_items`](https://rust-lang.github.io/rust-clippy/master/index.html#missing_docs_in_private_items), but has to be enabled explicitely. (Also it will lint on all private items, not only functions.

**Comment by shepmaster** [comment]
> this lint already exists

Ah, thanks! I only looked for an [official rustdoc lint](https://doc.rust-lang.org/rustdoc/lints.html).

**Comment by flip1995** [comment]
See also #5736

**Comment by BatmanAoD** [comment]
I agree this should be closed.
