### ISSUE TITLE
New lint: Suggest stream_position for `self.seek(SeekFrom::Current(0))`

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rust-clippy#7886]
### What it does

Suggests to use `stream_position()` over `seek(SeekFrom::Current(0))`.

### Categories (optional)

- Kind: clippy::style

Since Rust 1.51, the Seek trait has a stream_position method.
Using it makes the intent more clear over `seek`.

### Drawbacks

None.

### Example

```rust
use std::fs::File;
use std::io::{self, Write, Seek, SeekFrom};

fn main() -> io::Result<()> {
    let mut f = File::create("foo.txt")?;
    f.write_all(b"Hi!")?;
    eprintln!("Written {} bytes.", f.seek(SeekFrom::Current(0))?);
    Ok(())
}
```

Could be written as:

```rust
use std::fs::File;
use std::io::{self, Write, Seek};

fn main() -> io::Result<()> {
    let mut f = File::create("foo.txt")?;
    f.write_all(b"Hi!")?;
    eprintln!("Written {} bytes.", f.stream_position()?);
    Ok(())
}
```

**Comment by koka831** [comment]
Hi, @ahmedkrmn. Do you still work on this? or may I try to have it?

**Comment by maxcnunes** [comment]
https://github.com/rust-lang/rust-clippy/issues/7886 mentions it addressed this request. If that is correct, could someone close this ticket please?
