### ISSUE TITLE
Enhance missing backtick detection for global identifiers `doc_markdown`

### ISSUE THREAD

**Issue by xFrednet** [rust-lang/rust-clippy#7914]
The lint [`clippy::doc_markdown`](https://rust-lang.github.io/rust-clippy/master/index.html#doc_markdown) can detect missing backticks around identifiers. Global identifiers like `::a::global::item` are only detected after the first double colon `::`. It would be good if the suggestion also included the initial `::` for a global identifier.

**Test File**

https://github.com/rust-lang/rust-clippy/blob/f37dc2521b8b8cdb27dd36e364b8e838a5aa51b6/tests/ui/doc/doc.rs#L12

**Lint output**

https://github.com/rust-lang/rust-clippy/blob/f37dc2521b8b8cdb27dd36e364b8e838a5aa51b6/tests/ui/doc/doc.stderr#L21-L25

It should instead span over the complete `::a::global:path` and suggest `` `::a::global:path` ``

---

@rustbot label +C-enhancement

**Comment by samueltardieu** [comment]
Looks interesting.

@rustbot claim

**Comment by xFrednet** [comment]
A heads-up that #7904 is also editing something on the lint. You might get some merge conflicts. Otherwise, have fun :+1:

**Comment by samueltardieu** [comment]
Duly noted. I'll see what happens next, I'm about to open a PR.
