### ISSUE TITLE
`shadow_same` is just plain wrong in an async context

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/rust-clippy#7915]
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=bb8b58e91b2a00d51cd67875ebce1da6

**Code**

```rust
#![deny(clippy::shadow_same)]

pub async fn foo(_a: i32) {
}
```

**Output**

```
error: `_a` is shadowed by itself in `_a
```

**Comment by c410-f3r** [comment]
Is anyone willing to work on this issue? It shouldn't be too difficult to solve

**Comment by surechen** [comment]
I am very happy to follow up on this issue.
@rustbot claim

**Comment by c410-f3r** [comment]
Thank you!
