### ISSUE TITLE
Type name inside its impl-block

### ISSUE THREAD

**Issue by totikom** [rust-lang/rust-clippy#7932]
### What it does
All references to the type inside its `impl`-block should be changed to `Self`.

### Categories (optional)

- Kind: `clippy::style`

*What is the advantage of the recommended code over the original code*

- Remove the need to duplicate typename and (possibly) improve code readability

### Drawbacks

None.

### Example

```rust
struct MyType();

impl MyType {
    pub fn foo() -> MyType {
        \\...
    }
    fn bar() {
        MyType::foo();
    }
}
```

Could be written as:
```rust
struct MyType();

impl MyType {
    pub fn foo() -> Self {
        \\...
    }
    fn bar() {
        Self::foo();
    }
}
```

**Comment by giraffate** [comment]
FYI we already have the `use_self` lint: https://rust-lang.github.io/rust-clippy/master/index.html#use_self

**Comment by totikom** [comment]
Oh, yes...
`use_self` is in `clippy::nursery`, that's why I haven't found it.
