### ISSUE TITLE
Update tests/ui/match_wild_err_arm.rs to edition 2021

### ISSUE THREAD

**Issue by llogiq** [rust-lang/rust-clippy#7942]
This is one of the remaining tests still on edition 2015. We should either replace it outright (but risk that changes break older-edition code) or add another test file with the current edition. A good start is likely to copy the file, remove the `// edition: 2015` line and go from there.

@rustbot label +good-first-issue +E-needs-test

**Comment by phansch** [comment]
@llogiq The file doesn't have the `// edition: 2015` anymore. I suppose this can be closed then?

It only has annotations for 2018 and 2021 editions:
https://github.com/rust-lang/rust-clippy/blob/46687f1313454882df10609e12d47f997501962d/tests/ui/match_wild_err_arm.rs#L1-L3

**Comment by llogiq** [comment]
Nice!
