### ISSUE TITLE
ICE on running `cargo clippy`

### ISSUE THREAD

**Issue by pro465** [rust-lang/rust-clippy#7952]
### Code

```rust
fn main() {
    assert_eq!(0, 0);
}
```

### Meta

**Rust version (`rustc -Vv`):**
```
rustc 1.56.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: armv7-linux-androideabi
release: 1.56.0
LLVM version: 13.0.0
```

### Error output

```
thread 'rustc' panicked at 'index out of bounds: the len is 7 but the index is 3873421896', compiler/rustc_mir_build/src/build/cfg.rs:13:14
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.56

query stack during panic:
#0 [mir_built] building MIR for `main`
#1 [unsafety_check_result] unsafety-checking `main`
#2 [mir_const] processing MIR for `main`
#3 [mir_promoted] processing `main`
#4 [mir_borrowck] borrow-checking `main`
#5 [analysis] running analysis passes on this crate
end of query stack
```

<details><summary>Backtrace</summary>
  <p>
  
  ```
  <no backtrace>
  ```
  
  </p>
</details>

**Comment by giraffate** [comment]
Thanks for the report!

I can't reproduce that. Can you provide the backtrace with `RUST_BACKTRACE=full`, and try that in nightly?

**Comment by llogiq** [comment]
Interestingly the original report was on `armv7-linux-androideabi`, so someone is trying clippy on their tablet or mobile phone.

**Comment by pro465** [comment]
> Thanks for the report!
> 
> I can't reproduce that. Can you provide the backtrace with `RUST_BACKTRACE=full`, and try that in nightly?

<details>
<summary>Full backtrace</summary>

```
thread 'rustc' panicked at 'index out of bounds: the len is 7 but the index is 3884956232', compiler/rustc_mir_build/src/build/cfg.rs:13:14
stack backtrace:
   0: 0xe8723626 - <unknown>
   1: 0xe8759c28 - <unknown>
   2: 0xe86fc3f8 - <unknown>
   3: 0xe872568c - <unknown>
   4: 0xe8725318 - <unknown>
   5: 0xad4f0d2c - <unknown>
   6: 0xe8725dfe - <unknown>
   7: 0xe8725a96 - <unknown>
   8: 0xe87236e2 - <unknown>
   9: 0xe8725a34 - <unknown>
  10: 0xe8767146 - <unknown>
  11: 0xe8767120 - <unknown>
  12: 0xeda0ca72 - <unknown>
  13: 0xeda147ca - <unknown>
  14: 0xeda21d00 - <unknown>
  15: 0xeda13188 - <unknown>
  16: 0xeda0c6b6 - <unknown>
  17: 0xeda21fe0 - <unknown>
  18: 0xeda13794 - <unknown>
  19: 0xeda21d00 - <unknown>
  20: 0xeda13188 - <unknown>
  21: 0xeda21d00 - <unknown>
  22: 0xeda13188 - <unknown>
  23: 0xeda21b44 - <unknown>
  24: 0xed9c5e70 - <unknown>
  25: 0xeda1441a - <unknown>
  26: 0xeda21d00 - <unknown>
  27: 0xeda13188 - <unknown>
  28: 0xeda0c6b6 - <unknown>
  29: 0xeda21fe0 - <unknown>
  30: 0xeda13794 - <unknown>
  31: 0xeda11e34 - <unknown>
  32: 0xeda15a9a - <unknown>
  33: 0xeda15e04 - <unknown>
  34: 0xeda0c0c0 - <unknown>
  35: 0xeda21fe0 - <unknown>
  36: 0xeda13794 - <unknown>
  37: 0xeda21d00 - <unknown>
  38: 0xeda13188 - <unknown>
  39: 0xeda21d00 - <unknown>
  40: 0xeda13188 - <unknown>
  41: 0xeda0a7b8 - <unknown>
  42: 0xed9ca9e0 - <unknown>
  43: 0xeda093ba - <unknown>
  44: 0xedfd3a96 - <unknown>
  45: 0xedecb438 - <unknown>
  46: 0xee081448 - <unknown>
  47: 0xee2038b0 - <unknown>
  48: 0xedb52676 - <unknown>
  49: 0xedab51f4 - <unknown>
  50: 0xedfc5728 - <unknown>
  51: 0xedebd6de - <unknown>
  52: 0xee0e136c - <unknown>
  53: 0xee08b974 - <unknown>
  54: 0xee2051b0 - <unknown>
  55: 0xedd29d8a - <unknown>
  56: 0xedfd3a96 - <unknown>
  57: 0xedecb438 - <unknown>
  58: 0xee081448 - <unknown>
  59: 0xee203938 - <unknown>
  60: 0xedd2c434 - <unknown>
  61: 0xedfc9dc4 - <unknown>
  62: 0xeded08ee - <unknown>
  63: 0xee037f12 - <unknown>
  64: 0xee203d24 - <unknown>
  65: 0xedc52976 - <unknown>
  66: 0xedbc4178 - <unknown>
  67: 0xedfcb4f8 - <unknown>
  68: 0xeded4d2a - <unknown>
  69: 0xee0e200c - <unknown>
  70: 0xee013578 - <unknown>
  71: 0xee205ed4 - <unknown>
  72: 0xed5019ce - <unknown>
  73: 0xedfc76cc - <unknown>
  74: 0xedec38b0 - <unknown>
  75: 0xee1bfe3a - <unknown>
  76: 0xeeae5a16 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.56

query stack during panic:
#0 [mir_built] building MIR for `main`
#1 [unsafety_check_result] unsafety-checking `main`
#2 [mir_const] processing MIR for `main`
#3 [mir_promoted] processing `main`
#4 [mir_borrowck] borrow-checking `main`
#5 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `nn`

```

</details>

**Comment by pro465** [comment]
@giraffate it works both in `cargo 1.55.0` and `cargo 1.58.0-nightly` only in `1.56.0` does it result in an ICE

**Comment by giraffate** [comment]
Oh, I'm not sure if it's because it's running on `armv7-linux-androideabi`, but the backtrace isn't showing anything.

Anyway, thanks for the detail!

**Comment by pro465** [comment]
> Interestingly the original report was on `armv7-linux-androideabi`, so someone is trying clippy on their tablet or mobile phone.

didnt expect to see a detective here lol! and you are right about the guess. The truth is im still in high school and my mom has told me she will get me a laptop once i have passed 10th, as laptops are expensive and she will not let me waste money uselessly

**Comment by SoCreat** [comment]
so pass the 10th please，I came from china Zhihu

**Comment by llogiq** [comment]
@pro465 I have Termux installed on my mobile phone. While that will likely suffice to repro the issue, I'm unsure if I can learn more about it. Let's assume for now that the problem is indeed in some lint; perhaps we can at least bisect in which one? Start with -W `<`half of the perf lints`>`, and if it's in there, we can halve that, otherwise take half of the lints not checked until we have one or more lints that induce the problem. The `len is 7` also seems fishy. And the index doesn't look like a simple underflow to me.

**Comment by pro465** [comment]
@llogiq it seems the problem is with clippy itself, not some specific lint...

**Comment by flip1995** [comment]
I can't reproduce this on playground (rustc version 1.56.1). So maybe  it is really a problem with `armv7-linux-androideabi`. Has this target a different `usize` maybe, so that some cast in Clippy goes wrong?

**Comment by pro465** [comment]
@flip1995 running ```rust
fn main() {
    println!("{}", usize::BITS);
}
```

outputs `32`, but AFAIK clippy should not only work in 64-bit architectures...

**Comment by flip1995** [comment]
> but AFAIK clippy should not only work in 64-bit architectures...

We even test clippy on 32-bit linux, so it should work on 32-bit archs. But I could imagine that it may have something to do with this.

**Comment by pro465** [comment]
@flip1995 maybe `the len is 7` is the code reduced to 7 MIR tokens/instrs/(whatever that is called)? i think somebody must investigate what the mir output of the code is, as i think that is where the issue lies

**Comment by llogiq** [comment]
It didn't appear with 1.53, which I still had on my mobile phone. I'm currently upgrading to 1.56 to see if I can reproduce it.

**Comment by llogiq** [comment]
Trying to emit MIR brought me a bit more info:

```
~/ice $ RUSTC_OPTIONS=-C emit=mir cargo build
   Compiling ice v0.1.0 (/data/data/com.termux/files/home/ice)
    Finished dev [unoptimized + debuginfo] target(s) in 1.52s
~/ice $ cargo clippy --verbose
    Checking ice v0.1.0 (/data/data/com.termux/files/home/ice)
     Running `/data/data/com.termux/files/usr/bin/clippy-driver rustc --crate-name ice --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,metadata -C embed-bitcode=no -C debuginfo=2 -C metadata=b92c4fd6098fae26 -C extra-filename=-b92c4fd6098fae26 --out-dir /data/data/com.termux/files/home/ice/target/debug/deps -C incremental=/data/data/com.termux/files/home/ice/target/debug/incremental -L dependency=/data/data/com.termux/files/home/ice/target/debug/deps`
error: internal compiler error: compiler/rustc_mir_build/src/build/scope.rs:1397:17: cannot unwind from goto -> bb7
 --> src/main.rs:3:5
  |
3 |     assert_eq!(v.len(), 0);
  |     ^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error: internal compiler error originates in the macro `assert_eq` (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'Box<dyn Any>', /home/builder/.termux-build/rust/src/compiler/rustc_errors/src/lib.rs:1093:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.56

query stack during panic:
#0 [mir_built] building MIR for `main`
#1 [unsafety_check_result] unsafety-checking `main`
end of query stack
error: could not compile `ice`

Caused by:
  process didn't exit successfully: `/data/data/com.termux/files/usr/bin/clippy-driver rustc --crate-name ice --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,metadata -C embed-bitcode=no -C debuginfo=2 -C metadata=b92c4fd6098fae26 -C extra-filename=-b92c4fd6098fae26 --out-dir /data/data/com.termux/files/home/ice/target/debug/deps -C incremental=/data/data/com.termux/files/home/ice/target/debug/incremental -L dependency=/data/data/com.termux/files/home/ice/target/debug/deps` (exit status: 101)
```

**Comment by pro465** [comment]
@flip1995 wait, why does clippy panics with `Box<dyn Any>` in your env but a `the len is x but the index is y` in mine? the case is getting more mysterious...

**Comment by pro465** [comment]
@flip1995 oops sorry didn't mean to mention you,  i meant @llogiq, editing my previous comment...

**Comment by llogiq** [comment]
Could be differences in the release?

```
$ rustc -vV
rustc 1.56.1
binary: rustc
commit-hash: unknown
commit-date: unknown
host: aarch64-linux-android
release: 1.56.1
LLVM version: 13.0.0
```

**Comment by pro465** [comment]
@llogiq i just noticed two things:

1. `the len is x`- `x` changed from 7 to 6 when i changed the code from 
```rust
fn main() {
    let v: [f32; 0] = [];
    assert_eq!(v.len(), 0);
}
```
to
```rust
fn main() {
     assert_eq!(0, 0);
}
```
meaning the len is something related to the mir of the code;
2. `the index is y` - the value of `y` seems to be garbage, changing with every run

**Comment by s-cerevisiae** [comment]
> Trying to emit MIR brought me nothing, but `--verbose` got a bit more info:
> 
> ```
> ~/ice $ RUSTC_OPTIONS=-C emit=mir cargo build
>    Compiling ice v0.1.0 (/data/data/com.termux/files/home/ice)
>     Finished dev [unoptimized + debuginfo] target(s) in 1.52s
> ~/ice $ cargo clippy --verbose
>     Checking ice v0.1.0 (/data/data/com.termux/files/home/ice)
>      Running `/data/data/com.termux/files/usr/bin/clippy-driver rustc --crate-name ice --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,metadata -C embed-bitcode=no -C debuginfo=2 -C metadata=b92c4fd6098fae26 -C extra-filename=-b92c4fd6098fae26 --out-dir /data/data/com.termux/files/home/ice/target/debug/deps -C incremental=/data/data/com.termux/files/home/ice/target/debug/incremental -L dependency=/data/data/com.termux/files/home/ice/target/debug/deps`
> error: internal compiler error: compiler/rustc_mir_build/src/build/scope.rs:1397:17: cannot unwind from goto -> bb7
>  --> src/main.rs:3:5
>   |
> 3 |     assert_eq!(v.len(), 0);
>   |     ^^^^^^^^^^^^^^^^^^^^^^^
>   |
>   = note: this error: internal compiler error originates in the macro `assert_eq` (in Nightly builds, run with -Z macro-backtrace for more info)
> 
> thread 'rustc' panicked at 'Box<dyn Any>', /home/builder/.termux-build/rust/src/compiler/rustc_errors/src/lib.rs:1093:9
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> note: the compiler unexpectedly panicked. this is a bug.
> 
> note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new
> 
> note: Clippy version: clippy 0.1.56
> 
> query stack during panic:
> #0 [mir_built] building MIR for `main`
> #1 [unsafety_check_result] unsafety-checking `main`
> end of query stack
> error: could not compile `ice`
> 
> Caused by:
>   process didn't exit successfully: `/data/data/com.termux/files/usr/bin/clippy-driver rustc --crate-name ice --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,metadata -C embed-bitcode=no -C debuginfo=2 -C metadata=b92c4fd6098fae26 -C extra-filename=-b92c4fd6098fae26 --out-dir /data/data/com.termux/files/home/ice/target/debug/deps -C incremental=/data/data/com.termux/files/home/ice/target/debug/incremental -L dependency=/data/data/com.termux/files/home/ice/target/debug/deps` (exit status: 101)
> ```

I'm running into the same error on Termux with rustc 1.56.1 and clippy 0.1.56.

**Comment by AntonioLucibello** [comment]
Can confirm this bug also occurs in version 1.57 and for aarch64 architecture.
I've pasted the error messages of a few of my projects, hopefully this can be of use: https://github.com/termux/termux-packages/issues/7870#issue-1037655245

**Comment by thunder-coding** [comment]
> @giraffate it works both in `cargo 1.55.0` and `cargo 1.58.0-nightly` only in `1.56.0` does it result in an ICE

Yeah, I can't reproduce this issue on rust 1.58.1 built from termux/termux-packages#8812. This can now be closed.

Thanks for such an awesome language, I'd love to explore the language in future!

**Comment by pro465** [comment]
closing this since, as mentioned by @thunder-coding, is fixed in the latest update
