### ISSUE TITLE
Improve filtering options for Clippy's lint list

### ISSUE THREAD

**Issue by xFrednet** [rust-lang/rust-clippy#7958]
[Clippy's lint list](https://rust-lang.github.io/rust-clippy/master/index.html) currently allows filtering by lint and group. It would be helpful to add more filters for the applicability and version values which are available. The filter design that is currently used is not set in stone, feel free to experiment a bit and make some design suggestions.

The HTML document of the page can be found under [`util/gh-pages/index.html`](https://github.com/rust-lang/rust-clippy/blob/master/util/gh-pages/index.html). `cargo dev serve` can be used to test the changes locally. The current lint data representation can be found in the `gh-pages` branch [here](https://github.com/rust-lang/rust-clippy/blob/gh-pages/master/lints.json)

Main tracking issue #7172

**Comment by flip1995** [comment]
Possible improvements for the current filters:

- Group filter:
    - Make drop-down menu 
    - Add options to select all / none
- Lint levels:
    - Possibly the same as for groups?
- Search
    - Fuzzy search (for lint names)

Possible new lint groups:

- Version
    - greater
    - equal
    - less
- Applicability
    - Filter by applicability group
    - Same interface as the one suggested for groups and levels

**Comment by xFrednet** [comment]
A *search only in lint name* function would also be nice.

**Comment by repi** [comment]
Would be great to be able to esp. filter on the version the lint was introduced, use that quite frequently to test lints in newer Rust versions.

**Comment by Serial-ATA** [comment]
I'll give the version filter a shot

**Comment by SpencerAWill** [comment]
I'll take a look at the applicability filter
