### ISSUE TITLE
Add more information to the error in `needless_question_mark`

### ISSUE THREAD

**Issue by azzamsa** [rust-lang/rust-clippy#8016]
Hi.

I got the `needless_question_mark` error in the code below:

```rust
fn get_env(name: &str) -> anyhow::Result<String> {
    Ok(env::var(&name).context(format!("`{}` is not set", &name))?)
}
```

```rust
48 |     Ok(env::var(&name).context(format!("`{}` is not set", &name))?)
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `env::var(&name).context(format!("`{}` is not set", &name))`
   |
   = note: `#[warn(clippy::needless_question_mark)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master
```

Removing the question mark indeed breaks the program:

```rust
error[E0308]: mismatched types
  --> crates/server/src/lib.rs:48:8
   |
48 |     Ok(env::var(&name).context(format!("`{}` is not set", &name)))
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `std::string::String`, found enum `Result`
   |
   = note: expected struct `std::string::String`
                found enum `Result<std::string::String, anyhow::Error>`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `server` due to previous error
```

I am stuck here, so I asked in [Discord forum](https://discord.com/channels/273534239310479360/273541522815713281/912196533078863942), and they suggest to remove the `Ok` too.
With only the error message above, "remove the question mark" only, I would not solve it my self.
It should says "remove the question mark and the Ok".

In such case, is the error message can be improved?

```rust
rustc 1.56.0 (09c42c458 2021-10-18)
clippy 0.1.56 (09c42c4 2021-10-18)
x86_64-unknown-linux-gnu
```

@ rustbot label +C-enhancement

**Comment by dswij** [comment]
I see nothing wrong with the suggestion, but I do think that the displayed message can be improved :slightly_smiling_face: 

@rustbot claim

**Comment by xFrednet** [comment]
Oh, yes I misunderstood the description a bit, then this is only an enhancement. Thanks for pointing that out! :upside_down_face:
