### ISSUE TITLE
Lint suggesting to replace `str::bytes().count()` with `str::len()`

### ISSUE THREAD

**Issue by r00ster91** [rust-lang/rust-clippy#8083]
### What it does

It checks for `str::bytes().count()` and suggests replacing it with `str::len()` that does the same but shorter and possibly more performant.

Extra: can something like this be done for https://doc.rust-lang.org/std/io/trait.Read.html#method.bytes too?

### Lint Name

bytes_count_to_len

### Category

complexity

### Advantage

- Might be more performant
- Shorter
- Possibly easier to read

### Example

```rust
fn main() {
    "hello".bytes().count();
}
```

Could be written as:

```rust
fn main() {
    "hello".len();
}
```

**Comment by sivchari** [comment]
Can I try it ?

**Comment by nindalf** [comment]
@sivchari  are you still working on this?

**Comment by sivchari** [comment]
I don't have no progress, so I unassign me.
@rustbot release-assignment

**Comment by c-rus** [comment]
Hello, I was wondering if I could work on this issue?
