### ISSUE TITLE
[ER] Useless str -> String allocation

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust-clippy#8088]
### What it does

Inspired also by:
https://github.com/rust-lang/rust/pull/91626

In this code:

```rust
use std::collections::HashSet;
fn main() {
    let mut s = HashSet::from(["a".to_string(), "b".to_string()]);
    println!("{}", s.remove(&"b".to_string()));
}
```

I'd like Clippy to suggest to avoid the string allocation:

```rust
s.remove("b")
```

Similar suggestions are useful to HashMap, etc.

### Lint Name

useless_string_allocation

### Category

pedantic

### Example

```rust
<code>
```

Could be written as:

```rust
<code>
```

**Comment by bugadani** [comment]
Maybe this could be generalized to useless_allocation as well, for the `Vec<->slice` or similar cases?
