### ISSUE TITLE
Bug: Clippy Crash

### ISSUE THREAD

**Issue by ens-scmeeu** [rust-lang/rust-clippy#8095]
NOTE: Apologies that this is likely going to be a very unhelpful bug report. The codebase is a company proprietary one so I can't share much (I can probably share small snippets if helpful). Let me know what else you need and I will see what I'm allowed to share. Thanks for making these great tools.

Clippy crashed when used in conjunction with cargo watch (`cargo watch -x clippy`). It was working fine, I made a code edit, saved, and then it crashed. The file that triggered the crash per the below report is not the one I was working on when it occurred (it does use the module I was working on). Also, when I did `cargo clean` and ran clippy again, no crash occurred, so the bug seems to be in relation to incremental scanning possibly. My code actually compiled successfully, so it wasn't due to an error in my code either (Also, FYI before I did `cargo clean` I did `cargo build` and `cargo check` and both worked fine).

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/compiler/rustc_hir/src/definitions.rs:452:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.57 (f1edd04 2021-11-29)

query stack during panic:
#0 [unsafety_check_result] unsafety-checking `commit::<impl at src/commit/mod.rs:191:1: 467:2>::process_resources::{closure#0}`
#1 [unsafety_check_result] unsafety-checking `commit::<impl at src/commit/mod.rs:191:1: 467:2>::process_resources`
end of query stack
error: could not compile `netapi_v2`
[Finished running. Exit status: 101]
```

**Comment by giraffate** [comment]
Looks like the same issue as https://github.com/rust-lang/rust-clippy/issues/7927.

**Comment by giraffate** [comment]
It seems to be rustc issue, so I'm closing this.
