### ISSUE TITLE
[Question] How do deal with `unseparated_literal_suffix` and `separated_literal_suffix` when using `-D clippy::restriction`?

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/rust-clippy#8101]
### Description

`unseparated_literal_suffix` and `separated_literal_suffix` are both market as `restriction` but they conflict with each other when using `-D clippy::restriction`.

```rust
   |
34 |   let a = 0u8;
   |           ^^^ help: add an underscore: `0_u8`
   |
   = note: `-D clippy::unseparated-literal-suffix` implied by `-D clippy::restriction`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unseparated_literal_suffix
```

```rust
   |
34 |   let a = 0_u8;
   |           ^^^^ help: remove the underscore: `0u8`
   |
   = note: `-D clippy::separated-literal-suffix` implied by `-D clippy::restriction`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#separated_literal_suffix
```

I think it is clear that such conflict is pretty much wrong

**Comment by giraffate** [comment]
It's recommended that you only enable what you need in the `restriction` category. FYI we have the [`blanket_clippy_restriction_lints`](https://rust-lang.github.io/rust-clippy/master/index.html#blanket_clippy_restriction_lints) lint.

**Comment by c410-f3r** [comment]
Yet another use case of https://github.com/rust-lang/cargo/issues/5034

Closing since this situation looks more like a feature than a bug
