### ISSUE TITLE
`bool_assert_comparison`: assert_eq! with a literal bool

### ISSUE THREAD

**Issue by cemoktra** [rust-lang/rust-clippy#8118]
### Description

Hi,

i have a macro which generated a function for use in unit tests which is:
```
assert_eq!($MacroInput, my_struct.macro_input());
```

Clippy indicates in this case that i should use `assert!` but this would mean that i have to write an if/else block to handle both cases. 
While this makes sense if i have a hardcoded boolean literal, but in this case i have macro generated boolean literals.

### Version

```text
rustc 1.57.0 (f1edd0429 2021-11-29)
binary: rustc
commit-hash: f1edd0429582dd29cccacaf50fd134b05593bd9c
commit-date: 2021-11-29
host: x86_64-unknown-linux-gnu
release: 1.57.0
LLVM version: 13.0.0
```

**Comment by giraffate** [comment]
Can you provide a minimal reproduction on the playground?

**Comment by cemoktra** [comment]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d1294390d2e6e3e4a416c600ccbcb74b
