### ISSUE TITLE
Add SARIF Support

### ISSUE THREAD

**Issue by josepalafox** [rust-lang/rust-clippy#8121]
### Description

[SARIF is an OASIS](https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=sarif) standard for outputting Security Alerts in JSON.
GitHub has implemented a feature called[ Code Scanning](https://github.com/features/security), which can consume SARIF reports and display them as inline PR comments. This is available for free for any OSS project.

Would you be open to us adding the SARIF output format to the linter? If so we can write a GitHub Action (see linked ticket) to run the linter during CI and send the reports to the code scanning feature in GitHub. The UX would be that users can just one click install the scanner on a target repo and get the results cleanly integrated back in the GH UI.

@michaelcfanning and @yongyan-gh

**Comment by llogiq** [comment]
Since clippy is reusing the rustc lint machinery for its messages, the best way to go is likely to add this as another output format to the compiler. This would also cover the normal Rust lints.

To do that, you need to change rust, not clippy.

**Comment by flip1995** [comment]
Since this can't be done in Clippy, but only in rustc, and there is already some discussion in #8122 about this, I'm closing this issue.
