### ISSUE TITLE
Improve documentation of `borrowed_box`

### ISSUE THREAD

**Issue by flip1995** [rust-lang/rust-clippy#8161]
### Description

This came up in #3971.

The documentation could need some improvement. It should mention, that by removing the Box from ``&Box<T>``, you no longer have to box the parameter when it is passed to the function. For more information, see the discussion in #3971.

**Comment by 1nF0rmed** [comment]
If I understand correctly, there needs to be a change in the "Why is this bad?" section [here](https://github.com/rust-lang/rust-clippy/blob/92048f4826a445872eb50760a4f46a92837b243e/clippy_lints/src/types/mod.rs#L164), where it elaborates more on how removing `Box` from a function parameter can generalize the function.

Would that be right?

**Comment by flip1995** [comment]
Yes, exactly
