### ISSUE TITLE
Clippy fails to compute type ("failed to lookup `SourceFile` in new context")

### ISSUE THREAD

**Issue by ammongit** [rust-lang/rust-clippy#8164]
This [GitHub workflow is failing](https://github.com/scpwiki/wikijump/runs/4623778342?check_suite_focus=true) with the following:
```
Run cd deepwell && cargo clippy
   Compiling deepwell v0.3.0 (/home/runner/work/wikijump/wikijump/deepwell)
thread 'rustc' panicked at 'failed to lookup `SourceFile` in new context', compiler/rustc_query_impl/src/on_disk_cache.rs:500:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.59 (c09a952 2021-12-23)

query stack during panic:
#0 [type_of] computing type of `web::ratelimit::GovernorMiddleware::limiter`
#1 [inferred_outlives_crate] computing the inferred outlives predicates for items in this crate
end of query stack
error: could not compile `deepwell`
Error: Process completed with exit code 101.
```

The relevant type is [`/deepwell/src/web/ratelimit.rs`](https://github.com/scpwiki/wikijump/blob/develop/deepwell/src/web/ratelimit.rs#L51) (declared as `Arc<RateLimiter<IpAddr, DefaultKeyedStateStore<IpAddr>, DefaultClock>>`), which sources its internals from the [`governor` crate](https://crates.io/crates/governor).

This happens intermittently, I cannot reproduce it consistently. If there's any other information I will do my best.

**Comment by Serial-ATA** [comment]
https://github.com/rust-lang/rust/issues/92163

**Comment by QiangHeisenberg** [comment]
You can delete the incremental cache, or use ```CARGO_INCREMENTAL=0``` environment variable to disable it.

**Comment by flip1995** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/92163 (nothing that could be done in Clippy)
