### ISSUE TITLE
New lint: `iter_overeager_cloned`

### ISSUE THREAD

**Issue by pmnoxx** [rust-lang/rust-clippy#8202]
### What it does

Calling `.iter().cloned.last()` involved doing unnecessary work.
It's better to write it as `.iter().last().cloned()`

Same thing can rule can be applied to:
-  `.iter().cloned().next()` 
-  `.iter().cloned().count()` 
-  `.iter().cloned().flatten()`
-  `.iter().cloned().take(...)`
-  `.iter().cloned().skip(...)`
-  `.iter().cloned().nth(...)` 

### Lint Name

cloned_last

### Category

style, perf

### Advantage

- More efficient code

### Drawbacks

- I don't see any

### Example

```rust
    let _: Option<String> = vec!["1".to_string(), "2".to_string(), "3".to_string()]
        .iter().cloned().last()
```

Could be written as:

```rust
    let _: Option<String> = vec!["1".to_string(), "2".to_string(), "3".to_string()]
        .iter().last().cloned()
```

**Comment by pmnoxx** [comment]
I created a new PR for that lint: https://github.com/rust-lang/rust-clippy/pull/8203

**Comment by kornelski** [comment]
Iterators are lazy, so `.iter().cloned().take(...)` and `.iter().cloned().next()` are perfectly fine.

**Comment by llogiq** [comment]
By themselves `.cloned().take()` is ok, but that could be followed by `.last()` and  that would trigger the lint next time.

With `.next()` I somewhat agree, though I note that it will still produce more code to optimize away, so it will likely at least positively affect compile time (and probably debug runtime). Is there any benefit to not switching the order?

**Comment by kornelski** [comment]
Ok, I see your point. The benefit would be only in number of warnings from clippy for a not-strictly-necessary case.

**Comment by robertbastian** [comment]
I think the examples for this are bad and should be updated:
```rust
// Bad
vec.iter().cloned().take(10);

// Good
vec.iter().take(10).cloned();
```
These are equivalent, not a single clone happens. Even if we add `.next()`, only one clone will happen in both cases. `collect` would show it, or using `skip`:
```rust
// Bad
vec.iter().cloned().skip(10).next(); // 11 clones

// Good
vec.iter().skip(10).cloned().next(); // 0-1 clones
```
---
```rust
// Bad
vec.iter().cloned().last();

// Good
vec.iter().last().cloned();
```
This has a typo, the good line should be `.clone()`.

**Comment by llogiq** [comment]
No. `Option::cloned()` is the correct function to call here, and that's what the suggested code does.

**Comment by robertbastian** [comment]
What about the first part of my comment?
