### ISSUE TITLE
v.checked_sub(1).unwrap_or(v) is also an implicit_saturating_sub

### ISSUE THREAD

**Issue by gilescope** [rust-lang/rust-clippy#8215]
### Description

we already detect saturating_subs done one way:

https://github.com/rust-lang/rust-clippy/blob/master/clippy_lints/src/implicit_saturating_sub.rs

I came across someone doing it another way: `v.checked_sub(1).unwrap_or(v)`

Thought it might be one to add into the logic. Maybe an easy one for a new person to hack on?

### Version

```text
n/a
```

**Comment by giraffate** [comment]
As noted above, the [`manual_saturating_arithmetic`](https://rust-lang.github.io/rust-clippy/master/index.html#manual_saturating_arithmetic) covers this, so I'm closing this.
