### ISSUE TITLE
From an if predicate expression to T::from() suggestion

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust-clippy#8240]
### What it does

On functions like this:

```rust
fn foo1(x: u32, y: i32) -> u32 {
    x + if y > 5 { 1 } else { 0 }
}

fn foo2(x: u16, y: i32) -> u16 {
    x + if y > 5 { 0 } else { 1 }
}

fn foo3(x: u16, y: i32) -> u16 {
    x + if y > 5 { 3 } else { 2 }
}
```

Clippy could suggest to write instead:

```rust
fn foo1(x: u32, y: i32) -> u32 {
    x + u32::from(y > 5)
}

fn foo2(x: u16, y: i32) -> u16 {
    x + u16::from(y <= 5)
}

fn foo3(x: u16, y: i32) -> u16 {
    x + 2 + u16::from(y > 5)
}
```

The foo1, foo2, foo3 cases are progressively harder. Even giving a suggestion just for the basic foo1 case is enough.

### Example

```rust
<code>
```

Could be written as:

```rust
<code>
```

**Comment by camsteffen** [comment]
Duplicate of #8131. I'm not sure I agree with the third case.

**Comment by leonardo-m** [comment]
I close this as duplicate.
the third case is worth keeping in memory, but I agree it's less obviously an improvement :)
