### ISSUE TITLE
ICE: thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_metadata/src/rmeta/def_path_hash_map.rs:18:85

### ISSUE THREAD

**Issue by o0Ignition0o** [rust-lang/rust-clippy#8254]
```
$ rustc --version
rustc 1.57.0 (f1edd0429 2021-11-29)

$ cargo clippy --all --no-default-features -- -D warnings      

    Checking apollo-router-benchmarks v0.1.0-alpha.2 (/Users/ignition/projects/apollo/router/apollo-router-benchmarks)
    Checking test-span-macro v0.1.0 (/Users/ignition/projects/apollo/router/test-span-macro)
    Checking xtask v0.1.0-prealpha.1 (/Users/ignition/projects/apollo/router/xtask)
    Checking apollo-router v0.1.0-alpha.2 (/Users/ignition/projects/apollo/router/apollo-router)
    Finished dev [unoptimized + debuginfo] target(s) in 2.88s
ignition@ignition-apollo router % cargo clippy --all --tests -- -D warnings               Checking apollo-router v0.1.0-alpha.2 (/Users/ignition/projects/apollo/router/apollo-router)
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_metadata/src/rmeta/def_path_hash_map.rs:18:85
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.57 (f1edd042 2021-11-29)
```

`cargo clean` did the trick

The exact code I was running clippy against was committed [hrere](https://github.com/apollographql/router/pull/276/commits/8698f1025fa711537f5ac91a8f1ff7fcbf152491). CI seems to be happy with it (which tends to confirm cargo clean having solved the issue.

I was heavily fiddling with macros, I wonder if this has anything to do with incremental compilation or something 🤔 

This should probably be `P-low` or `P-let's not waste our time on it` since `cargo clean` fixes it ^^

**Comment by matthiaskrgr** [comment]
Yeah, smells like a rustc incremental compilation bug.
https://github.com/rust-lang/rust/issues?q=is%3Aissue+compiler%2Frustc_metadata%2Fsrc%2Frmeta%2Fdef_path_hash_map.rs+

**Comment by o0Ignition0o** [comment]
shall i close this and mark it as duplicate of https://github.com/rust-lang/rust/issues/91988 ?

**Comment by xFrednet** [comment]
Triage here, as suggested above. I'll close this issue for now. If it happens again, please create a new issue. Thank you for the report :D
