### ISSUE TITLE
Simplify `if let` statements that immediately return unwrapped value

### ISSUE THREAD

**Issue by tvolk131** [rust-lang/rust-clippy#8288]
### What it does

Reduce simple `if let` statements that immediately return the unwrapped value by replacing the `if let` with a `?`.

### Lint Name

collapsible_if_let_return

### Category

style

### Advantage

Encourages concise code and proper use of the `?` operator.

### Drawbacks

None that I can think of.

### Example

```
fn example_fn() -> Result<(), CustomError> {
    if let Err(err) = run_some_process() {
        return Err(err);
    }
    // Other function logic...
    Ok(())
}
```

Could be written as:

```
fn example_fn() -> Result<(), CustomError> {
    run_some_process()?;
    // Other function logic...
    Ok(())
}
```

And, if there were no other function logic, could further be reduced to:

```
fn example_fn() -> Result<(), CustomError> {
    run_some_process()
}
```

**Comment by camsteffen** [comment]
This can be an enhancement of the `question_mark` lint.

**Comment by J-ZhengLi** [comment]
Is it true that the `clippy_utils::higher::IfLet::hir` function does not pickup `if let Err(err) = function_call() {}` as a recognized pattern?

**Comment by dswij** [comment]
> Is it true that the `clippy_utils::higher::IfLet::hir` function does not pickup `if let Err(err) = function_call() {}` as a recognized pattern?
> 
> It detects
> 
> ```rust
> if let Err(err) = function_call() {
>     return Err(err);
> } else {}
> ```
> 
> but not without `else`, what am I missing?

If you're referring to https://github.com/rust-lang/rust-clippy/blob/0b143e347c61ab2fc62e9b533d48009aede2f3fc/clippy_lints/src/question_mark.rs#L98-L99 not firing without `else`, it's because of the pattern match in L98 to only match on `if_else: Some(..)`.

`clippy_utils::higher::IfLet::hir` does pick up `if let` without `else`. In fact, `question_mark` lint only checks for returns in the else arm right now.

**Comment by J-ZhengLi** [comment]
> ... it's because of the pattern match in L98 to only match on `if_else: Some(..)`.
> `clippy_utils::higher::IfLet::hir` does pick up `if let` without `else`. In fact, `question_mark` lint only checks for returns in the else arm right now.

Thank you for pointing that out~

**Comment by dswij** [comment]
@J-ZhengLi are you working on this? If so, you can comment `@rustbot claim` to assign yourself to this issue :)

**Comment by J-ZhengLi** [comment]
> @J-ZhengLi are you working on this? If so, you can comment `@rustbot claim` to assign yourself to this issue :)

Well... fine, I guess I'll give it a try.

@rustbot claim

**Comment by J-ZhengLi** [comment]
> This can be an enhancement of the `question_mark` lint.

As the author mentioned: 

> And, if there were no other function logic, could further be reduced to:
> 
> ```
> fn example_fn() -> Result<(), CustomError> {
>     run_some_process()
> }
> ```

It might be hard to detect what's inside of `Ok()` except for "void", but easier for option, for example:

```rust
fn foo(x: Option<i32>) -> Option<i32> {
    // do something
    if let Some(a) = x {
        return Some(a);
    }
    None
}
```
Or
```rust
fn foo(x: Option<i32>) -> Option<i32> {
    // do something
    if let Some(a) = x {
        Some(a)
    } else {
        None
    }
}
```

These could all be replaced by a simple `x` return, which could indeed be a new lint right?
