### ISSUE TITLE
cargo clippy --explain <lintname>

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-clippy#8291]
### Description

Rustc has this nice `rustc --explain E060` feature.
I wonder if we could have the same in form of `cargo clippy --explain needless_borrow` for example.
This would print the lints explanation of the doc-comment ( https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow ) into the terminal, the advantage being that we don't need a web browser and internet to access the lint explanation :slightly_smiling_face:

**Comment by xFrednet** [comment]
I've added the nominated tag. Having this sounds like a good idea :upside_down_face:

**Comment by xFrednet** [comment]
FYI: This was discussed in today's meeting. See [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Meeting.202022-01-25/near/269275900) Everyone agreed that this is a good idea and @llogiq wants to work on this.

@rustbot label -I-nominated

**Comment by llogiq** [comment]
I wonder how to best store the collected data. To start, I'm going to build a macro that will move the doc comment to a string argument.

**Comment by xFrednet** [comment]
Sounds like a good idea, the Metadata collector for our lint list collects the docs from the doc comment. If you change the macro it would be good to reapply the doc comments to the lint item.

Storage will be an interesting problem, I've looked into some ideas while I was working on #8211 but haven't found a nice solution yet. I even thought about building a wrapper type about rustc's lint to store some additional Clippy data, but that didn't feel quite right to only implement nightly lints. I'm interested to see what you come up with :upside_down_face:
