### ISSUE TITLE
Check usages of undefined features

### ISSUE THREAD

**Issue by EFanZh** [rust-lang/rust-clippy#8301]
### What it does

Warn usages of features that are not defined in `features` section of `Cargo.toml` and are not optional dependencies.

### Lint Name

undefined-features

### Category

correctness, suspicious

### Advantage

- Check misspelled feature names.
- Check unused code.

### Example

```rust
fn foo() {}

#[cfg(feature = "bar")]
fn bar() {}
```

If feature `"bar"` is not defined in `Cargo.toml`, the code above could be written as:

```rust
fn foo() {}
```

**Comment by jplatte** [comment]
Duplicate of #1614.

**Comment by epage** [comment]
Looks like there is also #11649 for this.  There is also native support coming to rustc/cargo, see https://github.com/rust-lang/rust/issues/82450

**Comment by Alexendoo** [comment]
Closing in favour of https://github.com/rust-lang/rust/issues/82450
