### ISSUE TITLE
explicit_counter_loop reports wrong lint

### ISSUE THREAD

**Issue by mimoo** [rust-lang/rust-clippy#8312]
### Summary

here `GATES` is a `pub const GATES: usize = 1 << 16;` imported from a different module:

<img width="949" alt="Screen Shot 2022-01-18 at 10 21 31 PM" src="https://user-images.githubusercontent.com/1316043/150075479-195d4602-f7f7-4529-9e27-4cab3d34b0d1.png">

### Reproducer

```rust
pub mod A { 
  pub const GATES: usize = 1 << 16;
}

use A::GATES;

for _ in 0..GATES {
  println!("hey hey");
}
```

**Comment by camsteffen** [comment]
Can you add a code snippet under Reproducer?

**Comment by mimoo** [comment]
added one, hopefully it works unless the bug is caused by something else... but that's basically my code.

**Comment by camsteffen** [comment]
I wasn't able to reproduce in a [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=7f7ef30a6c9918dbdb38d172082d9655).
