### ISSUE TITLE
`unneeded unit expression`on wasm_bindgen macro

### ISSUE THREAD

**Issue by keiya01** [rust-lang/rust-clippy#8314]
### Summary

I encountered `unneeded unit expression` clippy error on `#[wasm_bindgen]`.
This error was not occurred until yesterday.
I think this error is affected by `rustc 1.60.0-nightly (5e57faa78 2022-01-19)`. But I can not find the reason.

See encountered GitHub Actions error: https://github.com/keiya01/og_image_writer/runs/4876028199?check_suite_focus=true

### Lint Name

unneeded unit expression

### Reproducer

I tried this code:

```rust
#[wasm_bindgen(js_class = Rgba)]
```

I saw this happen:

```
error: unneeded unit expression

help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unused_unit
   = note: this error originates in the attribute macro `wasm_bindgen::prelude::__wasm_bindgen_class_marker` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### Version

```text
rustc 1.60.0-nightly (5e57faa78 2022-01-19)
host: ubuntu-latest
```

**Comment by morenol** [comment]
Related to https://github.com/rustwasm/wasm-bindgen/issues/2774
