### ISSUE TITLE
New lint: suggest using "implicit named arguments"

### ISSUE THREAD

**Issue by stanislav-tkach** [rust-lang/rust-clippy#8368]
### What it does

This lint suggests using the feature added in the 1.58 version of Rust: implicit named arguments for formatting macros.

### Lint Name

implicit_named_arguments

### Category

style

### Advantage

- Slightly less verbose code.
- (Arguably) less error prone code.

### Drawbacks

The only drawback that I can see is that not everyone would probably be happy with this lint, so perhaps it should be opt-in (pedantic).

### Example

```rust
println!("1 = {}, 2 = {}, 3 = {}", first, second, third);
```

Could be written as:

```rust
println!("1 = {first}, 2 = {second}, 3 = {third}");
```

**Comment by stanislav-tkach** [comment]
Perhaps this issue duplicated https://github.com/rust-lang/rust-clippy/issues/633.

**Comment by nyurik** [comment]
I began av implementation of this lint based on the https://github.com/rust-lang/rust-clippy/pull/8518 by @Alexendoo. So far I got it to identify most cases, but I am still struggling with the internal API -- for some reason the suggestions do not modify the source code. I am also not certain how to parse the structs in case the same value is used multiple times, i.e. `("{0} {0}", var)` case.  Any help and feedback is greatly appreciated :)

**Comment by Alexendoo** [comment]
You could do the same as in `check_literal`, using a map to only consider arguments that are used once

https://github.com/rust-lang/rust-clippy/blob/818a91e8c83b5acd040594bb03199966f6394f1a/clippy_lints/src/write.rs#L423-L430

**Comment by nyurik** [comment]
I added some more implementation code, and some of it even works (kinda).  Any feedback is welcome - probably best to do it on the #9233 PR.  Thanks!

**Comment by nyurik** [comment]
Forgot to comment on this one... DONE! :D
