### ISSUE TITLE
Infinite recursion in 1.59 clippy

### ISSUE THREAD

**Issue by jntrnr** [rust-lang/rust-clippy#8469]
### Summary

Trying to run `cargo clippy` on a fresh checkout of nushell (https://github.com/nushell/nushell) I get the following:

```
error: process didn't exit successfully: `rustc -vV` (exit status: 1)
--- stderr
error: infinite recursion detected
```

I tried other variations, like `cargo clippy --all --all-features`, and still have the same issue.

### Reproducer

I tried this code: 

(see above)

I expected to see this happen: clippy to run correctly

Instead, this happened: clippy exits with an error about infinite recursion

### Version

```text
rustc 1.59.0 (9d1b2106e 2022-02-23)
binary: rustc
commit-hash: 9d1b2106e23b1abd32fce1f17267604a5102f57a
commit-date: 2022-02-23
host: x86_64-unknown-linux-gnu
release: 1.59.0
LLVM version: 13.0.0
```

**Comment by Jarcho** [comment]
Seems to work on Windows using commit `cbad648` and for some reason `clippy --target` doesn't work.

```
rustc 1.59.0 (9d1b2106e 2022-02-23)
binary: rustc
commit-hash: 9d1b2106e23b1abd32fce1f17267604a5102f57a
commit-date: 2022-02-23
host: x86_64-pc-windows-msvc
release: 1.59.0
LLVM version: 13.0.0
```

**Comment by jntrnr** [comment]
Closing as this morning I can't repro. I'm guessing it was an environment variable I'd set previously that caused it issue. A fresh terminal and checkout seem fine.
