### ISSUE TITLE
suggest map_or  for simple None substitutions

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-clippy#8492]
### What it does

Find patterns like
````rust
pub fn a(s: Option<String>) -> usize {
    match s {
        Some(string) => string.len(),
        None => 1, 
    }
}
````

and suggest to use `map_or` instead:

````rust
pub fn a(s: Option<String>) -> usize {
    s.map_or(1, |string| string.len())
}
````

We might need to consider restricting such a lint to simple matches that don't have a lot of "stuff going on"

### Lint Name

map_or_match? matching_map_or? mmh

### Category

style

### Advantage

for simple matches, this reduces lines from 4 to 1, and I think it's a bit easier to grasp what is going on if you are familiar with `map_or`.

### Drawbacks

:shrug: 

We might want to bail out on matches where a single arm spans several lines.

### Example

```rust
pub fn a(s: Option<String>) -> usize {
    match s {
        Some(string) => string.len(),
        None => 1, 
    }
}
```

Could be written as:

```rust
pub fn a(s: Option<String>) -> usize {
    s.map_or(1, |string| string.len())
}
```

**Comment by J-ZhengLi** [comment]
Seems like this hasn't been fixed yet... @rustbot claim

**Comment by J-ZhengLi** [comment]
> Just a note for anyone taking this. There is `option_if_let_some_else_none` which covers this only for `if let ... else ...`.

should I extend that lint and change its name or add a new one?
