### ISSUE TITLE
`unnecessary_to_owned` suggestion causes error due to lifetime and boxed trait objects

### ISSUE THREAD

**Issue by ltentrup** [rust-lang/rust-clippy#8507]
### Summary

When applying the suggested fix to the following code, the compiler emits an error.
I observed the original behavior in a project using the `warp` framework.

Clippy is a great project, I use it daily and learned a lot from the suggestions!

The issue seems to be with the `build` function, which takes a type with `AsRef<str>` as an argument. But instead of calling `AsRef::as_ref`, the ownership of the argument is transferred to the returned struct. The suggestion removes the `to_string()` call on the input, which causes the returned struct to be bound by the lifetime of the input, thus, the compiler error.
The lint is no longer applied if the `s.to_string()` call is moved to a separate line.

### Lint Name

unnecessary_to_owned

### Reproducer

I tried this code:

```rust
struct Opaque<P>(P);

pub trait Abstracted {}

impl<P> Abstracted for Opaque<P> {}

fn build<P>(p: P) -> Opaque<P>
where
    P: AsRef<str>,
{
    Opaque(p)
}

pub fn test(s: &str) -> Box<dyn Abstracted> {
    Box::new(build(s.to_string()))
}
```

I saw this happen:

```
warning: unnecessary use of `to_string`
  [--> src/main.rs:19:20
](https://play.rust-lang.org/#)   |
19 |     Box::new(build(s.to_string()))
   |                    ^^^^^^^^^^^^^ help: use: `s`
   |
   = note: `#[warn(clippy::unnecessary_to_owned)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_to_owned
```

I expected to see this happen:

The lint should not have triggered.

### Version

```text
rustc 1.61.0-nightly
2022-03-04 9fcbc32053d5084d1de7
```

**Comment by smoelius** [comment]
Ooh, this one's tricky:
```
Compiling playground v0.0.1 (/playground)
error[[E0759]](https://doc.rust-lang.org/stable/error-index.html#E0759): `s` has an anonymous lifetime `'_` but it needs to satisfy a `'static` lifetime requirement
  [--> src/lib.rs:15:20
](https://play.rust-lang.org/#)   |
14 | pub fn test(s: &str) -> Box<dyn Abstracted> {
   |                ---- this data with an anonymous lifetime `'_`...
15 |     Box::new(build(s))
   |                    ^ ...is used and required to live as long as `'static` here
   |
note: `'static` lifetime requirement introduced by the return type
  [--> src/lib.rs:14:29
](https://play.rust-lang.org/#)   |
14 | pub fn test(s: &str) -> Box<dyn Abstracted> {
   |                             ^^^^^^^^^^^^^^ `'static` requirement introduced here
15 |     Box::new(build(s))
   |     ------------------ because of this returned expression
help: to declare that the trait object captures data from argument `s`, you can add an explicit `'_` lifetime bound
   |
14 | pub fn test(s: &str) -> Box<dyn Abstracted + '_> {
   |                                            ++++

For more information about this error, try `rustc --explain E0759`.
error: could not compile `playground` due to previous error
```
Thanks, @ltentrup. I'll try to find an appropriate fix.

**Comment by ltentrup** [comment]
Maybe it is possible to check whether the type `P` is used in the return type of the function? That should eliminate this and similar problems.

**Comment by smoelius** [comment]
> Maybe it is possible to check whether the type `P` is used in the return type of the function? That should eliminate this and similar problems.

Yeah, that's essentially what I did.
