### ISSUE TITLE
unnecessary const modulo const

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust-clippy#8508]
### What it does

lints on modulo operations where both inputs are literals and for which `lhs < rhs` holds
```rust
fn wrapping_add(x: u32) -> u32 {
    x + 1 % 32
}
```

this ended up causing a logic bug in a recent project, see https://github.com/lcnr/shitty-bot-game/commit/cdcff2c7d5de7f5fb32aa445031c651db1454cce

### Example

```rust
fn wrapping_add(x: u32) -> u32 {
    x + 1 % 32
}
```
suggesting either
```rust
fn wrapping_add(x: u32) -> u32 {
    (x + 1) % 32
}
```
or if that isn't trivially possible
```rust
fn wrapping_add(x: u32) -> u32 {
    x + 1
}
```

**Comment by tysg** [comment]
I'll try this one! @rustbot claim
