### ISSUE TITLE
"Clippy Lints" page forgets "Lint groups" selection

### ISSUE THREAD

**Issue by smoelius** [rust-lang/rust-clippy#8510]
### Description

If you search for a Clippy lint by selecting one or more "Lint groups," click "View Source," and then click the back button, the lint groups will still be selected, but the selection will not be respected.

What I did:
1. Go to the [Clippy Lints](https://rust-lang.github.io/rust-clippy/master/) page.
2. Unselect all "Lint groups" but "Restriction."
3. Expand "indexing_slicing."
4. Click "View Source."
5. Click the browser back button.

What I saw: more than just "Restriction" lints.

What I expected to see: just "Restriction" lints.

In fact, after clicking the back button, if you select and unselect a lint group, you can see those lints disappearing from the listing.

Clicking "Related Issues" seems to exhibit the same behavior.

**Comment by smoelius** [comment]
I was considering cc-ing you, @xFrednet. Do you know what is required to fix this?

**Comment by xFrednet** [comment]
Nice, I really like the lint list, thanks for the thought. :upside_down_face: 

Yes, the implementation simply has to store the selection in `localstorage` and retrieve it once the website loads. This is already done for the theme. 

[Here is the complete snippet](https://github.com/rust-lang/rust-clippy/blob/0c483f69db979f9dc88f96493ea4b21d946d845d/util/gh-pages/index.html#L605-L613) The important lines are:
* 607 as that stores the actual value
* 613 as that loads the theme on page load

It's a bit hacky as I'm a novice with JS and angular.js, but it works fairly well. You can use the same approach if you want :upside_down_face:. You are welcome to ping me for the review or any questions or just if you think something could be interesting to me :upside_down_face:

**Comment by xFrednet** [comment]
Side note: we might merge #8070 soon (I just asked if we want to merge it ^^). That might cause some conflict, but those should be simple to solve, or you base your branch on that PR :upside_down_face:

**Comment by pitaj** [comment]
I can't reproduce this in Firefox. Either it's already been fixed or isn't an issue on some browsers.

**Comment by xFrednet** [comment]
I can reproduce it on my Firefox (99.0b7 (64-bit)). I simply open the [lint list](https://rust-lang.github.io/rust-clippy/master/index.html) change the group selection (Just select or deselect something).

![image](https://user-images.githubusercontent.com/17087237/160086069-bd72c8fd-0d7a-4363-a0f4-f01ee86b83df.png)

When I reload the page the selection is reset to the default. 

![image](https://user-images.githubusercontent.com/17087237/160086121-71ff3ee4-443c-493e-9c55-9dbfb077f597.png)

**Comment by smoelius** [comment]
I too still see the problem with Chrome Version 99.0.4844.82 (Official Build) snap (64-bit).

But thank you for checking @pitaj. :pray:

**Comment by pitaj** [comment]
@xFrednet Reloading the page will reset it, but viewing the source then hitting back seems to be cached by Firefox.

**Comment by xFrednet** [comment]
Interesting :), if you want you can claim the issue. Note that this only involve JavaScript changes and nothing written in Rust :upside_down_face:

**Comment by smoelius** [comment]
IMHO, your idea is a good one, @whee.

**Comment by xFrednet** [comment]
I agree that this is a good idea :)

**Comment by smoelius** [comment]
Very nice, @whee . :)
