### ISSUE TITLE
Useless `peekable` iterator

### ISSUE THREAD

**Issue by mcarton** [rust-lang/rust-clippy#854]
Just noticed that when refactoring. We could warn when making an iterator [peekable](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.peekable), but never actually peeking it(/returning it/passing it to a function).

**Comment by birkenfeld** [comment]
Sounds pretty specific. Are you sure it's worth it?

**Comment by lukaslueg** [comment]
@birkenfeld FWIW I've seen this in the wild, too
