### ISSUE TITLE
Warn if function name `default()` is used without implementing the `Default` trait

### ISSUE THREAD

**Issue by kamulos** [rust-lang/rust-clippy#8550]
### Description

Just stumbled on this in a code review. Would it make sense to check the naming of a member function? If a `default()` function is used (especially as a constructor) I would expect, that the `Default` trait is implemented.

Not sure if this would be it's own lint or integrated in an existing one

**Comment by smoelius** [comment]
Personally, I would generalize this to: any inherent method decalartion whose name matches a `std` trait method name.

There may be reasons why this is *too* general, but I can't think of any offhand.

**Comment by smoelius** [comment]
Today, I noticed this: https://github.com/rust-lang/rust-clippy/blob/f07ee8a998eff61977d594eeac44dc1d0ead7b02/clippy_lints/src/methods/mod.rs#L2642
Apparently, `should_implement_trait` has been around for a while. This seems to be the PR that introduced it: https://github.com/rust-lang/rust-clippy/pull/228
