### ISSUE TITLE
Clippy wants to break my code in option_map_unit_fn

### ISSUE THREAD

**Issue by 1Dragoon** [rust-lang/rust-clippy#8569]
### Summary

Clippy is showing a lint on this line in my code:

https://github.com/1Dragoon/fcp/blob/5a3bcb72e6df0e6d4b6d5dd0c70cecc24b0533f3/src/main.rs#L117

Basically it wants to transform this:

```rust
err.map(|e| println!("{:?}", e));
```

(Where err is Option<Error>)

Into this:

```rust
if let Some(e) = err { $crate::io::_print($crate::format_args_nl!($($arg)*)); }
```

I get why it doesn't like what I put there, but its suggested fix is quite a ways off the mark :)

I think it was going for this:

```rust
if let Some(e) = err {println!("{:?}", e)}
```

Though TBH I think doing a one-off thing with an option or result like that is probably more concise my way than the "if let" way, but I don't know what the rest of the Rust community feels about that.

### Lint Name

option_map_unit_fn

### Reproducer

I tried this code:

```rust
err.map(|e| println!("{:?}", e));
```

I saw this happen:

```rust
if let Some(e) = err { $crate::io::_print($crate::format_args_nl!($($arg)*)); }
```

I expected to see this happen:

```rust
if let Some(e) = err {println!("{:?}", e)}
```

### Version

```text
rustc 1.59.0 (9d1b2106e 2022-02-23)
binary: rustc
commit-hash: 9d1b2106e23b1abd32fce1f17267604a5102f57a
commit-date: 2022-02-23
host: x86_64-pc-windows-msvc
release: 1.59.0
LLVM version: 13.0.0
```

**Comment by giraffate** [comment]
I tried [this](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=f6bc7800f57cf470fe772e969565e7e2) on the playground, but I can't reproduce it. Can you provide the reproduction on the playground? (I don't have windows, so can't build this repo.)

**Comment by Alexendoo** [comment]
I can reproduce this locally, odd it doesn't happen on the playground

@rustbot claim

**Comment by Alexendoo** [comment]
I couldn't reproduce it from the playground on a local linux device but could on a windows one. After a bit of confusion I realised the linux one didn't have `rust_src` installed 😄
