### ISSUE TITLE
Prefer `Seek#rewind()` over `Seek#seek(SeekFrom::Start(0))`

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust-clippy#8600]
### What it does

Suggests using the helper shortcut method, which is shorter.

https://doc.rust-lang.org/stable/std/io/trait.Seek.html#method.rewind

### Example

```rust
fn foo<T: io::Seek>(t: T) {
    t.seek(io::SeekFrom::Start(0));
}
```

Could be written as:

```rust
fn foo<T: io::Seek>(t: T) {
    t.rewind();
}
```

**Comment by J-ZhengLi** [comment]
seems interesting...
@rustbot claim

**Comment by J-ZhengLi** [comment]
> @rustbot claim
> 
> @J-ZhengLi I'm still new to Rust and this would be my first contribution to clippy so would you be available for questions if I run into issues?

Sure, but I doubt if I could be anyway near as helpful as the official members lol.

**Comment by giraffate** [comment]
@brleinad If you have any questions, you can ask me too. Or you can ask on the [zulip](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy) chat.

**Comment by brleinad** [comment]
A quick update: 
I've been working on this on and off for the last two weeks but I've been pretty busy with other things  so progress is slow. I might not be able to work on it until May. If anybody else is interested in taking this while I'm away here's the Zulip [thread](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/rewind.20over.20seek.20from.20start.20-.20new.20lint).

**Comment by Rqnsom** [comment]
Is it okay if I take over this one?

**Comment by Rqnsom** [comment]
@brleinad Ping me when you continue working on this. I've prepared a draft commit (for my learning purposes) which is partially done. I can share it with you since maybe it can help you.

**Comment by brleinad** [comment]
Thanks for that @Rqnsom! Life has been too busy in the last few weeks to work on any Rust projects 😢 so feel free to take this over. I'm sorry for the late reply.

**Comment by Rqnsom** [comment]
> Life has been too busy in the last few weeks to work on any Rust projects

@brleinad No worries, I feel ya!


I'll see if I can do it during the next week maybe.

@rustbot claim

**Comment by frewsxcv** [comment]
@Rqnsom Are you still working on this?

**Comment by Rqnsom** [comment]
Not really. Wanted to. But I couldn't find the time.
Could you unassign me?

**Comment by dorublanzeanu** [comment]
I would like to give it a go if nobody else is working on this, it would be my first contribution to clippy.
