### ISSUE TITLE
Incomplete suggestion combines poorly with other tools (rust-analyzer)

### ISSUE THREAD

**Issue by Crzyrndm** [rust-lang/rust-clippy#8739]
### Summary

Summary: 
* `clippy::while_let_loop` suggests a replacement where the body of the if is not included. Note that `cargo clippy --fix` doesn't update anything
* rust-analyzer sees the suggestion and ends up removing the body of the `if` when user doesn't fully comprehend the suggested action

Unknown if while_let_loop is the only clippy lint to include this behaviour (incomplete suggested replacement)

https://github.com/rust-lang/rust-analyzer/issues/12069
> Some clippy replacements are incomplete. They provide a template for the suggested output, but direct copy paste will not give equivalent/improved behaviour. Some sections are left to the user to fill in
> 
> A simple example is the `clippy::while_let_loop` lint (I feel like it's not the only one, but perhaps I just keep running into the same issue)
> ![image](https://user-images.githubusercontent.com/8765278/164956560-568741c7-5a9d-4b37-a894-66915fa8fb07.png)
> clippy correctly identifies this as an opportunity to suggest a while-let loop
> ![image](https://user-images.githubusercontent.com/8765278/164956581-27e6aba2-4bfc-4e54-9255-3c72725420eb.png)
> Note that the internals of the loop is left to the the user in the suggested replacement. This is where things become problematic
> 
> RA picks up the suggested replacement
> ![image](https://user-images.githubusercontent.com/8765278/164956626-6ac0ef6c-455e-4f9a-a10d-289a9e86f158.png)
> And now any code that was in the body of the if is gone
> ![image](https://user-images.githubusercontent.com/8765278/164956639-b31aac27-96f1-415b-bb09-2218eeb636c2.png)

### Reproducer

Using vscode + rust-analyzer with clippy suggestions
I tried this code:

```rust
pub fn loop_lint(x: Option<i32>) {
    loop {
        if let Some(_i) = x {
            // many lines of work
        } else {
            break;
        }
    }
}
```

I expected to see this happen:
```rust
pub fn loop_lint(x: Option<i32>) {
    while let Some(_i) = x {
        // many lines of work
    }
}
```
Instead, this happened:
```rust
pub fn loop_lint(x: Option<i32>) {
    while let Some(_i) = x { .. }
}
```

### Version

```text
rustc --version
rustc 1.60.0 (7737e0b5c 2022-04-04)
```

**Comment by Serial-ATA** [comment]
The body is intentionally left out, I'd say this is a RA issue.

https://github.com/rust-lang/rust-clippy/blob/388e6b78544de7cf0423ae93074d0d82b70f10a5/clippy_lints/src/loops/while_let_loop.rs#L83-L88

**Comment by Crzyrndm** [comment]
https://github.com/rust-lang/rust-analyzer/pull/12075
^^ Seems to be the RA resolution
