### ISSUE TITLE
suggest replacing let else with ? statement where applicable

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-clippy#8755]
Sorry, filed via mobil which doesn't know about issue templates. 😅

might be nice if clippy could lint patterns like this: https://github.com/rust-lang/rust/pull/96471

**Comment by est31** [comment]
I guess the `question_mark` lint could be extended to handle this case? Also, maybe one needs to watch out to not suggest let-else first (#8437) to then suggest `?`, but suggest `?` right away. IDK how conflicts like this are handled.

**Comment by est31** [comment]
Another example where this lint would have been useful: https://github.com/rust-lang/cargo/commit/cf716fc3c2b0785013b321f08d6cf9e277f89c84

**Comment by est31** [comment]
Given the two samples that we have, I think that *most* of the times the lint would fire is for functions that return `Option`. So that means that checking for the pattern should be pretty easy.

**Comment by MarijnS95** [comment]
Yes, would love to see the `question_mark` lint extended to `let-else`, and also the mention by @est31 to not first suggest `manual_let_else` on a block of code, followed by `question_mark` on the refactored code.

We currently have two patterns in our codebase with both `Option` and `Result` where the question mark operator could/should be suggested:

```rust
    let x = None::<u32>;
    // Suggest ? here
    let Some(x) = x else {
        return None;
    };

    // Suggest .ok()? here
    let Ok(x) = std::fs::read_to_string("foo") else {
        return None;
    };
```

Thanks!
