### ISSUE TITLE
warns on chars().nth(index)

### ISSUE THREAD

**Issue by gengjiawen** [rust-lang/rust-clippy#8787]
### Description

Similar to https://rust-lang.github.io/rust-clippy/master/index.html#iter_nth, but for string

Ref: https://www.reddit.com/r/rust/comments/tbsffu/why_charsnthindexunwrap_is_so_slow/

**Comment by xFrednet** [comment]
Hey @gengjiawen, thank you for the issue. Do you have an idea what `chars().nth(index)` should be replaced with? For `iter_nth` the user can use direct index access, however in this case, it's not possible to access a specific character in another UTF-8 save way AFAIK :upside_down_face:

**Comment by gengjiawen** [comment]
I think `let str_vec: Vec<char> = s.chars().collect();` should do, but you need do further work if original string contains non-ascii char.

**Comment by samueltardieu** [comment]
Suggesting to close the issue.

**Comment by xFrednet** [comment]
Yeah, I think that's reasonable :)
