### ISSUE TITLE
Improve "unknown key" error message?

### ISSUE THREAD

**Issue by smoelius** [rust-lang/rust-clippy#8806]
### Description

Personally, I find this error message hard to read:
https://github.com/rust-lang/rust-clippy/blob/c3f3c588b0c776bb658ab8e3b803b409b4f63f44/tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr#L1

I think it would be easier to read if the available keys were sorted and printed one per line.

Would you be open to a PR to improve this error message?

**Comment by xFrednet** [comment]
I'm open to it, but this has also been bugging me a bit. Maybe we can have more than one field per line. :upside_down_face:
