### ISSUE TITLE
clippy bug report

### ISSUE THREAD

**Issue by bobi6666** [rust-lang/rust-clippy#8850]
[bug.txt](https://github.com/rust-lang/rust-clippy/files/8738400/bug.txt)

**Comment by Alexendoo** [comment]
Are you able to share the code this crashed on? If not running it with RUST_BACKTRACE=1 would still be helpful

**Comment by bobi6666** [comment]
#[dynamic(lazy)]
pub static BASS_ChannelBytes2Seconds: Symbol<'static, unsafe extern
"system" fn(u32, u64) -> f64> =
    unsafe { BASSLIB.get(b"BASS_ChannelBytes2Seconds").unwrap() };


2022-05-20 13:11 GMT+02:00, Alex Macleod ***@***.***>:

**Comment by bobi6666** [comment]
is there any steps to resolve this bug?

2022-05-20 13:15 GMT+02:00, Peter Kubek ***@***.***>:

**Comment by Alexendoo** [comment]
If you're able to the full source code would be helpful so we can reproduce it ourselves, or if you could reduce the code to a smaller example that exhibits the error that would be even better

If you aren't able to share the full code, sharing the output of

```bat
set RUST_BACKTRACE=1
cargo clippy
```

Would also be helpful

**Comment by bobi6666** [comment]
is this enough? if no i share code
Microsoft Windows [Version 10.0.19044.1706]
(c) Microsoft Corporation. Všetky práva vyhradené.

F:\github projekty\the-killer-bgt\nwengine>set RUST_BACKTRACE=1

F:\github projekty\the-killer-bgt\nwengine>cargo clippy
    Checking windows-sys v0.36.1
    Checking mio v0.8.3
    Checking schannel v0.1.20
    Checking native-tls v0.2.10
    Checking tokio v1.18.2
    Checking tokio-util v0.7.2
    Checking tokio-native-tls v0.3.0
    Checking h2 v0.3.13
    Checking hyper v0.14.18
    Checking hyper-tls v0.5.0
    Checking reqwest v0.11.10
    Checking downloader v0.2.6 (https://github.com/hunger/downloader#969c20e6)
    Checking nwengine v0.1.0 (F:\github projekty\the-killer-bgt\nwengine)
warning: long literal lacking separators
    --> src\lib.rs:1983:23
     |
1983 |         0x0000_0001 | 0x00000002,
     |                       ^^^^^^^^^^ help: consider: `0x0000_0002`
     |
note: the lint level is defined here
    --> src\lib.rs:10:5
     |
10   |     clippy::pedantic,
     |     ^^^^^^^^^^^^^^^^
     = note: `#[warn(clippy::unreadable_literal)]` implied by
`#[warn(clippy::pedantic)]`
     = help: for further information visit
https://rust-lang.github.io/rust-clippy/master/index.html#unreadable_literal

warning: redundant else block
    --> src\lib.rs:2016:12
     |
2016 |       } else {
     |  ____________^
2017 | |         if dtd.TrimEnabled != 0 {
2018 | |             *ptr = 1;
2019 | |         } else {
2020 | |             *ptr = 0;
2021 | |         }
2022 | |     };
     | |_____^
     |
     = note: `#[warn(clippy::redundant_else)]` implied by
`#[warn(clippy::pedantic)]`
     = help: remove the `else` block and move the contents out
     = help: for further information visit
https://rust-lang.github.io/rust-clippy/master/index.html#redundant_else

warning: this `else { if .. }` block can be collapsed
    --> src\lib.rs:2016:12
     |
2016 |       } else {
     |  ____________^
2017 | |         if dtd.TrimEnabled != 0 {
2018 | |             *ptr = 1;
2019 | |         } else {
2020 | |             *ptr = 0;
2021 | |         }
2022 | |     };
     | |_____^
     |
     = note: `#[warn(clippy::collapsible_else_if)]` on by default
     = help: for further information visit
https://rust-lang.github.io/rust-clippy/master/index.html#collapsible_else_if
help: collapse nested if block
     |
2016 ~     } else if dtd.TrimEnabled != 0 {
2017 +         *ptr = 1;
2018 +     } else {
2019 +         *ptr = 0;
2020 ~     };
     |

warning: `if` chain can be rewritten with `match`
  --> src\mods\dialog.rs:43:17
   |
43 | /                 if result.selected_file_paths.len() == 1 {
44 | |                     temp.final_path =
result.selected_file_path.to_str()?.to_owned();
45 | |                 } else if result.selected_file_paths.len() > 1 {
46 | |                     temp.final_path = result
...  |
53 | |                     temp.final_path = String::from("");
54 | |                 }
   | |_________________^
   |
   = note: `#[warn(clippy::comparison_chain)]` on by default
   = help: consider rewriting the `if` chain to use `cmp` and `match`
   = help: for further information visit
https://rust-lang.github.io/rust-clippy/master/index.html#comparison_chain

warning: item name starts with its containing module's name
  --> src\mods\downloader.rs:72:1
   |
72 | / pub struct DownloaderInfo {
73 | |     pub downloading: i32,
74 | |     pub current_downloaded_size: u64,
75 | |     pub speed: u64,
76 | |     pub total_file_size: u64,
77 | |     pub succeeded: i32,
78 | | }
   | |_^
   |
   = note: `#[warn(clippy::module_name_repetitions)]` implied by
`#[warn(clippy::pedantic)]`
   = help: for further information visit
https://rust-lang.github.io/rust-clippy/master/index.html#module_name_repetitions

warning: `dl` is shadowed
   --> src\mods\downloader.rs:118:9
    |
118 |     let dl = dl.progress(SimpleReporter::create());
    |         ^^
    |
note: the lint level is defined here
   --> src\lib.rs:12:5
    |
12  |     clippy::restriction,
    |     ^^^^^^^^^^^^^^^^^^^
    = note: `#[warn(clippy::shadow_reuse)]` implied by
`#[warn(clippy::restriction)]`
note: previous binding is here
   --> src\mods\downloader.rs:110:9
    |
110 |     let mut dl = downloader::Download::new(url);
    |         ^^^^^^
    = help: for further information visit
https://rust-lang.github.io/rust-clippy/master/index.html#shadow_reuse

warning: indexing may panic
   --> src\lib.rs:394:12
    |
394 |         if dialog::DIALOG_RESULTS[index].final_path.is_empty() {
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(clippy::indexing_slicing)]` implied by
`#[warn(clippy::restriction)]`
    = help: consider using `.get(n)` or `.get_mut(n)` instead
    = help: for further information visit
https://rust-lang.github.io/rust-clippy/master/index.html#indexing_slicing

warning: indexing may panic
   --> src\lib.rs:398:53
    |
398 |
CString::from_vec_unchecked(encode(&dialog::DIALOG_RESULTS[index].final_path))
    |
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: consider using `.get(n)` or `.get_mut(n)` instead
    = help: for further information visit
https://rust-lang.github.io/rust-clippy/master/index.html#indexing_slicing

warning: casting `f64` to `u64` may lose the sign of the value
   --> src\lib.rs:446:40
    |
446 |     let converted_creation_time: u64 = creationtime as u64;
    |                                        ^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(clippy::cast_sign_loss)]` implied by
`#[warn(clippy::pedantic)]`
    = help: for further information visit
https://rust-lang.github.io/rust-clippy/master/index.html#cast_sign_loss

warning: casting `f64` to `u64` may lose the sign of the value
   --> src\lib.rs:447:43
    |
447 |     let converted_last_access_time: u64 = lastaccesstime as u64;
    |                                           ^^^^^^^^^^^^^^^^^^^^^
    |
    = help: for further information visit
https://rust-lang.github.io/rust-clippy/master/index.html#cast_sign_loss

warning: casting `f64` to `u64` may lose the sign of the value
   --> src\lib.rs:448:42
    |
448 |     let converted_last_write_time: u64 = lastwritetime as u64;
    |                                          ^^^^^^^^^^^^^^^^^^^^
    |
    = help: for further information visit
https://rust-lang.github.io/rust-clippy/master/index.html#cast_sign_loss

warning: casting `usize` to `i32` may wrap around the value on targets
with 32-bit wide pointers
    --> src\lib.rs:1327:16
     |
1327 |     *len_ptr = final_buffer.len() as i32;
     |                ^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: `#[warn(clippy::cast_possible_wrap)]` implied by
`#[warn(clippy::pedantic)]`
     = help: for further information visit
https://rust-lang.github.io/rust-clippy/master/index.html#cast_possible_wrap

warning: casting `usize` to `i32` may wrap around the value on targets
with 32-bit wide pointers
    --> src\lib.rs:1357:16
     |
1357 |     *len_ptr = final_buffer.len() as i32;
     |                ^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = help: for further information visit
https://rust-lang.github.io/rust-clippy/master/index.html#cast_possible_wrap

warning: this function has too many lines (132/100)
    --> src\lib.rs:1654:1
     |
1654 | / pub unsafe extern "C" fn bass_load(
1655 | |     filenameptr: *const u8,
1656 | |     memory_ptr: *mut i32,
1657 | |     bass_handle: *mut u32,
...    |
1790 | |     f64::from(sample_rate)
1791 | | }
     | |_^
     |
     = note: `#[warn(clippy::too_many_lines)]` implied by
`#[warn(clippy::pedantic)]`
     = help: for further information visit
https://rust-lang.github.io/rust-clippy/master/index.html#too_many_lines

error: internal compiler error:
compiler\rustc_typeck\src\collect.rs:1974:13: unexpected sort of node
in fn_sig(): Item(Item { ident: BASS_ChannelBytes2Seconds#0, def_id:
DefId(0:710 ~ nwengine[9487]::mods::bass_sound::BASS_ChannelBytes2Seconds),
kind: Static(Ty { hir_id: HirId { owner: DefId(0:710 ~
nwengine[9487]::mods::bass_sound::BASS_ChannelBytes2Seconds),
local_id: 1 }, kind: Path(Resolved(None, Path { span:
src\mods\bass_sound.rs:42:1: 42:17 (#262), res: Def(Struct,
DefId(19:1945 ~ static_init[229d]::lazy::Lazy)), segments:
[PathSegment { ident: {{root}}#262, hir_id: Some(HirId { owner:
DefId(0:710 ~ nwengine[9487]::mods::bass_sound::BASS_ChannelBytes2Seconds),
local_id: 2 }), res: Some(Err), args: None, infer_args: false },
PathSegment { ident: static_init#262, hir_id: Some(HirId { owner:
DefId(0:710 ~ nwengine[9487]::mods::bass_sound::BASS_ChannelBytes2Seconds),
local_id: 3 }), res: Some(Def(Mod, DefId(19:0 ~ static_init[229d]))),
args: None, infer_args: false }, PathSegment { ident: lazy#262,
hir_id: Some(HirId { owner: DefId(0:710 ~
nwengine[9487]::mods::bass_sound::BASS_ChannelBytes2Seconds),
local_id: 4 }), res: Some(Def(Mod, DefId(19:1510 ~
static_init[229d]::lazy))), args: None, infer_args: false },
PathSegment { ident: Lazy#262, hir_id: Some(HirId { owner: DefId(0:710
~ nwengine[9487]::mods::bass_sound::BASS_ChannelBytes2Seconds),
local_id: 17 }), res: Some(Err), args: Some(GenericArgs { args:
[Type(Ty { hir_id: HirId { owner: DefId(0:710 ~
nwengine[9487]::mods::bass_sound::BASS_ChannelBytes2Seconds),
local_id: 5 }, kind: Path(Resolved(None, Path { span:
src\mods\bass_sound.rs:43:39: 43:98 (#0), res: Def(Struct,
DefId(16:307 ~ libloading[22e8]::safe::Symbol)), segments:
[PathSegment { ident: Symbol#0, hir_id: Some(HirId { owner:
DefId(0:710 ~ nwengine[9487]::mods::bass_sound::BASS_ChannelBytes2Seconds),
local_id: 14 }), res: Some(Err), args: Some(GenericArgs { args:
[Lifetime(lifetime(HirId { owner: DefId(0:710 ~
nwengine[9487]::mods::bass_sound::BASS_ChannelBytes2Seconds),
local_id: 6 }: 'static)), Type(Ty { hir_id: HirId { owner: DefId(0:710
~ nwengine[9487]::mods::bass_sound::BASS_ChannelBytes2Seconds),
local_id: 13 }, kind: BareFn(BareFnTy { unsafety: Unsafe, abi: System
{ unwind: false }, generic_params: [], decl: FnDecl { inputs: [Ty {
hir_id: HirId { owner: DefId(0:710 ~
nwengine[9487]::mods::bass_sound::BASS_ChannelBytes2Seconds),
local_id: 7 }, kind: Path(Resolved(None, Path { span:
src\mods\bass_sound.rs:43:81: 43:84 (#0), res: PrimTy(Uint(U32)),
segments: [PathSegment { ident: u32#0, hir_id: Some(HirId { owner:
DefId(0:710 ~ nwengine[9487]::mods::bass_sound::BASS_ChannelBytes2Seconds),
local_id: 8 }), res: Some(Err), args: None, infer_args: false }] })),
span: src\mods\bass_sound.rs:43:81: 43:84 (#0) }, Ty { hir_id: HirId {
owner: DefId(0:710 ~
nwengine[9487]::mods::bass_sound::BASS_ChannelBytes2Seconds),
local_id: 9 }, kind: Path(Resolved(None, Path { span:
src\mods\bass_sound.rs:43:86: 43:89 (#0), res: PrimTy(Uint(U64)),
segments: [PathSegment { ident: u64#0, hir_id: Some(HirId { owner:
DefId(0:710 ~ nwengine[9487]::mods::bass_sound::BASS_ChannelBytes2Seconds),
local_id: 10 }), res: Some(Err), args: None, infer_args: false }] })),
span: src\mods\bass_sound.rs:43:86: 43:89 (#0) }], output: Return(Ty {
hir_id: HirId { owner: DefId(0:710 ~
nwengine[9487]::mods::bass_sound::BASS_ChannelBytes2Seconds),
local_id: 11 }, kind: Path(Resolved(None, Path { span:
src\mods\bass_sound.rs:43:94: 43:97 (#0), res: PrimTy(Float(F64)),
segments: [PathSegment { ident: f64#0, hir_id: Some(HirId { owner:
DefId(0:710 ~ nwengine[9487]::mods::bass_sound::BASS_ChannelBytes2Seconds),
local_id: 12 }), res: Some(Err), args: None, infer_args: false }] })),
span: src\mods\bass_sound.rs:43:94: 43:97 (#0) }), c_variadic: false,
implicit_self: None }, param_names: [#0, #0] }), span:
src\mods\bass_sound.rs:43:55: 43:97 (#0) })], bindings: [],
parenthesized: false, span_ext: src\mods\bass_sound.rs:43:45: 43:98
(#0) }), infer_args: false }] })), span: src\mods\bass_sound.rs:43:39:
43:98 (#0) }), Type(Ty { hir_id: HirId { owner: DefId(0:710 ~
nwengine[9487]::mods::bass_sound::BASS_ChannelBytes2Seconds),
local_id: 15 }, kind: Path(Resolved(None, Path { span:
src\mods\bass_sound.rs:42:1: 42:17 (#262), res: Def(Struct,
DefId(0:703 ~ nwengine[9487]::mods::bass_sound::__StaticInitGeneratorFor_BASS_ChannelBytes2Seconds)),
segments: [PathSegment { ident:
__StaticInitGeneratorFor_BASS_ChannelBytes2Seconds#262, hir_id:
Some(HirId { owner: DefId(0:710 ~
nwengine[9487]::mods::bass_sound::BASS_ChannelBytes2Seconds),
local_id: 16 }), res: Some(Err), args: None, infer_args: false }] })),
span: src\mods\bass_sound.rs:42:1: 42:17 (#262) })], bindings: [],
parenthesized: false, span_ext: src\mods\bass_sound.rs:42:1: 42:17
(#262) }), infer_args: false }] })), span:
src\mods\bass_sound.rs:42:1: 42:17 (#262) }, Not, BodyId { hir_id:
HirId { owner: DefId(0:710 ~
nwengine[9487]::mods::bass_sound::BASS_ChannelBytes2Seconds),
local_id: 47 } }), vis: Spanned { node: Public, span:
src\mods\bass_sound.rs:43:1: 43:4 (#0) }, span:
src\mods\bass_sound.rs:43:1: 44:67 (#0) })

thread 'rustc' panicked at 'Box<dyn Any>',
compiler\rustc_errors\src\lib.rs:1279:9
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a
verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report:
https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.61 (fe5b13d6 2022-05-18)

query stack during panic:
#0 [fn_sig] computing function signature of
`mods::bass_sound::BASS_ChannelBytes2Seconds`
#1 [analysis] running analysis passes on this crate
end of query stack
warning: `nwengine` (lib) generated 14 warnings
error: could not compile `nwengine`; 14 warnings emitted

F:\github projekty\the-killer-bgt\nwengine>

2022-05-25 13:15 GMT+02:00, Alex Macleod ***@***.***>:

**Comment by bobi6666** [comment]
i started backtrace full and there is another result:
stack backtrace:
   0:     0x7ffb9377988f -
<std::sys_common::backtrace::_print::DisplayBacktrace as
core::fmt::Display>::fmt::h50aa8caf753a2b27
   1:     0x7ffb937a4c3a - core::fmt::write::h838fc71521d9a769
   2:     0x7ffb9376c709 - <std::io::IoSliceMut as
core::fmt::Debug>::fmt::h36f954dfa88567a7
   3:     0x7ffb9377ceab - std::panicking::default_hook::h14f77031689d5a65
   4:     0x7ffb9377ca9e - std::panicking::default_hook::h14f77031689d5a65
   5:     0x7ff647b8aa35 - <unknown>
   6:     0x7ffb9377d78a -
std::panicking::rust_panic_with_hook::h093296cdc6b43259
   7:     0x7ffb5a5988b5 -
<rustc_errors[38df458bda2d9087]::diagnostic::StringPart as
core[14ebc1417b592300]::fmt::Debug>::fmt
   8:     0x7ffb5a598489 -
<rustc_errors[38df458bda2d9087]::diagnostic::StringPart as
core[14ebc1417b592300]::fmt::Debug>::fmt
   9:     0x7ffb5a8b4309 -
rustc_query_system[36f3c4afb232c86b]::query::plumbing::incremental_verify_ich_cold
  10:     0x7ffb5a57c319 -
<rustc_errors[38df458bda2d9087]::emitter::FileWithAnnotatedLines as
core[14ebc1417b592300]::fmt::Debug>::fmt
  11:     0x7ffb5a58518a -
<rustc_errors[38df458bda2d9087]::HandlerInner>::emit_diagnostic
  12:     0x7ffb5a5826f2 - <rustc_errors[38df458bda2d9087]::Handler>::bug
  13:     0x7ffb5a33ab53 -
<rustc_middle[f8c5bc87ecf9dc9e]::ty::consts::int::ScalarInt as
core[14ebc1417b592300]::fmt::Display>::fmt
  14:     0x7ffb5a33df7c -
<rustc_middle[f8c5bc87ecf9dc9e]::ty::diagnostics::StaticLifetimeVisitor
as rustc_hir[ff973f7ee110f744]::intravisit::Visitor>::visit_lifetime
  15:     0x7ffb5a8a0918 - rustc_middle[f8c5bc87ecf9dc9e]::util::bug::bug_fmt
  16:     0x7ffb588427f5 -
<rustc_typeck[d01742f453e9ddd4]::collect::AnonConstInParamTyDetector
as rustc_hir[ff973f7ee110f744]::intravisit::Visitor>::visit_anon_const
  17:     0x7ffb593b628b -
<rustc_query_impl[5f7022dda011ac8e]::on_disk_cache::EncodedSourceFileId
as core[14ebc1417b592300]::fmt::Debug>::fmt
  18:     0x7ffb594803c3 -
<rustc_query_impl[5f7022dda011ac8e]::queries::global_backend_features
as rustc_query_system[36f3c4afb232c86b]::query::config::QueryDescription<rustc_query_impl[5f7022dda011ac8e]::plumbing::QueryCtxt>>::describe
  19:     0x7ffb595cb930 -
<rustc_query_impl[5f7022dda011ac8e]::queries::global_backend_features
as rustc_query_system[36f3c4afb232c86b]::query::config::QueryDescription<rustc_query_impl[5f7022dda011ac8e]::plumbing::QueryCtxt>>::describe
  20:     0x7ffb596e6551 -
<rustc_query_impl[5f7022dda011ac8e]::queries::global_backend_features
as rustc_query_system[36f3c4afb232c86b]::query::config::QueryDescription<rustc_query_impl[5f7022dda011ac8e]::plumbing::QueryCtxt>>::describe
  21:     0x7ffb59392f66 -
<rustc_query_impl[5f7022dda011ac8e]::Queries as
rustc_middle[f8c5bc87ecf9dc9e]::ty::query::QueryEngine>::try_mark_green
  22:     0x7ff647bf9c8f - <unknown>
  23:     0x7ff647e5a446 - <unknown>
  24:     0x7ff647bf934e - <unknown>
  25:     0x7ffb59f69263 -
<rustc_lint[e55e866308f56200]::early::EarlyLintPassObjects as
rustc_lint[e55e866308f56200]::passes::EarlyLintPass>::check_pat
  26:     0x7ffb55e2d857 - rustc_interface[897cdb8f2c10f1bf]::passes::analysis
  27:     0x7ffb55e2cd51 - rustc_interface[897cdb8f2c10f1bf]::passes::analysis
  28:     0x7ffb55dd9151 -
rustc_interface[897cdb8f2c10f1bf]::util::commit_date_str
  29:     0x7ffb55e2f164 - rustc_interface[897cdb8f2c10f1bf]::passes::analysis
  30:     0x7ffb55ddabbc -
rustc_interface[897cdb8f2c10f1bf]::util::commit_date_str
  31:     0x7ffb55dd609c -
rustc_interface[897cdb8f2c10f1bf]::util::commit_date_str
  32:     0x7ffb55dd4f56 -
rustc_interface[897cdb8f2c10f1bf]::util::commit_date_str
  33:     0x7ffb55d5eac5 -
<tracing_subscriber[7520e40ba33f8f7e]::util::TryInitError as
core[14ebc1417b592300]::fmt::Display>::fmt
  34:     0x7ffb55d5eeac -
<tracing_subscriber[7520e40ba33f8f7e]::util::TryInitError as
core[14ebc1417b592300]::fmt::Display>::fmt
  35:     0x7ffb55dda2c9 -
rustc_interface[897cdb8f2c10f1bf]::util::commit_date_str
  36:     0x7ffb55d61f0e -
<tracing_subscriber[7520e40ba33f8f7e]::util::TryInitError as
core[14ebc1417b592300]::fmt::Display>::fmt
  37:     0x7ffb55de75c7 - rustc_interface[897cdb8f2c10f1bf]::passes::analysis
  38:     0x7ffb593b776e -
<rustc_query_impl[5f7022dda011ac8e]::on_disk_cache::EncodedSourceFileId
as core[14ebc1417b592300]::fmt::Debug>::fmt
  39:     0x7ffb594997ef -
<rustc_query_impl[5f7022dda011ac8e]::queries::global_backend_features
as rustc_query_system[36f3c4afb232c86b]::query::config::QueryDescription<rustc_query_impl[5f7022dda011ac8e]::plumbing::QueryCtxt>>::describe
  40:     0x7ffb59630d9b -
<rustc_query_impl[5f7022dda011ac8e]::queries::global_backend_features
as rustc_query_system[36f3c4afb232c86b]::query::config::QueryDescription<rustc_query_impl[5f7022dda011ac8e]::plumbing::QueryCtxt>>::describe
  41:     0x7ffb596e6c66 -
<rustc_query_impl[5f7022dda011ac8e]::queries::global_backend_features
as rustc_query_system[36f3c4afb232c86b]::query::config::QueryDescription<rustc_query_impl[5f7022dda011ac8e]::plumbing::QueryCtxt>>::describe
  42:     0x7ffb55c365df -
<chalk_engine[d6f38e9d841939be]::TableIndex>::increment
  43:     0x7ffb55c9c5cd -
<rustc_driver[644f353906beda0e]::Compilation as
core[14ebc1417b592300]::fmt::Debug>::fmt
  44:     0x7ffb55c287b0 -
<rustc_driver[644f353906beda0e]::args::Error as
core[14ebc1417b592300]::fmt::Debug>::fmt
  45:     0x7ffb55cbb390 -
<rustc_driver[644f353906beda0e]::Compilation as
core[14ebc1417b592300]::fmt::Debug>::fmt
  46:     0x7ffb55c29ca7 -
<rustc_driver[644f353906beda0e]::args::Error as
core[14ebc1417b592300]::fmt::Debug>::fmt
  47:     0x7ffb55c98396 -
<rustc_driver[644f353906beda0e]::Compilation as
core[14ebc1417b592300]::fmt::Debug>::fmt
  48:     0x7ffb55c34c68 -
<chalk_engine[d6f38e9d841939be]::TableIndex>::increment
  49:     0x7ffb9378cb4c -
std::sys::windows::thread::Thread::new::h866e729703db88c5
  50:     0x7ffbcba27034 - BaseThreadInitThunk
  51:     0x7ffbcbde2651 - RtlUserThreadStart

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report:
https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.61 (fe5b13d6 2022-05-18)

query stack during panic:
#0 [fn_sig] computing function signature of
`mods::bass_sound::BASS_ChannelBytes2Seconds`
#1 [analysis] running analysis passes on this crate
end of query stack
warning: `nwengine` (lib) generated 13 warnings
error: could not compile `nwengine`; 13 warnings emitted

F:\github projekty\the-killer-bgt\nwengine>

2022-05-25 14:18 GMT+02:00, Peter Kubek ***@***.***>:

**Comment by giraffate** [comment]
Does this happen when executing `cargo check` or `cargo build`? Seeing backtraces, I couldn't find clippy logs.

**Comment by bobi6666** [comment]
no that happens when i try to do cargo clippy or cargo clippy --fix
but with normal building no

2022-05-26 2:12 GMT+02:00, Takayuki Nakata ***@***.***>:

**Comment by bobi6666** [comment]
here is complete example that crashing clippy
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=493836f3a3701e3080bdfb13539816fa
and to your cargo.toml:
libloading = "0.7.3"
static_init = "1.0.2"


2022-05-26 2:31 GMT+02:00, Peter Kubek ***@***.***>:

**Comment by Alexendoo** [comment]
Thanks for that!

Reduced:

```rust
fn f() -> usize { 1 }
static FN: fn() -> usize = f;

fn g() -> usize {
    let res = FN() + 1;
    res
}
```

Output:

```
error: internal compiler error: compiler/rustc_typeck/src/collect.rs:1931:13: unexpected sort of node in fn_sig(): Item(Item { ident: FN#0, def_id: DefId(0:4 ~ temp[70b1]::FN), kind: Static(Ty { hir_id: HirId { owner: DefId(0:4 ~ temp[70b1]::FN), local_id: 3 }, kind: BareFn(BareFnTy { unsafety: Normal, abi: Rust, generic_params: [], decl: FnDecl { inputs: [], output: Return(Ty { hir_id: HirId { owner: DefId(0:4 ~ temp[70b1]::FN), local_id: 1 }, kind: Path(Resolved(None, Path { span: src/lib.rs:2:20: 2:25 (#0), res: PrimTy(Uint(Usize)), segments: [PathSegment { ident: usize#0, hir_id: Some(HirId { owner: DefId(0:4 ~ temp[70b1]::FN), local_id: 2 }), res: Some(Err), args: None, infer_args: false }] })), span: src/lib.rs:2:20: 2:25 (#0) }), c_variadic: false, implicit_self: None }, param_names: [] }), span: src/lib.rs:2:12: 2:25 (#0) }, Not, BodyId { hir_id: HirId { owner: DefId(0:4 ~ temp[70b1]::FN), local_id: 5 } }), span: src/lib.rs:2:1: 2:30 (#0), vis_span: src/lib.rs:2:1: 2:1 (#0) })

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/cd282d7f75da9080fda0f1740a729516e7fbec68/compiler/rustc_errors/src/lib.rs:1335:9
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: std::panic::panic_any::<rustc_errors::ExplicitBug>
   2: <rustc_errors::HandlerInner>::bug::<&alloc::string::String>
   3: <rustc_errors::Handler>::bug::<&alloc::string::String>
   4: rustc_middle::ty::context::tls::with_opt::<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, ()>
   5: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>
   6: rustc_middle::util::bug::bug_fmt
   7: rustc_typeck::collect::fn_sig
   8: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId, rustc_middle::ty::sty::Binder<rustc_middle::ty::sty::FnSig>>
   9: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::ty::sty::Binder<rustc_middle::ty::sty::FnSig>>>
  10: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::fn_sig, rustc_query_impl::plumbing::QueryCtxt>
  11: rustc_middle::ty::query::TyCtxtAt::fn_sig
             at /rustc/cd282d7f75da9080fda0f1740a729516e7fbec68/compiler/rustc_middle/src/ty/query.rs:261:17
  12: rustc_middle::ty::query::<impl rustc_middle::ty::context::TyCtxt>::fn_sig
             at /rustc/cd282d7f75da9080fda0f1740a729516e7fbec68/compiler/rustc_middle/src/ty/query.rs:242:17
  13: <clippy_lints::returns::BorrowVisitor as rustc_hir::intravisit::Visitor>::visit_expr
             at /home/alex/rust/clippy/clippy_lints/src/returns.rs:295:28
  14: rustc_hir::intravisit::walk_expr
             at /rustc/cd282d7f75da9080fda0f1740a729516e7fbec68/compiler/rustc_hir/src/intravisit.rs:1144:13
  15: clippy_lints::returns::last_statement_borrows
             at /home/alex/rust/clippy/clippy_lints/src/returns.rs:279:5
  16: <clippy_lints::returns::Return as rustc_lint::passes::LateLintPass>::check_block
             at /home/alex/rust/clippy/clippy_lints/src/returns.rs:92:17
  17: <rustc_lint::late::LateLintPassObjects as rustc_lint::passes::LateLintPass>::check_block
  18: rustc_hir::intravisit::walk_expr::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  19: rustc_hir::intravisit::walk_body::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  20: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_nested_body
  21: rustc_hir::intravisit::walk_item::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  22: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_nested_item
  23: rustc_lint::late::late_lint_pass_crate::<rustc_lint::late::LateLintPassObjects>
  24: rustc_lint::late::late_lint_crate::<rustc_lint::BuiltinCombinedLateLintPass>
  25: <rustc_session::session::Session>::time::<(), rustc_lint::late::check_crate<rustc_lint::BuiltinCombinedLateLintPass, rustc_interface::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#0}::{closure#0}>
  26: <rustc_session::session::Session>::time::<(), rustc_interface::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}>
  27: <core::panic::unwind_safe::AssertUnwindSafe<rustc_interface::passes::analysis::{closure#5}::{closure#1}> as core::ops::function::FnOnce<()>>::call_once
  28: <rustc_session::session::Session>::time::<(), rustc_interface::passes::analysis::{closure#5}>
  29: rustc_interface::passes::analysis
  30: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  31: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), core::result::Result<(), rustc_errors::ErrorGuaranteed>>>
  32: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
  33: <rustc_interface::passes::QueryContext>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}::{closure#3}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  34: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  35: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  36: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
  37: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.63 (bc4d39e5f 2022-05-26)

query stack during panic:
#0 [fn_sig] computing function signature of `FN`
#1 [analysis] running analysis passes on this crate
end of query stack
```

**Comment by bobi6666** [comment]
did you figure out how clippy can be fixed to avoid this runtime?

2022-05-26 15:13 GMT+02:00, Alex Macleod ***@***.***>:

**Comment by Alexendoo** [comment]
Yeah, you can follow #8896 for details
