### ISSUE TITLE
undocumented_unsafe_blocks doesn't notice safety comment inside a macro

### ISSUE THREAD

**Issue by Ryan1729** [rust-lang/rust-clippy#8868]
### Summary

The `undocumented_unsafe_blocks` lint produces an error even after a safety comment has been added inside a macro. The following example was reduced down from code containing an `assert!`-like macro that checked for errors via an FFI function.

### Lint Name

undocumented_unsafe_blocks

### Reproducer

I tried this code:

```rust
#![deny(clippy::undocumented_unsafe_blocks)]

unsafe fn a() {}

macro_rules! m {
    () => {
        // SAFETY: A good reason
        unsafe { a() }
    };
}

pub fn b() {
    m!();
}
```

I saw this happen:

```
    Checking example v0.1.0 (/home/ryan/code/rust/bug_repros/undocumented_unsafe_blocks/example)
error: unsafe block in macro expansion missing a safety comment
  --> src/lib.rs:8:9
   |
8  |         unsafe { a() }
   |         ^^^^^^^^^^^^^^
...
13 |     m!();
   |     ---- in this macro invocation
   |
note: the lint level is defined here
  --> src/lib.rs:1:9
   |
1  | #![deny(clippy::undocumented_unsafe_blocks)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = help: consider adding a safety comment in the macro definition
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#undocumented_unsafe_blocks
   = note: this error originates in the macro `m` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `example` due to previous error
```
This is exactly the same output as when the safety comment is not there, except the line numbers have changed.

I expected to see this happen:
Since the safety comment (`// SAFETY: A good reason`) has been added in the above example, I expected running `cargo clippy` to produce no errors.

### Version

```text
rustc 1.61.0 (fe5b13d68 2022-05-18)
binary: rustc
commit-hash: fe5b13d681f25ee6474be29d748c65adcd91f69e
commit-date: 2022-05-18
host: x86_64-unknown-linux-gnu
release: 1.61.0
LLVM version: 14.0.0
```

**Comment by Jarcho** [comment]
I can't reproduce this on the playground (uses nightly 2022-05-21). I guess this was fixed already.

**Comment by Ryan1729** [comment]
Just to confirm, I ran `rustup install nightly` and ran `cargo +nightly clippy` on my existing example repo. In that case, the error was in fact gone, so it does seem like this has been fixed already.
