### ISSUE TITLE
`self_named_module_files` warns about dependencies when `CARGO_HOME` is a subdirectory of the project

### ISSUE THREAD

**Issue by abonander** [rust-lang/rust-clippy#8887]
### Summary

When setting up a CI script in Gitlab, I want to save the local Cargo cache between jobs to avoid re-downloading from crates.io every time.

However, Gitlab CI's caching only allows saving directories under the project directory: https://docs.gitlab.com/ee/ci/caching/#how-cache-is-different-from-artifacts

So I set `CARGO_HOME` to `$CI_PROJECT_DIR/.cargo` (where `$CI_PROJECT_DIR` is provided by Gitlab) and then configure the CI jobs to cache that directory by default.

However, this causes the `self_named_module_files` lint to emit lint warnings for my dependencies (turned into errors here because of `#![deny(...)]`):

```
error: `mod.rs` files are required, found `/.cargo/registry/src/github.com-1ecc6299db9ec823/lock_api-0.4.7/src/rwlock.rs`
 --> /builds/<REDACTED>/.cargo/registry/src/github.com-1ecc6299db9ec823/lock_api-0.4.7/src/rwlock.rs:1:1
  |
1 | // Copyright 2016 Amanieu d'Antras
  | ^
  |
note: the lint level is defined here
 --> <REDACTED>/src/lib.rs:2:9
  |
2 | #![deny(clippy::self_named_module_files)]
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = help: move `/.cargo/registry/src/github.com-1ecc6299db9ec823/lock_api-0.4.7/src/rwlock.rs` to `/.cargo/registry/src/github.com-1ecc6299db9ec823/lock_api-0.4.7/src/rwlock/mod.rs`
```

I suspect that the lint is just checking whether a source file's path is a descendant of the project/workspace root instead of ensuring that it is actually part of the local crate.

### Lint Name

self_named_module_files

### Reproducer

This should be possible to reproduce with a simple project created by `cargo new`.

Add to `Cargo.toml`:
```toml
[dependencies]
# The choice of dependency is arbitrary, this one is known to trigger the lint.
# `digest`, `tokio-stream`, `tower`, `bytes` all also trigger the lint.
lock_api = "0.4"
```

`main.rs`
```rust
#![deny(clippy::self_named_module_files)]

// Not sure if the dependency needs to actually be imported to trigger the lint
// as I was getting warnings from transitive dependencies as well.
//
// It probably just has to appear in the crate graph.
use lock_api;
```

Execute `cargo clippy`, setting `CARGO_HOME` to a subdirectory of the project:
```sh
env CARGO_HOME="$(pwd)/.cargo" cargo clippy
```

### Version

```text
rustc 1.61.0 (fe5b13d68 2022-05-18)
binary: rustc
commit-hash: fe5b13d681f25ee6474be29d748c65adcd91f69e
commit-date: 2022-05-18
host: x86_64-unknown-linux-gnu
release: 1.61.0
LLVM version: 14.0.0
```

**Comment by SohumB** [comment]
I'd like to add that this applies to `mod_module_files` too.

**Comment by hehaoqian** [comment]
This bug still exist in 1.69.0
