### ISSUE TITLE
Arithmetic lint

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/rust-clippy#8903]
Are you guys open to include an allow-by-default restricted lint that will warn `+`/`-`/`/`/`*` regardless of the involved type? For example, `num-bigint` (among others) has arithmetic implementations that aren't triggered by `clippy::integer_arithmetic`.

If yes, then I will create a PR. If not, then feel free to close this issue.

**Comment by llogiq** [comment]
This could be a restriction lint, and we may even want to make types to block arithmetic on configurable.

**Comment by c410-f3r** [comment]
Like @llogiq said, types should be configurable. Built-in types that don't panic would then be listed as allowed somehow.

I was thinking about creating an `arithmetic` lint that could suppress `integer_arithmetic` in the long run.
