### ISSUE TITLE
cargo clippy with the --no-deps flag in the nightly version checks the dependencies

### ISSUE THREAD

**Issue by MedzikUser** [rust-lang/rust-clippy#8904]
### Summary

cargo clippy with the --no-deps flag in the nightly version checks dependencies and it should not. 

Check [logs on GitHub Actions](https://github.com/MedzikUser/HomeDisk/runs/6626599020?check_suite_focus=true)

### Reproducer

run `cargo clippy --no-deps` in any project

### Version

```text
/home/runner/.cargo/bin/rustc -V
  rustc 1.63.0-nightly (490324f7b 2022-05-26)
/home/runner/.cargo/bin/cargo -V
  cargo 1.63.0-nightly (39ad1039d 2022-05-25)
/home/runner/.cargo/bin/rustup -V
  rustup 1.24.3 (ce5817a94 2021-05-31)
  info: This is the version for the rustup toolchain manager, not the rustc compiler.
  info: The currently active `rustc` version is `rustc 1.63.0-nightly (490324f7b 2022-05-26)`
```

**Comment by Jarcho** [comment]
Clippy uses `cargo check` which will still run on everything. `--no-deps` just stops clippy from adding it's lints to dependencies.
