### ISSUE TITLE
doc_link_with_quotes false postive for code inside code block

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust-clippy#8961]
### Summary

The `doc_link_with_quotes` lint is documented as:

> Detects the syntax `['foo']` in documentation comments (notice quotes instead of backticks) **outside of code blocks**

However it is incorrectly triggering on code inside of code blocks.

### Lint Name

doc_link_with_quotes

### Reproducer

```rust
/// This is a code block:
///
/// ```
/// let _ = vec!['w', 'a', 't'];
/// ```
fn main() {}
```

```console
error: possible intra-doc link using quotes instead of backticks
 --> src/main.rs:4:1
  |
4 | /// let _ = vec!['w', 'a', 't'];
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `-D clippy::doc-link-with-quotes` implied by `-D clippy::pedantic`
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#doc_link_with_quotes
```

It is indeed a code block though.

![Screenshot from 2022-06-07 00-27-18](https://user-images.githubusercontent.com/1940490/172321239-6d87fec0-230b-4cee-8f46-ba61ecf47947.png)

Mentioning @cameron1024 since this lint was recently added in https://github.com/rust-lang/rust-clippy/pull/8385.

### Version

```text
rustc 1.63.0-nightly (50b00252a 2022-06-06)
binary: rustc
commit-hash: 50b00252aeb77b10db04d65dc9e12ce758def4b5
commit-date: 2022-06-06
host: x86_64-unknown-linux-gnu
release: 1.63.0-nightly
LLVM version: 14.0.5
```

**Comment by cameron1024** [comment]
Hmm this looks pretty bad, I'll have a look at this. I'm pretty new to clippy so I'm not sure how long it will take 😅

**Comment by cameron1024** [comment]
Hmm this looks pretty bad, I'll have a look at this. I'm pretty new to clippy though so I'm not sure how long it will take 😅

**Comment by tamaroning** [comment]
@cameron1024 
Hi, this lint seems not to deal with code blocks (` ``` ... ``` `) for now.
You should add `in_code_block: bool` field  to `DocLinkWithQuotes` struct and a logic which change its value when bumping into ` ``` `. (do not forget to add tests for it)
(See https://github.com/rust-lang/rust-clippy/blob/master/book/src/development/adding_lints.md#adding-configuration-to-a-lint)

If you do not tackle with this, it is ok and I am going to assign this to me😀

**Comment by Alexendoo** [comment]
`doc.rs` contains code that reassembles + parses markdown from doc comments, the lint could be down by replacing `fake_broken_link_callback` with a closure that checks if the link is enclosed in `'`. That would also avoid any weird behaviour with backticks appearing in code blocks

https://github.com/rust-lang/rust-clippy/blob/b3c94c0828c3746437304e8bc26547486c7a5699/clippy_lints/src/doc.rs#L470-L473

**Comment by ikopysov** [comment]
Sorry, came here because  #9321 tagged as "good-first-issue" but this markdown parser seems too complex for me to understand how it should be implemented.
Maybe it was tagged as such with first change in ming (ignoring everything in the ``` code block), but with parser I don't believe it's actually good issue to start with.

**Comment by Alexendoo** [comment]
That's fair, I'll close that one as a duplicate

**Comment by llogiq** [comment]
I've written some of the code in that module, I can take it.

@rustbot claim
