### ISSUE TITLE
derive_partial_eq_without_eq triger for types that can't implement Eq

### ISSUE THREAD

**Issue by zeenix** [rust-lang/rust-clippy#8970]
### Summary

On [this struct](https://gitlab.freedesktop.org/dbus/zbus/-/blob/5e7968fb21a4cf468a86d16c801437d41c65a86a/zvariant/src/array.rs#L18), I get a warning:

```
warning: you are deriving `PartialEq` and can implement `Eq`
   --> zvariant/src/array.rs:261:24
    |
261 | #[derive(Debug, Clone, PartialEq)]
    |                        ^^^^^^^^^ help: consider deriving `Eq` as well: `PartialEq, Eq`
    |
    = note: `#[warn(clippy::derive_partial_eq_without_eq)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq
```
Now if I add `Eq` on this `Array` struct, I've to also add it on the[ `Value` enum](https://gitlab.freedesktop.org/dbus/zbus/-/blob/5e7968fb21a4cf468a86d16c801437d41c65a86a/zvariant/src/value.rs#L73) but that can't derive `Eq` because [it contains an `f64`](https://gitlab.freedesktop.org/dbus/zbus/-/blob/5e7968fb21a4cf468a86d16c801437d41c65a86a/zvariant/src/value.rs#L84) which doesn't and can't implement `Eq`.

### Lint Name

derive_partial_eq_without_eq

### Reproducer

Just run ` cargo +nightly clippy` in the repo.

### Version

```text
cargo 1.63.0-nightly (38472bc19 2022-05-31)
```

**Comment by Jarcho** [comment]
Does this still occur on the latest nightly? I haven't been able to get it on the playground.

**Comment by zeenix** [comment]
> Does this still occur on the latest nightly? I haven't been able to get it on the playground.

Actually you're right. I can't reproduce anymore. Thanks.
