### ISSUE TITLE
New lint: ref_pattern, for disallowing the ref keyword

### ISSUE THREAD

**Issue by jplatte** [rust-lang/rust-clippy#9010]
### What it does

I would like to have a lint that fires on any use of the `ref` keyword.

### Lint Name

ref_pattern

### Category

restriction

### Advantage

Code that doesn't use it is easier to read for newcomers since they're unlikely to be aware of what it does.

### Example

```rust
if let Some(ref foo) = *rwlock.read().unwrap() {}
```

Could be written as:

```rust
if let Some(foo) = &*rwlock.read().unwrap() {}
```

**Comment by chetankokil** [comment]
can i work on this ?
