### ISSUE TITLE
Find unused/irelevant clippy annotations

### ISSUE THREAD

**Issue by SylvainDe** [rust-lang/rust-clippy#9020]
### What it does

Here is the use case:

1. I define an entity which causes a defect found by clippy
2. I add a temporary annotation to to be able to run clippy and ensure that new defects are quickly found and fixed
3. I fix the original defect and I completely forget about remove the clippy annotation

-> The clippy annotation is useless but on top of that:

- can be confusing
- can hide issues added to the code later on

### Lint Name

useless-clippy-annotation

### Category

pedantic

### Advantage

Get rid of useless clippy annotations

### Drawbacks

I do not know the clippy internals and thus, I have no idea if this can be easy to implement

### Example

I tend to have the problem with "#[allow(clippy::missing_const_for_fn)]" which I use when prototyping and then forget to remove.

**Comment by Jarcho** [comment]
This is being added to rust as `#[expect(...)]` rust-lang/rust#54503

**Comment by SylvainDe** [comment]
Great! Thanks for the quick answer :)

**Comment by SylvainDe** [comment]
Duplicate of:

- https://github.com/rust-lang/rust-clippy/issues/4636
- https://github.com/rust-lang/rust-clippy/issues/3122
