### ISSUE TITLE
want to lint `binary_heap` in `manual_retain` when API is stabilized

### ISSUE THREAD

**Issue by kyoto7250** [rust-lang/rust-clippy#9059]
### Description

I created [manual_retain](https://github.com/rust-lang/rust-clippy/pull/8972), but  `binary_heap_retain` method is nightly API now, so we do not lint.

When this API is stabilized, we should lint `binary_heap_retain` as well.
It will work if we rewrite the process a little and add some tests.

If you have any questions, please ask me.

ref:
- [code](https://github.com/rust-lang/rust-clippy/blob/master/clippy_lints/src/manual_retain.rs)
- [tests](https://github.com/rust-lang/rust-clippy/blob/d85539571ffa3befbbdd6b2933a79d31c28b42a0/tests/ui/manual_retain.rs#L27)
- [tracking issue](https://github.com/rust-lang/rust/issues/71503)

### Additional Labels

@rustbot label +C-enhancement +good-first-issue

**Comment by unvalley** [comment]
It seems that `binary_heap_retain` API is stabilized in [the PR](https://github.com/rust-lang/rust/pull/109701) (but not shipped yet). I'm interested in working on this.
