### ISSUE TITLE
More lints from 1.62 with an incorrect "added in" version

### ISSUE THREAD

**Issue by yoav-lavi** [rust-lang/rust-clippy#9088]
This is a continuation of https://github.com/rust-lang/rust-clippy/issues/9081 (cc @xFrednet)

I'm on mobile so hopefully this comes out formatted properly.

The following lints from `1.62` have an incorrect "added in" version:

- [cast_abs_to_unsigned](https://rust-lang.github.io/rust-clippy/master/index.html#cast_abs_to_unsigned)
- [err_expect](https://rust-lang.github.io/rust-clippy/master/index.html#err_expect)
- [crate_in_macro_def](https://rust-lang.github.io/rust-clippy/master/index.html#crate_in_macro_def)
- [needless_option_take](https://rust-lang.github.io/rust-clippy/master/index.html#needless_option_take)
- [is_digit_ascii_radix](https://rust-lang.github.io/rust-clippy/master/index.html#is_digit_ascii_radix)
- [await_holding_invalid_type](https://rust-lang.github.io/rust-clippy/master/index.html#await_holding_invalid_type) - this one says `1.49` haha
- [empty_drop](https://rust-lang.github.io/rust-clippy/master/index.html#empty_drop)
- [drop_non_drop](https://rust-lang.github.io/rust-clippy/master/index.html#drop_non_drop)
- [forget_non_drop](https://rust-lang.github.io/rust-clippy/master/index.html#forget_non_drop)

Hopefully this is helpful!

**Comment by xFrednet** [comment]
This is very helpful. I guess that I'll add reviewing this as a part of writing the changelog :sweat_smile:. I'll fix these tomorrow if nobody else got to it beforehand
