### ISSUE TITLE
clippy.toml is not taken into account if running `cargo build` from a subdirectory

### ISSUE THREAD

**Issue by JohanLorenzo** [rust-lang/rust-clippy#909]
## Steps to reproduce
1. `git clone https://github.com/JohanLorenzo/clippy-toml-bug.git`
2. `cd clippy-toml-bug/foo` . Please note we're in the subdirectory "foo"
3. `cargo build` => Build fails because `MyIdent` is not between ticks
4. `cd .. && cargo build` => Build passes, because `MyIdent` is [whitelisted in clippy.toml](https://github.com/JohanLorenzo/clippy-toml-bug/blob/master/clippy.toml)
## Potential cause

I'm not too sure. It seems clippy.toml is [not prefixed with the project path](https://github.com/Manishearth/rust-clippy/blob/855b292cda017fe47674725b2866ba760fed1f67/src/lib.rs#L275). What do you all think?

**Comment by mcarton** [comment]
I did not even realize you could `cargo build` from a subdirectory :flushed: 
I’m unsure whether cargo exports the path to the crate root/path to its `Cargo.toml`. Anyone?

**Comment by mcarton** [comment]
Ah, looks like it’s `CARGO_MANIFEST_DIR`.

**Comment by mcarton** [comment]
So cargo just searches for a `Cargo.toml` file in the cwd and its parents recursively. We could do the same with `clippy.toml`, or we could do that to search for the directory of the `Cargo.toml` file and check whether there is a `clippy.toml` file there. The only difference would be if one has a subdirectory with a “subcrate”, should the root `clippy.toml` apply to that too?

**Comment by mcarton** [comment]
(Thanks for the really nice “Steps to reproduce” BTW :smile:)

**Comment by JohanLorenzo** [comment]
Thanks for the fast investigation!

I believe adopting the same behavior than `cargo & Cargo.toml` would make sense. So, I'd go with "find `Cargo.toml` and see if there's a `clippy.toml` there".

One issue I can see: If a rule applies to both the main crate and the sub one, you'd need to create 2 `clippy.toml`s with that same rule. We could avoid that by importing a one `clippy.toml` from another. What's your take on this, @mcarton ?

(My pleasure! :smiley:)

**Comment by DemiMarie** [comment]
Can we just use `CARGO_MANIFEST_DIR`?

**Comment by oli-obk** [comment]
@Arnavion did your changes fix this, too?

**Comment by Arnavion** [comment]
I doubt it. I did not do anything for `clippy.toml`, and it seems to be in different code path from what I changed.

**Comment by Alexendoo** [comment]
This has long been fixed
