### ISSUE TITLE
Non standard trailing commas in vscode tasks

### ISSUE THREAD

**Issue by Serial-ATA** [rust-lang/rust-clippy#9108]
### Description

The [vscode tasks file](https://github.com/rust-lang/rust-clippy/blob/master/util/etc/vscode-tasks.json) has trailing commas, which are not allowed by the JSON standard.

### Version

```text
rustc 1.64.0-nightly (f2d93935f 2022-07-02)
binary: rustc
commit-hash: f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3
commit-date: 2022-07-02
host: x86_64-unknown-linux-gnu
release: 1.64.0-nightly
LLVM version: 14.0.6
```

### Additional Labels

@rustbot label +good-first-issue

**Comment by Alexendoo** [comment]
It won't hurt anything to remove them, but vscode's configuration/task/etc files aren't required to be standard JSON. The files also typically contain comments for example

**Comment by Serial-ATA** [comment]
@Alexendoo I just make issues for small things like this to get new contributors interested 😄.
