### ISSUE TITLE
Warn on redundant / needless type annotations

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/rust-clippy#9155]
### What it does

Warns about needless / redundant type annotations.

### Lint Name

redundant_type_annotation

### Category

style, pedantic

### Advantage

Code is more idiomatic, shorter, and easier to modify.

### Drawbacks

Types may be added by some novice Rust developers as hints to help remember what type is present.

### Example

```rust
let foo: String = String::new();
```

Could be written as:

```rust
let foo = String::new();
```

**Comment by smoelius** [comment]
Related: https://github.com/rust-lang/rust-clippy/issues/7081

**Comment by SoryRawyer** [comment]
hi folks, is this issue ready to be picked up? I was thinking of looking into this issue as my first opportunity to cross the clippy user/clippy contributor barrier but before I do I wanted to see (1) if I'd be stepping on anyone's toes, (2) if there were any outstanding questions about this issue, and (3) if you all had any tips for where to look to get started. thanks!

**Comment by llogiq** [comment]
Just comment `<at>`rustbot claim, but with the `<at>` replaced by @ to claim the issue.

If you are unsure how to proceed, feel free to comment your questions on the issue or in the clippy channel on the rust-lang zulip.

**Comment by llogiq** [comment]
As for open questions, I'd suggest picking the `pedantic` lint group first, and start with linting on (method) calls with a non-generic return type.

**Comment by paul-ohl** [comment]
Hi everyone!

If I succeed, this will be my first contribution to any opensource software, so hopefully it goes well!

**Comment by paul-ohl** [comment]
I am sorry for the amount of time this issue is taking me, but I think I'm on the right track, and I'm still working on it!

**Comment by paul-ohl** [comment]
It seems pretty logical to me that this lint should also flag the use of redundant type annotations in the case of a `struct`, but I want to make sure, is it the case? example:
```rust
let a_struct: A = A;
let b_struct: B = B::new();
```

**Comment by paul-ohl** [comment]
Actually, now that I think about it, when is it useful to actually have the type annotation? Because it feels like it's always redundant, except maybe for numbers? But even then it could be considered redundant. So is this what I should check for? Or am I missing something?

**Comment by shepmaster** [comment]
Effectively, I'd expect that the lint would have the same behavior (but likely a vastly different implementation) as removing the type annotation and then seeing if the code still compiles. I think that `Iterator::collect` is a key example:

```rust
use std::iter;

fn main() {
    let type_required: Vec<()> = iter::once(()).collect();
    dbg!(type_required);

    let type_not_required: Vec<()> = iter::once(()).collect();
    usage(type_not_required);
}

fn usage(v: Vec<()>) {
    dbg!(v);
}
```

**Comment by paul-ohl** [comment]
I'm very sorry, but I think this is not for me.

**Comment by AlessioC31** [comment]
Ok I managed to get it to work somehow, for now it lints on function calls with non generic types.
Commit: https://github.com/AlessioC31/rust-clippy/commit/a9674740ed55e9a622d148e92926e4118048cfcd

Do you think that I could add more test cases? (As it's my first lint I'm not 100% of the assumptions I'm doing when checking the types)
Maybe there's a less cumbersome way to do it? :D

Thanks!
