### ISSUE TITLE
Use cube root function lint

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust-clippy#9201]
### What it does

The lint suggest to replace a FP::powf() call with a different method call.

### Lint Name

use_cube_root_function

### Category

perf

### Advantage

It's more precise, shorter and simpler.

### Drawbacks

None, I think.

### Example

```rust
#![warn(clippy::all)]
#![warn(clippy::nursery)]
#![warn(clippy::pedantic)]
fn main() {
    println!("{}", 1.5_f64.powf(1.0 / 3.0));
}
```

Could be written as:

```rust
#![warn(clippy::all)]
#![warn(clippy::nursery)]
#![warn(clippy::pedantic)]
fn main() {
    println!("{}", 1.5_f64.cbrt());
}
```
Also note that they output slightly different results. cbrt is more precise.

**Comment by nerdypepper** [comment]
this is already implemented in the `imprecise_flops` lint:

```rust
#![warn(clippy::nursery)]

fn main() {
    let x = 3f64;
    let _ = x.powf(1.0 / 3.0);
}
```

however, the lint does not seem to fire on:

```rust
#![warn(clippy::imprecise_flops)]

fn main() {
    let _ = 1.5_f64.powf(1.0 / 3.0);
}
```

which seems to be a separate issue.
