### ISSUE TITLE
Will not run and panicks on multiple [[bin]] sections in Cargo.toml without --bin flag

### ISSUE THREAD

**Issue by vadixidav** [rust-lang/rust-clippy#932]
Running cargo clippy without a --bin <name> parameter results in clippy producing this error and panicking (some stuff omitted):

```
$ cargo clippy               
error: extra arguments to `rustc` can only be passed to one target, consider filtering
the package by passing e.g. `--lib` or `--bin NAME` to specify a single target
thread '<main>' panicked at 'cargo rustc failed', /.../master/src/lib.rs:131
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Sadly, I cannot use clippy with atom's rust-linter unless it can lint all the binaries in the Cargo.toml. Is this something that should be added?

**Comment by oli-obk** [comment]
I think this should work now
