### ISSUE TITLE
Remove all `if_chain!` macros

### ISSUE THREAD

**Issue by nyurik** [rust-lang/rust-clippy#9353]
### Description

Current Clippy code has a lot of legacy `if_chain!` macros even though the nightly [if let chains](https://rust-lang.github.io/rfcs/2497-if-let-chains.html) is already in use. I would like to remove all `if_chain!` macro usage, replacing it with the regular if statement, unless of course there is any reason to avoid that?

One thing to note is that `cargo fmt` still hasn't been decided (see [rfc](https://github.com/rust-dev-tools/fmt-rfcs/issues/169)) on how to handle it, and doesn't seem likely to be decided soon. This is not a blocker, as the code can always be reformatted later.

#### Possible Lint?
P.S. I just realized that this might be a good automated lint because it would be useful to other existing code as well. See #9354

**Comment by schubart** [comment]
`#[clippy::author]` should probably also be updated to produce if let chains instead of if_chain!.

This utility (recommended by the [Clippy Book](https://doc.rust-lang.org/nightly/clippy/development/adding_lints.html#author-lint)) currently produces code that uses `if_chain!`, so new lint developers are still being steered towards this old style.

**Comment by xFrednet** [comment]
There have been multiple discussions about it on Zulip and in PRs (See https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/removing.20if_chain.20dependency/near/292061902). The consensus is, that we want to move to `if let chains` but until rustfmt supports their formatting we'll not convert our codebase. There are already some tools to automatically migrate from `if_chain!` to let chains.

Updating the documentation is a good point :)
