### ISSUE TITLE
Running cargo-clippy directly or switching toolchains breaks dynamic linking

### ISSUE THREAD

**Issue by brson** [rust-lang/rust-clippy#937]
Because clippy dynamically links to rustc it needs to be able to find the rustc libraries at runtime. When invoking a subcommand, cargo does set the environment so that anything in sysroot can be found, but that doesn't apply when running `cargo-clippy`.

Possibly worse still, when the active toolchain changes, clippy will not be able to find the dynamic libraries. So after installing `cargo-clippy`, the next time somebody runs `rustup update nightly` clippy will be dead.

**Comment by llogiq** [comment]
Yeah, that's a problem. Would it be possible to bind clippy to an installed nightly, so that rustup reinstalls it when the nightly changes? Or add clippy as an optional part of the toolchain?

**Comment by cyplo** [comment]
Not sure if this is still an issue ?

**Comment by oli-obk** [comment]
Still an issue for self-built installs, but hese are funky anyway
