### ISSUE TITLE
Lint `map.iter().map(|(_,v)| v)`

### ISSUE THREAD

**Issue by hotate29** [rust-lang/rust-clippy#9376]
### What it does

Warning to iterator operations that are equivalent to `.keys()` and `.values()`.

Similar lint: https://rust-lang.github.io/rust-clippy/stable/index.html#for_kv_map

### Lint Name

iter_kv_map

### Category

style

### Advantage

Simpler and readable than the original code.

### Example

```rust
let map = HashMap::new();

let keys = map.iter().map(|(key, _)| key).collect::<Vec<_>>();
let values = map.iter().map(|(_, value)| value).collect::<Vec<_>>();
```

Could be written as:

```rust
let map = HashMap::new();

let keys = map.keys().collect::<Vec<_>>();
let values = map.values().collect::<Vec<_>>();
```

**Comment by DidiBear** [comment]
Just mentioning that the lint also works when the `key` or `value` is used to create another value.

For example, these two lines are equivalent:
```rs
map.iter().map(|(key, _)| key.to_uppercase());

map.keys().map(|key| key.to_uppercase());
```
