### ISSUE TITLE
Add lint `IMPLICIT_SATURATING_ADD`

### ISSUE THREAD

**Issue by alex-semenyuk** [rust-lang/rust-clippy#9393]
### What it does

Add lint similar to `IMPLICIT_SATURATING_SUB`, but for `ADD`. So it will be `IMPLICIT_SATURATING_ADD`

### Lint Name

IMPLICIT_SATURATING_ADD

### Category

pedantic

### Example

```rust
#![warn(clippy::implicit_saturating_add)]

fn main() {
    let mut i: u32 = 3;

    if i != MAX {
        i += 1;
    }
    println!("{}", i);
}

```

Could be written as:

```rust
#![warn(clippy::implicit_saturating_add)]

fn main() {
    let mut i: u32 = 3;

    if i != MAX {
        i = i.saturating_add(1);
    }
    println!("{}", i);
}

```

**Comment by Jarcho** [comment]
I'm assume you mean `if i !=MAX { i += 1 }` -> `i = i.saturating_add(1)`.
