### ISSUE TITLE
unnecessary iter()

### ISSUE THREAD

**Issue by mimoo** [rust-lang/rust-clippy#9442]
### What it does

I have a lot of these in the current codebase I'm working in:

```rust
for x in thing.iter() { /* ... */ }
```

and pretty much all of them could be replaced with:

```rust
for x in &thing { /* ... */ }
```

the same might be true for `into_iter()`

### Lint Name

unnecessary_iter

### Category

style

### Advantage

- I think this works because the types in what I'm seeing mostly implement `IntoIter`? So if they don't implement it perhaps it wouldn't work?

### Drawbacks

- some types might not implement

**Comment by giraffate** [comment]
Does it mean the [`explicit_iter_loop`](https://rust-lang.github.io/rust-clippy/master/index.html#explicit_iter_loop) lint?

**Comment by mimoo** [comment]
ah yes it does seem like it!
