### ISSUE TITLE
[regression] Some format expressions no longer parsed by FormatArgsExpn::parse

### ISSUE THREAD

**Issue by nyurik** [rust-lang/rust-clippy#9468]
### Summary

After #9458, some complex format expressions no longer return a value from `FormatArgsExpn::parse(...)`.

### Reproducer

To test, add this to [tests/ui/explicit_write.rs](https://github.com/rust-lang/rust-clippy/blob/master/tests/ui/explicit_write.rs) (e.g. around line 39).

```rust
        let val = 1;
        let width = 2;
        writeln!(std::io::stderr(), "{:w$}", val, w = width).unwrap();
```

I expected it to produce a suggestion `eprintln!("{:w$}", val, w = width);`, but instead it now silently ignores the above.  Reverting 1b245e7e0e83d387ab9d2cc7a157b081ba5d0ef2 and re-testing starts showing the expected suggestion.

### Version

```text
rustc 1.65.0-nightly (c2804e6ec 2022-09-07)
binary: rustc
commit-hash: c2804e6ec2c29a5c7368600ea173b890e2655c3d
commit-date: 2022-09-07
host: x86_64-unknown-linux-gnu
release: 1.65.0-nightly
LLVM version: 15.0.0
```

**Comment by giraffate** [comment]
Nice catch, thanks!
