### ISSUE TITLE
Suggest usage of `Ord::clamp`, `f32::clamp`, and `f64::clamp` to simplify code

### ISSUE THREAD

**Issue by Xaeroxe** [rust-lang/rust-clippy#9477]
### What it does

Identifies good opportunities for a `clamp` function from `std` or `core`, and suggests using it.

`clamp` functions

[`f32::clamp`](https://doc.rust-lang.org/std/primitive.f32.html#method.clamp)
[`f64::clamp`](https://doc.rust-lang.org/std/primitive.f64.html#method.clamp)
[`Ord::clamp`](https://doc.rust-lang.org/std/cmp/trait.Ord.html#method.clamp)

### Lint Name

clamping_without_clamp

### Category

complexity

### Advantage

It's much shorter and easier to read, also doesn't use any control flow.

### Drawbacks

The clamp functions panic in some circumstances which the original patterns will merely malfunction on. Namely, `Ord` types will panic if `max < min` and the floating point functions will additionally  panic if `min.is_nan()` or `max.is_nan()`. Some may consider this a perk, but I'm listing it as a drawback because it may introduce panics where there weren't any before.

### Example

```rust
if input > max {
    max
}
else if input < min {
    min
} else {
    input
}
```

```rust
input.max(min).min(max)
```

```rust
match input {
    input if input > max => max,
    input if input < min => min,
    input => input,
}
```

Could all be written as:

```rust
input.clamp(min, max)
```

**Comment by Xaeroxe** [comment]
Another clamp anti-pattern

```rust
let mut x = input;
if x < min { x = min; }
if x > max { x = max; }
```

Should be

```rust
let x = input.clamp(min, max);
```

**Comment by kylecarow** [comment]
Another anti-patten exists in chained min/max calls:

```rust
input.min(max).max(min);
```

and

```rust
input.max(min).min(max);
```

Should both be
```rust
input.clamp(min, max);
```
