### ISSUE TITLE
`std_instead_of_core` always lint `std::error::Error` 

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/rust-clippy#9515]
```rust
#[deny(clippy::std_instead_of_core)]

fn _foo() -> impl std::error::Error { // Error!
    std::env::VarError::NotPresent
}
```

The same behaviour does not happen with other `std` structures.

```rust
#[deny(clippy::std_instead_of_core)]

fn _foo() -> std::env::VarError { // OK !
    std::env::VarError::NotPresent
}
```

**Comment by Alexendoo** [comment]
`std::error::Error` is a re-export of `core::error::Error` now so that'll be why it's linting, however you can't actually use `core::error::Error` without `#![feature(error_in_core)]` so we'd definitely want to handle that somehow
