### ISSUE TITLE
result_large_err include largest enum variant

### ISSUE THREAD

**Issue by andrewgazelka** [rust-lang/rust-clippy#9538]
### What it does

Right now `clippy::result_large_err` returns something along the following lines

```text
error: the `Err`-variant returned from this function is very large
  --> maps/src/geom.rs:11:54
   |
11 | pub fn func_name(a: f64) -> Result<f64, Error> {
   |                                                    ^^^^^^^^^^^^^^^^^^ the `Err`-variant is at least 152 bytes
   |
```

However, it does not specify which variant of `Error` contributes to the large size. This can make finding the variant to include Box'd fields annoying.

### Advantage

- Improves code refactoring speed

### Drawbacks

- A larger error message

**Comment by teor2345** [comment]
I'm pretty sure the large enum variant lint already does this - so they could re-use the same code.

**Comment by giraffate** [comment]
Could you provide the reproduction on the playground?
