### ISSUE TITLE
`arithmetic_side_effects` misses `T / integral`, `T * float` and similar

### ISSUE THREAD

**Issue by Alexendoo** [rust-lang/rust-clippy#9544]
### Summary

`has_valid_op` doesn't check that the other side of the operation is also integral. There's a similar issue for types present in `HARD_CODED_ALLOWED`

cc @c410-f3r

### Lint Name

arithmetic_side_effects

### Reproducer

The following panics at runtime but isn't linted [(playground)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=03993e2273a32c9b0e8f6e0e152ea5ae)

```rust
#![warn(clippy::arithmetic_side_effects)]

fn main() {
    let c = num_rational::Ratio::new(1u8, 128u8);
    let _ = c / 2;
}
```

For the `HARD_CODED_ALLOWED` side [(playground)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b25ce350ca18191f5c7793d1ac20a4ad)

```rust
#![warn(clippy::arithmetic_side_effects)]

fn main() {
    let c = ordered_float::NotNan::new(0f64).unwrap();
    let _ = c * f64::INFINITY;
}
```

**Comment by c410-f3r** [comment]
I will investigate these use-cases. Thanks @Alexendoo
