### ISSUE TITLE
Status of rustc_tools_util?

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust-clippy#9553]
vergen is causing some licensing pain in Miri, so I checked what clippy does to determine the git commit for version information. Looks like clippy has an in-tree crate `rustc_tools_util` for that. An old version of that crate exists on crates.io but clippy uses a path dependency of a more up-to-date version of that crate.

Would it make sense for clippy and Miri to share that crate? clippy should then probably fetch the dependency from crates.io rather than using a path dependency, so that the dependency is actually shared in the rustc workspace.

**Comment by matthiaskrgr** [comment]
I could do another clippy repo -> cratess.io sync (aka release) and we could switch clippy to also use the crates-io version while keeping the source in tree, I guess?

**Comment by RalfJung** [comment]
Yeah I think that would be good. :)

**Comment by matthiaskrgr** [comment]
rustc_tools_util 0.2.1 is now on crates-io :tada:

**Comment by RalfJung** [comment]
Thanks. :) it is being bumped in Miri [as we speak](https://github.com/rust-lang/miri/pull/2578).

**Comment by matthiaskrgr** [comment]
we might still need a clippy sync to get rid of the path dep in the rustc repo though

**Comment by RalfJung** [comment]
Yeah and a Miri sync needs to happen for Miri to even start using it. Short-term there might be some duplication but in the near future, after they both got synced, we'll have this code shared. :)
