### ISSUE TITLE
avoid matching on a lock guard

### ISSUE THREAD

**Issue by nappa85** [rust-lang/rust-clippy#9597]
### What it does

I think something similar already exists for a match that holds an await value
Matching on a lock guard and trying to use the lock inside the match results in a deadlock

### Lint Name

match_holding_lock_guard

### Category

suspicious

### Advantage

- avoid deadlocks, difficult to debug

### Drawbacks

I understand that the main difficulty for clippy could be knowing what a guard is, maybe a notation on the guard struct is needed, something like `#[blocks]` or `#[holds_block]`

### Example

```
let my_lock = std::sync::Mutex::new(0);
match *my_lock.lock().unwrap() {
  0 => {
    let mut value = my_lock.lock().unwrap();
    *value = 1;
  },
  _ => unreachable!(),
}
```

Could be written as:

```
let my_lock = std::sync::Mutex::new(0);
let val = *my_lock.lock().unwrap();
match val {
  0 => {
    let mut value = my_lock.lock().unwrap();
    *value = 1;
  },
  _ => unreachable!(),
}
```

**Comment by lukaslueg** [comment]
Similar to `IF_LET_MUTEX`

**Comment by swarnimarun** [comment]
actually now that I think about it we may already have something similar,
https://rust-lang.github.io/rust-clippy/master/index.html#significant_drop_in_scrutinee

**Comment by nappa85** [comment]
> actually now that I think about it we may already have something similar, https://rust-lang.github.io/rust-clippy/master/index.html#significant_drop_in_scrutinee

That's exactly what I was looking for
Thank you
