### ISSUE TITLE
Suggest use of captured format args

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rust-clippy#9618]
### What it does

In edition 2021 `format!` and related macros have a new ability to use implicitly captured variables instead of positional arguments: `format!("hello {name}");`

### Lint Name

format_uncaptured_variables

### Category

pedantic

### Advantage

A lint with an auto-fix could help migrate codebases to the new style. Opposite of #5404.

### Drawbacks

`format!` with a mix of captured and positional args may be confusing:

```rust
format("{} {second}", x.first);
```

so the lint could be limited to cases where all args can be captured.

### Example

```rust
format!("hello {:^5}", name);
```

Could be written as:

```rust
format!("hello {name:^5}");
```

**Comment by kraktus** [comment]
Already implemented on nightly https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args
