### ISSUE TITLE
From over Into for external crate types which is impossible to implement

### ISSUE THREAD

**Issue by Firstyear** [rust-lang/rust-clippy#9638]
### Summary

Clippy lints stating that from over into is preferred is impossible to satisfy. You can't implement a trait on a struct from an external crate. 

Also common to hit with should_implement_trait.

Clippy should not recommend From over Into or Should implement trait when the target type is an out of crate type which is impossible to compile for. 

### Lint Name

from_over_into

### Reproducer

```
error: an implementation of `From` is preferred since it gives you `Into<_>` for free where the reverse isn't true
   --> webauthn-rs-proto/src/extensions.rs:186:1
    |
186 | impl Into<js_sys::Object> for &RequestAuthenticationExtensions {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: consider to implement `From<&extensions::RequestAuthenticationExtensions>` instead
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#from_over_into

```

### Version

```text
rustc 1.64.0 (a55dd71d5 2022-09-19)
binary: rustc
commit-hash: a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52
commit-date: 2022-09-19
host: aarch64-apple-darwin
release: 1.64.0
LLVM version: 14.0.6
```

**Comment by kraktus** [comment]
You can implement `From<LocalStruct> for ExternalStruct`, as `From<LocalStruct>` is considered an internal trait. This behavior could be édition gated though I don’t remember the details

**Comment by Firstyear** [comment]
@kraktus It doesn't work with FromIterator though I think?

**Comment by Alexendoo** [comment]
Do you have an example of a `should_implement_trait` case that would fail to compile?

For `from_over_into` we could emit a note saying it's fine to do `From<Local> for Foreign` if a foreign type is involved, as this is a very common source of confusion

**Comment by Firstyear** [comment]
@Alexendoo A more complex example, but https://github.com/kanidm/kanidm/blob/master/kanidmd/lib/src/valueset/spn.rs#L28 . tl;dr you can't do fromIterator on a tuple of strings because tuple is always foreign.

It's worth saying the note doesn't really help here because clippy will still lint and say "do this!" when clippy shouldn't be suggesting something that is impossible in the first place I think. The crux of this issue is clippy shouldn't be telling users to implement traits on things that are impossible to satisfy :) 

Thanks!

**Comment by Alexendoo** [comment]
The note would be only on the From case, as `impl From<&RequestAuthenticationExtensions> for js_sys::Object` is valid

That `from_iter` example is a bug, it would be applicable if it were `-> Self` but as it's `-> Option<...>` both sides of the impl are foreign so we need to check for that

**Comment by Alexendoo** [comment]
Added the `from_over_into` note as part of #9649, and we'll track the `should_implement_trait` signature incompatibility in #5612. Thanks!
