### ISSUE TITLE
Add warning for &array[..].

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang/rust-clippy#965]
It's the same as `&array`.

**Comment by oli-obk** [comment]
Sadly it's not. There are cases where inference doesn't work yet. The only one i can think off right now is matching with slice patterns, but I think there are more.

**Comment by Yamakaky** [comment]
Do you have a code example?

**Comment by mcarton** [comment]
@Yamakaky:

```rust
#![feature(slice_patterns)]

fn main() {
    let foo = [1, 2, 3];

    match &foo[..] {
        [1, 2, ..] => {
            println!("3!");
        }
        _ => {
            println!(":(");
        }
    }
}
```

This won’t compile without `[..]` because `&foo` is of type `&[u32; 3]` and won’t coerce to `&[u32]` automatically. On the other hand `&foo[..]` is `&[u32]`.

**Comment by oli-obk** [comment]
```rust
match &vec![] {
    [] => {},
    _ => {},
}
```

**Comment by Yamakaky** [comment]
@mcarton oh, ok.
@oli-obk ??

**Comment by llogiq** [comment]
oli-obk's example uses a Vec instead of an array, but otherwise shows the same concept: A `Vec` is not a slice.

**Comment by Yamakaky** [comment]
Ok, sorry, I'm not familiar to the slice patterns ^^

**Comment by oli-obk** [comment]
slice patterns don't allow references as their argument anymore, so I think this is ok now? We can fix any issues once slice patterns become stable.

This should probably be implemented for all types that implement `Unsize<[T]>` if the expression's result type was `&[T]` (and the expression is of the `&x[..]` kind). Or does anyone see a reason to limit it to arrays and vectors?

**Comment by camsteffen** [comment]
I don't think this is actionable, `&array[..]` is not the same as `&array`.
