### ISSUE TITLE
A mixed assignment bug from Python

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust-clippy#9650]
### Description

This is a request for a possible new Clippy lint, but this time I don't have a clear mind regarding what to lint against. So I'm asking for help.

I translate (port) Python code to Rust often enough, and sometimes I introduce bugs (like when some python code uses a division among signed values and I must need to remember to use .div_euclid() in the Rust code). This is a Python example, the code is kind of silly because it's reduced from the real code, but it shows the problem:

```python
def foo(lst):
    result = 0
    x = 20
    for i in range(len(lst)):
        (x, x_prev) = (lst[i], x)
        result += (x - x_prev) * 5
    return result

r = foo(list(range(10)))
print(r) # Prints: -55
```

A basic Rust translation is:

```rust
fn foo(lst: &[i32]) -> i32 {
    let mut result = 0;
    let mut x = 20;
    for i in 0 .. lst.len() {
        let (x, x_prev) = (lst[i], x);
        result += (x - x_prev) * 5;
    }
    result
}

fn main() {
    let r = foo(&(0 .. 10).collect::<Vec<_>>());
    println!("{r}"); // Prints: -775
}
```

The compiler tells us that x doesn't need to be mutable, so removing that mut the Rust code becomes:

```rust
fn foo(lst: &[i32]) -> i32 {
    let mut result = 0;
    let x = 20;
    for i in 0 .. lst.len() {
        let (x, x_prev) = (lst[i], x);
        result += (x - x_prev) * 5;
    }
    result
}

fn main() {
    let r = foo(&(0 .. 10).collect::<Vec<_>>());
    println!("{r}"); // Prints: -775
}
```

Now the code compiles and runs and it's wrong, giving a different result.

The problem comes from the tuple assignment inside the for loop. In Python such line of code is mixed, because x_prev is a newly created variable and x is just updated.

In the Rust code both variables are created new because Rust doesn't have such mixed assignments. A hypotetical syntax that avoids the bug:

(x, let x_prev) = (lst[i], x);

But such syntax, while looking sufficiently clear/explicit, is probably overkill for Rust. I'm not advocating it.

So my real question is: could Clippy (or even rustc) spot that porting bug?

### Version

```text
rustc 1.66.0-nightly (bf15a9e52 2022-10-14)
```

**Comment by smoelius** [comment]
Just an observation, the restriction lint [`shadow_reuse`](https://rust-lang.github.io/rust-clippy/master/#shadow_reuse) emits this warning:
```
warning: `x` is shadowed
 --> src/main.rs:7:14
  |
7 |         let (x, x_prev) = (lst[i], x);
  |              ^
  |
note: previous binding is here
 --> src/main.rs:5:9
  |
5 |     let x = 20;
  |         ^
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#shadow_reuse
```

**Comment by leonardo-m** [comment]
Peraphs there's no better way to spot this problem, so I'll probably close this issue down. Thank you smoelius.

**Comment by dswij** [comment]
As @smoelius suggested, I think `shadow_reuse` is the perfect lint for this :)

I'll be closing the issue.
