### ISSUE TITLE
Add a lint for missing implementations of `Error`

### ISSUE THREAD

**Issue by PatchMixolydic** [rust-lang/rust-clippy#9672]
### What it does

This lint lints against local types which are used as a `Result`'s `E` type, but don't implement the `Error` trait.

### Lint Name

`missing_error_impls`

### Category

style, pedantic, or restriction

### Advantage

* Allows the error to be passed to functions expecting `dyn Error`/`impl Error`
* Enables the use of `?` on the `Result` type in functions/try blocks that return `Result<_, Box<dyn Error>>` or `anyhow::Result<_>`

### Drawbacks

* Requires up to two trait implementations and a derive to resolve (or a dependency if the programmer opts to use `thiserror`)
* On `no_std`, `Error` is only available with the [`error_in_core`](https://doc.rust-lang.org/nightly/core/error/index.html) feature gate

### Example

```rust
pub struct MyError;

pub fn foo() -> Result<(), MyError> {
    Ok(())
}
```

Could be written as:

```rust
#[derive(Debug)]
pub struct MyError;

impl std::error::Error for MyError {}

impl std::fmt::Display for MyError {
    fn fmt(&self, _: &mut std::fmt::Formatter<'_>) -> Result<(), std::fmt::Error> {
        todo!()
    }
}

pub fn foo() -> Result<(), MyError> {
    Ok(())
}

```

Or as:
```rust
#[derive(Debug, thiserror::Error)]
#[error("todo")]
pub struct MyError;

pub fn foo() -> Result<(), MyError> {
    Ok(())
}
```

**Comment by lukaslueg** [comment]
Same as #6409?

**Comment by PatchMixolydic** [comment]
Seems like it; my bad 😅
