### ISSUE TITLE
Lint against `mod lib;`

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/rust-clippy#9677]
### What it does

Found that some beginners write `mod lib;` in `main.rs` to reference `lib.rs` contents. Definitely not what people actually want to do!

### Category

suspicious

### Example

```rust
// main.rs
mod lib;
```

Could be written as:

```rust
use this_package as lib;
```

**Comment by st3fan** [comment]
@crlf0710 I'm interested in working on this issue.

**Comment by Alexendoo** [comment]
Great, thanks @st3fan!

If you need any help at all feel free to ask in here or on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/clippy)

**Comment by Alexendoo** [comment]
Looks like rustc had beaten us to this one https://github.com/rust-lang/rust/pull/94467

Sorry about that @st3fan, I wasn't aware of that lint at the time

**Comment by st3fan** [comment]
No worries. I enjoyed hacking on this and I learned some new things. I'll find something else to contribute!
