### ISSUE TITLE
Needless Result

### ISSUE THREAD

**Issue by melotic** [rust-lang/rust-clippy#9732]
### What it does

There are some times, after refactoring, that a method signature returns a `Result`, but there is no other option in the code to return anything but `Ok` or `Err`. 

A lint should (optionally) inform the user that the method signature should just return the result type `T`, or `E`. Take for instance this code:

### Lint Name

needless_result

### Category

pedantic

### Advantage

- Simpler error handling for end-users (no need to handle an error that will never happen)

### Drawbacks

- Library developers may wish to future-proof their API for stability, and believe that eventually the method may utilize the `Err` variant.

### Example

```rust
/// Computes the entropy on the file
fn get_entropy(file: &[u8]) -> Result<f32> {
    let mut counts = [0; 256];
    let mut total = 0;

    for byte in file.iter() {
        counts[*byte as usize] += 1;
        total += 1;
    }

    let mut entropy = 0.0;

    for count in counts.iter() {
        if *count > 0 {
            let p = *count as f64 / total as f64;
            entropy -= p * p.log2();
        }
    }

    Ok(entropy as f32)
}
```

Could be written as:

```rust
/// Computes the entropy on the file
fn get_entropy(file: &[u8]) -> f32 {
    let mut counts = [0; 256];
    let mut total = 0;

    for byte in file.iter() {
        counts[*byte as usize] += 1;
        total += 1;
    }

    let mut entropy = 0.0;

    for count in counts.iter() {
        if *count > 0 {
            let p = *count as f64 / total as f64;
            entropy -= p * p.log2();
        }
    }

    entropy as f32
}
```

**Comment by smoelius** [comment]
I think this is [`unnecessary_wraps`](https://rust-lang.github.io/rust-clippy/master/#unnecessary_wraps)(?).

**Comment by melotic** [comment]
> I think this is [`unnecessary_wraps`](https://rust-lang.github.io/rust-clippy/master/#unnecessary_wraps)(?).

It’s pretty much identical, except that is only for Options.

**Comment by melotic** [comment]
Actually, @smoelius you're right! I wasn't enabling `pedantic`. Thanks!
