### ISSUE TITLE
Suggest `let...else` with `return` over `match` with `return`

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust-clippy#9749]
### What it does

Utilizes the [new `let...else` syntax](https://github.com/rust-lang/rust/issues/87335) when the user returns in the non-unwrapping case

### Lint Name

let-else-return

### Category

style

### Advantage

More concise

### Example

```rust
let n = match some_option {
    Some(n) => n,
    None => return something_else,
};
```

Or

```rust
let n = if let Some(n) = some_option {
    n
} else {
    return something_else;
};
```

Could be written as:

```rust
let Some(n) = some_option else {
    return something_else,
};
```

Ideally this would also work with `Result`.

**Comment by est31** [comment]
I think you are looking for #8437. It is not in nightly yet, but will be after the the next clippy bump.
