### ISSUE TITLE
`http::HeaderName` interacts poorly with `declare_interior_mutable_const`

### ISSUE THREAD

**Issue by lucacasonato** [rust-lang/rust-clippy#9776]
### Summary

The reproducer code emits a `declare_interior_mutable_const` warning, even though `HeaderName` is not interior mutable AFAICT.

### Lint Name

declare_interior_mutable_const

### Reproducer

```rs
use http::HeaderName;

const X_FOO_BAR: HeaderName = HeaderName::from_static("x-foo-bar");
```

### Version

```text
rustc 1.64.0 (a55dd71d5 2022-09-19)
binary: rustc
commit-hash: a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52
commit-date: 2022-09-19
host: aarch64-apple-darwin
release: 1.64.0
LLVM version: 14.0.6
```

**Comment by lucacasonato** [comment]
Quite possibly caused by #5812.

**Comment by rail-rain** [comment]
The lints now (#11678) don't think of `Bytes` as interior mutable. It's probably a bug in the implementation that types that wrap `Bytes` still trigger the lints.

**Comment by djc** [comment]
This also seems to trigger `mutable_key_type`, which seems unwarranted as well. Would be nice to get this fixed?

**Comment by ThinkerDreamer** [comment]
It also seems triggered by `http::header::value::HeaderValue` which has `Bytes` inside as well.
```
const MY_HEADER_VAL: HeaderValue = HeaderValue::from_static("my_header_value");
```

**Comment by djc** [comment]
@Alexendoo awesome, thanks!
