### ISSUE TITLE
needless_borrows_for_generic_args is wrong

### ISSUE THREAD

**Issue by e00E** [rust-lang/rust-clippy#9782]
### Summary

Started showing up with Rust 1.65.0 .

### Lint Name

needless_borrow

### Reproducer

I tried this code:

```rust
fn foo<T: AsRef<[u8]>>(t: T) {
    println!("{}", std::mem::size_of::<T>());
    let _t: &[u8] = t.as_ref();
}

fn main() {
    let a: [u8; 100] = [0u8; 100];

    // 100
    foo::<[u8; 100]>(a);
    foo(a);

    // 16
    foo::<&[u8]>(&a);
    foo(a.as_slice());

    // 8
    foo::<&[u8; 100]>(&a);
    foo(&a);
}
```

I saw this happen:

```
warning: the borrowed expression implements the required traits
  --> src/main.rs:14:18
   |
14 |     foo::<&[u8]>(&a);
   |                  ^^ help: change this to: `a`
   |
   = note: `#[warn(clippy::needless_borrow)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

warning: the borrowed expression implements the required traits
  --> src/main.rs:18:23
   |
18 |     foo::<&[u8; 100]>(&a);
   |                       ^^ help: change this to: `a`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

warning: the borrowed expression implements the required traits
  --> src/main.rs:19:9
   |
19 |     foo(&a);
   |         ^^ help: change this to: `a`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

warning: `a` (bin "a") generated 3 warnings
```

I expected to see this happen:
> no lint

While it is true that the trait is implemented by the borrowed expression, it is not true that this operation "is going to be dereferenced immediately by the compiler", and it is wrong to suggest that these instances should be changed to not use a reference. First, the calls where the type of T is specified no longer compile with the suggestion, and more importantly this changes the semantics of the code. There might be very different implementations based on the type or a reference was intentionally used to not copy a large object into the function.

### Version

```text
rustc 1.65.0 (897e37553 2022-11-02)
binary: rustc
commit-hash: 897e37553bba8b42751c67658967889d11ecd120
commit-date: 2022-11-02
host: x86_64-unknown-linux-gnu
release: 1.65.0
LLVM version: 15.0.0
```

**Comment by e00E** [comment]
Update as of today with Rust 1.69.0. Same code as before.

```
  --> src/main.rs:19:9
   |
19 |     foo(&a);
   |         ^^ help: change this to: `a`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
   = note: `#[warn(clippy::needless_borrow)]` on by default
```

The clippy suggestions that lead to invalid code have disappeared. Clippy only lints line 19. This lint is still wrong with the same reason as before.

**Comment by sourcefrog** [comment]
I hit what seems like the same bug here: https://github.com/sourcefrog/cargo-mutants/blob/09622021aaf0906ce64aa6a2587eb7416d5ae3cb/src/fnvalue.rs#L321-L337

Clippy says

```
warning: this expression creates a reference which is immediately dereferenced by the compiler
   --> src/fnvalue.rs:334:39
    |
334 |             return Some((&last.ident, &key_type, &value_type));
    |                                       ^^^^^^^^^ help: change this to: `key_type`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
    = note: `#[warn(clippy::needless_borrow)]` on by default
```

However if I make that change I get 

```
expected &Type, found Type
```

There are ways to write it without the `&` but I'm not sure they're really improvements.

**Comment by Jarcho** [comment]
I can't reproduce that. `Some((&last.ident, key_type, value_type))` works fine, same with removing only one of the references.

**Comment by sourcefrog** [comment]
OK, strangely with the `&` removed I see an error from rust-analyzer 0.3.1916 (which seems to be [current](https://rust-analyzer.github.io/thisweek/2024/04/08/changelog-228.html)) but not from `cargo check` or `cargo clippy` on stable or nightly. I guess that means the clippy suggestion is OK and it's a rust-analyzer bug.

**Comment by e00E** [comment]
Closing this because the original test cases no longer apply and the lint name and description have changed. I might open a new issue for the remaining case.
