### ISSUE TITLE
Can't use `swap` or `replace` as suggested by `manual_swap`

### ISSUE THREAD

**Issue by mcarton** [rust-lang/rust-clippy#981]
On the following:

``` rust
fn main() {
    let mut foo = [1, 2];
    let temp = foo[0];
    foo[0] = foo[1];
    foo[1] = temp;
}
```

Clippy suggests `std::mem::swap(&mut foo[0], &mut foo[1]);`, but this would mutably borrow `foo` twice. The correct suggestion for slices would be [`foo.swap(0, 1)`](https://doc.rust-lang.org/std/primitive.slice.html#method.swap). For other types, we should check that the suggestion would not mutably borrow something twice somehow.

**Comment by mcarton** [comment]
Oh wait, actually the full suggestion is:
```rust
let std::mem::swap(&mut foo[0], &mut foo[1]);
^^^
```

@Manishearth I there a trick with `compiletest-rs` to check that there is nothing else before/after the suggestion?

**Comment by thomcc** [comment]
I have the related issue where clippy wants me to use mem::swap instead of my manual swap. It's a field through a slice, so it's the same kind of problem:
```rust
let id = tris[a].id;
tris[a].id = tris[b].id;
tris[b].id = id;
```
