### ISSUE TITLE
Use `map_or` instead of `map` followed by `unwrap_or`

### ISSUE THREAD

**Issue by porky11** [rust-lang/rust-clippy#9812]
### What it does

Suggests to use `map_or` instead of `map` followed by `unwrap_or`.

Should be implemented for both, options and results.

### Lint Name

map_unwrap_or

### Category

default (?)

### Advantage

One method call instead of two; might also increase performance.

### Drawbacks

None

### Example

```rust
    Some(1).map(|i| i + 1).unwrap_or(0);
    Ok::<_, ()>(1).map(|i| i + 1).unwrap_or(0);
```

Could be written as:

```rust
    Some(1).map_or(0, |i| i + 1);
    Ok::<_, ()>(1).map_or(0, |i| i + 1);
```

**Comment by kraktus** [comment]
[`map_unwrap_or`](https://rust-lang.github.io/rust-clippy/master/index.html#map_unwrap_or) lint already exists! It's just under the pedantic category.

**Comment by porky11** [comment]
Thanks. Is there a good reason, why it's not enabled by default?
