### ISSUE TITLE
iter_nth_zero fires within implementations of the next method

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust-clippy#9820]
### Description

The `iter_nth_zero` lint warns you against calling `nth(0)`, and that you should call `next()` instead, *even when* you're implementing the `next` method with the call to `nth(0)`.

### Version

clippy 0.1.66 (b8c35ca2 2022-10-15)

**Comment by Ablu** [comment]
Example code that triggers this: https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git/tree/bindings/rust/libgpiod/src/event_buffer.rs?h=v2.0.1&id=ae275c375477f207912113e5cf190fada78f3f90#n57
