### ISSUE TITLE
str::split instead of to_string().split()

### ISSUE THREAD

**Issue by lexeyOK** [rust-lang/rust-clippy#9965]
### What it does

It suggests to use `str::split` instead of chaining `.to_string().split()`.

### Lint Name

str_split_instead_of_to_string_chain

### Category

style

### Advantage

shorter, there is no overhead as far as i know
<https://godbolt.org/z/ET7Y55P4E>

### Example

```rust
fn count_string(s: &str) -> usize {
    s.to_string().split(",").count()
}
```

Could be written as:

```rust
fn count_str(s: &str) -> usize {
    s.split(",").count()
}
```

**Comment by Alexendoo** [comment]
Would be a good enhancement to `unnecessary_to_owned`

**Comment by GuillaumeGomez** [comment]
Sending a PR shortly to handle this case.
