### ISSUE TITLE
About "Applicability"

### ISSUE THREAD

**Issue by Andres-Nju** [rust-lang/rust-clippy#9984]
### Description

I got 2 questions:

1. I saw the applicability of some lints is "unresolved", and I clicked the weblink provided but couldn't find such variant in the official doc. 
There are only these:
pub enum Applicability {
    MachineApplicable,
    MaybeIncorrect,
    HasPlaceholders,
    Unspecified,
}
So I wonder what does this "Applicability" mean? or if it is a little bit different from those of the lints which are provided by rustc?

2. I also wonder whether the applicability is related to the capability of fixing codes automatically with the lint's suggestions?
For example, applicability "unresolved" means this kind of smell/bad code **cannot be fixed automatically** by using "cargo clippy --fix", or it just means the process of fixing can still be done, but the substitution codes still have problems?

**Comment by xFrednet** [comment]
I'm closing this in favor of https://github.com/rust-lang/rust-clippy/discussions/9994 I had seen this issue, but didn't get the time to answer it yet. If you have any more questions, feel free to ask them in the discussion.
